/**
 * Constructeurs purs d'événements métier (extraits d'AppContext pour être
 * réutilisables et testables). buildCreateEvents / buildUpdateEvents décrivent
 * les effets inter-modules d'une écriture. Le rejeu hors ligne
 * (offlineReplayEvents.js) s'appuie dessus pour réémettre les mêmes événements
 * de façon idempotente.
 */

const eventDateOf = (record, ...keys) => keys.map((key) => record?.[key]).find(Boolean) || new Date().toISOString();

const acquisitionEventType = (mode) => ({ achat: ['acquisition', 'Acquisition par achat'], naissance_ferme: ['naissance', 'Naissance sur la ferme'], reproduction_interne: ['reproduction', 'Naissance issue de reproduction interne'], don: ['acquisition', 'Entree par don'], autre: ['acquisition', 'Entree dans la ferme'] }[mode || 'achat'] || ['acquisition', 'Entree dans la ferme']);

export const buildCreateEvents = (moduleKey, record) => {
  if (!record?.id) return [];
  if (moduleKey === 'animaux') { const [eventType, title] = acquisitionEventType(record.mode_acquisition); return [{ event_type: eventType, module_source: 'animaux', entity_type: 'animal', entity_id: record.id, title, description: `${record.name || record.id} - ${record.type || 'animal'} entre dans la ferme.`, amount: Number(record.purchase_cost || 0) || null, event_date: eventDateOf(record, 'date_achat', 'date_naissance', 'date_entree_ferme'), severity: 'info' }]; }
  if (moduleKey === 'avicole') return [{ event_type: 'creation_lot', module_source: 'avicole', entity_type: 'lot_avicole', entity_id: record.id, title: 'Creation lot avicole', description: `${record.name || record.id} - effectif initial ${record.initial_count || 0}.`, event_date: eventDateOf(record, 'date_debut'), severity: 'info' }];
  if (moduleKey === 'production_oeufs_logs') return [{ event_type: 'production_oeufs', module_source: 'avicole', entity_type: 'lot_avicole', entity_id: record.lot_id || record.id, title: 'Production oeufs enregistree', description: `${record.oeufs_produits || 0} oeufs produits, ${record.oeufs_casses || 0} casses.`, event_date: eventDateOf(record, 'date'), severity: Number(record.oeufs_casses || 0) > Number(record.oeufs_produits || 0) * 0.08 ? 'warning' : 'info' }];
  if (moduleKey === 'alimentation_logs') { const isLot = record.type_cible === 'lot_avicole' || Boolean(record.lot_id); return [{ event_type: isLot ? 'alimentation_lot' : 'alimentation', module_source: isLot ? 'avicole' : 'animaux', entity_type: isLot ? 'lot_avicole' : 'categorie_animale', entity_id: record.cible_id || record.lot_id || record.categorie || record.id, title: isLot ? 'Alimentation lot avicole' : 'Alimentation categorie animale', description: `${record.categorie || 'Aliment'} - ${record.quantite || 0} ${record.unite || ''} pour ${record.montant_total || 0} FCFA.`, amount: Number(record.montant_total || 0) || null, event_date: eventDateOf(record, 'date'), severity: 'info' }]; }
  if (moduleKey === 'sante') { const done = record.statut === 'fait' || Boolean(record.effectuee); return [{ event_type: done ? 'vaccination' : 'soin', module_source: 'sante', entity_type: 'animal', entity_id: record.animal || record.id, title: done ? 'Vaccination effectuee' : 'Action sante planifiee', description: `${record.nom || 'Sante'} - veterinaire ${record.vet || 'non renseigne'}.`, event_date: eventDateOf(record, 'effectuee', 'prevue'), severity: record.statut === 'retard' ? 'warning' : 'info' }]; }
  if (moduleKey === 'cultures') return [{ event_type: record.date_semis ? 'semis' : 'incident_culture', module_source: 'cultures', entity_type: 'culture', entity_id: record.id, title: 'Culture enregistree', description: `${record.nom || record.id} - ${record.type || 'culture'} sur ${record.parcelle || 'parcelle non renseignee'}.`, event_date: eventDateOf(record, 'date_semis', 'created_at'), severity: record.statut === 'perdu' ? 'critique' : 'info' }];
  if (moduleKey === 'stock') return [{ event_type: Number(record.quantite || 0) <= Number(record.seuil || 0) ? 'stock_critique' : 'entree_stock', module_source: 'stocks', entity_type: 'stock', entity_id: record.id, title: Number(record.quantite || 0) <= Number(record.seuil || 0) ? 'Stock critique detecte' : 'Produit stock enregistre', description: `${record.produit || record.id}: ${record.quantite || 0} ${record.unite || ''}.`, amount: Number(record.quantite || 0) * Number(record.prixunit || record.prixUnit || 0) || null, severity: Number(record.quantite || 0) <= Number(record.seuil || 0) ? 'warning' : 'info' }];
  if (moduleKey === 'finances') return [{ event_type: record.type === 'entree' ? 'recette' : 'depense', module_source: 'finances', entity_type: 'transaction', entity_id: record.id, title: record.type === 'entree' ? 'Recette enregistree' : 'Depense enregistree', description: record.libelle || record.description || record.categorie || 'Transaction financiere', amount: Number(record.montant || 0), event_date: eventDateOf(record, 'date'), linked_transaction_id: record.id, severity: record.statut === 'impaye' ? 'warning' : 'info' }];
  if (moduleKey === 'documents') return [{ event_type: 'document_ajoute', module_source: 'documents', entity_type: record.entity_type || 'document', entity_id: record.entity_id || record.id, title: 'Document ajoute', description: `${record.title || record.id} - ${record.document_category || 'document'}.`, linked_document_id: record.id, severity: 'info' }];
  if (moduleKey === 'sales_orders') return [{ event_type: record.type_document === 'devis' ? 'facture' : 'vente', module_source: 'ventes', entity_type: 'vente', entity_id: record.id, title: 'Commande commerciale enregistree', description: `${record.type_document || 'commande'} - client ${record.client_id || 'non renseigne'}.`, amount: Number(record.montant_total || 0) || null, event_date: eventDateOf(record, 'date'), linked_sale_id: record.id, severity: 'info' }];
  if (moduleKey === 'sales_opportunities') return [{ event_type: 'opportunite_vente_detectee', module_source: 'ventes', entity_type: record.source_type || 'opportunite_vente', entity_id: record.source_id || record.id, title: record.title || 'Opportunite de vente detectee', description: record.reason || record.description || 'Opportunite commerciale a verifier.', amount: Number(record.estimated_value || 0) || null, event_date: eventDateOf(record, 'detected_at'), severity: 'info' }];
  if (moduleKey === 'invoices') return [{ event_type: 'facture', module_source: 'ventes', entity_type: 'facture', entity_id: record.id, title: 'Facture emise', description: record.numero_facture || record.order_id || 'Facture commerciale', amount: Number(record.montant_total || 0) || null, linked_sale_id: record.order_id || null, severity: 'info' }];
  if (moduleKey === 'payments') return [{ event_type: 'paiement', module_source: 'ventes', entity_type: 'paiement', entity_id: record.id, title: 'Paiement recu', description: `${record.moyen_paiement || 'paiement'} - commande ${record.order_id || 'non renseignee'}.`, amount: Number(record.montant || 0) || null, linked_sale_id: record.order_id || null, severity: 'info' }];
  if (moduleKey === 'alertes_center' && ['critique', 'urgence'].includes(record.severity)) return [{ event_type: 'incident', module_source: record.module_source || 'alertes', entity_type: record.entity_type || 'alerte', entity_id: record.entity_id || record.id, title: record.title || 'Alerte critique', description: record.message || record.action_recommandee || '', severity: record.severity }];
  return [];
};

export const buildUpdateEvents = (moduleKey, previousRow, record) => {
  if (!record?.id) return [];
  const events = [];
  if (moduleKey === 'animaux') {
    if (previousRow?.status !== record.status && record.status === 'vendu') events.push({ event_type: 'vente', module_source: 'animaux', entity_type: 'animal', entity_id: record.id, title: 'Animal vendu', description: `${record.name || record.id} vendu a ${record.client_id || 'client non renseigne'}.`, amount: Number(record.prix_vente_reel || record.sale_price || 0) || null, event_date: eventDateOf(record, 'date_vente'), linked_transaction_id: record.linked_transaction_id || null, severity: 'info' });
    if (previousRow?.status !== record.status && record.status === 'mort') events.push({ event_type: 'deces', module_source: 'animaux', entity_type: 'animal', entity_id: record.id, title: 'Deces animal', description: record.cause_deces || `${record.name || record.id} marque comme mort.`, event_date: eventDateOf(record, 'date_deces'), severity: 'critique' });
    if (Number(previousRow?.poids || 0) !== Number(record.poids || 0)) events.push({ event_type: 'croissance', module_source: 'animaux', entity_type: 'animal', entity_id: record.id, title: 'Poids animal mis a jour', description: `Ancien poids ${previousRow?.poids || 0} kg, nouveau poids ${record.poids || 0} kg.`, severity: 'info' });
    if (previousRow?.health_status !== record.health_status) events.push({ event_type: ['malade', 'blesse', 'a_surveiller'].includes(record.health_status) ? 'incident' : 'soin', module_source: 'animaux', entity_type: 'animal', entity_id: record.id, title: 'Etat de sante modifie', description: `${previousRow?.health_status || 'inconnu'} -> ${record.health_status || 'inconnu'}.`, severity: ['malade', 'blesse'].includes(record.health_status) ? 'warning' : 'info' });
    if (!previousRow?.en_gestation && record.en_gestation) events.push({ event_type: 'gestation', module_source: 'animaux', entity_type: 'animal', entity_id: record.id, title: 'Debut gestation', description: `Femelle declaree en gestation. Mise bas prevue: ${record.date_prevue_mise_bas || 'non renseignee'}.`, event_date: eventDateOf(record, 'date_debut_gestation'), severity: 'info' });
  }
  if (moduleKey === 'avicole') {
    if (Number(record.mortality || 0) > Number(previousRow?.mortality || 0)) events.push({ event_type: 'mortalite_lot', module_source: 'avicole', entity_type: 'lot_avicole', entity_id: record.id, title: 'Mortalite lot mise a jour', description: `${previousRow?.mortality || 0} -> ${record.mortality || 0} morts.`, severity: Number(record.initial_count || 0) && Number(record.mortality || 0) > Number(record.initial_count || 0) * 0.04 ? 'critique' : 'warning' });
    if (previousRow?.health_status !== record.health_status) events.push({ event_type: 'soin_lot', module_source: 'avicole', entity_type: 'lot_avicole', entity_id: record.id, title: 'Etat sanitaire lot modifie', description: `${previousRow?.health_status || 'inconnu'} -> ${record.health_status || 'inconnu'}.`, severity: ['malade', 'critique'].includes(record.health_status) ? 'warning' : 'info' });
    if (previousRow?.status !== record.status && ['vendu', 'termine', 'perdu'].includes(record.status)) events.push({ event_type: record.status === 'perdu' ? 'incident' : 'cloture_lot', module_source: 'avicole', entity_type: 'lot_avicole', entity_id: record.id, title: 'Statut lot modifie', description: `${previousRow?.status || 'inconnu'} -> ${record.status}.`, severity: record.status === 'perdu' ? 'critique' : 'info' });
  }
  if (moduleKey === 'stock' && Number(previousRow?.quantite || 0) !== Number(record.quantite || 0)) events.push({ event_type: Number(record.quantite || 0) <= Number(record.seuil || 0) ? 'stock_critique' : 'mouvement_stock', module_source: 'stocks', entity_type: 'stock', entity_id: record.id, title: Number(record.quantite || 0) <= Number(record.seuil || 0) ? 'Stock critique' : 'Mouvement stock', description: `${record.produit || record.id}: ${previousRow?.quantite || 0} -> ${record.quantite || 0} ${record.unite || ''}.`, severity: Number(record.quantite || 0) <= Number(record.seuil || 0) ? 'warning' : 'info' });
  if (moduleKey === 'sante' && previousRow?.statut !== record.statut && record.statut === 'fait') events.push({ event_type: 'vaccination', module_source: 'sante', entity_type: 'animal', entity_id: record.animal || record.id, title: 'Vaccination effectuee', description: record.nom || 'Vaccination marquee comme faite.', event_date: eventDateOf(record, 'effectuee'), severity: 'info' });
  if (moduleKey === 'cultures' && previousRow?.statut !== record.statut && record.statut === 'recolte') events.push({ event_type: 'recolte', module_source: 'cultures', entity_type: 'culture', entity_id: record.id, title: 'Culture en recolte', description: `${record.nom || record.id} - quantite recoltee ${record.quantite_recoltee || 0}.`, event_date: eventDateOf(record, 'date_recolte_reelle'), severity: 'info' });
  if (moduleKey === 'sales_opportunities' && previousRow?.status !== record.status && record.status === 'converti') events.push({ event_type: 'opportunite_convertie', module_source: 'ventes', entity_type: record.source_type || 'opportunite_vente', entity_id: record.source_id || record.id, title: 'Opportunite convertie', description: record.title || 'Opportunite transformee en commande/vente.', amount: Number(record.estimated_value || 0) || null, linked_sale_id: record.converted_sale_id || null, severity: 'info' });
  return events;
};
