const clean=(v='')=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]+/g,' ').replace(/\s+/g,' ').trim();
const has=(t,arr)=>arr.some(w=>clean(t).includes(clean(w)));
const n=v=>Number(v||0)||0;
const d=r=>Date.parse(r?.created_at||r?.updated_at||r?.date||r?.recorded_at||0)||0;
const sort=a=>[...a].sort((x,y)=>d(y)-d(x));
const money=v=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(Math.round(v||0));
async function read(table,role,language,limit=120){const r=await fetch('/api/erp-read',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({table,role,language,search:'',limit})});const j=await r.json().catch(()=>({}));return Array.isArray(j.rows)?j.rows:[]}
function tbl(mod,rows=[],max=8){const p={oeufs:['date','lot_id','oeufs_produits','oeufs_casses','taux_ponte'],avicole:['name','type','current_count','phase','status'],animaux:['reference','name','type','status','health_status'],stock:['produit','quantite','unite','seuil'],alimentation:['id','date','categorie','type_cible','cible_id'],taches:['title','status','priority','due_date'],alertes:['title','severity','status','created_at']}[mod]||Object.keys(rows[0]||{}).slice(0,5);const c=p.filter(k=>rows.some(r=>r&&k in r)).slice(0,5);return{columns:c,rows:rows.slice(0,max).map(r=>c.map(k=>r?.[k]??'—'))}}
const eggQty=r=>n(r.oeufs_produits||r.oeufs_ramasses||r.quantity||r.quantite||r.nombre_oeufs);
const eggBad=r=>n(r.oeufs_casses||r.broken_eggs);
const isBovin=r=>has(JSON.stringify(r),['bovin','boeuf','vache','taureau','veau']);
const isOvin=r=>has(JSON.stringify(r),['ovin','mouton','brebis','belier','agneau']);
const isPoultry=r=>has(JSON.stringify(r),['poule','poulet','ganaar','guinar','guinaar','avicole','pondeuse','chair','volaille']);
const isChair=r=>has(JSON.stringify(r),['chair','broiler','poulet de chair']);
const isPond=r=>has(JSON.stringify(r),['pondeuse','ponte']);
const countLot=r=>n(r.current_count||r.effectif||r.nombre||r.quantite||r.quantity||r.initial_count);
const risky=r=>{const x=clean(JSON.stringify(r));return has(x,['surveillance','critique','traitement','diagnostic','risque','alerte','febar','febaar'])&&!has(x,['ok','sain','normal','stable'])};
function intent(t=''){const x=clean(t);if(has(x,['aujourd hui','today'])&&x.split(' ').length<=3)return'analysis';if(has(x,['compare','comparer','deux derniers ramassages','dernier ramassage','ecart'])&&has(x,['oeuf','nene','neen','ponte','ramassage']))return'egg_compare';if(has(x,['baan guinar','ban guinar','quel poulet','quelle bande'])&&has(x,['feb','sante','surveillance']))return'sick_poultry';if(has(x,['naka nene','naka neen','nene yi','neen yi','comment va la production d oeufs','comment va la ponte','production bi bakhna','production bakhna','oeufs bakhna','ponte bakhna']))return'production_status';if(has(x,['combien d oeufs','nombre d oeufs','total oeufs','oeufs ramasses','ponte totale']))return'eggs_total';if(has(x,['combien de bovins','nombre de bovins','bovin yi','nata nag','niata nag']))return'cattle_count';if(has(x,['combien de moutons','combien d ovins','nombre de moutons','ovin yi','mouton yi']))return'sheep_count';if(has(x,['animal malade','animaux malades','quel animal est malade','qui est malade','malade']))return'sick_animals';if(has(x,['stock disponible','stocks disponibles','inventaire disponible']))return'stock_summary';if(has(x,['alimentation','aliment','provende','feed']))return'feed_status';if(has(x,['naira guinar','nata guinar','nata guinaar','nata ganaar','niata guinar','niata guinaar','combien de poulets','nombre de poulets','combien de volailles','guinar','guinaar','ganaar']))return'poultry_count';if(has(x,['opportunite','opportunites','vente possible','a vendre']))return'opportunities';if(has(x,['analyse','analyser','pourquoi','baisse','hausse','recommand','risque','que faire','priorite','cette semaine','ce mois']))return'analysis';return'fallback'}
async function eggs(language,role){const rows=sort(await read('production_oeufs_logs',role,language));const total=rows.reduce((a,r)=>a+eggQty(r),0),bad=rows.reduce((a,r)=>a+eggBad(r),0),last=rows[0]||{};return{side:'assistant',language,text:`Production d’œufs\n\n- Total œufs : ${total}\n- Œufs cassés : ${bad}\n- Relevés : ${rows.length}\n- Dernier relevé : ${d(last)?new Date(d(last)).toLocaleDateString('fr-FR'):'non renseigné'}`,table:tbl('oeufs',rows),erp:{module:'oeufs',intent:'eggs_total',count:rows.length,total}}}
async function prod(language,role){const rows=sort(await read('production_oeufs_logs',role,language)),lots=await read('lots',role,language);const total=rows.reduce((a,r)=>a+eggQty(r),0),bad=rows.reduce((a,r)=>a+eggBad(r),0),avg=rows.length?Math.round(total/rows.length):0,pond=lots.filter(isPond).reduce((a,r)=>a+countLot(r),0);let verdict='je n’ai pas assez de données pour juger correctement.';if(total>0&&bad/Math.max(total,1)<=0.05)verdict='la production existe et les pertes semblent limitées.';else if(total>0)verdict='la production existe, mais les pertes sont à surveiller.';return{side:'assistant',language,text:`État de la production d’œufs\n\n- Verdict : ${verdict}\n- Œufs enregistrés : ${total}\n- Œufs cassés : ${bad}\n- Moyenne par relevé : ${avg}\n- Pondeuses enregistrées : ${pond||'non renseigné'}`,table:tbl('oeufs',rows),erp:{module:'production',intent:'production_status'}}}
async function eggCompare(language,role){const rows=sort(await read('production_oeufs_logs',role,language));if(rows.length<2)return{side:'assistant',language,text:'Je n’ai pas assez de relevés pour comparer les deux derniers ramassages.',erp:{module:'oeufs',intent:'egg_compare'}};const a=rows[0],b=rows[1],qa=eggQty(a),qb=eggQty(b),diff=qa-qb;const c=diff>0?`hausse de ${diff} œuf(s)`:diff<0?`baisse de ${Math.abs(diff)} œuf(s)`:'production stable';return{side:'assistant',language,text:`Comparaison des deux derniers ramassages\n\nDernier : ${a.lot_id||'lot ?'} — ${qa} œuf(s), ${eggBad(a)} cassé(s).\nPrécédent : ${b.lot_id||'lot ?'} — ${qb} œuf(s), ${eggBad(b)} cassé(s).\n\nConclusion : ${c}.`,table:{columns:['releve','lot','oeufs','casses'],rows:[['Dernier',a.lot_id||'—',qa,eggBad(a)],['Précédent',b.lot_id||'—',qb,eggBad(b)]]},erp:{module:'oeufs',intent:'egg_compare'}}}
async function poultry(t,language,role){const lots=await read('lots',role,language),animals=await read('animals',role,language),x=clean(t);let rows=lots.filter(isPoultry),label='Volaille / poulets';if(has(x,['chair','poulet de chair','broiler'])){rows=rows.filter(isChair);label='Poulets de chair'}else if(has(x,['pondeuse','ponte','nene','neen'])){rows=rows.filter(isPond);label='Pondeuses'}const total=rows.reduce((a,r)=>a+countLot(r),0)||animals.filter(isPoultry).length;return{side:'assistant',language,text:`${label}\n\n- Total estimé : ${total}\n- Bandes concernées : ${rows.length}`,table:tbl('avicole',rows),erp:{module:'avicole',intent:'poultry_count',count:total}}}
async function countAnimals(language,role,pred,label,module){const rows=await read('animals',role,language),sel=rows.filter(pred);return{side:'assistant',language,text:`${label}\n\n- Total : ${sel.length}\n- Total animaux : ${rows.length}`,table:tbl('animaux',sel),erp:{module,intent:module+'_count',count:sel.length}}}
async function sickPoultry(language,role){const rows=(await read('lots',role,language)).filter(r=>isPoultry(r)&&risky(r));if(!rows.length)return{side:'assistant',language,text:'Je n’ai trouvé aucune bande/poulet clairement à surveiller dans les données accessibles.',erp:{module:'avicole',intent:'sick_poultry',count:0}};return{side:'assistant',language,text:`Poulets / bandes à surveiller : ${rows.length}`,table:tbl('avicole',rows),erp:{module:'avicole',intent:'sick_poultry',count:rows.length}}}
async function sickAnimals(language,role){const rows=[...(await read('animal_health_records',role,language)),...(await read('animals',role,language))].filter(risky);if(!rows.length)return{side:'assistant',language,text:'Je n’ai trouvé aucun animal clairement à surveiller dans les données accessibles.',erp:{module:'sante',intent:'sick_animals',count:0}};return{side:'assistant',language,text:`Animaux à surveiller : ${rows.length}`,table:tbl('sante',rows),erp:{module:'sante',intent:'sick_animals',count:rows.length}}}
async function stocks(language,role){const rows=await read('stocks',role,language);const low=rows.filter(r=>n(r.quantite)<=n(r.seuil||r.seuil_alerte));return{side:'assistant',language,text:`Stock disponible\n\n- Lignes de stock : ${rows.length}\n- Produits sous seuil : ${low.length}`,table:tbl('stock',rows),erp:{module:'stock',intent:'stock_summary',count:rows.length,critical:low.length}}}
async function feed(language,role){const rows=sort(await read('alimentation_logs',role,language));return{side:'assistant',language,text:`Alimentation\n\n- Lignes enregistrées : ${rows.length}\n- Quantité totale visible : ${rows.reduce((a,r)=>a+n(r.quantite||r.quantity||r.amount),0)||'non renseignée'}`,table:tbl('alimentation',rows),erp:{module:'alimentation',intent:'feed_status',count:rows.length}}}
async function analysis(language,role){const sales=await read('sales_orders',role,language,100),tx=await read('transactions',role,language,100),eg=await read('production_oeufs_logs',role,language,100),st=await read('stocks',role,language,100),al=await read('alertes_center',role,language,100);return{side:'assistant',language,text:`Analyse ERP Horizon Farm\n\n- Ventes : ${sales.length}\n- Transactions : ${tx.length}\n- Production d’œufs : ${eg.reduce((a,r)=>a+eggQty(r),0)} œuf(s) sur ${eg.length} relevé(s)\n- Stocks : ${st.length} ligne(s)\n- Alertes : ${al.length}\n\nPriorités : vérifier les alertes, les stocks sous seuil et les dernières productions.`,erp:{module:'analyse',intent:'analysis'}}}
export async function askErpFromChat({text='',language='fr',role='admin',actor={}}={}){const safe=['admin','manager','employe','veterinaire','comptable'].includes(String(role).toLowerCase())?String(role).toLowerCase():'admin';const i=intent(text);if(i==='egg_compare')return eggCompare(language,safe);if(i==='production_status')return prod(language,safe);if(i==='eggs_total')return eggs(language,safe);if(i==='sick_poultry')return sickPoultry(language,safe);if(i==='sick_animals')return sickAnimals(language,safe);if(i==='cattle_count')return countAnimals(language,safe,isBovin,'Bovins dans la ferme','bovins');if(i==='sheep_count')return countAnimals(language,safe,isOvin,'Ovins / moutons dans la ferme','ovins');if(i==='poultry_count')return poultry(text,language,safe);if(i==='stock_summary')return stocks(language,safe);if(i==='feed_status')return feed(language,safe);if(i==='analysis')return analysis(language,safe);const tableMap={tache:'tasks',alerte:'alertes_center',stock:'stocks',oeuf:'production_oeufs_logs',nene:'production_oeufs_logs',neen:'production_oeufs_logs',guinar:'lots',guinaar:'lots',ganaar:'lots',animal:'animals',bovin:'animals',vente:'sales_orders',client:'clients',finance:'transactions',aliment:'alimentation_logs'};const key=Object.keys(tableMap).find(k=>clean(text).includes(k));if(!key)return null;const table=tableMap[key];const rows=sort(await read(table,safe,language,100));return{side:'assistant',language,text:`J’ai trouvé ${rows.length} donnée(s) ERP dans ${key}.`,table:tbl(key==='guinar'||key==='guinaar'||key==='ganaar'?'avicole':key==='oeuf'||key==='nene'||key==='neen'?'oeufs':key,rows),erp:{module:key,table,count:rows.length,intent:'list'}}}
