const MAP = {
  equipements: 'equipment', taches: 'tasks', alertes: 'alertes_center', clients: 'clients', creances: 'client_receivables',
  ventes: 'sales_orders', finances: 'transactions', paiements: 'payments', factures: 'invoices', fournisseurs: 'fournisseurs',
  cultures: 'cultures', sante: 'animal_health_records', animaux: 'animals', avicole: 'lots', lots: 'lots', oeufs: 'production_oeufs_logs',
  production: 'production', alimentation: 'alimentation_logs', stock: 'stocks', documents: 'documents', rapports: 'reports', capteurs: 'sensor_devices',
  smartfarm: 'sensor_readings', comptabilite: 'accounting_entries', business_plan: 'business_plans', audit: 'audit_logs'
};
const ROUTES = [
  ['equipements', /equip|équip|materiel|matériel|tracteur|panne|maintenance|machine/i], ['taches', /tache|tâche|task|mission|travail|liggéey|retard/i], ['alertes', /alerte|alert|rappel|notification|urgence/i],
  ['creances', /creance|créance|reste.?a.?payer|impay|dette client/i], ['clients', /client|customer|acheteur/i], ['paiements', /paiement|payment|payé|paye/i], ['factures', /facture|invoice/i], ['ventes', /vente|commande|livraison|sale|order|jaay/i],
  ['finances', /finance|transaction|depense|dépense|revenu|montant/i], ['fournisseurs', /fournisseur|supplier|achat/i], ['cultures', /culture|champ|parcelle|recolte|récolte|semis|rendement/i],
  ['sante', /sante|santé|vaccin|malade|traitement|diagnostic|symptome|symptôme/i], ['animaux', /animal|animaux|mouton|vache|bovin|ovin|poids|gestation/i],
  ['oeufs', /oeuf|œuf|egg|ponte|production.*oeuf|production.*œuf/i], ['production', /production/i], ['alimentation', /aliment|alimentation|feed|provende/i], ['avicole', /avicole|poule|poulet|ganaar|lot|mortalite|mortalité/i],
  ['stock', /stock|inventaire|rupture|maïs|mais|mboq|intrant/i], ['documents', /document|fichier|preuve|file|pdf/i], ['rapports', /rapport|report|bilan|synthese|synthèse/i], ['smartfarm', /capteur|sensor|mesure|temperature|humidité|meteo|météo/i],
  ['comptabilite', /compta|comptabilite|comptabilité|journal|debit|débit|credit|crédit/i], ['business_plan', /business.?plan|prévision|prevision|projection|investissement|roi/i], ['audit', /audit|log|historique action|security/i]
];
const COLS = { taches: ['title','status','priority','due_date'], alertes: ['title','severity','status','created_at'], equipements: ['name','type','status','maintenance_due'], oeufs: ['date','lot_id','oeufs_produits','oeufs_casses','taux_ponte'], production: ['date','lot_id','type','quantity'], avicole: ['name','type','current_count','phase','status'], ventes: ['date','client_id','montant_total','statut_commande','statut_paiement'], finances: ['date','libelle','montant','type','status'], stock: ['produit','quantite','unite','seuil'], clients: ['nom','name','tel','phone','statut'], creances: ['client_id','remaining_amount','status','due_date'], factures: ['numero_facture','date_facture','montant_total','statut'] };
const ANALYSIS_TABLES = ['sales_orders','transactions','client_receivables','stocks','production_oeufs_logs','equipment','tasks','alertes_center'];
function actionOf(text = '') { if (/(crée|cree|créer|creer|ajoute|ajouter|create|add|defal|fais).*?(alerte|alert|rappel|notification)/i.test(text)) return 'create_alert'; if (/(crée|cree|créer|creer|ajoute|ajouter|create|add|defal|fais).*?(tache|tâche|task|mission|travail|liggéey)/i.test(text)) return 'create_task'; return ''; }
function moduleOf(text = '') { return ROUTES.find(([, rx]) => rx.test(text))?.[0] || ''; }
function intentOf(text = '') { if (/(analyse|analyser|compare|compar|pourquoi|baisse|hausse|recommand|préco|preco|interpr|risque|que faire|conseille|priorité|priorite)/i.test(text)) return 'analysis'; if (/(combien|nombre|total|how many|count|ñata|nata)/i.test(text)) return 'count'; if (/(dernier|dernière|derniere|plus récente|plus recente|récent|recent|latest|last)/i.test(text)) return 'latest'; return 'list'; }
function titleOf(text = '', action = '') { return String(text).replace(/^(crée|cree|créer|creer|ajoute|ajouter|create|add|defal|fais)\s*/i, '').trim() || (action === 'create_alert' ? 'Alerte Horizon Chat' : 'Tâche Horizon Chat'); }
function valueOf(row, key) { const value = row?.[key]; return value === null || value === undefined || value === '' ? '—' : String(value).slice(0, 80); }
function dateValue(row = {}) { return Date.parse(row.created_at || row.updated_at || row.date || row.due_date || row.date_facture || row.entry_date || row.recorded_at || 0) || 0; }
function sortRows(rows = []) { return [...rows].sort((a, b) => dateValue(b) - dateValue(a)); }
function columnsFor(module, rows = []) { const preferred = COLS[module] || []; const keys = preferred.filter((key) => rows.some((row) => row && key in row)); if (keys.length) return keys.slice(0, 5); return Object.keys(rows[0] || {}).filter((key) => !['owner_user_id','updated_at'].includes(key)).slice(0, 5); }
function tableFor(module, rows = [], max = 8) { const selected = rows.slice(0, max); const columns = columnsFor(module, selected); return { columns, rows: selected.map((row) => columns.map((key) => valueOf(row, key))) }; }
function label(module) { return ({ taches: 'tâches', alertes: 'alertes', oeufs: 'production d’œufs', avicole: 'lots avicoles', equipements: 'équipements' }[module] || module); }
function intro(language, module, count, intent) { const name = label(module); if (intent === 'count') return language === 'en' ? `There are ${count} ERP record(s) in ${name}.` : language === 'wo' ? `Am na ${count} résultat ci ${name}.` : `Il y a ${count} donnée(s) ERP dans ${name}.`; if (intent === 'latest') return language === 'en' ? `Here is the most recent ERP record in ${name}.` : language === 'wo' ? `Lii mooy résultat bi gën a bees ci ${name}.` : `Voici la donnée ERP la plus récente dans ${name}.`; return language === 'en' ? `I found ${count} ERP record(s) in ${name}.` : language === 'wo' ? `Gis naa ${count} résultat ci ${name}.` : `J’ai trouvé ${count} donnée(s) ERP dans ${name}.`; }
function num(v) { return Number(v || 0) || 0; }
function sum(rows, keys) { return rows.reduce((a, r) => a + keys.reduce((v, k) => v || num(r[k]), 0), 0); }
function money(v) { return new Intl.NumberFormat('fr-FR', { maximumFractionDigits: 0 }).format(Math.round(v || 0)); }
function periodInfo(text = '') { const now = new Date(); let start = 0, label = 'données récentes accessibles'; if (/aujourd|today/i.test(text)) { start = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime(); label = 'aujourd’hui'; } else if (/semaine|week/i.test(text)) { start = Date.now() - 7 * 86400000; label = 'cette semaine'; } else if (/mois|month/i.test(text)) { start = new Date(now.getFullYear(), now.getMonth(), 1).getTime(); label = 'ce mois'; } return { start, label }; }
async function readTable(table, role, language, limit = 120) { const r = await fetch('/api/erp-read', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ table, role, language, search: '', limit }) }); const d = await r.json().catch(() => ({})); return Array.isArray(d.rows) ? d.rows : []; }
async function analyze(text, language, role) { const period = periodInfo(text); const data = {}; await Promise.all(ANALYSIS_TABLES.map(async (t) => { const rows = await readTable(t, role, language); data[t] = period.start ? rows.filter((r) => dateValue(r) >= period.start) : rows; })); const sales = data.sales_orders || [], tx = data.transactions || [], rec = data.client_receivables || [], stocks = data.stocks || [], eggs = data.production_oeufs_logs || [], equipment = data.equipment || [], tasks = data.tasks || [], alerts = data.alertes_center || []; const expenses = tx.filter((r) => /depense|dépense|expense|sortie/i.test(`${r.type} ${r.transaction_type} ${r.category} ${r.categorie}`)); const lowStocks = stocks.filter((r) => num(r.quantite) <= num(r.seuil || r.seuil_alerte)); const broken = equipment.filter((r) => /panne|maintenance|hs|repair/i.test(`${r.status} ${r.notes} ${r.type}`)); const activeAlerts = alerts.filter((r) => !/resolved|closed|termine|terminé|archive/i.test(`${r.status}`)); const openTasks = tasks.filter((r) => !/done|termine|terminé|closed|archive/i.test(`${r.status} ${r.statut}`)); const salesTotal = sum(sales, ['montant_total','total_amount','montant']); const expensesTotal = sum(expenses, ['montant','amount']); const debt = sum(rec, ['remaining_amount','reste_a_payer']); const eggsTotal = sum(eggs, ['oeufs_produits','quantity']); const margin = salesTotal - expensesTotal; const recos = []; if (activeAlerts.length) recos.push(`Priorité haute : traiter ${activeAlerts.length} alerte(s) active(s).`); if (lowStocks.length) recos.push(`Priorité haute : réapprovisionner ${lowStocks.length} stock(s) sous seuil.`); if (broken.length) recos.push(`Priorité haute : planifier la maintenance de ${broken.length} équipement(s).`); if (debt > 0) recos.push(`Priorité moyenne : relancer ${money(debt)} FCFA de créances visibles.`); if (margin < 0) recos.push('Priorité moyenne : contrôler les dépenses, marge visible négative.'); if (!recos.length) recos.push('Suivi normal : aucun risque critique immédiat dans les données filtrées.'); return `Analyse ERP Horizon Farm — ${period.label}\n\nConstats clés :\n- Ventes : ${sales.length} ligne(s), total estimé ${money(salesTotal)} FCFA\n- Dépenses : ${expenses.length} ligne(s), total estimé ${money(expensesTotal)} FCFA\n- Marge visible estimée : ${money(margin)} FCFA\n- Créances restantes : ${money(debt)} FCFA\n- Production d’œufs : ${eggsTotal} œuf(s) sur ${eggs.length} relevé(s)\n- Stocks sous seuil : ${lowStocks.length}\n- Équipements à surveiller : ${broken.length}\n- Tâches ouvertes : ${openTasks.length}\n- Alertes actives : ${activeAlerts.length}\n\nPréconisations priorisées :\n${recos.map((r) => `- ${r}`).join('\n')}\n\nVous pouvez demander une période précise : aujourd’hui, cette semaine ou ce mois.`; }
export async function askErpFromChat({ text = '', language = 'fr', role = 'admin', actor = {} } = {}) { const safeRole = ['admin', 'manager', 'employe', 'veterinaire', 'comptable'].includes(String(role).toLowerCase()) ? String(role).toLowerCase() : 'admin'; const action = actionOf(text); if (action) { const response = await fetch('/api/erp-action', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, role: safeRole, language, actor, args: { title: titleOf(text, action), description: text, message: text } }) }); const data = await response.json().catch(() => ({})); if (!response.ok && !data.message) throw new Error(data.error || 'Action ERP indisponible.'); return { side: 'assistant', language, text: data.message || 'Action ERP traitée.', displayMode: 'text', erp: { action, created: data.created, duplicate: data.duplicate } }; } const intent = intentOf(text); if (intent === 'analysis') return { side: 'assistant', language, text: await analyze(text, language, safeRole), displayMode: 'text', erp: { module: 'analyse', intent: 'analysis' } }; const module = moduleOf(text); const table = MAP[module]; if (!table) return null; const response = await fetch('/api/erp-read', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ table, role: safeRole, language, search: text, limit: intent === 'latest' ? 20 : 100 }) }); const data = await response.json().catch(() => ({})); if (!response.ok && !data.message) throw new Error(data.error || 'Lecture ERP indisponible.'); const allRows = sortRows(Array.isArray(data.rows) ? data.rows : []); const rows = intent === 'latest' ? allRows.slice(0, 1) : allRows; return { side: 'assistant', language, text: data.message || intro(language, module, allRows.length, intent), displayMode: 'text', table: intent === 'count' ? null : tableFor(module, rows), erp: { module, table, count: allRows.length, intent } }; }
