// Generated from Supabase information_schema export pasted by the user.
export const ERP_REAL_SCHEMA = {
  accounting_accounts: ['id','code','name','type','category','normal_balance','description','is_active','owner_user_id','created_at','updated_at'],
  accounting_budgets: ['id','period','category','budget_amount','actual_amount','status','notes','owner_user_id','created_at','updated_at'],
  accounting_closures: ['id','period','closure_type','status','closed_at','summary','owner_user_id','created_at','updated_at'],
  accounting_documents: ['id','transaction_id','entry_id','label','document_type','file_url','uploaded_at','owner_user_id','created_at','updated_at'],
  accounting_entries: ['id','entry_date','journal','reference','source_module','source_id','label','status','total_debit','total_credit','validated_at','owner_user_id','created_at','updated_at'],
  accounting_entry_lines: ['id','entry_id','account_id','account_code','label','debit','credit','owner_user_id','created_at','updated_at'],
  alert_events: ['id','rule_key','module','severity','title','message','status','related_id','occurred_at','resolved_at','owner_user_id','created_at','updated_at'],
  alert_rules: ['id','key','module','label','severity','enabled','threshold','channel_erp','channel_whatsapp','frequency','owner_user_id','created_at','updated_at'],
  alertes: ['id','type','message','niveau','envoye','date'],
  alertes_center: ['id','title','message','module','severity','status','source','action_recommandee','send_whatsapp','recipients','owner_user_id','created_at','updated_at','module_source','entity_type','entity_id'],
  alertes_history: ['id','alert_id','event_type','message','created_by','owner_user_id','created_at','updated_at'],
  alertes_settings: ['id','key','label','enabled','severity','frequency','recipients','send_whatsapp','owner_user_id','created_at','updated_at'],
  alimentation: ['id','lot_id','quantity','cost','date'],
  alimentation_logs: ['id','date','categorie','type_cible','cible_id','animal_id','lot_id','quantite','unite','montant_total','duree_jours','fournisseur_id','notes','owner_user_id','created_at','updated_at'],
  animal_health_records: ['id','animal_id','date','health_status','record_type','diagnostic','symptomes','traitement','ras','veterinaire_id','intervention_id','next_action_date','notes','owner_user_id','created_at','updated_at'],
  animal_purchases: ['id','date','categorie','total_animaux','montant_total','cout_moyen_par_tete','fournisseur_id','notes','owner_user_id','created_at','updated_at'],
  animal_weight_records: ['id','animal_id','date','poids','tendance','notes','owner_user_id','created_at','updated_at'],
  animals: ['id','lot_id','type','status','weight','age','created_at','tag','name','sex','birth_date','purchase_cost','feed_lot_monthly','feed_lot_count','health_cost','sale_price','sale_date','buyer','buyer_phone','weights','owner_user_id','updated_at','photo_url','race','qr_url','historique_poids','historique_sante','traitements','score_sante','health_status','sexe','poids','alimentation','sante','naissance','mode_acquisition','date_achat','date_naissance','date_entree_ferme','fournisseur_vendeur','mere_id','pere_id','portee_id','notes_reproduction','en_gestation','date_debut_gestation','date_prevue_mise_bas','male_reproducteur_id','statut_reproduction','traitements_notes','frais_sante','autres_frais','date_vente','prix_vente_reel','client_id','moyen_paiement','commentaire_vente','date_deces','cause_deces','valeur_perte_estimee','commentaire_deces','date_vol_detecte','lieu_vol','commentaire_vol','date_reforme','motif_reforme','valeur_residuelle','commentaire_reforme','date_detection_maladie','symptomes','traitement_prevu','veterinaire_id','cout_traitement_estime','date_debut_traitement','date_fin_traitement_prevue','traitement_en_cours','cout_traitement','raison_surveillance','date_prochaine_verification','ras_veterinaire','source','poids_objectif','date_objectif_vente','sale_readiness_score','sale_readiness_status','pret_vente_recommande','pret_vente_confirme','date_pret_vente_recommande','date_pret_vente_confirme','raison_pret_vente','fournisseur_id','provenance'],
  api_webhooks: ['id','name','event','target_url','enabled','secret_hint','owner_user_id','created_at','updated_at'],
  audit_logs: ['id','actor','action','module','record_id','device','metadata','owner_user_id','created_at','updated_at'],
  automation_settings: ['id','key','label','description','enabled','category','frequency','message_template','audience','last_run_at','next_run_at','history','owner_user_id','created_at','updated_at'],
  farm_cost_settings: ['id','settings','owner_user_id','created_at','updated_at'],
  farm_rh_directory: ['id','directory','owner_user_id','created_at','updated_at'],
  bp_funding_sources: ['id','business_plan_id','source_type','nom_source','montant','taux_interet_pct','duree_remboursement_mois','date_obtention','conditions','statut','notes','owner_user_id','created_at','updated_at'],
  bp_investment_lines: ['id','business_plan_id','designation','categorie','quantite','unite','prix_unitaire','total','ordre','notes','owner_user_id','created_at','updated_at'],
  bp_lines_history: ['id','business_plan_id','line_table','line_id','old_value','new_value','reason','changed_by','owner_user_id','created_at','updated_at'],
  bp_links: ['id','business_plan_id','entity_type','entity_id','link_type','notes','owner_user_id','created_at','updated_at'],
  bp_recurring_costs: ['id','business_plan_id','designation','categorie','montant_mensuel','frequence','date_debut','date_fin','notes','owner_user_id','created_at','updated_at'],
  bp_revenue_projections: ['id','business_plan_id','mois_index','date_mois','capacite_active','production_estimee','unite_production','prix_unitaire_estime','ca_estime','charges_estimees','marge_estimee','remboursement_prevu','notes','owner_user_id','created_at','updated_at'],
  bp_risks: ['id','business_plan_id','categorie','titre','description','probabilite','impact','mesure_attenuation','cout_attenuation','statut','owner_user_id','created_at','updated_at'],
  bp_versions: ['id','business_plan_id','version_label','snapshot','validated_at','notes','owner_user_id','created_at','updated_at'],
  business_events: ['id','event_type','module_source','entity_type','entity_id','title','description','amount','event_date','linked_document_id','linked_transaction_id','linked_sale_id','severity','owner_user_id','created_at','updated_at'],
  business_plans: ['id','nom','activity_type','description','localisation','date_debut','date_fin_prevue','duree_cycle_mois','capacite_initiale','unite_capacite','objectif_production','statut','apport_personnel','financement_recherche','apport_total','taux_remboursement_pct','unite_calcul_cout','nombre_tetes_prevu','nombre_tetes_reel','quantite_production_prevue','quantite_production_reelle','prix_vente_prevu_unitaire','prix_vente_reel_unitaire','notes','owner_user_id','created_at','updated_at','mode_projection'],
  camera_devices: ['id','name','zone','type','stream_url','snapshot_url','status','last_seen_at','owner_user_id','created_at','updated_at'],
  client_receivables: ['id','client_id','sale_order_id','initial_amount','paid_amount','remaining_amount','status','due_date','notes','owner_user_id','created_at','updated_at','order_id'],
  clients: ['id','name','phone','type','preferences','total_spent','last_purchase','created_at','score','owner_user_id','updated_at','photo_url','whatsapp','email','adresse','gps','statut','historique_achats','historique_communications','notes_internes','nom','tel','totalachats','dernierecommande','prefs'],
  couts: ['id','type','montant','lot_id','date'],
  cultures: ['id','nom','type','variete','parcelle','surface','date_semis','date_repiquage','date_recolte_prevue','date_recolte_reelle','quantite_prevue','quantite_recoltee','pertes','rendement','cout_semences','cout_engrais','cout_eau','cout_main_oeuvre','cout_traitement','cout_total','revenu_estime','revenu_reel','marge_estimee','marge_reelle','statut','score_sante','historique','owner_user_id','created_at','updated_at','photo_url'],
  deliveries: ['id','order_id','date_livraison','statut','destinataire','adresse','notes','owner_user_id','created_at','updated_at'],
  documents: ['id','title','file_url','file_type','module_source','entity_type','entity_id','document_category','notes','owner_user_id','created_at','updated_at'],
  employes: ['id','name','role','salaire','performance','created_at'],
  equipment: ['id','name','type','status','purchase_date','purchase_cost','maintenance_due','fuel_cost','notes','owner_user_id','created_at','updated_at'],
  erp_documents: ['id','title','document_type','module_lie','related_id','file_url','status','tags','owner_user_id','created_at','updated_at'],
  finances: ['id','type','amount','description','date','category','payment','proof_url','note'],
  fournisseurs: ['id','name','phone','product','price','delivery_time','created_at','owner_user_id','updated_at','photo_url','statut','nom','tel','whatsapp','email','categorie','contact','note','dettes','livraisons','source','latitude','longitude','distance_km','external_id','verified','favorite','notes'],
  intervention_medications: ['id','intervention_id','stock_id','produit','posologie','duree_jours','delai_attente_jours','delai_attente_produit','quantite_utilisee','unite','notes','owner_user_id','created_at','updated_at'],
  investissements: ['id','type','montant','description','date','rentabilite_estimee','statut','name','objective','start_date','roi_est','owner_user_id','created_at','updated_at','libelle','roi','objectif','gain','business_plan_id'],
  investments: ['id','type','name','amount','objective','roi_est','status','start_date','created_at'],
  invoices: ['id','order_id','numero_facture','date_facture','montant_total','pdf_url','statut','owner_user_id','created_at','updated_at'],
  localisation: ['id','type','name','latitude','longitude'],
  logs: ['id','action','utilisateur','module','date'],
  lots: ['id','type','initial_count','current_count','mortality','weight_avg','phase','created_at','morts','vols','malades','oeufs_casses','taux_ponte','revenu_estime','marge','productionjour','owner_user_id','updated_at','photo_url','name','ic','scores_sante','vendus','reformes','sorties','frais_sante','health_status','status','autres_frais','prix_vente_prevu','prix_vente_reel','cout_poussins','date_debut','date_fin_prevue','date_fin_reelle','poids_objectif','effectif_vendable','sale_readiness_score','sale_readiness_status','pret_vente_recommande','pret_vente_confirme','date_pret_vente_recommande','date_pret_vente_confirme','raison_pret_vente','duree_cycle_valeur','duree_cycle_unite','age_lot_jours'],
  meteo: ['id','temperature','humidite','pluie','vent','date'],
  notifications: ['id','message','type','status','created_at'],
  objectifs: ['id','title','target','current','status','created_at'],
  offline_queue: ['id','module','operation','payload','status','conflict_strategy','device','owner_user_id','created_at','updated_at'],
  payments: ['id','order_id','invoice_id','date_paiement','montant','moyen_paiement','reference','notes','owner_user_id','created_at','updated_at'],
  price_catalog: ['id','item_name','categorie','unite','prix_unitaire','fournisseur_id','source','date_releve','notes','owner_user_id','created_at','updated_at'],
  production: ['id','lot_id','type','quantity','date'],
  production_oeufs_logs: ['id','lot_id','date','oeufs_produits','oeufs_casses','taux_ponte','notes','owner_user_id','created_at','updated_at'],
  push_subscriptions: ['id','user_id','label','channels','endpoint','subscription','created_at','updated_at','active','last_sent_at'],
  recommandations: ['id','type','message','priorite','statut','date'],
  reports: ['id','title','report_type','period','status','channel','file_url','summary','owner_user_id','created_at','updated_at'],
  reproduction_events: ['id','femelle_id','male_id','date_saillie','date_debut_gestation','date_prevue_mise_bas','date_mise_bas_reelle','resultat','nombre_petits','notes','owner_user_id','created_at','updated_at'],
  sales: ['id','date','client_id','type','produit','quantite','montant','statut','paiement','livraison_date','notes','owner_user_id','created_at','updated_at'],
  sales_opportunities: ['id','opportunity_type','source_type','source_id','title','description','quantity','unit','estimated_value','estimated_margin','score','reason','suggested_clients','status','detected_at','converted_sale_id','owner_user_id','created_at','updated_at'],
  sales_order_items: ['id','order_id','source_type','source_id','product_name','quantity','unit','unit_price','discount','total','cost_estimated','margin_estimated','owner_user_id','created_at','updated_at','item_type','label','available_quantity_snapshot','cost_snapshot','margin_snapshot','description','line_total'],
  sales_orders: ['id','date','client_id','type_document','statut_commande','statut_paiement','statut_livraison','montant_ht','remise','montant_total','montant_paye','reste_a_payer','moyen_paiement','notes','owner_user_id','created_at','updated_at','source_type','source_id','source_label','finance_transaction_id','receivable_id','invoice_document_id','impact_applied_at','cancelled_at','payment_method','total_amount','paid_amount','remaining_amount','payment_status','order_status','delivery_status'],
  sante: ['id','lot_id','type','description','date','status','name','animal','planned','done','vet','vet_phone'],
  score_ferme: ['id','productivite','sante','rentabilite','score_global','date'],
  security_events: ['id','actor','event_type','severity','device','ip_address','message','owner_user_id','created_at','updated_at'],
  sensor_devices: ['id','name','type','zone','location','status','last_seen_at','battery_level','owner_user_id','created_at','updated_at'],
  sensor_readings: ['id','device_id','metric','value','unit','payload','recorded_at','owner_user_id','created_at','updated_at'],
  stock: ['id','produit','quantite','seuil_alerte','date','unit','unit_price'],
  stocks: ['id','produit','categorie','quantite','unite','seuil','prixunit','created_at','updated_at','owner_user_id','photo_url','is_sellable'],
  system_settings: ['key','value','is_secret'],
};

export const ERP_REAL_TABLES = Object.keys(ERP_REAL_SCHEMA);

export const ERP_REAL_MODULES = {
  comptabilite: ['accounting_accounts','accounting_budgets','accounting_closures','accounting_documents','accounting_entries','accounting_entry_lines','finances','invoices','payments'],
  alertes: ['alert_events','alert_rules','alertes','alertes_center','alertes_history','alertes_settings','notifications','recommandations'],
  alimentation: ['alimentation','alimentation_logs'],
  animaux: ['animal_health_records','animal_purchases','animal_weight_records','animals','reproduction_events'],
  avicole: ['couts','lots','production','production_oeufs_logs'],
  investissements: ['bp_funding_sources','bp_investment_lines','bp_lines_history','bp_links','bp_recurring_costs','bp_revenue_projections','bp_risks','bp_versions','business_plans','investissements','investments'],
  clients: ['client_receivables','clients'],
  ventes: ['deliveries','invoices','payments','sales','sales_opportunities','sales_order_items','sales_orders'],
  cultures: ['cultures'],
  documents: ['accounting_documents','documents','erp_documents'],
  equipements: ['equipment'],
  finances: ['client_receivables','finances','payments'],
  fournisseurs: ['fournisseurs'],
  sante: ['animal_health_records','intervention_medications','sante'],
  smartfarm: ['camera_devices','meteo','sensor_devices','sensor_readings'],
  systeme: ['api_webhooks','audit_logs','automation_settings','logs','offline_queue','push_subscriptions','security_events','system_settings'],
};

export function getTablesForModule(module = '') {
  return ERP_REAL_MODULES[module] || [];
}

export function hasTable(table = '') {
  return Boolean(ERP_REAL_SCHEMA[table]);
}
