import { AlertTriangle, BarChart3, ClipboardList, FileText, Handshake, PackageCheck, ShoppingBag, Truck, Utensils, Warehouse } from 'lucide-react';
import { useMemo, useState } from 'react';
import { fmtCurrency, fmtNumber } from '../utils/format';

const arr = (value) => Array.isArray(value) ? value : [];
const lower = (value) => String(value || '').toLowerCase();
const n = (value = 0) => Number(value || 0);
const stockQty = (row = {}) => n(row.quantite ?? row.quantity ?? row.stock ?? row.disponible ?? row.quantity_available);
const stockThreshold = (row = {}) => n(row.seuil ?? row.threshold ?? row.stock_min ?? row.minimum_stock);
const stockValue = (row = {}) => stockQty(row) * n(row.prix_unitaire ?? row.unit_price ?? row.cout_unitaire ?? row.purchase_price ?? row.price);
const stockLabel = (row = {}) => row.produit || row.name || row.nom || row.libelle || row.title || row.id || 'Produit';
const supplierName = (row = {}) => row.nom || row.name || row.raison_sociale || row.title || row.id || 'Fournisseur';
const isFeed = (row = {}) => /aliment|feed|provende|son|mais|maïs|foin|fourrage/.test(lower(`${stockLabel(row)} ${row.categorie || row.category || ''}`));
const isPurchase = (row = {}) => /achat|approvisionnement|fournisseur|stock|aliment|entrée stock|entree stock/.test(lower(`${row.type || ''} ${row.categorie || ''} ${row.category || ''} ${row.libelle || ''} ${row.title || ''} ${row.module_source || ''}`));
const amountOf = (row = {}) => n(row.montant ?? row.amount ?? row.total ?? row.montant_total ?? row.cout ?? row.cost ?? row.prix_total);
const dateOf = (row = {}) => row.date || row.event_date || row.created_at || row.updated_at || '—';
const supplierDebt = (row = {}) => n(row.dettes ?? row.dette ?? row.solde ?? row.balance ?? row.reste_a_payer);
const movementQty = (row = {}) => n(row.quantite ?? row.quantity ?? row.qty ?? row.mouvement_quantite);
const movementLabel = (row = {}) => row.produit || row.product_name || row.stock_name || row.title || row.libelle || row.id || 'Mouvement';

function StatLine({ label, value, tone = 'neutral' }) {
  const cls = tone === 'good' ? 'text-emerald-600' : tone === 'warn' ? 'text-amber-600' : tone === 'bad' ? 'text-red-600' : 'text-[#2f2415]';
  return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="text-xs text-[#8a7456]">{label}</p><p className={`mt-1 text-xl font-black ${cls}`}>{value}</p></div>;
}
function Section({ icon: Icon, title, children, action }) {
  return <section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="flex items-center gap-2 text-lg font-black text-[#2f2415]"><Icon size={20} /> {title}</h2>{action}</div>{children}</section>;
}
function ActionButton({ children, onClick }) { return <button type="button" onClick={onClick} className="rounded-xl border border-[#d6c3a0] bg-[#fffdf8] px-3 py-2 text-xs font-black text-[#2f2415] hover:bg-[#dcfce7]">{children}</button>; }
function Pill({ children, tone = 'neutral' }) { const cls = tone === 'good' ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : tone === 'warn' ? 'border-amber-200 bg-amber-50 text-amber-700' : tone === 'bad' ? 'border-red-200 bg-red-50 text-red-700' : 'border-[#eadcc2] bg-[#fffdf8] text-[#8a7456]'; return <span className={`rounded-full border px-3 py-1 text-xs font-black ${cls}`}>{children}</span>; }
function DataRow({ title, detail, value, tone = 'neutral', onClick }) { return <button type="button" onClick={onClick} className="grid w-full grid-cols-1 gap-2 border-b border-[#eadcc2]/70 py-4 text-left last:border-b-0 md:grid-cols-[260px_1fr_auto] md:items-center hover:bg-[#fffdf8]"><span className="font-black text-[#2f2415]">{title}</span><span className="text-sm text-[#8a7456]">{detail}</span><Pill tone={tone}>{value}</Pill></button>; }
function FieldBox({ label, value }) { return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="text-xs text-[#8a7456]">{label}</p><p className="mt-1 font-black text-[#2f2415]">{value}</p></div>; }
function Empty({ label }) { return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-5 text-sm text-[#8a7456]">{label}</div>; }
function Tabs({ active, onChange }) { const tabs = ['Résumé', 'Stock', 'Achats', 'Fournisseurs', 'Alimentation', 'Alertes', 'Mouvements', 'Historique']; return <div className="overflow-x-auto"><div className="flex min-w-max gap-2 rounded-2xl border border-[#d6c3a0] bg-white p-2">{tabs.map((tab) => <button key={tab} type="button" onClick={() => onChange(tab)} className={`rounded-xl px-4 py-2 text-sm font-black transition ${active === tab ? 'bg-[#22c55e] text-[#052e16]' : 'text-[#8a7456] hover:bg-[#fffdf8] hover:text-[#2f2415]'}`}>{tab}</button>)}</div></div>; }

function SummaryTab({ data, setActiveTab }) {
  return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><StatLine label="Valeur stock" value={fmtCurrency(data.totalStockValue)} /><StatLine label="Sous seuil" value={fmtNumber(data.lowStock.length)} tone={data.lowStock.length ? 'warn' : 'good'} /><StatLine label="Achats suivis" value={fmtNumber(data.purchases.length)} /><StatLine label="Fournisseurs" value={fmtNumber(data.suppliers.length)} /><StatLine label="Aliment critique" value={fmtNumber(data.lowFeed.length)} tone={data.lowFeed.length ? 'warn' : 'good'} /></div><Section icon={AlertTriangle} title="Priorités" action={<ActionButton onClick={() => setActiveTab('Achats')}>Achat rapide</ActionButton>}>{data.priorities.length ? data.priorities.map((item) => <DataRow key={item.id} title={item.title} detail={item.detail} value={item.value} tone={item.tone} onClick={() => setActiveTab(item.tab)} />) : <Empty label="Aucune priorité stock." />}</Section><Section icon={ClipboardList} title="Actions rapides"><div className="flex flex-wrap gap-2"><ActionButton onClick={() => setActiveTab('Stock')}>Ajouter stock</ActionButton><ActionButton onClick={() => setActiveTab('Achats')}>Nouvel achat</ActionButton><ActionButton onClick={() => setActiveTab('Mouvements')}>Sortie stock</ActionButton><ActionButton onClick={() => setActiveTab('Fournisseurs')}>Fournisseur</ActionButton><ActionButton onClick={() => setActiveTab('Alertes')}>Alertes</ActionButton></div></Section></div>;
}
function StockTab({ data, selectedStock, setSelectedStock, setActiveTab }) {
  const selected = selectedStock || data.stocks[0];
  return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><StatLine label="Produits" value={fmtNumber(data.stocks.length)} /><StatLine label="Sous seuil" value={fmtNumber(data.lowStock.length)} tone={data.lowStock.length ? 'warn' : 'good'} /><StatLine label="Valeur" value={fmtCurrency(data.totalStockValue)} /><StatLine label="Alimentation" value={fmtNumber(data.feedStocks.length)} /></div><div className="grid grid-cols-1 gap-4 xl:grid-cols-[1fr_420px]"><Section icon={Warehouse} title="Inventaire" action={<ActionButton onClick={() => setActiveTab('Mouvements')}>Mouvements</ActionButton>}>{data.stocks.length ? data.stocks.slice(0, 14).map((row) => <DataRow key={row.id || stockLabel(row)} title={stockLabel(row)} detail={`${fmtNumber(stockQty(row))} disponible · seuil ${fmtNumber(stockThreshold(row))} · ${row.categorie || row.category || 'Stock'}`} value={stockQty(row) <= stockThreshold(row) ? 'Bas' : 'OK'} tone={stockQty(row) <= stockThreshold(row) ? 'warn' : 'good'} onClick={() => setSelectedStock(row)} />) : <Empty label="Aucun produit en stock." />}</Section><Section icon={PackageCheck} title="Fiche produit"><div className="space-y-3">{selected ? <><FieldBox label="Produit" value={stockLabel(selected)} /><FieldBox label="Quantité" value={fmtNumber(stockQty(selected))} /><FieldBox label="Seuil" value={fmtNumber(stockThreshold(selected))} /><FieldBox label="Catégorie" value={selected.categorie || selected.category || 'Stock'} /><FieldBox label="Valeur estimée" value={fmtCurrency(stockValue(selected))} /><FieldBox label="Statut" value={stockQty(selected) <= stockThreshold(selected) ? 'À réapprovisionner' : 'OK'} /></> : <Empty label="Aucun produit sélectionné." />}</div></Section></div></div>;
}
function PurchasesTab({ data, setActiveTab }) {
  return <div className="space-y-5"><Section icon={ShoppingBag} title="Achat rapide"><div className="grid grid-cols-1 gap-3 xl:grid-cols-4"><FieldBox label="Fournisseur" value="Choisir" /><FieldBox label="Produit" value="Choisir" /><FieldBox label="Quantité" value="À saisir" /><FieldBox label="Montant" value="À saisir" /></div><div className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">Une seule saisie doit pouvoir créer l’achat, l’entrée stock, la dépense finance, le document preuve et l’historique.</div></Section><Section icon={Truck} title="Achats suivis" action={<ActionButton onClick={() => setActiveTab('Fournisseurs')}>Fournisseurs</ActionButton>}>{data.purchases.length ? data.purchases.slice(0, 12).map((row) => <DataRow key={row.id || row.title || row.libelle} title={row.title || row.libelle || row.categorie || 'Achat'} detail={`${dateOf(row)} · ${row.fournisseur || row.supplier_name || row.supplier || 'Fournisseur non renseigné'}`} value={fmtCurrency(amountOf(row))} />) : <Empty label="Aucun achat détecté." />}</Section></div>;
}
function SuppliersTab({ data, selectedSupplier, setSelectedSupplier }) {
  const selected = selectedSupplier || data.suppliers[0];
  return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><StatLine label="Fournisseurs" value={fmtNumber(data.suppliers.length)} /><StatLine label="Dettes" value={fmtCurrency(data.supplierDebt)} tone={data.supplierDebt ? 'warn' : 'good'} /><StatLine label="À risque" value={fmtNumber(data.suppliersAtRisk.length)} tone={data.suppliersAtRisk.length ? 'warn' : 'good'} /><StatLine label="Achats" value={fmtNumber(data.purchases.length)} /></div><div className="grid grid-cols-1 gap-4 xl:grid-cols-[1fr_420px]"><Section icon={Handshake} title="Fournisseurs">{data.suppliers.length ? data.suppliers.slice(0, 12).map((row) => <DataRow key={row.id || supplierName(row)} title={supplierName(row)} detail={`${row.telephone || row.phone || row.contact || 'Contact non renseigné'} · dette ${fmtCurrency(supplierDebt(row))}`} value={supplierDebt(row) ? 'À régler' : 'OK'} tone={supplierDebt(row) ? 'warn' : 'good'} onClick={() => setSelectedSupplier(row)} />) : <Empty label="Aucun fournisseur." />}</Section><Section icon={Handshake} title="Fiche fournisseur"><div className="space-y-3">{selected ? <><FieldBox label="Fournisseur" value={supplierName(selected)} /><FieldBox label="Contact" value={selected.telephone || selected.phone || selected.contact || '—'} /><FieldBox label="Dette" value={fmtCurrency(supplierDebt(selected))} /><FieldBox label="Statut" value={selected.statut || selected.status || (supplierDebt(selected) ? 'À régler' : 'OK')} /><FieldBox label="Produits habituels" value={selected.produits || selected.products || selected.specialite || 'À renseigner'} /></> : <Empty label="Aucun fournisseur sélectionné." />}</div></Section></div></div>;
}
function FeedTab({ data, setActiveTab }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><StatLine label="Produits aliment" value={fmtNumber(data.feedStocks.length)} /><StatLine label="Sous seuil" value={fmtNumber(data.lowFeed.length)} tone={data.lowFeed.length ? 'warn' : 'good'} /><StatLine label="Consommation" value={fmtNumber(data.feedConsumption)} /><StatLine label="Mouvements" value={fmtNumber(data.feedLogs.length)} /></div><Section icon={Utensils} title="Alimentation" action={<ActionButton onClick={() => setActiveTab('Achats')}>Acheter aliment</ActionButton>}>{data.feedStocks.length ? data.feedStocks.slice(0, 12).map((row) => <DataRow key={row.id || stockLabel(row)} title={stockLabel(row)} detail={`${fmtNumber(stockQty(row))} disponible · seuil ${fmtNumber(stockThreshold(row))}`} value={stockQty(row) <= stockThreshold(row) ? 'Bas' : 'OK'} tone={stockQty(row) <= stockThreshold(row) ? 'warn' : 'good'} />) : <Empty label="Aucun stock aliment." />}</Section></div>; }
function AlertsTab({ data, setActiveTab }) { return <Section icon={AlertTriangle} title="Alertes stock" action={<ActionButton onClick={() => setActiveTab('Achats')}>Réapprovisionner</ActionButton>}>{data.alerts.length ? data.alerts.map((item) => <DataRow key={item.id} title={item.title} detail={item.detail} value={item.value} tone={item.tone} onClick={() => setActiveTab(item.tab)} />) : <Empty label="Aucune alerte stock." />}</Section>; }
function MovementsTab({ data }) { return <Section icon={Truck} title="Mouvements stock">{data.movements.length ? data.movements.slice(0, 14).map((row) => <DataRow key={row.id || row.title || movementLabel(row)} title={movementLabel(row)} detail={`${dateOf(row)} · ${row.type || row.movement_type || row.categorie || 'Mouvement'}`} value={fmtNumber(movementQty(row))} />) : <Empty label="Aucun mouvement stock." />}</Section>; }
function HistoryTab({ data }) { return <Section icon={ClipboardList} title="Historique">{data.events.length ? data.events.slice(0, 14).map((event) => <DataRow key={event.id || event.title} title={event.title || event.event_type || 'Événement'} detail={dateOf(event)} value={event.severity || event.status || 'Suivi'} tone={['warning', 'critique', 'critical'].includes(lower(event.severity || event.status)) ? 'warn' : 'neutral'} />) : <Empty label="Aucun historique achats/stock." />}</Section>; }
function GraphsTab({ data }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><StatLine label="Valeur stock" value={fmtCurrency(data.totalStockValue)} /><StatLine label="Sous seuil" value={fmtNumber(data.lowStock.length)} tone={data.lowStock.length ? 'warn' : 'good'} /><StatLine label="Achats" value={fmtCurrency(data.purchaseAmount)} /><StatLine label="Dettes fournisseurs" value={fmtCurrency(data.supplierDebt)} /></div><Section icon={BarChart3} title="Graphiques"><div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-5"><div className="space-y-4"><div><div className="mb-1 flex justify-between text-xs text-[#8a7456]"><span>Stock sain</span><span>{fmtNumber(Math.max(0, data.stocks.length - data.lowStock.length))}</span></div><div className="h-3 rounded-full bg-[#e8f3e8]"><div className="h-3 rounded-full bg-[#22c55e]" style={{ width: `${data.stocks.length ? Math.min(100, ((data.stocks.length - data.lowStock.length) / data.stocks.length) * 100) : 0}%` }} /></div></div><div><div className="mb-1 flex justify-between text-xs text-[#8a7456]"><span>Stock sous seuil</span><span>{fmtNumber(data.lowStock.length)}</span></div><div className="h-3 rounded-full bg-[#e8f3e8]"><div className="h-3 rounded-full bg-amber-500" style={{ width: `${data.stocks.length ? Math.min(100, (data.lowStock.length / data.stocks.length) * 100) : 0}%` }} /></div></div></div></div></Section></div>; }

export default function AchatsStockModule({ stocks = [], fournisseurs = [], suppliers = [], transactions = [], finances = [], alimentationLogs = [], businessEvents = [], alertes = [], documents = [] }) {
  const [activeTab, setActiveTab] = useState('Résumé');
  const [selectedStock, setSelectedStock] = useState(null);
  const [selectedSupplier, setSelectedSupplier] = useState(null);
  const data = useMemo(() => {
    const stockRows = arr(stocks);
    const supplierRows = arr(fournisseurs).length ? arr(fournisseurs) : arr(suppliers);
    const txRows = [...arr(transactions), ...arr(finances)].filter(Boolean);
    const purchaseRows = txRows.filter(isPurchase);
    const feedStocks = stockRows.filter(isFeed);
    const lowStock = stockRows.filter((row) => stockThreshold(row) > 0 && stockQty(row) <= stockThreshold(row));
    const lowFeed = feedStocks.filter((row) => stockThreshold(row) > 0 && stockQty(row) <= stockThreshold(row));
    const totalStockValue = stockRows.reduce((sum, row) => sum + stockValue(row), 0);
    const supplierDebtTotal = supplierRows.reduce((sum, row) => sum + supplierDebt(row), 0);
    const supplierRisk = supplierRows.filter((row) => supplierDebt(row) > 0 || ['a_risque', 'retard', 'bloque'].includes(lower(row.statut || row.status)));
    const feedLogs = arr(alimentationLogs);
    const feedConsumption = feedLogs.reduce((sum, row) => sum + n(row.quantite ?? row.quantity ?? row.qty), 0);
    const events = arr(businessEvents).filter((event) => /stock|achat|fournisseur|aliment|approvisionnement/.test(lower(`${event.module_source || event.module || ''} ${event.event_type || ''} ${event.title || ''}`)));
    const alertRows = arr(alertes).filter((alert) => /stock|achat|fournisseur|aliment|approvisionnement/.test(lower(`${alert.module_source || alert.module || ''} ${alert.title || ''} ${alert.message || ''}`)));
    const movementRows = [...feedLogs, ...events, ...purchaseRows].slice(0, 80);
    const alerts = [
      ...lowStock.slice(0, 8).map((row) => ({ id: `stock-${row.id || stockLabel(row)}`, title: stockLabel(row), detail: `${fmtNumber(stockQty(row))} disponible · seuil ${fmtNumber(stockThreshold(row))}`, value: 'Acheter', tone: 'warn', tab: 'Achats' })),
      ...supplierRisk.slice(0, 5).map((row) => ({ id: `supplier-${row.id || supplierName(row)}`, title: supplierName(row), detail: `Dette ${fmtCurrency(supplierDebt(row))}`, value: 'À régler', tone: 'warn', tab: 'Fournisseurs' })),
      ...alertRows.slice(0, 5).map((row) => ({ id: `alert-${row.id || row.title}`, title: row.title || 'Alerte stock', detail: row.message || row.description || dateOf(row), value: row.severity || 'Alerte', tone: 'warn', tab: 'Alertes' })),
    ].slice(0, 18);
    const priorities = alerts.slice(0, 6);
    const purchaseAmount = purchaseRows.reduce((sum, row) => sum + amountOf(row), 0);
    return { stocks: stockRows, suppliers: supplierRows, purchases: purchaseRows, feedStocks, lowStock, lowFeed, totalStockValue, supplierDebt: supplierDebtTotal, suppliersAtRisk: supplierRisk, feedLogs, feedConsumption, events, alertRows, alerts, priorities, movements: movementRows, purchaseAmount, documents: arr(documents) };
  }, [stocks, fournisseurs, suppliers, transactions, finances, alimentationLogs, businessEvents, alertes, documents]);

  const content = activeTab === 'Résumé' ? <SummaryTab data={data} setActiveTab={setActiveTab} /> : activeTab === 'Stock' ? <StockTab data={data} selectedStock={selectedStock} setSelectedStock={setSelectedStock} setActiveTab={setActiveTab} /> : activeTab === 'Achats' ? <PurchasesTab data={data} setActiveTab={setActiveTab} /> : activeTab === 'Fournisseurs' ? <SuppliersTab data={data} selectedSupplier={selectedSupplier} setSelectedSupplier={setSelectedSupplier} /> : activeTab === 'Alimentation' ? <FeedTab data={data} setActiveTab={setActiveTab} /> : activeTab === 'Alertes' ? <AlertsTab data={data} setActiveTab={setActiveTab} /> : activeTab === 'Mouvements' ? <MovementsTab data={data} /> : activeTab === 'Historique' ? <HistoryTab data={data} /> : <GraphsTab data={data} />;

  return <div className="space-y-6"><div className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs uppercase tracking-[0.25em] text-[#9a6b12] font-black">Gestion</p><h1 className="mt-1 text-2xl font-black text-[#2f2415]">Achats & Stock</h1></div><div className="flex flex-wrap gap-2"><ActionButton onClick={() => setActiveTab('Achats')}>Achat rapide</ActionButton><ActionButton onClick={() => setActiveTab('Stock')}>Stock</ActionButton><ActionButton onClick={() => setActiveTab('Fournisseurs')}>Fournisseurs</ActionButton></div></div></div><Tabs active={activeTab} onChange={setActiveTab} />{content}</div>;
}
