import { ClipboardList, Database, Lock, RefreshCw, ShieldAlert, ShieldCheck, UserCog, Wifi, WifiOff } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { canPerformSystemAction } from '../utils/systemAccessWorkflows';

const arr = (v) => Array.isArray(v) ? v : [];
const low = (v) => String(v || '').toLowerCase();
const open = (r = {}) => !['termine','terminé','done','closed','clos','résolu','resolu'].includes(low(r.status || r.statut));
const late = (r = {}) => ['retard','overdue','en_retard'].includes(low(r.status || r.statut));
const title = (r = {}) => r.title || r.nom || r.name || r.event_type || r.libelle || r.id || 'Élément';
const dateOf = (r = {}) => r.event_date || r.date || r.created_at || r.updated_at || '—';
function Stat({ label, value, tone = 'neutral' }) { const cls = tone === 'good' ? 'text-emerald-600' : tone === 'warn' ? 'text-amber-600' : 'text-[#2f2415]'; return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="text-xs text-[#8a7456]">{label}</p><p className={`mt-1 text-xl font-black ${cls}`}>{value}</p></div>; }
function Section({ icon: Icon, title, children }) { return <section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><h2 className="mb-4 flex items-center gap-2 text-lg font-black text-[#2f2415]"><Icon size={20} /> {title}</h2>{children}</section>; }
function Pill({ children, tone = 'neutral' }) { const cls = tone === 'good' ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : tone === 'warn' ? 'border-amber-200 bg-amber-50 text-amber-700' : 'border-[#eadcc2] bg-[#fffdf8] text-[#8a7456]'; return <span className={`rounded-full border px-3 py-1 text-xs font-black ${cls}`}>{children}</span>; }
function Row({ title, detail, value, tone = 'neutral' }) { return <div className="grid grid-cols-1 gap-2 border-b border-[#eadcc2]/70 py-4 last:border-b-0 md:grid-cols-[260px_1fr_auto] md:items-center"><b className="text-[#2f2415]">{title}</b><span className="text-sm text-[#8a7456]">{detail}</span><Pill tone={tone}>{value}</Pill></div>; }
function Field({ icon: Icon, title, text }) { return <div className="rounded-3xl border border-[#eadcc2] bg-[#fffdf8] p-5"><Icon size={20} className="text-[#9a6b12]" /><p className="mt-3 font-black text-[#2f2415]">{title}</p><p className="mt-1 text-sm text-[#8a7456]">{text}</p></div>; }
export default function AdminSyncModule({ online = true, lastOnlineAt, tasks = [], taches = [], alertes = [], businessEvents = [], auditLogs = [], equipements = [], transactions = [], finances = [], documents = [], onRefreshAll, onFlushOffline }) {
  const { role } = useAuth();
  const taskRows = arr(tasks).length ? arr(tasks) : arr(taches);
  const trxRows = arr(transactions).length ? arr(transactions) : arr(finances);
  const openTasks = taskRows.filter(open);
  const lateTasks = taskRows.filter(late);
  const openAlerts = arr(alertes).filter(open);
  const canManage = canPerformSystemAction(role, 'modifier');
  const checks = [
    { title: 'Connexion ERP', detail: lastOnlineAt ? `Dernière connexion : ${lastOnlineAt}` : 'État actuel de l’application', value: online ? 'En ligne' : 'Hors ligne', tone: online ? 'good' : 'warn' },
    { title: 'Actions terrain', detail: `${openTasks.length} tâche(s) ouverte(s), ${lateTasks.length} en retard`, value: lateTasks.length ? 'Priorité' : 'OK', tone: lateTasks.length ? 'warn' : 'good' },
    { title: 'Alertes', detail: `${openAlerts.length} alerte(s) non clôturée(s)`, value: openAlerts.length ? 'À traiter' : 'OK', tone: openAlerts.length ? 'warn' : 'good' },
    { title: 'Accès utilisateur', detail: canManage ? 'Le rôle actuel peut administrer les réglages.' : 'Le rôle actuel est limité en lecture.', value: canManage ? 'Admin' : 'Lecture', tone: canManage ? 'good' : 'warn' },
    { title: 'Données financières', detail: `${trxRows.length} mouvement(s) suivis dans Finance & Pilotage.`, value: 'Suivi' },
    { title: 'Documents', detail: `${arr(documents).length} document(s) suivis dans Documents & Rapports.`, value: 'Suivi' },
    { title: 'Ressources', detail: `${arr(equipements).length} équipement(s) suivis dans Opérations & Ressources.`, value: 'Suivi' },
  ];
  return <div className="space-y-6"><section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs uppercase tracking-[0.25em] text-[#9a6b12] font-black">Administration</p><h1 className="mt-1 text-2xl font-black text-[#2f2415]">Administration & Sync</h1><p className="mt-1 text-sm text-[#8a7456]">Synchronisation, accès, sécurité et état global de l’ERP dans un seul espace.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={onRefreshAll} className="rounded-xl border border-[#d6c3a0] bg-[#fffdf8] px-3 py-2 text-xs font-black text-[#2f2415]"><RefreshCw size={14} className="inline mr-1" /> Actualiser</button><button type="button" onClick={onFlushOffline} className="rounded-xl border border-[#d6c3a0] bg-[#fffdf8] px-3 py-2 text-xs font-black text-[#2f2415]">Synchroniser</button></div></div></section><div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><Stat label="Connexion" value={online ? 'En ligne' : 'Hors ligne'} tone={online ? 'good' : 'warn'} /><Stat label="Rôle" value={role || 'Utilisateur'} tone={canManage ? 'good' : 'warn'} /><Stat label="Retards" value={lateTasks.length} tone={lateTasks.length ? 'warn' : 'good'} /><Stat label="Alertes" value={openAlerts.length} tone={openAlerts.length ? 'warn' : 'good'} /><Stat label="Logs" value={arr(auditLogs).length} /></div><Section icon={online ? Wifi : WifiOff} title="État & contrôles">{checks.map((item) => <Row key={item.title} {...item} />)}</Section><section className="grid grid-cols-1 gap-4 lg:grid-cols-3"><Field icon={UserCog} title="Utilisateurs" text="Gérer les rôles et accès selon les responsabilités." /><Field icon={Database} title="Données" text="Contrôler les volumes et la cohérence des informations ERP." /><Field icon={Lock} title="Sécurité" text="Les actions sensibles restent réservées aux profils autorisés." /></section><Section icon={ClipboardList} title="Dernière activité">{arr(businessEvents).slice(0, 8).map((event) => <Row key={event.id || title(event)} title={title(event)} detail={dateOf(event)} value={event.severity || event.status || 'Suivi'} tone={open(event) ? 'neutral' : 'good'} />)}</Section><section className={`rounded-3xl border p-5 ${canManage ? 'border-emerald-200 bg-emerald-50' : 'border-amber-200 bg-amber-50'}`}><h2 className={`flex items-center gap-2 font-black ${canManage ? 'text-emerald-800' : 'text-amber-800'}`}>{canManage ? <ShieldCheck size={18} /> : <ShieldAlert size={18} />}{canManage ? 'Actions admin autorisées' : 'Lecture seule'}</h2><p className={`mt-1 text-sm ${canManage ? 'text-emerald-800' : 'text-amber-800'}`}>Ce module fusionne la synchronisation et la gestion système sans exposer des détails techniques inutiles.</p></section></div>;
}
