import { AlertTriangle, CheckCircle2, CreditCard, MessageCircle, Receipt, Users } from 'lucide-react';
import { analyzeClientIntegrity } from '../services/clientIntegrityService';
import { fmtCurrency } from '../utils/format';

const label = (row = {}) => row.nom || row.name || row.product_name || row.libelle || row.id || 'Élément';
function Card({ icon: Icon, label, value, danger = false }) { return <div className={`rounded-2xl border p-4 ${danger ? 'border-red-200 bg-red-50' : 'border-[#eadcc2] bg-[#fffdf8]'}`}><p className="flex items-center gap-2 text-xs uppercase tracking-wide text-[#8a7456]"><Icon size={14} /> {label}</p><p className={`mt-2 text-xl font-black ${danger ? 'text-red-600' : 'text-[#2f2415]'}`}>{value}</p></div>; }
export default function ClientQualityControl({ rows = [], salesOrders = [], payments = [], transactions = [] }) {
  const audit = analyzeClientIntegrity({ clients: rows, salesOrders, payments, transactions });
  const contact = audit.issues.filter((i) => i.type.includes('Contact')).length;
  const creance = audit.issues.filter((i) => i.type.includes('Créance') || i.type.includes('soldé')).length;
  const ventes = audit.issues.filter((i) => i.type.includes('Vente')).length;
  const pay = audit.issues.filter((i) => i.type.includes('Paiement')).length;
  return <section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm space-y-4"><div className="flex flex-col md:flex-row md:items-start md:justify-between gap-3"><div><p className="flex items-center gap-2 text-lg font-black text-[#2f2415]"><Users size={20} /> Contrôle clients, créances & paiements</p><p className="mt-1 text-sm text-[#8a7456]">Repère les clients mal liés, créances sans relance, paiements orphelins et ventes sans client.</p></div><div className={`${audit.issueCount ? 'bg-amber-50 text-amber-800 border-amber-200' : 'bg-emerald-50 text-emerald-800 border-emerald-200'} rounded-2xl border px-4 py-3 text-sm font-bold`}>{audit.issueCount ? `${audit.issueCount} point(s) à vérifier` : 'Clients cohérents'}</div></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Card icon={MessageCircle} label="Contacts manquants" value={contact} danger={contact > 0} /><Card icon={AlertTriangle} label="Créances / relances" value={creance} danger={creance > 0} /><Card icon={Receipt} label="Ventes à relier" value={ventes} danger={ventes > 0} /><Card icon={CreditCard} label="Paiements à relier" value={pay} danger={pay > 0} /></div>{audit.issueCount ? <div className="overflow-x-auto rounded-2xl border border-[#eadcc2]"><table className="min-w-full text-sm"><thead><tr className="border-b border-[#eadcc2] bg-[#fffdf8] text-left text-xs uppercase text-[#8a7456]"><th className="py-2 px-3">Élément</th><th className="py-2 px-3">Problème</th><th className="py-2 px-3">Montant</th></tr></thead><tbody>{audit.issues.slice(0, 12).map((issue, i) => <tr key={`${issue.id}-${i}`} className="border-b border-[#f0e5d0]"><td className="py-3 px-3 font-bold text-[#2f2415]">{label(issue.client || issue.order || issue.payment || issue)}</td><td className="py-3 px-3"><span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-700">{issue.type}</span></td><td className="py-3 px-3">{issue.amount ? fmtCurrency(issue.amount) : '—'}</td></tr>)}</tbody></table></div> : <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 size={16} className="inline" /> Aucune incohérence critique détectée côté clients.</div>}</section>;
}
