import { BarChart3, ClipboardList, Droplets, Leaf, PackageCheck, Scissors, Sprout, Tractor, Wheat } from 'lucide-react';
import { useMemo, useState } from 'react';
import { fmtCurrency, fmtNumber } from '../utils/format';

const arr = (v) => Array.isArray(v) ? v : [];
const low = (v) => String(v || '').toLowerCase();
const num = (v = 0) => Number(v || 0);
const labelOf = (r = {}) => r.nom || r.name || r.culture || r.title || r.libelle || r.id || 'Culture';
const parcelOf = (r = {}) => r.parcelle || r.parcelle_nom || r.field_name || r.zone || r.emplacement || 'Parcelle non renseignée';
const statusOf = (r = {}) => r.statut || r.status || r.etat || 'En suivi';
const dateOf = (r = {}) => r.date || r.date_semis || r.planting_date || r.created_at || r.updated_at || '—';
const areaOf = (r = {}) => num(r.surface || r.area || r.superficie || r.hectares);
const harvestQty = (r = {}) => num(r.stock_recolte ?? r.quantite_recoltee ?? r.quantite_disponible ?? r.quantity_available ?? r.recolte ?? r.harvest_qty);
const scoreOf = (r = {}) => num(r.score_sante ?? r.health_score ?? r.score ?? 100);
const isRisk = (r = {}) => scoreOf(r) < 80 || ['risque', 'malade', 'perdu', 'stress', 'attaque'].includes(low(statusOf(r)));
const isHarvested = (r = {}) => harvestQty(r) > 0 || ['recolte', 'récolté', 'harvested'].includes(low(statusOf(r)));
const amountOf = (r = {}) => num(r.montant || r.amount || r.total || r.cout || r.cost);
const stockLabel = (r = {}) => r.produit || r.name || r.nom || r.libelle || r.title || 'Intrant';
const isInput = (r = {}) => /semence|engrais|fertilisant|pesticide|fongicide|insecticide|herbicide|intrant|npk|uree|urée/.test(low(`${stockLabel(r)} ${r.categorie || r.category || ''}`));
const isCultureEvent = (r = {}) => /culture|parcelle|semis|recolte|récolte|irrigation|traitement|intrant/.test(low(`${r.module_source || r.module || ''} ${r.event_type || ''} ${r.title || ''} ${r.description || ''}`));

function Stat({ label, value, tone = 'neutral' }) {
  const cls = tone === 'good' ? 'text-emerald-600' : tone === 'warn' ? 'text-amber-600' : tone === 'bad' ? 'text-red-600' : 'text-[#2f2415]';
  return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="text-xs text-[#8a7456]">{label}</p><p className={`mt-1 text-xl font-black ${cls}`}>{value}</p></div>;
}
function Section({ icon: Icon, title, children, action }) { return <section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="flex items-center gap-2 text-lg font-black text-[#2f2415]"><Icon size={20} /> {title}</h2>{action}</div>{children}</section>; }
function Button({ children, onClick }) { return <button type="button" onClick={onClick} className="rounded-xl border border-[#d6c3a0] bg-[#fffdf8] px-3 py-2 text-xs font-black text-[#2f2415] hover:bg-[#dcfce7]">{children}</button>; }
function Pill({ children, tone = 'neutral' }) { const cls = tone === 'good' ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : tone === 'warn' ? 'border-amber-200 bg-amber-50 text-amber-700' : tone === 'bad' ? 'border-red-200 bg-red-50 text-red-700' : 'border-[#eadcc2] bg-[#fffdf8] text-[#8a7456]'; return <span className={`rounded-full border px-3 py-1 text-xs font-black ${cls}`}>{children}</span>; }
function Row({ title, detail, value, tone = 'neutral', onClick }) { return <button type="button" onClick={onClick} className="grid w-full grid-cols-1 gap-2 border-b border-[#eadcc2]/70 py-4 text-left last:border-b-0 md:grid-cols-[260px_1fr_auto] md:items-center hover:bg-[#fffdf8]"><span className="font-black text-[#2f2415]">{title}</span><span className="text-sm text-[#8a7456]">{detail}</span><Pill tone={tone}>{value}</Pill></button>; }
function Field({ label, value }) { return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="text-xs text-[#8a7456]">{label}</p><p className="mt-1 font-black text-[#2f2415]">{value}</p></div>; }
function Empty({ label }) { return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-5 text-sm text-[#8a7456]">{label}</div>; }
function Tabs({ active, onChange }) { const tabs = ['Résumé', 'Parcelles', 'Cultures', 'Travaux', 'Récoltes', 'Intrants', 'Santé', 'Historique', 'Graphiques']; return <div className="overflow-x-auto"><div className="flex min-w-max gap-2 rounded-2xl border border-[#d6c3a0] bg-white p-2">{tabs.map((tab) => <button key={tab} type="button" onClick={() => onChange(tab)} className={`rounded-xl px-4 py-2 text-sm font-black transition ${active === tab ? 'bg-[#22c55e] text-[#052e16]' : 'text-[#8a7456] hover:bg-[#fffdf8] hover:text-[#2f2415]'}`}>{tab}</button>)}</div></div>; }

function Summary({ data, setTab }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><Stat label="Cultures" value={fmtNumber(data.cultures.length)} /><Stat label="Parcelles" value={fmtNumber(data.parcels.length)} /><Stat label="À risque" value={fmtNumber(data.riskCultures.length)} tone={data.riskCultures.length ? 'warn' : 'good'} /><Stat label="Récoltes" value={fmtNumber(data.harvested.length)} tone="good" /><Stat label="Intrants" value={fmtNumber(data.inputs.length)} /></div><Section icon={ClipboardList} title="Priorités cultures" action={<Button onClick={() => setTab('Travaux')}>Voir travaux</Button>}>{data.priorities.length ? data.priorities.map((item) => <Row key={item.id} title={item.title} detail={item.detail} value={item.value} tone={item.tone} onClick={() => setTab(item.tab)} />) : <Empty label="Aucune priorité culture." />}</Section></div>; }
function Parcels({ data, setTab }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Parcelles" value={fmtNumber(data.parcels.length)} /><Stat label="Surface" value={`${fmtNumber(data.totalArea)} ha`} /><Stat label="Occupées" value={fmtNumber(data.parcels.filter((p) => p.count > 0).length)} /><Stat label="À risque" value={fmtNumber(data.parcels.filter((p) => p.risk > 0).length)} tone={data.parcels.some((p) => p.risk > 0) ? 'warn' : 'good'} /></div><Section icon={Sprout} title="Parcelles">{data.parcels.length ? data.parcels.map((p) => <Row key={p.name} title={p.name} detail={`${fmtNumber(p.count)} culture(s) · ${fmtNumber(p.area)} ha`} value={p.risk ? 'À suivre' : 'OK'} tone={p.risk ? 'warn' : 'good'} onClick={() => setTab('Cultures')} />) : <Empty label="Aucune parcelle renseignée." />}</Section></div>; }
function CulturesTab({ data, selected, setSelected, setTab }) { const row = selected || data.cultures[0]; return <div className="grid grid-cols-1 gap-4 xl:grid-cols-[1fr_420px]"><Section icon={Wheat} title="Fiches cultures" action={<Button onClick={() => setTab('Santé')}>Santé</Button>}>{data.cultures.length ? data.cultures.slice(0, 14).map((c) => <Row key={c.id || labelOf(c)} title={labelOf(c)} detail={`${parcelOf(c)} · ${dateOf(c)} · ${statusOf(c)}`} value={isRisk(c) ? 'À suivre' : isHarvested(c) ? 'Récolte' : 'OK'} tone={isRisk(c) ? 'warn' : isHarvested(c) ? 'good' : 'neutral'} onClick={() => setSelected(c)} />) : <Empty label="Aucune culture." />}</Section><Section icon={Leaf} title="Fiche sélectionnée"><div className="space-y-3">{row ? <><Field label="Culture" value={labelOf(row)} /><Field label="Parcelle" value={parcelOf(row)} /><Field label="Statut" value={statusOf(row)} /><Field label="Surface" value={`${fmtNumber(areaOf(row))} ha`} /><Field label="Score santé" value={`${fmtNumber(scoreOf(row))}/100`} /><Field label="Récolte disponible" value={fmtNumber(harvestQty(row))} /></> : <Empty label="Aucune culture sélectionnée." />}</div></Section></div>; }
function Works({ data, setTab }) { return <Section icon={Tractor} title="Travaux agricoles" action={<Button onClick={() => setTab('Intrants')}>Intrants</Button>}>{data.works.length ? data.works.slice(0, 14).map((e) => <Row key={e.id || labelOf(e)} title={labelOf(e)} detail={`${dateOf(e)} · ${e.module_source || e.module || e.event_type || 'Travail'}`} value={e.status || e.statut || 'Suivi'} tone={isCultureEvent(e) ? 'neutral' : 'good'} />) : <Empty label="Aucun travail agricole enregistré." />}</Section>; }
function Harvests({ data }) { return <Section icon={Scissors} title="Récoltes">{data.harvested.length ? data.harvested.slice(0, 14).map((c) => <Row key={c.id || labelOf(c)} title={labelOf(c)} detail={`${parcelOf(c)} · stock récolte ${fmtNumber(harvestQty(c))}`} value="Disponible" tone="good" />) : <Empty label="Aucune récolte disponible." />}</Section>; }
function Inputs({ data, setTab }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Intrants" value={fmtNumber(data.inputs.length)} /><Stat label="Sous seuil" value={fmtNumber(data.lowInputs.length)} tone={data.lowInputs.length ? 'warn' : 'good'} /><Stat label="Coût travaux" value={fmtCurrency(data.workCost)} /><Stat label="Mouvements" value={fmtNumber(data.inputEvents.length)} /></div><Section icon={PackageCheck} title="Intrants cultures" action={<Button onClick={() => setTab('Travaux')}>Travaux</Button>}>{data.inputs.length ? data.inputs.slice(0, 14).map((s) => <Row key={s.id || stockLabel(s)} title={stockLabel(s)} detail={`${fmtNumber(num(s.quantite ?? s.quantity ?? s.stock))} disponible · seuil ${fmtNumber(num(s.seuil ?? s.threshold))}`} value={num(s.seuil ?? s.threshold) && num(s.quantite ?? s.quantity ?? s.stock) <= num(s.seuil ?? s.threshold) ? 'Bas' : 'OK'} tone={num(s.seuil ?? s.threshold) && num(s.quantite ?? s.quantity ?? s.stock) <= num(s.seuil ?? s.threshold) ? 'warn' : 'good'} />) : <Empty label="Aucun intrant culture." />}</Section></div>; }
function Health({ data, setTab }) { return <Section icon={Droplets} title="Santé végétale" action={<Button onClick={() => setTab('Travaux')}>Planifier travail</Button>}>{data.riskCultures.length ? data.riskCultures.slice(0, 14).map((c) => <Row key={c.id || labelOf(c)} title={labelOf(c)} detail={`${parcelOf(c)} · score ${fmtNumber(scoreOf(c))}/100 · ${statusOf(c)}`} value="À traiter" tone="warn" />) : <Empty label="Aucune culture à risque." />}</Section>; }
function History({ data }) { return <Section icon={ClipboardList} title="Historique cultures">{data.history.length ? data.history.slice(0, 16).map((e) => <Row key={e.id || labelOf(e)} title={labelOf(e)} detail={`${dateOf(e)} · ${e.module_source || e.module || 'Culture'}`} value={e.status || e.statut || e.event_type || 'Suivi'} />) : <Empty label="Aucun historique culture." />}</Section>; }
function Graphs({ data }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Cultures" value={fmtNumber(data.cultures.length)} /><Stat label="Récoltes" value={fmtNumber(data.harvested.length)} tone="good" /><Stat label="À risque" value={fmtNumber(data.riskCultures.length)} tone={data.riskCultures.length ? 'warn' : 'good'} /><Stat label="Surface" value={`${fmtNumber(data.totalArea)} ha`} /></div><Section icon={BarChart3} title="Graphiques"><div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-5"><div className="space-y-4"><div><div className="mb-1 flex justify-between text-xs text-[#8a7456]"><span>Cultures saines</span><span>{fmtNumber(data.cultures.length - data.riskCultures.length)}</span></div><div className="h-3 rounded-full bg-[#e8f3e8]"><div className="h-3 rounded-full bg-[#22c55e]" style={{ width: `${data.cultures.length ? Math.min(100, ((data.cultures.length - data.riskCultures.length) / data.cultures.length) * 100) : 0}%` }} /></div></div><div><div className="mb-1 flex justify-between text-xs text-[#8a7456]"><span>Récoltes disponibles</span><span>{fmtNumber(data.harvested.length)}</span></div><div className="h-3 rounded-full bg-[#e8f3e8]"><div className="h-3 rounded-full bg-[#22c55e]" style={{ width: `${data.cultures.length ? Math.min(100, (data.harvested.length / data.cultures.length) * 100) : 0}%` }} /></div></div></div></div></Section></div>; }

export default function CulturesModule({ rows = [], cultures = [], stocks = [], transactions = [], finances = [], businessEvents = [], opportunities = [] }) {
  const [tab, setTab] = useState('Résumé');
  const [selectedCulture, setSelectedCulture] = useState(null);
  const data = useMemo(() => {
    const cultureRows = arr(rows).length ? arr(rows) : arr(cultures);
    const riskCultures = cultureRows.filter(isRisk);
    const harvested = cultureRows.filter(isHarvested);
    const inputs = arr(stocks).filter(isInput);
    const lowInputs = inputs.filter((s) => num(s.seuil ?? s.threshold) > 0 && num(s.quantite ?? s.quantity ?? s.stock) <= num(s.seuil ?? s.threshold));
    const events = arr(businessEvents).filter(isCultureEvent);
    const works = events.filter((e) => /semis|travail|irrigation|traitement|fertilisation|recolte|récolte|culture/.test(low(`${e.event_type || ''} ${e.title || ''}`)));
    const inputEvents = events.filter((e) => /intrant|engrais|semence|traitement|pesticide/.test(low(`${e.event_type || ''} ${e.title || ''}`)));
    const workCost = [...arr(transactions), ...arr(finances), ...events].reduce((sum, r) => sum + (isCultureEvent(r) ? amountOf(r) : 0), 0);
    const parcelMap = new Map();
    cultureRows.forEach((c) => { const name = parcelOf(c); const prev = parcelMap.get(name) || { name, count: 0, area: 0, risk: 0 }; prev.count += 1; prev.area += areaOf(c); prev.risk += isRisk(c) ? 1 : 0; parcelMap.set(name, prev); });
    const parcels = [...parcelMap.values()];
    const totalArea = cultureRows.reduce((sum, c) => sum + areaOf(c), 0);
    const priorities = [...riskCultures.slice(0, 5).map((c) => ({ id: `risk-${c.id || labelOf(c)}`, title: labelOf(c), detail: `${parcelOf(c)} · score ${fmtNumber(scoreOf(c))}/100`, value: 'Traiter', tone: 'warn', tab: 'Santé' })), ...lowInputs.slice(0, 5).map((s) => ({ id: `input-${s.id || stockLabel(s)}`, title: stockLabel(s), detail: 'Intrant sous seuil', value: 'Acheter', tone: 'warn', tab: 'Intrants' })), ...harvested.slice(0, 4).map((c) => ({ id: `harvest-${c.id || labelOf(c)}`, title: labelOf(c), detail: `${fmtNumber(harvestQty(c))} disponible`, value: 'Récolte', tone: 'good', tab: 'Récoltes' }))].slice(0, 10);
    const history = [...events, ...cultureRows, ...arr(opportunities)].sort((a, b) => String(dateOf(b)).localeCompare(String(dateOf(a))));
    return { cultures: cultureRows, riskCultures, harvested, inputs, lowInputs, events, works, inputEvents, workCost, parcels, totalArea, priorities, history };
  }, [rows, cultures, stocks, transactions, finances, businessEvents, opportunities]);
  const content = tab === 'Résumé' ? <Summary data={data} setTab={setTab} /> : tab === 'Parcelles' ? <Parcels data={data} setTab={setTab} /> : tab === 'Cultures' ? <CulturesTab data={data} selected={selectedCulture} setSelected={setSelectedCulture} setTab={setTab} /> : tab === 'Travaux' ? <Works data={data} setTab={setTab} /> : tab === 'Récoltes' ? <Harvests data={data} /> : tab === 'Intrants' ? <Inputs data={data} setTab={setTab} /> : tab === 'Santé' ? <Health data={data} setTab={setTab} /> : tab === 'Historique' ? <History data={data} /> : <Graphs data={data} />;
  return <div className="space-y-6"><div className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs uppercase tracking-[0.25em] text-[#9a6b12] font-black">Production végétale</p><h1 className="mt-1 text-2xl font-black text-[#2f2415]">Cultures</h1></div><div className="flex flex-wrap gap-2"><Button onClick={() => setTab('Cultures')}>Cultures</Button><Button onClick={() => setTab('Travaux')}>Travaux</Button><Button onClick={() => setTab('Récoltes')}>Récoltes</Button></div></div></div><Tabs active={tab} onChange={setTab} />{content}</div>;
}
