import { BarChart3, ClipboardList, Download, FileText, FolderOpen, Image, PackageCheck, Search, ShieldCheck } from 'lucide-react';
import { useMemo, useState } from 'react';
import { fmtCurrency, fmtNumber } from '../utils/format';

const arr = (v) => Array.isArray(v) ? v : [];
const low = (v) => String(v || '').toLowerCase();
const dateOf = (r = {}) => r.date || r.created_at || r.updated_at || r.event_date || '—';
const labelOf = (r = {}) => r.title || r.nom || r.name || r.filename || r.libelle || r.id || 'Document';
const typeOf = (r = {}) => r.type || r.categorie || r.category || r.module_source || 'Document';
const detailOf = (r = {}) => r.description || r.notes || r.module_source || r.related_type || r.entity_type || '—';
const amountOf = (r = {}) => Number(r.montant || r.amount || r.total || r.montant_total || 0);
const hasProof = (r = {}) => Boolean(r.document_id || r.proof_url || r.justificatif_id || r.file_url || r.url);
const docIsProof = (r = {}) => /preuve|recu|reçu|facture|paiement|justificatif|finance|achat|vente/.test(low(`${typeOf(r)} ${labelOf(r)}`));
const docIsReport = (r = {}) => /rapport|report|bilan|analyse|export/.test(low(`${typeOf(r)} ${labelOf(r)}`));
const docIsMedia = (r = {}) => /image|photo|media|jpeg|jpg|png/.test(low(`${typeOf(r)} ${labelOf(r)} ${r.mime_type || ''}`));

function Stat({ label, value, tone = 'neutral' }) {
  const cls = tone === 'good' ? 'text-emerald-600' : tone === 'warn' ? 'text-amber-600' : tone === 'bad' ? 'text-red-600' : 'text-[#2f2415]';
  return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="text-xs text-[#8a7456]">{label}</p><p className={`mt-1 text-xl font-black ${cls}`}>{value}</p></div>;
}
function Section({ icon: Icon, title, children, action }) {
  return <section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="flex items-center gap-2 text-lg font-black text-[#2f2415]"><Icon size={20} /> {title}</h2>{action}</div>{children}</section>;
}
function Button({ children, onClick }) { return <button type="button" onClick={onClick} className="rounded-xl border border-[#d6c3a0] bg-[#fffdf8] px-3 py-2 text-xs font-black text-[#2f2415] hover:bg-[#dcfce7]">{children}</button>; }
function Pill({ children, tone = 'neutral' }) { const cls = tone === 'good' ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : tone === 'warn' ? 'border-amber-200 bg-amber-50 text-amber-700' : tone === 'bad' ? 'border-red-200 bg-red-50 text-red-700' : 'border-[#eadcc2] bg-[#fffdf8] text-[#8a7456]'; return <span className={`rounded-full border px-3 py-1 text-xs font-black ${cls}`}>{children}</span>; }
function Row({ title, detail, value, tone = 'neutral', onClick }) { return <button type="button" onClick={onClick} className="grid w-full grid-cols-1 gap-2 border-b border-[#eadcc2]/70 py-4 text-left last:border-b-0 md:grid-cols-[260px_1fr_auto] md:items-center hover:bg-[#fffdf8]"><span className="font-black text-[#2f2415]">{title}</span><span className="text-sm text-[#8a7456]">{detail}</span><Pill tone={tone}>{value}</Pill></button>; }
function Field({ label, value }) { return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="text-xs text-[#8a7456]">{label}</p><p className="mt-1 font-black text-[#2f2415]">{value}</p></div>; }
function Empty({ label }) { return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-5 text-sm text-[#8a7456]">{label}</div>; }
function Tabs({ active, onChange }) { const tabs = ['Résumé', 'Bibliothèque', 'Preuves', 'Rapports', 'Exports', 'Modèles', 'Historique']; return <div className="overflow-x-auto"><div className="flex min-w-max gap-2 rounded-2xl border border-[#d6c3a0] bg-white p-2">{tabs.map((tab) => <button key={tab} type="button" onClick={() => onChange(tab)} className={`rounded-xl px-4 py-2 text-sm font-black transition ${active === tab ? 'bg-[#22c55e] text-[#052e16]' : 'text-[#8a7456] hover:bg-[#fffdf8] hover:text-[#2f2415]'}`}>{tab}</button>)}</div></div>; }

function Summary({ data, setTab }) {
  return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><Stat label="Documents" value={fmtNumber(data.documents.length)} /><Stat label="Preuves" value={fmtNumber(data.proofs.length)} tone="good" /><Stat label="Rapports" value={fmtNumber(data.reports.length)} /><Stat label="Sans preuve" value={fmtNumber(data.missingProof.length)} tone={data.missingProof.length ? 'warn' : 'good'} /><Stat label="Médias" value={fmtNumber(data.media.length)} /></div><Section icon={ClipboardList} title="Priorités documentaires" action={<Button onClick={() => setTab('Preuves')}>Voir preuves</Button>}>{data.priorities.length ? data.priorities.map((item) => <Row key={item.id} title={item.title} detail={item.detail} value={item.value} tone={item.tone} onClick={() => setTab(item.tab)} />) : <Empty label="Aucune priorité documentaire." />}</Section></div>;
}
function Library({ data, selected, setSelected }) { const row = selected || data.documents[0]; return <div className="grid grid-cols-1 gap-4 xl:grid-cols-[1fr_420px]"><Section icon={FolderOpen} title="Bibliothèque">{data.documents.length ? data.documents.slice(0, 16).map((doc) => <Row key={doc.id || labelOf(doc)} title={labelOf(doc)} detail={`${typeOf(doc)} · ${dateOf(doc)} · ${detailOf(doc)}`} value={docIsProof(doc) ? 'Preuve' : docIsReport(doc) ? 'Rapport' : 'Doc'} tone={docIsProof(doc) ? 'good' : 'neutral'} onClick={() => setSelected(doc)} />) : <Empty label="Aucun document." />}</Section><Section icon={Search} title="Fiche document"><div className="space-y-3">{row ? <><Field label="Document" value={labelOf(row)} /><Field label="Type" value={typeOf(row)} /><Field label="Date" value={dateOf(row)} /><Field label="Origine" value={row.module_source || row.related_type || '—'} /><Field label="Détail" value={detailOf(row)} /></> : <Empty label="Aucun document sélectionné." />}</div></Section></div>; }
function Proofs({ data }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Preuves" value={fmtNumber(data.proofs.length)} tone="good" /><Stat label="Sans preuve" value={fmtNumber(data.missingProof.length)} tone={data.missingProof.length ? 'warn' : 'good'} /><Stat label="Montant à justifier" value={fmtCurrency(data.missingProofAmount)} tone={data.missingProofAmount ? 'warn' : 'good'} /><Stat label="Factures/reçus" value={fmtNumber(data.invoiceDocs.length)} /></div><Section icon={ShieldCheck} title="Éléments sans preuve">{data.missingProof.length ? data.missingProof.slice(0, 14).map((row) => <Row key={row.id || labelOf(row)} title={labelOf(row)} detail={`${dateOf(row)} · preuve à joindre`} value={fmtCurrency(amountOf(row))} tone="warn" />) : <Empty label="Aucune preuve manquante détectée." />}</Section></div>; }
function Reports({ data }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Rapports" value={fmtNumber(data.reports.length)} /><Stat label="Modules couverts" value={fmtNumber(data.coveredModules.length)} /><Stat label="Exports" value={fmtNumber(data.exports.length)} /><Stat label="Modèles" value={fmtNumber(data.templates.length)} /></div><Section icon={BarChart3} title="Rapports disponibles">{data.reports.length ? data.reports.slice(0, 14).map((row) => <Row key={row.id || labelOf(row)} title={labelOf(row)} detail={`${typeOf(row)} · ${dateOf(row)} · ${detailOf(row)}`} value="Rapport" />) : <Empty label="Aucun rapport enregistré." />}</Section></div>; }
function Exports({ data }) { return <Section icon={Download} title="Exports"><div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3"><Field label="Export ventes" value={`${fmtNumber(data.salesOrders.length)} vente(s)`} /><Field label="Export finance" value={`${fmtNumber(data.transactions.length)} mouvement(s)`} /><Field label="Export élevage" value={`${fmtNumber(data.animaux.length + data.lots.length)} élément(s)`} /><Field label="Export stock" value={`${fmtNumber(data.stocks.length)} produit(s)`} /><Field label="Export cultures" value={`${fmtNumber(data.cultures.length)} culture(s)`} /><Field label="Export clients" value={`${fmtNumber(data.clients.length)} client(s)`} /></div></Section>; }
function Templates({ data }) { const templates = data.templates.length ? data.templates : [{ id: 'vente', title: 'Reçu de vente', type: 'Modèle' }, { id: 'finance', title: 'Justificatif dépense', type: 'Modèle' }, { id: 'stock', title: 'Fiche inventaire', type: 'Modèle' }, { id: 'sante', title: 'Fiche sanitaire', type: 'Modèle' }]; return <Section icon={FileText} title="Modèles de documents">{templates.map((row) => <Row key={row.id || labelOf(row)} title={labelOf(row)} detail={`${typeOf(row)} · prêt à utiliser`} value="Modèle" />)}</Section>; }
function History({ data }) { return <Section icon={ClipboardList} title="Historique documentaire">{data.history.length ? data.history.slice(0, 16).map((row) => <Row key={row.id || labelOf(row)} title={labelOf(row)} detail={`${dateOf(row)} · ${detailOf(row)}`} value={typeOf(row)} />) : <Empty label="Aucun historique documentaire." />}</Section>; }

export default function DocumentsRapportsModule({ documents = [], rapports = [], reports = [], transactions = [], finances = [], salesOrders = [], payments = [], animaux = [], lots = [], cultures = [], stocks = [], clients = [], fournisseurs = [], businessPlans = [], investissements = [], businessEvents = [] }) {
  const [tab, setTab] = useState('Résumé');
  const [selectedDocument, setSelectedDocument] = useState(null);
  const data = useMemo(() => {
    const docs = [...arr(documents), ...arr(rapports), ...arr(reports)].filter(Boolean);
    const tx = [...arr(transactions), ...arr(finances)].filter(Boolean);
    const proofs = docs.filter(docIsProof);
    const invoiceDocs = docs.filter((d) => /facture|recu|reçu|paiement/.test(low(`${typeOf(d)} ${labelOf(d)}`)));
    const reportDocs = docs.filter(docIsReport);
    const media = docs.filter(docIsMedia);
    const templates = docs.filter((d) => /modele|modèle|template/.test(low(`${typeOf(d)} ${labelOf(d)}`)));
    const exports = docs.filter((d) => /export|csv|excel|pdf/.test(low(`${typeOf(d)} ${labelOf(d)}`)));
    const missingProof = tx.filter((r) => amountOf(r) > 0 && !hasProof(r) && !docs.some((d) => String(d.transaction_id || d.source_record_id || d.related_id) === String(r.id)));
    const missingProofAmount = missingProof.reduce((sum, row) => sum + amountOf(row), 0);
    const coveredModules = [...new Set(docs.map((d) => d.module_source || d.module || d.related_type).filter(Boolean))];
    const priorities = missingProof.slice(0, 8).map((row) => ({ id: `proof-${row.id || labelOf(row)}`, title: labelOf(row), detail: `${dateOf(row)} · justificatif manquant`, value: fmtCurrency(amountOf(row)), tone: 'warn', tab: 'Preuves' }));
    const history = [...docs, ...arr(businessEvents)].sort((a, b) => String(dateOf(b)).localeCompare(String(dateOf(a))));
    return { documents: docs, proofs, invoiceDocs, reports: reportDocs, media, templates, exports, missingProof, missingProofAmount, coveredModules, priorities, history, transactions: tx, salesOrders: arr(salesOrders), payments: arr(payments), animaux: arr(animaux), lots: arr(lots), cultures: arr(cultures), stocks: arr(stocks), clients: arr(clients), fournisseurs: arr(fournisseurs), businessPlans: arr(businessPlans), investissements: arr(investissements) };
  }, [documents, rapports, reports, transactions, finances, salesOrders, payments, animaux, lots, cultures, stocks, clients, fournisseurs, businessPlans, investissements, businessEvents]);
  const content = tab === 'Résumé' ? <Summary data={data} setTab={setTab} /> : tab === 'Bibliothèque' ? <Library data={data} selected={selectedDocument} setSelected={setSelectedDocument} /> : tab === 'Preuves' ? <Proofs data={data} /> : tab === 'Rapports' ? <Reports data={data} /> : tab === 'Exports' ? <Exports data={data} /> : tab === 'Modèles' ? <Templates data={data} /> : <History data={data} />;
  return <div className="space-y-6"><div className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs uppercase tracking-[0.25em] text-[#9a6b12] font-black">Dossiers</p><h1 className="mt-1 text-2xl font-black text-[#2f2415]">Documents & Rapports</h1></div><div className="flex flex-wrap gap-2"><Button onClick={() => setTab('Bibliothèque')}>Bibliothèque</Button><Button onClick={() => setTab('Rapports')}>Rapports</Button><Button onClick={() => setTab('Exports')}>Exports</Button></div></div></div><Tabs active={tab} onChange={setTab} />{content}</div>;
}
