import { Award, BarChart2, Edit, ExternalLink, File, FileCheck, FileText, Image, Package, Plus, Receipt, RefreshCw, Search, Syringe, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import ActionIconButton from '../components/ActionIconButton';
import Btn from '../components/Btn';
import KpiCard from '../components/KpiCard';
import ModuleTimeline from '../components/ModuleTimeline';
import SectionHeader from '../components/SectionHeader';
import CreateModal from '../modals/CreateModal';
import DeleteModal from '../modals/DeleteModal';
import EditModal from '../modals/EditModal';
import { documentFields, normalizeDocumentPayload } from '../utils/documentForms';
import { generateSequentialId } from '../utils/ids';

const CATEGORIES = ['facture', 'recu', 'ordonnance', 'certificat', 'contrat', 'bon_livraison', 'photo', 'rapport', 'presentation_projet', 'autre'];
const CAT_ICONS = { facture: FileText, recu: Receipt, ordonnance: Syringe, certificat: Award, contrat: FileCheck, bon_livraison: Package, photo: Image, rapport: BarChart2, presentation_projet: FileCheck, autre: File };
const CAT_COLORS = { facture: 'bg-neutral-bg text-neutral border-line', recu: 'bg-positive-bg text-positive border-positive', ordonnance: 'bg-urgent-bg text-urgent border-urgent', certificat: 'bg-neutral-bg text-neutral border-line', contrat: 'bg-vigilance-bg text-horizon-dark border-vigilance', bon_livraison: 'bg-vigilance-bg text-horizon-dark border-vigilance', photo: 'bg-neutral-bg text-neutral border-line', rapport: 'bg-neutral-bg text-neutral border-line', presentation_projet: 'bg-horizon/20 text-horizon-dark border-horizon/40', autre: 'bg-neutral-bg text-neutral border-line' };
const MODULE_LABELS = { animaux: 'Animaux', avicole: 'Avicole', cultures: 'Cultures', finances: 'Finances', stock: 'Stock', stocks: 'Stock', ventes: 'Ventes', sante: 'Santé', documents: 'Documents', fournisseurs: 'Fournisseurs', clients: 'Clients', rapports: 'Rapports', autre: 'Autre' };
const readableModule = (key = '') => MODULE_LABELS[key] || String(key || '').replace(/_/g, ' ') || 'Autre';

function getEntityName(entityId, entityType, animaux, lots, cultures, clients, fournisseurs, stocks = [], transactions = []) { if (!entityId) return null; const id = String(entityId); if (entityType === 'animal') return animaux.find((a) => String(a.id) === id)?.name || id; if (entityType === 'lot_avicole') return lots.find((l) => String(l.id) === id)?.name || id; if (entityType === 'culture') return cultures.find((c) => String(c.id) === id)?.nom || id; if (entityType === 'client') return clients.find((c) => String(c.id) === id)?.nom || id; if (entityType === 'fournisseur') return fournisseurs.find((f) => String(f.id) === id)?.nom || id; if (entityType === 'stock') return stocks.find((s) => String(s.id) === id)?.produit || id; if (entityType === 'transaction') return transactions.find((t) => String(t.id) === id)?.libelle || id; return id; }

export default function Documents({ rows = [], animaux = [], lots = [], cultures = [], clients = [], fournisseurs = [], transactions = [], finances = [], stocks = [], loading, onCreate, onUpdate, onDelete, onRefresh, onNavigate }) {
  const [catFilter, setCatFilter] = useState('tous');
  const [moduleFilter, setModuleFilter] = useState('tous');
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState(null);
  const [modal, setModal] = useState(null);
  const [saving, setSaving] = useState(false);
  const formContext = useMemo(() => ({ animaux, lots, cultures, clients, fournisseurs, transactions, finances, stocks }), [animaux, lots, cultures, clients, fournisseurs, transactions, finances, stocks]);
  const fields = useMemo(() => documentFields(formContext), [formContext]);
  const txRows = transactions.length ? transactions : finances;
  const uniqueModules = useMemo(() => [...new Set(rows.map((r) => r.module_source).filter(Boolean))], [rows]);
  const filtered = useMemo(() => rows.filter((doc) => { if (catFilter !== 'tous' && doc.document_category !== catFilter) return false; if (moduleFilter !== 'tous' && doc.module_source !== moduleFilter) return false; if (query) { const q = query.toLowerCase(); const hit = (doc.title || '').toLowerCase().includes(q) || (doc.notes || '').toLowerCase().includes(q) || (doc.entity_id || '').toLowerCase().includes(q) || (doc.related_id || '').toLowerCase().includes(q); if (!hit) return false; } return true; }), [rows, catFilter, moduleFilter, query]);
  const catCounts = useMemo(() => { const counts = {}; CATEGORIES.forEach((c) => { counts[c] = rows.filter((r) => r.document_category === c).length; }); return counts; }, [rows]);
  const submitCreate = async (payload) => { try { setSaving(true); await onCreate(normalizeDocumentPayload(payload, formContext)); await onRefresh?.(); toast.success('Document ajouté'); setModal(null); } catch (err) { toast.error(err.message || 'Création document impossible'); } finally { setSaving(false); } };
  const submitEdit = async (payload) => { if (!selected) return; try { setSaving(true); await onUpdate(selected.id, normalizeDocumentPayload(payload, formContext)); await onRefresh?.(); toast.success('Document modifié'); setModal(null); } catch (err) { toast.error(err.message || 'Modification document impossible'); } finally { setSaving(false); } };
  const submitDelete = async () => { if (!selected) return; try { setSaving(true); await onDelete(selected.id); await onRefresh?.(); toast.success('Document supprimé'); setModal(null); } catch (err) { toast.error(err.message || 'Suppression document impossible'); } finally { setSaving(false); } };
  return <div className="space-y-6"><SectionHeader title="Documents" sub="Factures, ordonnances, certificats, contrats, photos, rapports" actions={<><Btn icon={RefreshCw} variant="outline" small onClick={onRefresh}>Actualiser</Btn><Btn icon={Plus} small onClick={() => setModal('create')}>Ajouter document</Btn></>} />
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><KpiCard icon={FileText} label="Total documents" value={rows.length} color="bg-neutral text-neutral" /><KpiCard icon={Receipt} label="Factures & reçus" value={(catCounts.facture || 0) + (catCounts.recu || 0)} color="bg-positive text-positive" /><KpiCard icon={Syringe} label="Ordonnances" value={catCounts.ordonnance || 0} color="bg-urgent text-urgent" /><KpiCard icon={Image} label="Photos" value={catCounts.photo || 0} color="bg-neutral text-neutral" /></div>
    <ModuleTimeline title="Historique des documents" subtitle="Derniers justificatifs, preuves et pièces ajoutées." rows={rows.map((doc) => ({ ...doc, status: doc.document_category, description: `${readableModule(doc.module_source)} · ${doc.notes || 'preuve enregistrée'}` }))} onRefresh={onRefresh} onNavigate={() => onNavigate?.('documents')} />
    <div className="bg-white border border-line rounded-2xl p-4 space-y-3"><div className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate" /><input type="text" placeholder="Rechercher titre, notes, élément concerné..." value={query} onChange={(e) => setQuery(e.target.value)} className="w-full pl-8 pr-4 py-2 rounded-xl border border-line text-sm bg-card focus:outline-none focus:border-horizon" /></div><div className="flex flex-wrap gap-2"><span className="text-xs text-slate self-center font-medium">Catégorie :</span>{['tous', ...CATEGORIES].map((cat) => <button key={cat} type="button" onClick={() => setCatFilter(cat)} className={`px-3 py-1 rounded-full text-xs font-medium capitalize transition-all ${catFilter === cat ? 'bg-earth text-white' : 'bg-white border border-line text-slate hover:border-horizon'}`}>{cat === 'tous' ? 'Toutes' : cat.replace('_', ' ')}{cat !== 'tous' && catCounts[cat] > 0 ? ` (${catCounts[cat]})` : ''}</button>)}</div>{uniqueModules.length > 0 && <div className="flex flex-wrap gap-2"><span className="text-xs text-slate self-center font-medium">Espace :</span>{['tous', ...uniqueModules].map((m) => <button key={m} type="button" onClick={() => setModuleFilter(m)} className={`px-3 py-1 rounded-full text-xs font-medium transition-all ${moduleFilter === m ? 'bg-earth text-white' : 'bg-white border border-line text-slate hover:border-horizon'}`}>{m === 'tous' ? 'Tous' : readableModule(m)}</button>)}</div>}</div>
    {loading && <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{Array.from({ length: 6 }).map((_, i) => <div key={i} className="h-36 rounded-2xl bg-line/40 animate-pulse" />)}</div>}
    {!loading && rows.length === 0 && <div className="rounded-2xl border border-dashed border-line bg-white p-12 text-center"><FileText size={40} className="mx-auto text-line mb-3" /><p className="font-semibold text-earth mb-1">Aucun document</p><p className="text-sm text-slate mb-4">Ajoutez factures, ordonnances, contrats, photos et rapports.</p><Btn icon={Plus} small onClick={() => setModal('create')}>Ajouter un document</Btn></div>}
    {!loading && rows.length > 0 && filtered.length === 0 && <div className="rounded-2xl border border-line bg-white p-8 text-center text-slate">Aucun document correspondant aux filtres.</div>}
    {!loading && filtered.length > 0 && <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{filtered.map((doc) => { const cat = doc.document_category || 'autre'; const CatIcon = CAT_ICONS[cat] || File; const catColor = CAT_COLORS[cat] || CAT_COLORS.autre; const entityName = getEntityName(doc.entity_id || doc.related_id, doc.entity_type, animaux, lots, cultures, clients, fournisseurs, stocks, txRows); const dateStr = doc.created_at ? new Date(doc.created_at).toLocaleDateString('fr-FR') : '-'; return <div key={doc.id} className="bg-white border border-line rounded-2xl p-4 hover:border-horizon hover:shadow-card transition-all flex flex-col"><div className="flex items-start gap-3 mb-3"><div className={`w-10 h-10 rounded-xl border flex items-center justify-center shrink-0 ${catColor}`}><CatIcon size={18} /></div><div className="flex-1 min-w-0"><p className="font-semibold text-earth truncate">{doc.title}</p><span className={`text-xs px-2 py-1 rounded-full border capitalize ${catColor}`}>{cat.replace('_', ' ')}</span></div></div>{(doc.module_source || entityName) && <div className="text-xs text-slate mb-2">{doc.module_source && <span className="font-medium">{readableModule(doc.module_source)}</span>}{entityName && <span> - {entityName}</span>}</div>}{doc.notes && <p className="text-xs text-slate line-clamp-2 mb-2 flex-1">{doc.notes}</p>}<div className="flex items-center justify-between mt-auto pt-3 border-t border-line"><span className="text-xs text-slate">{dateStr}</span><div className="flex items-center gap-1">{doc.file_url ? <a href={doc.file_url} target="_blank" rel="noopener noreferrer"><button type="button" title="Ouvrir" className="w-7 h-7 flex items-center justify-center rounded-lg bg-neutral text-neutral hover:bg-neutral transition-colors"><ExternalLink size={12} /></button></a> : null}<ActionIconButton icon={Edit} color="amber" title="Modifier" onClick={() => { setSelected(doc); setModal('edit'); }} /><ActionIconButton icon={Trash2} color="red" title="Supprimer" onClick={() => { setSelected(doc); setModal('delete'); }} /></div></div></div>; })}</div>}
    <CreateModal open={modal === 'create'} onClose={() => setModal(null)} onSubmit={submitCreate} fields={fields} initialValues={{ id: generateSequentialId('documents', rows), document_category: 'autre', module_source: 'autre' }} autoId={() => generateSequentialId('documents', rows)} uploadFolder="documents" loading={saving} title="Ajouter un document" submitLabel="Ajouter" />
    <EditModal open={modal === 'edit'} onClose={() => setModal(null)} onSubmit={submitEdit} fields={fields} initialValues={selected || {}} uploadFolder="documents" loading={saving} title="Modifier le document" submitLabel="Enregistrer" />
    <DeleteModal open={modal === 'delete'} onClose={() => setModal(null)} onConfirm={submitDelete} itemLabel={selected?.title || ''} loading={saving} />
  </div>;
}
