import { BarChart3, Calculator, ClipboardList, CreditCard, FileText, Landmark, PiggyBank, Scale, TrendingUp, Wallet } from 'lucide-react';
import { useMemo, useState } from 'react';
import { fmtCurrency, fmtNumber } from '../utils/format';

const arr = (v) => Array.isArray(v) ? v : [];
const low = (v) => String(v || '').toLowerCase();
const num = (v = 0) => Number(v || 0);
const amount = (r = {}) => num(r.montant ?? r.amount ?? r.total ?? r.montant_total ?? r.value ?? r.valeur);
const dateOf = (r = {}) => r.date || r.event_date || r.created_at || r.updated_at || '—';
const labelOf = (r = {}) => r.libelle || r.title || r.nom || r.name || r.description || r.id || 'Écriture';
const income = (r = {}) => ['entree', 'entrée', 'income', 'recette', 'vente'].includes(low(r.type || r.nature || r.sens));
const expense = (r = {}) => ['sortie', 'expense', 'depense', 'dépense', 'achat', 'charge'].includes(low(r.type || r.nature || r.sens));
const unpaid = (r = {}) => ['impaye', 'impayé', 'partiel', 'a_payer', 'à payer', 'due', 'unpaid'].includes(low(r.statut || r.status || r.payment_status));
const docLabel = (r = {}) => r.title || r.nom || r.name || r.filename || r.id || 'Document';

function Stat({ label, value, tone = 'neutral' }) {
  const cls = tone === 'good' ? 'text-emerald-600' : tone === 'warn' ? 'text-amber-600' : tone === 'bad' ? 'text-red-600' : 'text-[#2f2415]';
  return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="text-xs text-[#8a7456]">{label}</p><p className={`mt-1 text-xl font-black ${cls}`}>{value}</p></div>;
}
function Section({ icon: Icon, title, children, action }) {
  return <section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="flex items-center gap-2 text-lg font-black text-[#2f2415]"><Icon size={20} /> {title}</h2>{action}</div>{children}</section>;
}
function Button({ children, onClick }) { return <button type="button" onClick={onClick} className="rounded-xl border border-[#d6c3a0] bg-[#fffdf8] px-3 py-2 text-xs font-black text-[#2f2415] hover:bg-[#dcfce7]">{children}</button>; }
function Pill({ children, tone = 'neutral' }) { const cls = tone === 'good' ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : tone === 'warn' ? 'border-amber-200 bg-amber-50 text-amber-700' : tone === 'bad' ? 'border-red-200 bg-red-50 text-red-700' : 'border-[#eadcc2] bg-[#fffdf8] text-[#8a7456]'; return <span className={`rounded-full border px-3 py-1 text-xs font-black ${cls}`}>{children}</span>; }
function Row({ title, detail, value, tone = 'neutral', onClick }) { return <button type="button" onClick={onClick} className="grid w-full grid-cols-1 gap-2 border-b border-[#eadcc2]/70 py-4 text-left last:border-b-0 md:grid-cols-[260px_1fr_auto] md:items-center hover:bg-[#fffdf8]"><span className="font-black text-[#2f2415]">{title}</span><span className="text-sm text-[#8a7456]">{detail}</span><Pill tone={tone}>{value}</Pill></button>; }
function Field({ label, value }) { return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="text-xs text-[#8a7456]">{label}</p><p className="mt-1 font-black text-[#2f2415]">{value}</p></div>; }
function Empty({ label }) { return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-5 text-sm text-[#8a7456]">{label}</div>; }
function Tabs({ active, onChange }) { const tabs = ['Résumé', 'Trésorerie', 'Recettes', 'Dépenses', 'Comptabilité', 'Investissements', 'Prévisions', 'Documents']; return <div className="overflow-x-auto"><div className="flex min-w-max gap-2 rounded-2xl border border-[#d6c3a0] bg-white p-2">{tabs.map((tab) => <button key={tab} type="button" onClick={() => onChange(tab)} className={`rounded-xl px-4 py-2 text-sm font-black transition ${active === tab ? 'bg-[#22c55e] text-[#052e16]' : 'text-[#8a7456] hover:bg-[#fffdf8] hover:text-[#2f2415]'}`}>{tab}</button>)}</div></div>; }

function Summary({ data, setTab }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><Stat label="Solde estimé" value={fmtCurrency(data.balance)} tone={data.balance >= 0 ? 'good' : 'bad'} /><Stat label="Recettes" value={fmtCurrency(data.income)} tone="good" /><Stat label="Dépenses" value={fmtCurrency(data.expenses)} tone={data.expenses ? 'warn' : 'neutral'} /><Stat label="À régler" value={fmtCurrency(data.unpaidAmount)} tone={data.unpaidAmount ? 'warn' : 'good'} /><Stat label="Investissements" value={fmtNumber(data.investments.length)} /></div><Section icon={ClipboardList} title="Priorités financières" action={<Button onClick={() => setTab('Trésorerie')}>Voir trésorerie</Button>}>{data.priorities.length ? data.priorities.map((item) => <Row key={item.id} title={item.title} detail={item.detail} value={item.value} tone={item.tone} onClick={() => setTab(item.tab)} />) : <Empty label="Aucune priorité financière." />}</Section></div>; }
function Treasury({ data, selected, setSelected, setTab }) { const row = selected || data.transactions[0]; return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Solde" value={fmtCurrency(data.balance)} tone={data.balance >= 0 ? 'good' : 'bad'} /><Stat label="Entrées" value={fmtCurrency(data.income)} tone="good" /><Stat label="Sorties" value={fmtCurrency(data.expenses)} tone="warn" /><Stat label="Impayés" value={fmtCurrency(data.unpaidAmount)} tone={data.unpaidAmount ? 'warn' : 'good'} /></div><div className="grid grid-cols-1 gap-4 xl:grid-cols-[1fr_420px]"><Section icon={Wallet} title="Mouvements" action={<Button onClick={() => setTab('Documents')}>Preuves</Button>}>{data.transactions.length ? data.transactions.slice(0, 14).map((r) => <Row key={r.id || labelOf(r)} title={labelOf(r)} detail={`${dateOf(r)} · ${r.categorie || r.category || r.module_lie || 'Finance'}`} value={fmtCurrency(amount(r))} tone={income(r) ? 'good' : expense(r) ? 'warn' : 'neutral'} onClick={() => setSelected(r)} />) : <Empty label="Aucun mouvement financier." />}</Section><Section icon={CreditCard} title="Fiche mouvement"><div className="space-y-3">{row ? <><Field label="Libellé" value={labelOf(row)} /><Field label="Date" value={dateOf(row)} /><Field label="Montant" value={fmtCurrency(amount(row))} /><Field label="Type" value={row.type || row.nature || '—'} /><Field label="Catégorie" value={row.categorie || row.category || '—'} /><Field label="Statut" value={row.statut || row.status || '—'} /></> : <Empty label="Aucun mouvement sélectionné." />}</div></Section></div></div>; }
function RowsSection({ icon, title, rows, empty, tone = 'neutral' }) { const Icon = icon; return <Section icon={Icon} title={title}>{rows.length ? rows.slice(0, 14).map((r) => <Row key={r.id || labelOf(r)} title={labelOf(r)} detail={`${dateOf(r)} · ${r.categorie || r.category || r.statut || 'Suivi'}`} value={fmtCurrency(amount(r))} tone={tone === 'auto' ? (income(r) ? 'good' : expense(r) ? 'warn' : 'neutral') : tone} />) : <Empty label={empty} />}</Section>; }
function Accounting({ data }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Écritures" value={fmtNumber(data.transactions.length)} /><Stat label="Preuves" value={fmtNumber(data.financeDocs.length)} /><Stat label="Sans preuve" value={fmtNumber(data.missingProof.length)} tone={data.missingProof.length ? 'warn' : 'good'} /><Stat label="À régler" value={fmtCurrency(data.unpaidAmount)} tone={data.unpaidAmount ? 'warn' : 'good'} /></div><RowsSection icon={Calculator} title="Contrôle comptable" rows={data.missingProof} empty="Toutes les écritures contrôlées ont une preuve." tone="warn" /></div>; }
function Investments({ data, selected, setSelected, setTab }) { const row = selected || data.investments[0]; return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Investissements" value={fmtNumber(data.investments.length)} /><Stat label="Montant prévu" value={fmtCurrency(data.investmentAmount)} /><Stat label="Plans" value={fmtNumber(data.businessPlans.length)} /><Stat label="Coûts prévus" value={fmtCurrency(data.recurringCosts)} tone="warn" /></div><div className="grid grid-cols-1 gap-4 xl:grid-cols-[1fr_420px]"><Section icon={PiggyBank} title="Investissements" action={<Button onClick={() => setTab('Prévisions')}>Prévisions</Button>}>{data.investments.length ? data.investments.slice(0, 12).map((r) => <Row key={r.id || labelOf(r)} title={labelOf(r)} detail={`${dateOf(r)} · ${r.statut || r.status || 'Suivi'}`} value={fmtCurrency(amount(r))} tone={unpaid(r) ? 'warn' : 'neutral'} onClick={() => setSelected(r)} />) : <Empty label="Aucun investissement." />}</Section><Section icon={Landmark} title="Fiche investissement"><div className="space-y-3">{row ? <><Field label="Investissement" value={labelOf(row)} /><Field label="Montant" value={fmtCurrency(amount(row))} /><Field label="Statut" value={row.statut || row.status || '—'} /><Field label="Date" value={dateOf(row)} /><Field label="Objectif" value={row.objectif || row.goal || row.description || '—'} /></> : <Empty label="Aucun investissement sélectionné." />}</div></Section></div></div>; }
function Forecast({ data }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Business plans" value={fmtNumber(data.businessPlans.length)} /><Stat label="Recettes prévues" value={fmtCurrency(data.projectedRevenue)} tone="good" /><Stat label="Coûts récurrents" value={fmtCurrency(data.recurringCosts)} tone="warn" /><Stat label="Besoin" value={fmtCurrency(Math.max(0, data.recurringCosts + data.investmentAmount - data.projectedRevenue))} tone="warn" /></div><RowsSection icon={BarChart3} title="Plans et prévisions" rows={data.businessPlans} empty="Aucun business plan." /></div>; }
function Docs({ data }) { return <Section icon={FileText} title="Documents financiers">{data.financeDocs.length ? data.financeDocs.slice(0, 14).map((r) => <Row key={r.id || docLabel(r)} title={docLabel(r)} detail={`${r.type || r.categorie || 'Document'} · ${dateOf(r)}`} value="Preuve" />) : <Empty label="Aucun document financier." />}</Section>; }

export default function FinancePilotageModule(props) {
  const [tab, setTab] = useState('Résumé');
  const [selectedTransaction, setSelectedTransaction] = useState(null);
  const [selectedInvestment, setSelectedInvestment] = useState(null);
  const data = useMemo(() => {
    const transactions = [...arr(props.transactions), ...arr(props.finances)].filter(Boolean);
    const incomeRows = transactions.filter(income);
    const expenseRows = transactions.filter((r) => expense(r) || (!income(r) && amount(r) > 0));
    const totalIncome = incomeRows.reduce((s, r) => s + amount(r), 0);
    const totalExpenses = expenseRows.reduce((s, r) => s + amount(r), 0);
    const unpaidRows = transactions.filter(unpaid);
    const unpaidAmount = unpaidRows.reduce((s, r) => s + amount(r), 0);
    const financeDocs = arr(props.documents).filter((d) => /finance|facture|paiement|preuve|recu|reçu|compta|invest/.test(low(`${d.type || ''} ${d.categorie || ''} ${d.title || ''} ${d.nom || ''}`)));
    const missingProof = transactions.filter((r) => amount(r) > 0 && !r.proof_url && !r.document_id && !r.justificatif_id && !financeDocs.some((d) => String(d.transaction_id || d.source_record_id || d.related_id) === String(r.id)));
    const investments = arr(props.investissements);
    const investmentAmount = investments.reduce((s, r) => s + amount(r), 0);
    const projectedRevenue = arr(props.bpRevenueProjections).reduce((s, r) => s + amount(r), 0);
    const recurringCosts = arr(props.bpRecurringCosts).reduce((s, r) => s + amount(r), 0);
    const priorities = [...unpaidRows.slice(0, 4).map((r) => ({ id: `unpaid-${r.id}`, title: labelOf(r), detail: `${dateOf(r)} · à régler`, value: fmtCurrency(amount(r)), tone: 'warn', tab: 'Dépenses' })), ...missingProof.slice(0, 4).map((r) => ({ id: `proof-${r.id}`, title: labelOf(r), detail: 'Preuve manquante', value: fmtCurrency(amount(r)), tone: 'warn', tab: 'Documents' }))].slice(0, 8);
    return { transactions, incomeRows, expenseRows, income: totalIncome, expenses: totalExpenses, balance: totalIncome - totalExpenses, unpaidRows, unpaidAmount, financeDocs, missingProof, investments, investmentAmount, businessPlans: arr(props.businessPlans), projectedRevenue, recurringCosts, priorities };
  }, [props]);
  const content = tab === 'Résumé' ? <Summary data={data} setTab={setTab} /> : tab === 'Trésorerie' ? <Treasury data={data} selected={selectedTransaction} setSelected={setSelectedTransaction} setTab={setTab} /> : tab === 'Recettes' ? <RowsSection icon={TrendingUp} title="Recettes" rows={data.incomeRows} empty="Aucune recette." tone="good" /> : tab === 'Dépenses' ? <RowsSection icon={Scale} title="Dépenses" rows={data.expenseRows} empty="Aucune dépense." tone="auto" /> : tab === 'Comptabilité' ? <Accounting data={data} /> : tab === 'Investissements' ? <Investments data={data} selected={selectedInvestment} setSelected={setSelectedInvestment} setTab={setTab} /> : tab === 'Prévisions' ? <Forecast data={data} /> : <Docs data={data} />;
  return <div className="space-y-6"><div className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs uppercase tracking-[0.25em] text-[#9a6b12] font-black">Pilotage</p><h1 className="mt-1 text-2xl font-black text-[#2f2415]">Finance & Pilotage</h1></div><div className="flex flex-wrap gap-2"><Button onClick={() => setTab('Trésorerie')}>Trésorerie</Button><Button onClick={() => setTab('Comptabilité')}>Comptabilité</Button><Button onClick={() => setTab('Investissements')}>Investissements</Button></div></div></div><Tabs active={tab} onChange={setTab} />{content}</div>;
}
