import { Database, Lock, Settings, ShieldAlert, ShieldCheck, UserCog } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { canPerformSystemAction } from '../utils/systemAccessWorkflows';

const arr = (v) => Array.isArray(v) ? v : [];
function Stat({ label, value, tone = 'neutral' }) { const cls = tone === 'good' ? 'text-emerald-600' : tone === 'warn' ? 'text-amber-600' : 'text-[#2f2415]'; return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="text-xs text-[#8a7456]">{label}</p><p className={`mt-1 text-xl font-black ${cls}`}>{value}</p></div>; }
function Row({ title, detail, value, tone = 'neutral' }) { const cls = tone === 'good' ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : tone === 'warn' ? 'border-amber-200 bg-amber-50 text-amber-700' : 'border-[#eadcc2] bg-[#fffdf8] text-[#8a7456]'; return <div className="grid grid-cols-1 gap-2 border-b border-[#eadcc2]/70 py-4 last:border-b-0 md:grid-cols-[260px_1fr_auto] md:items-center"><b className="text-[#2f2415]">{title}</b><span className="text-sm text-[#8a7456]">{detail}</span><span className={`rounded-full border px-3 py-1 text-xs font-black ${cls}`}>{value}</span></div>; }
export default function GestionSystemeUnified({ equipements = [], transactions = [], documents = [], tasks = [] }) {
  const { role } = useAuth();
  const canManage = canPerformSystemAction(role, 'modifier');
  const checks = [
    { title: 'Accès utilisateur', detail: canManage ? 'Le rôle actuel peut administrer les réglages.' : 'Le rôle actuel est limité en lecture.', value: canManage ? 'Admin' : 'Lecture', tone: canManage ? 'good' : 'warn' },
    { title: 'Données financières', detail: `${arr(transactions).length} mouvement(s) suivis dans Finance & Pilotage.`, value: 'Suivi' },
    { title: 'Documents', detail: `${arr(documents).length} document(s) suivis dans Documents & Rapports.`, value: 'Suivi' },
    { title: 'Ressources', detail: `${arr(equipements).length} équipement(s) suivis dans Opérations & Ressources.`, value: 'Suivi' },
    { title: 'Actions', detail: `${arr(tasks).length} tâche(s) suivie(s) dans Activité & Suivi.`, value: 'Suivi' },
  ];
  return <div className="space-y-6"><section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs uppercase tracking-[0.25em] text-[#9a6b12] font-black">Administration</p><h1 className="mt-1 text-2xl font-black text-[#2f2415]">Gestion du système</h1><p className="mt-1 text-sm text-[#8a7456]">Paramètres, accès et santé globale de l’ERP, sans exposer de détails techniques inutiles.</p></div><div className={`rounded-2xl border px-4 py-3 text-sm font-black ${canManage ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-amber-200 bg-amber-50 text-amber-800'}`}>{canManage ? <ShieldCheck size={16} className="inline mr-1" /> : <ShieldAlert size={16} className="inline mr-1" />}{canManage ? 'Actions admin autorisées' : 'Lecture seule'}</div></div></section><div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><Stat label="Rôle" value={role || 'Utilisateur'} tone={canManage ? 'good' : 'warn'} /><Stat label="Équipements" value={arr(equipements).length} /><Stat label="Finances" value={arr(transactions).length} /><Stat label="Documents" value={arr(documents).length} /><Stat label="Tâches" value={arr(tasks).length} /></div><section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-black text-[#2f2415]"><Settings size={20} /> Contrôles système</h2><div className="mt-4">{checks.map((item) => <Row key={item.title} {...item} />)}</div></section><section className="grid grid-cols-1 gap-4 lg:grid-cols-3"><div className="rounded-3xl border border-[#eadcc2] bg-[#fffdf8] p-5"><UserCog size={20} className="text-[#9a6b12]" /><p className="mt-3 font-black text-[#2f2415]">Utilisateurs</p><p className="mt-1 text-sm text-[#8a7456]">Gérer les rôles et accès selon les responsabilités.</p></div><div className="rounded-3xl border border-[#eadcc2] bg-[#fffdf8] p-5"><Database size={20} className="text-[#9a6b12]" /><p className="mt-3 font-black text-[#2f2415]">Données</p><p className="mt-1 text-sm text-[#8a7456]">Contrôler les volumes et la cohérence des informations ERP.</p></div><div className="rounded-3xl border border-[#eadcc2] bg-[#fffdf8] p-5"><Lock size={20} className="text-[#9a6b12]" /><p className="mt-3 font-black text-[#2f2415]">Sécurité</p><p className="mt-1 text-sm text-[#8a7456]">Les actions sensibles doivent rester réservées aux profils autorisés.</p></div></section></div>;
}
