import { AlertTriangle, CheckCircle2, Landmark, Link2, TrendingUp, Wallet } from 'lucide-react';
import { analyzeInvestmentIntegrity } from '../services/investmentIntegrityService';
import { fmtCurrency } from '../utils/format';

const arr = (value) => (Array.isArray(value) ? value : []);
const label = (row = {}) => row.nom || row.name || row.title || row.libelle || row.id || 'Élément';
function Card({ icon: Icon, label, value, danger = false }) { return <div className={`rounded-2xl border p-4 ${danger ? 'border-urgent bg-urgent-bg' : 'border-line bg-card'}`}><p className="flex items-center gap-2 text-xs uppercase tracking-normal text-slate"><Icon size={14} aria-hidden="true" /> {label}</p><p className={`mt-2 text-xl font-semibold ${danger ? 'text-urgent' : 'text-earth'}`}>{value}</p></div>; }
export default function InvestmentQualityControl({ rows = [], businessPlans = [], bpInvestmentLines = [], bpFundingSources = [], transactions = [], lots = [], animaux = [], cultures = [] }) {
  const auditRaw = analyzeInvestmentIntegrity({ investments: rows, businessPlans, investmentLines: bpInvestmentLines, fundingSources: bpFundingSources, transactions, lots, animaux, cultures }) || {};
  const issues = arr(auditRaw.issues);
  const issueCount = Number(auditRaw.issueCount ?? issues.length ?? 0);
  const funding = issues.filter((i) => String(i.type || '').includes('financement') || String(i.type || '').includes('Financement')).length;
  const finance = issues.filter((i) => String(i.type || '').includes('Finance') || String(i.type || '').includes('transaction')).length;
  const activity = issues.filter((i) => String(i.type || '').includes('activité')).length;
  const budget = issues.filter((i) => String(i.type || '').includes('budget')).length;
  return <section className="rounded-3xl border border-line bg-white p-6 shadow-card space-y-4"><div className="flex flex-col md:flex-row md:items-start md:justify-between gap-3"><div><p className="flex items-center gap-2 text-lg font-semibold text-earth"><TrendingUp size={20} aria-hidden="true" /> Contrôle investissements</p><p className="mt-1 text-sm text-slate">Vérifie les BP sans financement, sorties Finance manquantes, activités non liées et écarts prévu/réel.</p></div><div className={`${issueCount ? 'bg-vigilance-bg text-horizon-dark border-vigilance' : 'bg-positive-bg text-positive border-positive'} rounded-2xl border px-4 py-3 text-sm font-semibold`}>{issueCount ? `${issueCount} point(s) à vérifier` : 'Investissements cohérents'}</div></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Card icon={Landmark} label="Financement" value={funding} danger={funding > 0} /><Card icon={Wallet} label="Finance à relier" value={finance} danger={finance > 0} /><Card icon={Link2} label="Activités à relier" value={activity} danger={activity > 0} /><Card icon={AlertTriangle} label="Budget" value={budget} danger={budget > 0} /></div>{issueCount ? <div className="overflow-x-auto rounded-2xl border border-line"><table className="min-w-full text-sm"><thead><tr className="border-b border-line bg-card text-left text-xs uppercase text-slate"><th className="py-2 px-3">Élément</th><th className="py-2 px-3">Problème</th><th className="py-2 px-3">Montant</th></tr></thead><tbody>{issues.slice(0, 12).map((issue, i) => <tr key={`${issue.id || 'issue'}-${i}`} className="border-b border-line"><td className="py-3 px-3 font-semibold text-earth">{label(issue.bp || issue.investment || issue.transaction || issue)}</td><td className="py-3 px-3"><span className="rounded-full bg-vigilance-bg px-2 py-1 text-xs font-semibold text-horizon-dark">{issue.type || 'À vérifier'}</span></td><td className="py-3 px-3">{issue.amount ? fmtCurrency(issue.amount) : '-'}</td></tr>)}</tbody></table></div> : <div className="rounded-2xl border border-positive bg-positive-bg p-3 text-sm text-positive"><CheckCircle2 size={16} className="inline" aria-hidden="true" /> Aucune incohérence critique détectée côté investissements.</div>}</section>;
}
