import { BarChart3, Bot, Camera, ClipboardList, HardHat, Search, Settings, Tractor, UserCog, Wifi, Wrench } from 'lucide-react';
import { useMemo, useState } from 'react';
import { fmtCurrency, fmtNumber } from '../utils/format';

const arr = (v) => Array.isArray(v) ? v : [];
const low = (v) => String(v || '').toLowerCase();
const n = (v = 0) => Number(v || 0);
const labelOf = (r = {}) => r.nom || r.name || r.title || r.libelle || r.matricule || r.id || 'Élément';
const dateOf = (r = {}) => r.date || r.due_date || r.created_at || r.updated_at || r.last_seen_at || '—';
const amountOf = (r = {}) => n(r.montant || r.amount || r.cout || r.cost || r.total);
const statusOf = (r = {}) => r.status || r.statut || r.etat || 'Suivi';
const isOpen = (r = {}) => !['termine', 'terminé', 'done', 'closed', 'clos', 'resolu', 'résolu'].includes(low(statusOf(r)));
const isEquipmentRisk = (r = {}) => ['panne', 'maintenance', 'hors_service', 'a_reparer', 'à réparer'].includes(low(statusOf(r)));
const isDeviceRisk = (r = {}) => ['offline', 'hors_ligne', 'panne', 'inactive'].includes(low(statusOf(r))) || r.online === false;
const isOpsEvent = (r = {}) => /rh|equipe|équipe|equipement|équipement|maintenance|smart|capteur|camera|caméra|terrain/.test(low(`${r.module_source || r.module || ''} ${r.event_type || ''} ${r.title || ''}`));
const taskRisk = (r = {}) => ['critique', 'urgent', 'haute'].includes(low(r.priority || r.priorite)) || ['retard', 'overdue'].includes(low(statusOf(r)));

function Stat({ label, value, tone = 'neutral' }) {
  const cls = tone === 'good' ? 'text-emerald-600' : tone === 'warn' ? 'text-amber-600' : tone === 'bad' ? 'text-red-600' : 'text-[#2f2415]';
  return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="text-xs text-[#8a7456]">{label}</p><p className={`mt-1 text-xl font-black ${cls}`}>{value}</p></div>;
}
function Section({ icon: Icon, title, children, action }) { return <section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="flex items-center gap-2 text-lg font-black text-[#2f2415]"><Icon size={20} /> {title}</h2>{action}</div>{children}</section>; }
function Button({ children, onClick }) { return <button type="button" onClick={onClick} className="rounded-xl border border-[#d6c3a0] bg-[#fffdf8] px-3 py-2 text-xs font-black text-[#2f2415] hover:bg-[#dcfce7]">{children}</button>; }
function Pill({ children, tone = 'neutral' }) { const cls = tone === 'good' ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : tone === 'warn' ? 'border-amber-200 bg-amber-50 text-amber-700' : tone === 'bad' ? 'border-red-200 bg-red-50 text-red-700' : 'border-[#eadcc2] bg-[#fffdf8] text-[#8a7456]'; return <span className={`rounded-full border px-3 py-1 text-xs font-black ${cls}`}>{children}</span>; }
function Row({ title, detail, value, tone = 'neutral', onClick }) { return <button type="button" onClick={onClick} className="grid w-full grid-cols-1 gap-2 border-b border-[#eadcc2]/70 py-4 text-left last:border-b-0 md:grid-cols-[260px_1fr_auto] md:items-center hover:bg-[#fffdf8]"><span className="font-black text-[#2f2415]">{title}</span><span className="text-sm text-[#8a7456]">{detail}</span><Pill tone={tone}>{value}</Pill></button>; }
function Field({ label, value }) { return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="text-xs text-[#8a7456]">{label}</p><p className="mt-1 font-black text-[#2f2415]">{value}</p></div>; }
function Empty({ label }) { return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-5 text-sm text-[#8a7456]">{label}</div>; }
function Tabs({ active, onChange }) { const tabs = ['Résumé', 'Équipe', 'Équipements', 'Maintenance', 'Smart Farm', 'Terrain', 'Historique', 'Graphiques']; return <div className="overflow-x-auto"><div className="flex min-w-max gap-2 rounded-2xl border border-[#d6c3a0] bg-white p-2">{tabs.map((tab) => <button key={tab} type="button" onClick={() => onChange(tab)} className={`rounded-xl px-4 py-2 text-sm font-black transition ${active === tab ? 'bg-[#22c55e] text-[#052e16]' : 'text-[#8a7456] hover:bg-[#fffdf8] hover:text-[#2f2415]'}`}>{tab}</button>)}</div></div>; }

function Summary({ data, setTab }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><Stat label="Équipe" value={fmtNumber(data.team.length)} /><Stat label="Équipements" value={fmtNumber(data.equipment.length)} /><Stat label="Maintenance" value={fmtNumber(data.equipmentRisk.length)} tone={data.equipmentRisk.length ? 'warn' : 'good'} /><Stat label="Capteurs" value={fmtNumber(data.devices.length)} /><Stat label="Terrain" value={fmtNumber(data.fieldTasks.length)} tone={data.fieldTasks.length ? 'warn' : 'good'} /></div><Section icon={ClipboardList} title="Priorités opérations" action={<Button onClick={() => setTab('Terrain')}>Voir terrain</Button>}>{data.priorities.length ? data.priorities.map((p) => <Row key={p.id} title={p.title} detail={p.detail} value={p.value} tone={p.tone} onClick={() => setTab(p.tab)} />) : <Empty label="Aucune priorité opérationnelle." />}</Section></div>; }
function Team({ data }) { return <Section icon={UserCog} title="Équipe">{data.team.length ? data.team.slice(0, 14).map((r) => <Row key={r.id || labelOf(r)} title={labelOf(r)} detail={`${r.role || r.poste || r.fonction || 'Membre équipe'} · ${r.telephone || r.phone || r.contact || 'contact non renseigné'}`} value={statusOf(r)} tone={isOpen(r) ? 'neutral' : 'good'} />) : <Empty label="Aucun membre d’équipe renseigné." />}</Section>; }
function Equipment({ data, selected, setSelected, setTab }) { const row = selected || data.equipment[0]; return <div className="grid grid-cols-1 gap-4 xl:grid-cols-[1fr_420px]"><Section icon={Tractor} title="Équipements" action={<Button onClick={() => setTab('Maintenance')}>Maintenance</Button>}>{data.equipment.length ? data.equipment.slice(0, 14).map((r) => <Row key={r.id || labelOf(r)} title={labelOf(r)} detail={`${r.type || r.categorie || 'Matériel'} · ${dateOf(r)}`} value={isEquipmentRisk(r) ? 'À traiter' : 'OK'} tone={isEquipmentRisk(r) ? 'warn' : 'good'} onClick={() => setSelected(r)} />) : <Empty label="Aucun équipement." />}</Section><Section icon={Search} title="Fiche équipement"><div className="space-y-3">{row ? <><Field label="Équipement" value={labelOf(row)} /><Field label="Type" value={row.type || row.categorie || '—'} /><Field label="Statut" value={statusOf(row)} /><Field label="Dernier suivi" value={dateOf(row)} /><Field label="Coût" value={fmtCurrency(amountOf(row))} /></> : <Empty label="Aucun équipement sélectionné." />}</div></Section></div>; }
function Maintenance({ data, setTab }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="À maintenir" value={fmtNumber(data.equipmentRisk.length)} tone={data.equipmentRisk.length ? 'warn' : 'good'} /><Stat label="Tâches maintenance" value={fmtNumber(data.maintenanceTasks.length)} /><Stat label="Coût estimé" value={fmtCurrency(data.maintenanceCost)} /><Stat label="Historique" value={fmtNumber(data.maintenanceEvents.length)} /></div><Section icon={Wrench} title="Maintenance" action={<Button onClick={() => setTab('Historique')}>Historique</Button>}>{data.maintenanceRows.length ? data.maintenanceRows.slice(0, 14).map((r) => <Row key={r.id || labelOf(r)} title={labelOf(r)} detail={`${dateOf(r)} · ${r.type || r.event_type || r.categorie || 'Maintenance'}`} value={isEquipmentRisk(r) || taskRisk(r) ? 'À faire' : statusOf(r)} tone={isEquipmentRisk(r) || taskRisk(r) ? 'warn' : 'good'} />) : <Empty label="Aucune maintenance." />}</Section></div>; }
function SmartFarm({ data }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Capteurs" value={fmtNumber(data.sensors.length)} /><Stat label="Caméras" value={fmtNumber(data.cameras.length)} /><Stat label="Hors ligne" value={fmtNumber(data.devicesRisk.length)} tone={data.devicesRisk.length ? 'warn' : 'good'} /><Stat label="Connectés" value={fmtNumber(data.devices.length - data.devicesRisk.length)} tone="good" /></div><Section icon={Wifi} title="Smart Farm">{data.devices.length ? data.devices.slice(0, 14).map((r) => <Row key={r.id || labelOf(r)} title={labelOf(r)} detail={`${r.type || r.device_type || 'Appareil'} · ${dateOf(r)}`} value={isDeviceRisk(r) ? 'Hors ligne' : 'OK'} tone={isDeviceRisk(r) ? 'warn' : 'good'} />) : <Empty label="Aucun appareil Smart Farm." />}</Section></div>; }
function FieldWork({ data }) { return <Section icon={HardHat} title="Terrain">{data.fieldTasks.length ? data.fieldTasks.slice(0, 14).map((r) => <Row key={r.id || labelOf(r)} title={labelOf(r)} detail={`${dateOf(r)} · ${r.module_source || r.module || r.category || 'Terrain'}`} value={taskRisk(r) ? 'Priorité' : statusOf(r)} tone={taskRisk(r) ? 'warn' : 'neutral'} />) : <Empty label="Aucune tâche terrain." />}</Section>; }
function History({ data }) { return <Section icon={ClipboardList} title="Historique opérations">{data.history.length ? data.history.slice(0, 16).map((r) => <Row key={r.id || labelOf(r)} title={labelOf(r)} detail={`${dateOf(r)} · ${r.module_source || r.module || r.type || 'Opérations'}`} value={statusOf(r)} />) : <Empty label="Aucun historique opérationnel." />}</Section>; }
function Graphs({ data }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Équipements OK" value={fmtNumber(data.equipment.length - data.equipmentRisk.length)} tone="good" /><Stat label="Maintenance" value={fmtNumber(data.equipmentRisk.length)} tone={data.equipmentRisk.length ? 'warn' : 'good'} /><Stat label="Smart Farm OK" value={fmtNumber(data.devices.length - data.devicesRisk.length)} tone="good" /><Stat label="Terrain" value={fmtNumber(data.fieldTasks.length)} /></div><Section icon={BarChart3} title="Graphiques"><div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-5"><div className="space-y-4"><div><div className="mb-1 flex justify-between text-xs text-[#8a7456]"><span>Équipements opérationnels</span><span>{fmtNumber(data.equipment.length - data.equipmentRisk.length)}</span></div><div className="h-3 rounded-full bg-[#e8f3e8]"><div className="h-3 rounded-full bg-[#22c55e]" style={{ width: `${data.equipment.length ? Math.min(100, ((data.equipment.length - data.equipmentRisk.length) / data.equipment.length) * 100) : 0}%` }} /></div></div><div><div className="mb-1 flex justify-between text-xs text-[#8a7456]"><span>Appareils connectés</span><span>{fmtNumber(data.devices.length - data.devicesRisk.length)}</span></div><div className="h-3 rounded-full bg-[#e8f3e8]"><div className="h-3 rounded-full bg-[#22c55e]" style={{ width: `${data.devices.length ? Math.min(100, ((data.devices.length - data.devicesRisk.length) / data.devices.length) * 100) : 0}%` }} /></div></div></div></div></Section></div>; }

export default function OperationsRessourcesModule({ equipe = [], rh = [], equipements = [], sensorDevices = [], cameraDevices = [], tasks = [], taches = [], transactions = [], finances = [], businessEvents = [], documents = [] }) {
  const [tab, setTab] = useState('Résumé');
  const [selectedEquipment, setSelectedEquipment] = useState(null);
  const data = useMemo(() => {
    const team = arr(equipe).length ? arr(equipe) : arr(rh);
    const equipment = arr(equipements);
    const sensors = arr(sensorDevices);
    const cameras = arr(cameraDevices);
    const devices = [...sensors, ...cameras];
    const taskRows = arr(tasks).length ? arr(tasks) : arr(taches);
    const events = arr(businessEvents).filter(isOpsEvent);
    const equipmentRisk = equipment.filter(isEquipmentRisk);
    const devicesRisk = devices.filter(isDeviceRisk);
    const fieldTasks = taskRows.filter((t) => /terrain|maintenance|equipement|équipement|smart|capteur|camera|caméra|rh|equipe|équipe/.test(low(`${t.module_source || t.module || ''} ${t.title || ''} ${t.description || ''}`)) || taskRisk(t));
    const maintenanceTasks = taskRows.filter((t) => /maintenance|panne|reparation|réparation|equipement|équipement/.test(low(`${t.title || ''} ${t.description || ''} ${t.category || ''}`)));
    const maintenanceEvents = events.filter((e) => /maintenance|panne|reparation|réparation|equipement|équipement/.test(low(`${e.event_type || ''} ${e.title || ''}`)));
    const maintenanceRows = [...equipmentRisk, ...maintenanceTasks, ...maintenanceEvents];
    const maintenanceCost = [...arr(transactions), ...arr(finances), ...maintenanceEvents].reduce((sum, r) => sum + (/maintenance|equipement|équipement|panne/.test(low(`${r.categorie || ''} ${r.category || ''} ${r.title || ''} ${r.module_source || ''}`)) ? amountOf(r) : 0), 0);
    const priorities = [...equipmentRisk.slice(0, 5).map((r) => ({ id: `eq-${r.id || labelOf(r)}`, title: labelOf(r), detail: statusOf(r), value: 'Maintenance', tone: 'warn', tab: 'Maintenance' })), ...devicesRisk.slice(0, 5).map((r) => ({ id: `dev-${r.id || labelOf(r)}`, title: labelOf(r), detail: 'Appareil hors ligne', value: 'Smart', tone: 'warn', tab: 'Smart Farm' })), ...fieldTasks.filter(taskRisk).slice(0, 5).map((r) => ({ id: `task-${r.id || labelOf(r)}`, title: labelOf(r), detail: dateOf(r), value: 'Terrain', tone: 'warn', tab: 'Terrain' }))].slice(0, 10);
    const history = [...events, ...equipment, ...devices, ...fieldTasks, ...arr(documents)].sort((a, b) => String(dateOf(b)).localeCompare(String(dateOf(a))));
    return { team, equipment, sensors, cameras, devices, devicesRisk, equipmentRisk, fieldTasks, maintenanceTasks, maintenanceEvents, maintenanceRows, maintenanceCost, priorities, history };
  }, [equipe, rh, equipements, sensorDevices, cameraDevices, tasks, taches, transactions, finances, businessEvents, documents]);
  const content = tab === 'Résumé' ? <Summary data={data} setTab={setTab} /> : tab === 'Équipe' ? <Team data={data} /> : tab === 'Équipements' ? <Equipment data={data} selected={selectedEquipment} setSelected={setSelectedEquipment} setTab={setTab} /> : tab === 'Maintenance' ? <Maintenance data={data} setTab={setTab} /> : tab === 'Smart Farm' ? <SmartFarm data={data} /> : tab === 'Terrain' ? <FieldWork data={data} /> : tab === 'Historique' ? <History data={data} /> : <Graphs data={data} />;
  return <div className="space-y-6"><div className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs uppercase tracking-[0.25em] text-[#9a6b12] font-black">Ressources</p><h1 className="mt-1 text-2xl font-black text-[#2f2415]">Opérations & Ressources</h1></div><div className="flex flex-wrap gap-2"><Button onClick={() => setTab('Équipe')}>Équipe</Button><Button onClick={() => setTab('Équipements')}>Équipements</Button><Button onClick={() => setTab('Smart Farm')}>Smart Farm</Button></div></div></div><Tabs active={tab} onChange={setTab} />{content}</div>;
}
