import { BarChart3, BrainCircuit, ClipboardList, Goal, Lightbulb, Scale, Sparkles, TrendingUp } from 'lucide-react';
import { useMemo, useState } from 'react';
import { fmtCurrency, fmtNumber } from '../utils/format';

const arr = (v) => Array.isArray(v) ? v : [];
const n = (v = 0) => Number(v || 0);
const low = (v) => String(v || '').toLowerCase();
const amount = (r = {}) => n(r.montant ?? r.amount ?? r.total ?? r.montant_total ?? r.value ?? r.valeur);
const label = (r = {}) => r.title || r.nom || r.name || r.libelle || r.description || r.id || 'Élément';
const dateOf = (r = {}) => r.date || r.event_date || r.created_at || r.updated_at || '—';
const open = (r = {}) => !['termine', 'terminé', 'done', 'closed', 'clos', 'resolu', 'résolu'].includes(low(r.status || r.statut || r.state));
const risk = (r = {}) => ['critique', 'urgent', 'retard', 'overdue', 'malade', 'panne', 'risque'].some((x) => low(`${r.status || ''} ${r.statut || ''} ${r.priority || ''} ${r.severity || ''}`).includes(x));
const lowStock = (s = {}) => n(s.seuil ?? s.threshold) > 0 && n(s.quantite ?? s.quantity ?? s.stock) <= n(s.seuil ?? s.threshold);
const sickAnimal = (a = {}) => ['malade', 'critique', 'a_surveiller'].includes(low(a.health_status || a.sante_status || a.status_sante));
const cultureRisk = (c = {}) => n(c.score_sante ?? c.health_score ?? 100) < 80 || ['risque', 'perdu', 'malade'].includes(low(c.status || c.statut));
function Stat({ label, value, tone = 'neutral' }) { const cls = tone === 'good' ? 'text-emerald-600' : tone === 'warn' ? 'text-amber-600' : tone === 'bad' ? 'text-red-600' : 'text-[#2f2415]'; return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="text-xs text-[#8a7456]">{label}</p><p className={`mt-1 text-xl font-black ${cls}`}>{value}</p></div>; }
function Section({ icon: Icon, title, children }) { return <section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><h2 className="mb-4 flex items-center gap-2 text-lg font-black text-[#2f2415]"><Icon size={20} /> {title}</h2>{children}</section>; }
function Pill({ children, tone = 'neutral' }) { const cls = tone === 'good' ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : tone === 'warn' ? 'border-amber-200 bg-amber-50 text-amber-700' : 'border-[#eadcc2] bg-[#fffdf8] text-[#8a7456]'; return <span className={`rounded-full border px-3 py-1 text-xs font-black ${cls}`}>{children}</span>; }
function Row({ title, detail, value, tone = 'neutral' }) { return <div className="grid grid-cols-1 gap-2 border-b border-[#eadcc2]/70 py-4 last:border-b-0 md:grid-cols-[260px_1fr_auto] md:items-center"><b className="text-[#2f2415]">{title}</b><span className="text-sm text-[#8a7456]">{detail}</span><Pill tone={tone}>{value}</Pill></div>; }
function Empty({ label }) { return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-5 text-sm text-[#8a7456]">{label}</div>; }
function Tabs({ tab, setTab }) { return <div className="overflow-x-auto"><div className="flex min-w-max gap-2 rounded-2xl border border-[#d6c3a0] bg-white p-2">{['Résumé','Décisions','Objectifs','Croissance','Impact','Historique','Graphiques'].map((x) => <button key={x} type="button" onClick={() => setTab(x)} className={`rounded-xl px-4 py-2 text-sm font-black ${tab === x ? 'bg-[#22c55e] text-[#052e16]' : 'text-[#8a7456] hover:bg-[#fffdf8]'}`}>{x}</button>)}</div></div>; }
export default function PilotageStrategieModule(props) {
  const [tab, setTab] = useState('Résumé');
  const data = useMemo(() => { const map = props.dataMap || {}; const animaux = arr(props.animaux || map.animaux); const lots = arr(props.lots || props.avicole || map.lots || map.avicole); const cultures = arr(props.cultures || map.cultures); const stocks = arr(props.stocks || props.stock || map.stocks || map.stock); const ventes = arr(props.salesOrders || props.sales_orders || map.salesOrders || map.sales_orders); const finances = arr(props.transactions || props.finances || map.transactions || map.finances); const tasks = arr(props.tasks || props.taches || map.tasks || map.taches); const alertes = arr(props.alertes || map.alertes); const docs = arr(props.documents || map.documents); const inv = arr(props.investissements || map.investissements); const plans = arr(props.businessPlans || props.business_plans || map.business_plans); const events = arr(props.businessEvents || map.businessEvents || map.business_events); const risks = [...stocks.filter(lowStock), ...animaux.filter(sickAnimal), ...cultures.filter(cultureRisk), ...tasks.filter(risk), ...alertes.filter(risk)]; const income = finances.filter((r) => ['entree','entrée','income','recette','vente'].includes(low(r.type || r.nature || r.sens))).reduce((s, r) => s + amount(r), 0); const expenses = finances.filter((r) => !['entree','entrée','income','recette','vente'].includes(low(r.type || r.nature || r.sens))).reduce((s, r) => s + amount(r), 0); const ca = ventes.reduce((s, r) => s + amount(r), 0); const score = Math.max(10, Math.min(100, 90 - risks.length * 6 + Math.min(10, docs.length / 2))); const decisions = [...stocks.filter(lowStock).slice(0,4).map((r)=>({title:label(r),detail:'Stock sous seuil dans Achats & Stock',value:'Acheter',tone:'warn'})), ...animaux.filter(sickAnimal).slice(0,4).map((r)=>({title:label(r),detail:'Animal à suivre dans Élevage',value:'Santé',tone:'warn'})), ...cultures.filter(cultureRisk).slice(0,4).map((r)=>({title:label(r),detail:'Culture à risque',value:'Traiter',tone:'warn'})), ...alertes.filter(open).slice(0,4).map((r)=>({title:label(r),detail:'Alerte ouverte dans Activité & Suivi',value:'Suivre',tone:'warn'}))]; const objectifs = [...plans.map((r)=>({title:label(r),detail:r.status||r.statut||'Plan',value:fmtCurrency(amount(r)),tone:'neutral'})), ...tasks.filter(open).map((r)=>({title:label(r),detail:dateOf(r),value:risk(r)?'Priorité':'Action',tone:risk(r)?'warn':'neutral'}))].slice(0,12); return { animaux,lots,cultures,stocks,ventes,finances,tasks,alertes,docs,inv,plans,events,risks,income,expenses,ca,score:Math.round(score),decisions,objectifs,net:income-expenses,production:animaux.length+lots.length+cultures.length }; }, [props]);
  const list = tab === 'Décisions' ? data.decisions : tab === 'Objectifs' ? data.objectifs : tab === 'Croissance' ? [{title:'Chiffre d’affaires',detail:'Ventes suivies dans Commercial',value:fmtCurrency(data.ca),tone:'good'},{title:'Investissements',detail:`${data.inv.length} investissement(s)`,value:fmtNumber(data.inv.length),tone:'neutral'},{title:'Plans de croissance',detail:`${data.plans.length} plan(s)`,value:fmtNumber(data.plans.length),tone:'neutral'}] : tab === 'Impact' ? [{title:'Impact financier',detail:'Recettes moins dépenses',value:fmtCurrency(data.net),tone:data.net>=0?'good':'warn'},{title:'Base productive',detail:'Animaux, lots et cultures',value:fmtNumber(data.production),tone:'neutral'},{title:'Preuves disponibles',detail:'Documents et justificatifs',value:fmtNumber(data.docs.length),tone:data.docs.length?'good':'warn'}] : tab === 'Historique' ? data.events.slice(0,16).map((r)=>({title:label(r),detail:dateOf(r),value:r.status||r.statut||r.event_type||'Suivi',tone:risk(r)?'warn':'neutral'})) : [];
  return <div className="space-y-6"><section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><p className="text-xs uppercase tracking-[0.25em] text-[#9a6b12] font-black">Pilotage</p><h1 className="mt-1 text-2xl font-black text-[#2f2415]">Pilotage & Stratégie</h1><p className="mt-1 text-sm text-[#8a7456]">Décisions, objectifs, croissance et impact dans un seul module.</p></section><Tabs tab={tab} setTab={setTab} />{tab === 'Résumé' ? <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><Stat label="Score ferme" value={`${data.score}/100`} tone={data.score>=75?'good':data.score>=50?'warn':'bad'} /><Stat label="Décisions" value={fmtNumber(data.decisions.length)} tone={data.decisions.length?'warn':'good'} /><Stat label="Objectifs" value={fmtNumber(data.objectifs.length)} /><Stat label="Impact net" value={fmtCurrency(data.net)} tone={data.net>=0?'good':'warn'} /><Stat label="Risques" value={fmtNumber(data.risks.length)} tone={data.risks.length?'warn':'good'} /></div><Section icon={Lightbulb} title="Priorités stratégiques">{data.decisions.length ? data.decisions.slice(0,8).map((r,i)=><Row key={i} {...r} />) : <Empty label="Aucune priorité stratégique." />}</Section></div> : tab === 'Graphiques' ? <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Score" value={`${data.score}/100`} tone={data.score>=75?'good':'warn'} /><Stat label="Risques" value={fmtNumber(data.risks.length)} tone={data.risks.length?'warn':'good'} /><Stat label="Production" value={fmtNumber(data.production)} /><Stat label="CA" value={fmtCurrency(data.ca)} tone="good" /></div><Section icon={BarChart3} title="Graphiques"><div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-5"><div className="mb-1 flex justify-between text-xs text-[#8a7456]"><span>Santé globale</span><span>{data.score}/100</span></div><div className="h-3 rounded-full bg-[#e8f3e8]"><div className="h-3 rounded-full bg-[#22c55e]" style={{ width: `${Math.min(100, data.score)}%` }} /></div></div></Section></div> : <Section icon={tab==='Décisions'?BrainCircuit:tab==='Objectifs'?Goal:tab==='Croissance'?TrendingUp:tab==='Impact'?Scale:ClipboardList} title={tab}>{list.length ? list.map((r,i)=><Row key={i} {...r} />) : <Empty label="Aucune donnée à afficher." />}</Section>}</div>;
}
