import { Beef, Bird, CalendarDays, Drumstick, Egg, TrendingUp } from 'lucide-react';
import MiniMetricCard from '../components/MiniMetricCard.jsx';
import { buildProductionCyclePlan } from '../services/productionCyclePlanService';
import { fmtNumber } from '../utils/format';

function Timeline({ rows = [], qtyKey = 'qty', title = 'Calendrier' }) {
  return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] overflow-hidden"><div className="px-4 py-3 border-b border-[#eadcc2]"><p className="font-black text-[#2f2415] flex items-center gap-2"><CalendarDays size={16} aria-hidden="true" /> {title}</p></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-2 p-3">{rows.map((row, index) => <div key={`${row.id || 'cycle'}-${index}`} className="rounded-xl border border-[#eadcc2] bg-white p-3"><div className="flex items-start justify-between gap-2"><div><p className="font-black text-[#2f2415]">{row.label}</p><p className="text-xs text-[#8a7456] mt-1">Lancement : <b>{row.launchDate}</b></p><p className="text-xs text-[#8a7456]">Vente / ponte : <b>{row.expectedSaleDate || row.firstEggDatePointOfLay || row.firstEggDateDayOld}</b></p></div><span className="rounded-full bg-[#2f2415] text-white px-2 py-1 text-xs font-black">{fmtNumber(row[qtyKey] || row.recommendedQty || row.placementQty || 0)}</span></div><p className="mt-2 text-xs text-[#7d6a4a] leading-relaxed">{row.action}</p></div>)}</div></div>;
}

export default function ProductionCyclePlanPanel({ dataMap = {}, lots = [], animaux = [], productionLogs = [], onNavigate }) {
  const plan = buildProductionCyclePlan({ ...dataMap, lots: lots?.length ? lots : dataMap.lots || dataMap.avicole || [], animaux: animaux?.length ? animaux : dataMap.animaux || [], productionLogs: productionLogs?.length ? productionLogs : dataMap.productionLogs || dataMap.production_oeufs_logs || [] });
  return <section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm space-y-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs uppercase tracking-[0.24em] text-[#9a6b12] font-black flex items-center gap-2"><TrendingUp size={15} aria-hidden="true" /> Plan de cycles de production</p><h2 className="mt-1 text-2xl font-black text-[#2f2415]">Cadencer les bandes pour tenir le plan financier</h2><p className="mt-1 text-sm text-[#8a7456] leading-relaxed">Le centre décisionnel transforme le prévisionnel en actions : lancer les bandes, préparer les ventes, remplacer les pondeuses et sécuriser la trésorerie.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => onNavigate?.('avicole')} className="min-h-[44px] rounded-xl border border-[#d6c3a0] bg-[#fffdf8] px-4 py-2 text-sm font-black text-[#7d6a4a] hover:bg-[#fff8e8]">Voir Avicole</button><button type="button" onClick={() => onNavigate?.('animaux')} className="min-h-[44px] rounded-xl bg-[#2f2415] px-4 py-2 text-sm font-black text-white hover:bg-[#3d2f1d]">Voir Animaux</button></div></div>
    <div className="grid grid-cols-2 xl:grid-cols-5 gap-3"><MiniMetricCard icon={Drumstick} tone="warning" label="Chair objectif" value="500 / 15 j" sub={`Rythme stable dès ${plan.chair.steadySaleStartDate}`} /><MiniMetricCard icon={CalendarDays} tone="white" label="1ère vente chair" value={plan.chair.firstSaleDate} sub="Cycle 45 jours" /><MiniMetricCard icon={Beef} tone="info" label="Bœufs départ" value="5" sub={`1ère vente ${plan.bovins.firstSaleDate}`} /><MiniMetricCard icon={Egg} tone="success" label="Œufs visés" value={`${fmtNumber(plan.pondeuses.targetEggsDay)}/jour`} sub={`${fmtNumber(plan.pondeuses.targetTabletsYear)} tablettes/an`} /><MiniMetricCard icon={Bird} tone="warning" label="Prochaine bande" value={fmtNumber(plan.pondeuses.recommendedNextBandSize)} sub="Pondeuses à sécuriser" /></div>
    <div className="grid grid-cols-1 xl:grid-cols-3 gap-4"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="font-black text-amber-900 flex items-center gap-2"><Drumstick size={17} aria-hidden="true" /> Poulets de chair</p><p className="mt-2 text-sm text-amber-900 leading-relaxed">Démarrer prudemment avec 500. Pour vendre 500 tous les 15 jours, il faut lancer des bandes chevauchées à J0, J15 et J30. La première vente arrive vers J45, puis le rythme devient stable vers J75.</p></div><div className="rounded-2xl border border-sky-200 bg-sky-50 p-4"><p className="font-black text-sky-900 flex items-center gap-2"><Beef size={17} aria-hidden="true" /> Bœufs</p><p className="mt-2 text-sm text-sky-900 leading-relaxed">Démarrer avec 5 bœufs sur 90 jours. Augmenter par palier seulement si la marge réelle, le poids de sortie et la trésorerie sont validés.</p></div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><p className="font-black text-emerald-900 flex items-center gap-2"><Egg size={17} aria-hidden="true" /> Pondeuses</p><p className="mt-2 text-sm text-emerald-900 leading-relaxed">Ne pas attendre 17 mois automatiquement. Réformer progressivement si le taux de ponte reste bas, et lancer des bandes chevauchées pour avoir des œufs toute l’année.</p></div></div>
    <Timeline title="Calendrier chair" rows={plan.chair.ramp} qtyKey="placementQty" /><Timeline title="Calendrier embouche bovine" rows={plan.bovins.cycles} qtyKey="qty" /><Timeline title="Calendrier pondeuses" rows={plan.pondeuses.bands} qtyKey="recommendedQty" />
  </section>;
}
