import { Banknote, Edit, Plus, Save, Trash2, UserCheck, Users } from 'lucide-react';
import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import Btn from '../components/Btn';
import KpiCard from '../components/KpiCard';
import SectionHeader from '../components/SectionHeader';
import { fmtCurrency, toNumber } from '../utils/format';
import { getRhDirectory, RH_MODULES, RH_ROLES, RH_TEAMS, saveRhDirectory } from '../utils/rhDirectory';
import { buildRhAbsenceFollowUp, buildRhAssignedTask } from '../utils/rhWorkflows';
import { commitRhPayroll } from '../utils/ressourcesWorkflow.js';
import RHCostCenterPanel from './RHCostCenterPanel.jsx';

const today = () => new Date().toISOString().slice(0, 10);
const newPerson = () => ({ id: `RH-${Date.now().toString(36).toUpperCase()}`, nom: '', role: 'Ouvrier ferme', fonction: 'Ouvrier polyvalent', statut: 'actif', equipe_id: 'TEAM-FERME', modules: ['avicole', 'stock'], phone: '', whatsapp: '', salaire_mensuel: 0, prime_mensuelle: 0, avance_mois: 0, date_entree: today() });
const newTeam = () => ({ id: `TEAM-${Date.now().toString(36).toUpperCase()}`, name: '', type: 'operationnelle', modules: ['avicole', 'stock'] });
const teamFor = (role = '') => role.includes('avicole') ? 'TEAM-AVICOLE' : role.includes('cultures') ? 'TEAM-CULTURES' : role.includes('stock') ? 'TEAM-STOCK' : role.includes('Commercial') ? 'TEAM-COMMERCIAL' : 'TEAM-FERME';
const modulesFor = (role = '') => role.includes('avicole') ? ['avicole', 'sante', 'stock'] : role.includes('cultures') ? ['cultures', 'stock'] : role.includes('stock') ? ['stock', 'fournisseurs'] : role.includes('Commercial') ? ['ventes', 'clients'] : ['avicole', 'stock'];
const normPerson = (p = {}) => ({ ...newPerson(), ...p, role: p.role || 'Ouvrier ferme', equipe_id: p.equipe_id || teamFor(p.role || ''), modules: Array.isArray(p.modules) && p.modules.length ? p.modules : modulesFor(p.role || '') });
const normTeam = (t = {}) => ({ ...newTeam(), ...t, name: t.name || t.nom || t.id || 'Équipe', modules: Array.isArray(t.modules) && t.modules.length ? t.modules : ['avicole', 'stock'] });
const payroll = (p = {}) => { const salaire = toNumber(p.salaire_mensuel); const prime = toNumber(p.prime_mensuelle); const avance = toNumber(p.avance_mois); return { salaire, prime, avance, brut: salaire + prime, net: Math.max(0, salaire + prime - avance) }; };
const teamName = (teams, id) => teams.find((t) => t.id === id)?.name || id || 'Équipe ferme';
const moduleName = (key) => RH_MODULES.find((m) => m.key === key)?.label || key;

function ModuleSection({ icon: Icon, title, subtitle, children }) {
  return <section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm space-y-4"><div><p className="flex items-center gap-2 text-lg font-black text-[#2f2415]"><Icon size={20} /> {title}</p>{subtitle ? <p className="mt-1 text-sm text-[#8a7456]">{subtitle}</p> : null}</div>{children}</section>;
}
function Field({ label, value, onChange, type = 'text' }) {
  return <label className="block text-sm"><span className="text-[#8a7456]">{label}</span><input type={type} className="mt-1 w-full rounded-lg border border-[#d6c3a0] bg-[#fffdf8] px-3 py-2" value={value ?? ''} onChange={(e) => onChange(e.target.value)} /></label>;
}
function ModulePicker({ value = [], onToggle }) {
  return <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 max-h-40 overflow-auto rounded-xl border border-[#eadcc2] bg-[#fffdf8] p-2">{RH_MODULES.map((m) => <label key={m.key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.includes(m.key)} onChange={() => onToggle(m.key)} /> {m.label}</label>)}</div>;
}

export default function RHPeopleTeams({ onRefresh, onCreateFinanceTransaction, onRefreshFinances, onCreateDocument, onRefreshDocuments, onCreateTask, onRefreshTasks, onCreateBusinessEvent, onRefreshBusinessEvents }) {
  const [directory, setDirectory] = useState(() => { const d = getRhDirectory(); return { people: (d.people || []).map(normPerson), teams: (d.teams || RH_TEAMS).map(normTeam) }; });
  const [person, setPerson] = useState(null);
  const [team, setTeam] = useState(null);
  const people = directory.people.map(normPerson);
  const teams = directory.teams.map(normTeam);
  const active = people.filter((p) => ['actif', 'active'].includes(String(p.statut || '').toLowerCase()));
  const totals = active.reduce((acc, p) => { const m = payroll(p); return { brut: acc.brut + m.brut, avance: acc.avance + m.avance, net: acc.net + m.net }; }, { brut: 0, avance: 0, net: 0 });
  useEffect(() => { const sync = () => { const d = getRhDirectory(); setDirectory({ people: (d.people || []).map(normPerson), teams: (d.teams || RH_TEAMS).map(normTeam) }); }; window.addEventListener('horizon-farm-rh-updated', sync); return () => window.removeEventListener('horizon-farm-rh-updated', sync); }, []);
  const persist = (nextPeople = people, nextTeams = teams) => { const next = saveRhDirectory({ people: nextPeople.map(normPerson), teams: nextTeams.map(normTeam) }); setDirectory({ people: next.people.map(normPerson), teams: next.teams.map(normTeam) }); };
  const setP = (key, value) => setPerson((prev) => ({ ...prev, [key]: value }));
  const setT = (key, value) => setTeam((prev) => ({ ...prev, [key]: value }));
  const togglePersonModule = (key) => setPerson((prev) => { const list = Array.isArray(prev.modules) ? prev.modules : []; return { ...prev, modules: list.includes(key) ? list.filter((x) => x !== key) : [...list, key] }; });
  const toggleTeamModule = (key) => setTeam((prev) => { const list = Array.isArray(prev.modules) ? prev.modules : []; return { ...prev, modules: list.includes(key) ? list.filter((x) => x !== key) : [...list, key] }; });
  const savePerson = () => { if (!String(person?.nom || '').trim()) return toast.error('Nom obligatoire'); const payload = normPerson({ ...person, salaire_mensuel: toNumber(person.salaire_mensuel), prime_mensuelle: toNumber(person.prime_mensuelle), avance_mois: toNumber(person.avance_mois), updated_at: new Date().toISOString() }); const exists = people.some((p) => p.id === payload.id); persist(exists ? people.map((p) => p.id === payload.id ? payload : p) : [...people, { ...payload, created_at: new Date().toISOString() }], teams); setPerson(null); toast.success(exists ? 'Fiche RH mise à jour' : 'RH ajoutée'); };
  const saveTeam = () => { if (!String(team?.name || '').trim()) return toast.error('Nom équipe obligatoire'); const payload = normTeam({ ...team, updated_at: new Date().toISOString() }); const exists = teams.some((t) => t.id === payload.id); persist(people, exists ? teams.map((t) => t.id === payload.id ? payload : t) : [...teams, { ...payload, created_at: new Date().toISOString() }]); setTeam(null); toast.success(exists ? 'Équipe mise à jour' : 'Équipe ajoutée'); };
  const removePerson = (p) => { if (p.id === 'RH-PENDA') return toast.error('Compte propriétaire protégé'); if (!window.confirm(`Supprimer ${p.nom} ?`)) return; persist(people.filter((x) => x.id !== p.id), teams); toast.success('RH supprimée'); };
  const removeTeam = (t) => { if (['TEAM-FERME', 'TEAM-AVICOLE', 'TEAM-CULTURES', 'TEAM-STOCK', 'TEAM-COMMERCIAL'].includes(t.id)) return toast.error('Équipe par défaut protégée'); if (people.some((p) => p.equipe_id === t.id)) return toast.error('Équipe utilisée par une RH'); if (!window.confirm(`Supprimer ${t.name} ?`)) return; persist(people, teams.filter((x) => x.id !== t.id)); toast.success('Équipe supprimée'); };
  const pay = async (p) => { const m = payroll(p); if (m.net <= 0) return toast.error('Aucun net à payer'); if (!window.confirm(`Enregistrer ${fmtCurrency(m.net)} pour ${p.nom} ?`)) return; try { const workflow = buildRhSalaryWorkflow({ person: p, teams, amount: m.net, date: today() }); await onCreateFinanceTransaction?.(workflow.financeTransaction); await onCreateDocument?.(workflow.document); await onCreateBusinessEvent?.(workflow.event); persist(people.map((x) => x.id === p.id ? { ...x, ...workflow.personPatch } : x), teams); await Promise.allSettled([onRefreshFinances?.(), onRefreshDocuments?.(), onRefreshBusinessEvents?.(), onRefresh?.()]); toast.success('Paiement RH enregistré en Finance avec preuve à joindre'); } catch (error) { toast.error(error.message || 'Paiement impossible'); } };
  const markAbsence = async (p) => { try { const workflow = buildRhAbsenceFollowUp({ person: p, date: today(), reason: 'Absence déclarée depuis RH.' }); if (workflow.task) await onCreateTask?.(workflow.task); await onCreateBusinessEvent?.(workflow.event); persist(people.map((x) => x.id === p.id ? { ...x, ...workflow.personPatch } : x), teams); await Promise.allSettled([onRefreshTasks?.(), onRefreshBusinessEvents?.(), onRefresh?.()]); toast.success('Absence signalée et tâche créée'); } catch (error) { toast.error(error.message || 'Absence impossible'); } };
  const assignDailyTask = async (p) => { try { const workflow = buildRhAssignedTask({ person: p, module: (p.modules || [])[0] || 'taches', title: `Action terrain du jour · ${p.nom || p.id}`, dueDate: today(), priority: 'moyenne', notes: 'Tâche assignée depuis RH & Équipe.' }); await onCreateTask?.(workflow.task); await onCreateBusinessEvent?.(workflow.event); await Promise.allSettled([onRefreshTasks?.(), onRefreshBusinessEvents?.()]); toast.success('Tâche assignée'); } catch (error) { toast.error(error.message || 'Assignation impossible'); } };
  const changeRole = (role) => setPerson((prev) => ({ ...prev, role, equipe_id: prev.equipe_id || teamFor(role), modules: prev.modules?.length ? prev.modules : modulesFor(role) }));

  return <div className="space-y-6 rh-mobile-structured">
    <style>{`@media (max-width: 640px){.rh-mobile-structured .rounded-2xl{border-radius:18px}.rh-mobile-structured table{font-size:12px}.rh-mobile-structured th,.rh-mobile-structured td{padding-left:10px!important;padding-right:10px!important}.rh-mobile-structured .text-2xl{font-size:1.35rem}.rh-mobile-structured .grid{gap:.75rem}.rh-mobile-structured .overflow-x-auto{max-width:100vw}}`}</style>

    <ModuleSection icon={Users} title="Synthèse RH" subtitle="Personnes, équipes actives, masse salariale et actions rapides.">
      <SectionHeader title="RH & Équipe" sub="Personnes, équipes, rémunérations et responsabilités" actions={<><Btn variant="outline" small onClick={onRefresh}>Actualiser</Btn><Btn icon={Plus} variant="outline" small onClick={() => setPerson(newPerson())}>Ajouter RH</Btn><Btn icon={Plus} small onClick={() => setTeam(newTeam())}>Nouvelle équipe</Btn></>} />
      <div className="grid grid-cols-2 xl:grid-cols-4 gap-4"><KpiCard icon={Users} label="Personnes" value={people.length} /><KpiCard icon={UserCheck} label="Actifs" value={active.length} /><KpiCard icon={Banknote} label="Masse brute" value={fmtCurrency(totals.brut)} /><KpiCard icon={Banknote} label="Net à payer" value={fmtCurrency(totals.net)} sub={`Avances ${fmtCurrency(totals.avance)}`} /></div>
    </ModuleSection>

    <ModuleSection icon={Banknote} title="Coûts et rémunérations" subtitle="Centre de coûts RH, affectation par équipe/module et impact Finance.">
      <RHCostCenterPanel people={people} teams={teams} />
    </ModuleSection>

    <ModuleSection icon={UserCheck} title="Répertoire RH" subtitle="Fiches personnes, rôles, modules accessibles, présences, tâches et paiements.">
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-4"><div className="xl:col-span-2 bg-white border border-[#d6c3a0] rounded-2xl p-5"><h3 className="font-black text-[#2f2415] mb-3">Personnes</h3><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{people.map((p) => { const m = payroll(p); return <div key={p.id} className="rounded-xl border border-[#eadcc2] bg-[#fffdf8] p-4"><div className="flex justify-between gap-3"><div><p className="font-black text-[#2f2415]">{p.nom || p.id}</p><p className="text-xs text-[#8a7456]">{p.role} · {p.fonction}</p><p className="text-xs text-[#8a7456] mt-1">{teamName(teams, p.equipe_id)} · {p.statut}</p></div><div className="flex gap-2"><button onClick={() => setPerson(p)} title="Modifier"><Edit size={16} /></button><button onClick={() => removePerson(p)} title="Supprimer" className="text-red-600"><Trash2 size={16} /></button></div></div><p className="text-xs text-[#8a7456] mt-2">Modules : {(p.modules || []).map(moduleName).join(', ')}</p>{p.last_absence_date ? <p className="mt-2 rounded-lg border border-amber-200 bg-amber-50 px-2 py-1 text-xs text-amber-800">Dernière absence : {p.last_absence_date}</p> : null}<div className="mt-3 rounded-lg bg-white border border-[#eadcc2] p-2 text-xs"><b>Net à payer : {fmtCurrency(m.net)}</b><br />Salaire {fmtCurrency(m.salaire)} · Prime {fmtCurrency(m.prime)} · Avance {fmtCurrency(m.avance)}</div><div className="mt-3 flex flex-wrap gap-2"><button className="rounded-lg bg-emerald-600 px-3 py-1 text-xs font-bold text-white" onClick={() => pay(p)}>Payer</button><button className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800" onClick={() => markAbsence(p)}>Absence</button><button className="rounded-lg border border-[#d6c3a0] bg-white px-3 py-1 text-xs font-bold text-[#2f2415]" onClick={() => assignDailyTask(p)}>Assigner tâche</button></div></div>; })}</div></div>
        {person ? <div className="bg-white border border-[#d6c3a0] rounded-2xl p-5 space-y-3"><h3 className="font-black text-[#2f2415]">{people.some((p) => p.id === person.id) ? 'Modifier RH' : 'Ajouter RH'}</h3><Field label="Nom" value={person.nom} onChange={(v) => setP('nom', v)} /><label className="block text-sm"><span className="text-[#8a7456]">Rôle</span><select className="mt-1 w-full rounded-lg border border-[#d6c3a0] bg-[#fffdf8] px-3 py-2" value={person.role} onChange={(e) => changeRole(e.target.value)}>{RH_ROLES.map((r) => <option key={r} value={r}>{r}</option>)}</select></label><Field label="Fonction" value={person.fonction} onChange={(v) => setP('fonction', v)} /><label className="block text-sm"><span className="text-[#8a7456]">Équipe</span><select className="mt-1 w-full rounded-lg border border-[#d6c3a0] bg-[#fffdf8] px-3 py-2" value={person.equipe_id} onChange={(e) => setP('equipe_id', e.target.value)}>{teams.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><Field label="Téléphone" value={person.phone} onChange={(v) => setP('phone', v)} /><Field label="WhatsApp" value={person.whatsapp} onChange={(v) => setP('whatsapp', v)} /><Field label="Salaire mensuel" type="number" value={person.salaire_mensuel} onChange={(v) => setP('salaire_mensuel', v)} /><Field label="Prime mensuelle" type="number" value={person.prime_mensuelle} onChange={(v) => setP('prime_mensuelle', v)} /><Field label="Avance du mois" type="number" value={person.avance_mois} onChange={(v) => setP('avance_mois', v)} /><div className="rounded-xl bg-[#fffdf8] border border-[#eadcc2] p-3 text-sm">Net calculé : <b>{fmtCurrency(payroll(person).net)}</b></div><ModulePicker value={person.modules || []} onToggle={togglePersonModule} /><div className="flex gap-2"><Btn icon={Save} onClick={savePerson}>Enregistrer</Btn><Btn variant="outline" onClick={() => setPerson(null)}>Fermer</Btn></div></div> : <div className="bg-white border border-[#d6c3a0] rounded-2xl p-5 text-sm text-[#8a7456]">Sélectionne une RH à modifier ou clique sur Ajouter RH.</div>}</div>
    </ModuleSection>

    <ModuleSection icon={Users} title="Équipes et responsabilités" subtitle="Groupes opérationnels, modules couverts et organisation terrain.">
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-4"><div className="xl:col-span-2 bg-white border border-[#d6c3a0] rounded-2xl p-5"><h3 className="font-black text-[#2f2415] mb-3">Équipes</h3><div className="grid grid-cols-1 md:grid-cols-3 gap-3">{teams.map((t) => <div key={t.id} className="rounded-xl border border-[#eadcc2] bg-[#fffdf8] p-3"><div className="flex justify-between gap-2"><div><p className="font-bold text-[#2f2415]">{t.name}</p><p className="text-xs text-[#8a7456]">{t.type} · {people.filter((p) => p.equipe_id === t.id).length} personne(s)</p></div><div className="flex gap-1"><button onClick={() => setTeam(t)} title="Modifier équipe"><Edit size={15} /></button><button onClick={() => removeTeam(t)} title="Supprimer équipe" className="text-red-600"><Trash2 size={15} /></button></div></div><p className="text-xs text-[#8a7456] mt-2">{(t.modules || []).map(moduleName).join(', ')}</p></div>)}</div></div>{team ? <div className="bg-white border border-[#d6c3a0] rounded-2xl p-5 space-y-3"><h3 className="font-black text-[#2f2415]">{teams.some((t) => t.id === team.id) ? 'Modifier équipe' : 'Nouvelle équipe'}</h3><Field label="Nom équipe" value={team.name} onChange={(v) => setT('name', v)} /><label className="block text-sm"><span className="text-[#8a7456]">Type</span><select className="mt-1 w-full rounded-lg border border-[#d6c3a0] bg-[#fffdf8] px-3 py-2" value={team.type} onChange={(e) => setT('type', e.target.value)}><option value="operationnelle">Opérationnelle</option><option value="commerciale">Commerciale</option><option value="technique">Technique</option><option value="administrative">Administrative</option></select></label><ModulePicker value={team.modules || []} onToggle={toggleTeamModule} /><div className="flex gap-2"><Btn icon={Save} onClick={saveTeam}>Enregistrer</Btn><Btn variant="outline" onClick={() => setTeam(null)}>Fermer</Btn></div></div> : <div className="bg-white border border-[#d6c3a0] rounded-2xl p-5 text-sm text-[#8a7456]">Sélectionne une équipe à modifier ou clique sur Nouvelle équipe.</div>}</div>
    </ModuleSection>
  </div>;
}
