import { Activity, AlertTriangle, Camera, Droplets, Eye, Gauge, Plus, Radio, RefreshCw, Thermometer, Trash2, Wind } from 'lucide-react';
import { useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import ActionIconButton from '../components/ActionIconButton';
import Btn from '../components/Btn';
import CollapsibleAdvancedSection from '../components/CollapsibleAdvancedSection.jsx';
import DataTable from '../components/DataTable';
import KpiCard from '../components/KpiCard';
import ModuleTimeline from '../components/ModuleTimeline';
import SectionHeader from '../components/SectionHeader';
import CreateModal from '../modals/CreateModal';
import DeleteModal from '../modals/DeleteModal';
import DetailsModal from '../modals/DetailsModal';
import EditModal from '../modals/EditModal';
import { MODULE_FORM_FIELDS } from '../utils/constants';
import { generateSequentialId } from '../utils/ids';
import SmartFarmSafetyBridge from './SmartFarmSafetyBridge.jsx';

const zoneExamples = ['poulailler', 'parc bovins', 'magasin stock', 'parcelle tomates', 'entrée principale'];

export default function SmartFarm({ meteo, online, sensors = [], cameras = [], tasks = [], sensorLoading, cameraLoading, onCreateSensor, onUpdateSensor, onDeleteSensor, onRefreshSensors, onCreateCamera, onUpdateCamera, onDeleteCamera, onRefreshCameras, onCreateTask, onRefreshTasks, onCreateAlert, onRefreshAlertes, onCreateBusinessEvent, onRefreshBusinessEvents }) {
  const [checking, setChecking] = useState(false);
  const [selectedSensor, setSelectedSensor] = useState(null);
  const [selectedCamera, setSelectedCamera] = useState(null);
  const [modal, setModal] = useState(null);
  const [saving, setSaving] = useState(false);
  const [showAdvanced, setShowAdvanced] = useState(false);
  const simulatedReadings = useMemo(() => [{ id: 'METEO-TEMP', zone: meteo?.locationLabel || 'Météo live', metric: 'Température', value: `${meteo?.temp ?? '-'} C`, status: meteo?.riskLevel === 'stable' ? 'stable' : 'surveillance' }, { id: 'METEO-HUM', zone: meteo?.locationLabel || 'Météo live', metric: 'Humidité', value: `${meteo?.humidite ?? '-'}%`, status: Number(meteo?.humidite || 0) >= 88 ? 'surveillance' : 'stable' }, { id: 'METEO-WIND', zone: 'Vent terrain', metric: 'Vent', value: meteo?.windLabel || '0 km/h', status: Number(meteo?.windSpeed || 0) >= 30 ? 'surveillance' : 'stable' }, { id: 'METEO-RAIN', zone: 'Pluie', metric: 'Pluie / probabilité', value: `${meteo?.pluie ? 'Pluie' : 'Sec'} - ${meteo?.precipitationProbability || 0}%`, status: meteo?.pluie ? 'surveillance' : 'stable' }], [meteo]);
  const configuredSensors = sensors.length ? sensors : [{ id: 'SIM-SENS-01', name: 'Simulation météo', type: 'temperature', zone: 'Station ferme', location: meteo?.locationLabel || 'Sénégal', status: 'simulation', battery_level: 100 }];
  const configuredCameras = cameras.length ? cameras : [{ id: 'SIM-CAM-01', name: 'Caméra simulation entrée', zone: 'entrée principale', type: 'simulation', status: 'simulation' }];
  const timelineRows = [...configuredSensors.map((s) => ({ ...s, title: s.name || s.id, description: `${s.type || 'capteur'} · ${s.zone || s.location || 'zone non renseignée'}`, created_at: s.created_at || s.updated_at || new Date().toISOString() })), ...configuredCameras.map((c) => ({ ...c, title: c.name || c.id, description: `${c.type || 'caméra'} · ${c.zone || 'zone non renseignée'}`, created_at: c.created_at || c.updated_at || new Date().toISOString() })), ...simulatedReadings.map((r) => ({ ...r, title: `${r.metric} — ${r.zone}`, description: r.value, created_at: new Date().toISOString() }))];
  const verifySensors = async () => { setChecking(true); try { await Promise.allSettled([onRefreshSensors?.(), onRefreshCameras?.()]); toast.success(online ? 'Smart Farm synchronisé' : 'Mode hors ligne: données locales conservées'); } finally { setChecking(false); } };
  const saveSensor = async (payload) => { try { setSaving(true); if (selectedSensor) await onUpdateSensor?.(selectedSensor.id, payload); else await onCreateSensor?.(payload); toast.success(selectedSensor ? 'Capteur modifié' : 'Capteur ajouté'); setModal(null); } catch (error) { toast.error(error.message || 'Erreur capteur'); } finally { setSaving(false); } };
  const saveCamera = async (payload) => { try { setSaving(true); if (selectedCamera) await onUpdateCamera?.(selectedCamera.id, payload); else await onCreateCamera?.(payload); toast.success(selectedCamera ? 'Caméra modifiée' : 'Caméra ajoutée'); setModal(null); } catch (error) { toast.error(error.message || 'Erreur caméra'); } finally { setSaving(false); } };
  const deleteSensor = async () => { if (!selectedSensor) return; try { setSaving(true); await onDeleteSensor?.(selectedSensor.id); toast.success('Capteur supprimé'); setModal(null); } catch (error) { toast.error(error.message || 'Erreur suppression capteur'); } finally { setSaving(false); } };
  const deleteCamera = async () => { if (!selectedCamera) return; try { setSaving(true); await onDeleteCamera?.(selectedCamera.id); toast.success('Caméra supprimée'); setModal(null); } catch (error) { toast.error(error.message || 'Erreur suppression caméra'); } finally { setSaving(false); } };
  return <div className="space-y-6"><SectionHeader title="Smart Farm" sub="Capteurs, caméras, météo et actions terrain" actions={<><Btn icon={RefreshCw} variant="outline" small onClick={verifySensors} disabled={checking}>{checking ? 'Vérification...' : 'Synchroniser'}</Btn><Btn icon={Plus} small onClick={() => { setSelectedSensor(null); setModal('createSensor'); }}>Ajouter capteur</Btn><Btn icon={Camera} variant="outline" small onClick={() => { setSelectedCamera(null); setModal('createCamera'); }}>Ajouter caméra</Btn></>} />
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><KpiCard icon={Thermometer} label="Température" value={`${meteo?.temp ?? '-'} C`} sub={`Ressenti ${meteo?.apparentTemp ?? '-'} C`} color="bg-amber-500/20 text-amber-400" /><KpiCard icon={Droplets} label="Humidité" value={`${meteo?.humidite ?? '-'}%`} sub={meteo?.condition || 'Météo'} color="bg-sky-500/20 text-sky-400" /><KpiCard icon={Wind} label="Vent" value={`${meteo?.windSpeed ?? 0} km/h`} sub={meteo?.windLabel || 'Direction inconnue'} color="bg-emerald-500/20 text-emerald-400" /><KpiCard icon={Camera} label="Caméras" value={`${cameras.length}/${Math.max(cameras.length, 4)}`} sub={cameras.length ? 'configurées' : 'simulation'} color="bg-purple-500/20 text-purple-400" /></div>
    <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
      <DataTable title="Capteurs configurés" rows={configuredSensors} columns={[{ key: 'name', label: 'Capteur', sortable: true, render: (row) => <span className="font-semibold text-[#2f2415]">{row.name}</span> }, { key: 'type', label: 'Type', sortable: true }, { key: 'zone', label: 'Zone', sortable: true }, { key: 'status', label: 'Statut', sortable: true }, { key: 'battery_level', label: 'Batterie', render: (row) => `${row.battery_level ?? '-'}%` }, { key: 'actions', label: 'Actions', render: (row) => row.id?.startsWith('SIM-') ? <span className="text-xs text-[#8a7456]">simulation</span> : <div className="flex gap-1"><ActionIconButton icon={Eye} title="Voir" color="sky" onClick={() => { setSelectedSensor(row); setModal('detailsSensor'); }} /><ActionIconButton icon={Gauge} title="Modifier" color="amber" onClick={() => { setSelectedSensor(row); setModal('editSensor'); }} /><ActionIconButton icon={Trash2} title="Supprimer" color="red" onClick={() => { setSelectedSensor(row); setModal('deleteSensor'); }} /></div> }]} loading={sensorLoading} initialSortKey="name" />
      <DataTable title="Caméras configurées" rows={configuredCameras} columns={[{ key: 'name', label: 'Caméra', sortable: true, render: (row) => <span className="font-semibold text-[#2f2415]">{row.name}</span> }, { key: 'zone', label: 'Zone', sortable: true }, { key: 'type', label: 'Type', sortable: true }, { key: 'status', label: 'Statut', sortable: true }, { key: 'stream_url', label: 'Flux', render: (row) => row.stream_url || 'non connecté' }, { key: 'actions', label: 'Actions', render: (row) => row.id?.startsWith('SIM-') ? <span className="text-xs text-[#8a7456]">simulation</span> : <div className="flex gap-1"><ActionIconButton icon={Eye} title="Voir" color="sky" onClick={() => { setSelectedCamera(row); setModal('detailsCamera'); }} /><ActionIconButton icon={Camera} title="Modifier" color="amber" onClick={() => { setSelectedCamera(row); setModal('editCamera'); }} /><ActionIconButton icon={Trash2} title="Supprimer" color="red" onClick={() => { setSelectedCamera(row); setModal('deleteCamera'); }} /></div> }]} loading={cameraLoading} initialSortKey="name" />
    </div>
    <CollapsibleAdvancedSection title="Smart Farm : sécurité, mesures, recommandations et timeline" description="La météo et les équipements restent visibles. Les analyses terrain détaillées sont rangées ici." open={showAdvanced} onToggle={() => setShowAdvanced((value) => !value)}>
      <SmartFarmSafetyBridge meteo={meteo} sensors={sensors} cameras={cameras} tasks={tasks} onCreateTask={onCreateTask} onRefreshTasks={onRefreshTasks} onCreateAlert={onCreateAlert} onRefreshAlertes={onRefreshAlertes} onCreateBusinessEvent={onCreateBusinessEvent} onRefreshBusinessEvents={onRefreshBusinessEvents} />
      <ModuleTimeline title="Timeline Smart Farm" subtitle="Dernières mesures, capteurs, caméras et signaux terrain." rows={timelineRows} onRefresh={verifySensors} navigateLabel="Synchroniser" />
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-4"><div className="bg-[#ffffff] border border-[#d6c3a0] rounded-2xl p-5"><p className="font-semibold text-[#2f2415] mb-4 flex items-center gap-2"><Radio size={16} className="text-emerald-400" />Mesures terrain</p><div className="space-y-3">{simulatedReadings.map((reading) => <div key={reading.id} className="flex items-center gap-3 bg-[#fffdf8] border border-[#d6c3a0] rounded-xl p-3"><Gauge size={16} className={reading.status === 'stable' ? 'text-emerald-400' : 'text-amber-400'} /><div className="flex-1"><p className="text-sm font-semibold text-[#2f2415]">{reading.zone}</p><p className="text-xs text-[#8a7456]">{reading.metric}</p></div><span className="text-sm font-bold text-[#2f2415]">{reading.value}</span></div>)}</div></div><div className="bg-[#ffffff] border border-[#d6c3a0] rounded-2xl p-5"><p className="font-semibold text-[#2f2415] mb-4 flex items-center gap-2"><Activity size={16} className="text-sky-400" />Zones suivies</p><div className="flex flex-wrap gap-2">{zoneExamples.map((zone) => <span key={zone} className="rounded-full border border-[#eadcc2] bg-[#fffdf8] px-3 py-1 text-xs text-[#7d6a4a]">{zone}</span>)}</div><div className="mt-4 rounded-xl bg-emerald-50 border border-emerald-200 p-3 text-sm text-emerald-700">Les alertes météo, capteurs et caméras peuvent créer une tâche terrain.</div></div><div className="bg-[#ffffff] border border-[#d6c3a0] rounded-2xl p-5"><p className="font-semibold text-[#2f2415] mb-4 flex items-center gap-2"><AlertTriangle size={16} className="text-amber-400" />Recommandations</p><div className="space-y-2">{(meteo?.recommendations || ['Configurer un capteur pour remplacer progressivement la simulation.']).slice(0, 5).map((rec) => <div key={rec} className="rounded-xl bg-amber-500/10 border border-amber-500/20 p-3 text-sm text-[#7d6a4a]">{rec}</div>)}</div></div></div>
    </CollapsibleAdvancedSection>
    <DetailsModal open={modal === 'detailsSensor'} onClose={() => setModal(null)} data={selectedSensor} title="Fiche capteur" /><CreateModal open={modal === 'createSensor'} onClose={() => setModal(null)} onSubmit={saveSensor} fields={MODULE_FORM_FIELDS.sensor_devices} initialValues={{ id: generateSequentialId('sensor_devices', sensors), status: 'simulation', battery_level: 100 }} autoId={() => generateSequentialId('sensor_devices', sensors)} loading={saving} title="Ajouter capteur" submitLabel="Ajouter" /><EditModal open={modal === 'editSensor'} onClose={() => setModal(null)} onSubmit={saveSensor} fields={MODULE_FORM_FIELDS.sensor_devices} initialValues={selectedSensor || {}} loading={saving} title="Modifier capteur" submitLabel="Enregistrer" /><DeleteModal open={modal === 'deleteSensor'} onClose={() => setModal(null)} onConfirm={deleteSensor} itemLabel={selectedSensor?.name || ''} loading={saving} />
    <DetailsModal open={modal === 'detailsCamera'} onClose={() => setModal(null)} data={selectedCamera} title="Fiche caméra" /><CreateModal open={modal === 'createCamera'} onClose={() => setModal(null)} onSubmit={saveCamera} fields={MODULE_FORM_FIELDS.camera_devices} initialValues={{ id: generateSequentialId('camera_devices', cameras), type: 'simulation', status: 'simulation' }} autoId={() => generateSequentialId('camera_devices', cameras)} loading={saving} title="Ajouter caméra" submitLabel="Ajouter" /><EditModal open={modal === 'editCamera'} onClose={() => setModal(null)} onSubmit={saveCamera} fields={MODULE_FORM_FIELDS.camera_devices} initialValues={selectedCamera || {}} loading={saving} title="Modifier caméra" submitLabel="Enregistrer" /><DeleteModal open={modal === 'deleteCamera'} onClose={() => setModal(null)} onConfirm={deleteCamera} itemLabel={selectedCamera?.name || ''} loading={saving} />
  </div>;
}
