import { Camera, Droplets, Eye, MapPin, Radio, ShieldCheck, ShoppingBag, Thermometer, Wifi } from 'lucide-react';

const NEEDS = [
  { key: 'temperature', icon: Thermometer, title: 'Température poulailler / magasin', equipment: 'Capteur température + humidité type Zigbee/Wi‑Fi, ou sonde connectée avec historique.', placement: 'À hauteur des animaux, loin du soleil direct et de l’eau.', priority: 'Très prioritaire', budget: '10 000 à 35 000 FCFA / zone', alert: 'Alerte si chaleur forte, humidité élevée ou risque stress.' },
  { key: 'humidity', icon: Droplets, title: 'Humidité et litière', equipment: 'Capteur humidité, idéalement avec historique et seuils configurables.', placement: 'Poulailler, magasin aliment, zone de stockage.', priority: 'Très prioritaire', budget: '10 000 à 30 000 FCFA', alert: 'Alerte si humidité excessive ou risque moisissure.' },
  { key: 'presence', icon: Eye, title: 'Présence humaine / intrusion', equipment: 'Détecteur mouvement PIR, caméra avec détection, ou capteur ouverture porte.', placement: 'Entrée principale, magasin stock, poulailler, zone bovins.', priority: 'Prioritaire', budget: '15 000 à 60 000 FCFA', alert: 'Alerte nuit ou présence hors horaires.' },
  { key: 'camera_entry', icon: Camera, title: 'Caméra entrée ferme', equipment: 'Caméra IP Wi‑Fi/4G, modèle extérieur, vision nuit, stockage carte SD/cloud.', placement: 'Entrée, portail, zone livraison.', priority: 'Prioritaire', budget: '25 000 à 120 000 FCFA', alert: 'Alerte mouvement, preuve vidéo et contrôle accès.' },
  { key: 'camera_poultry', icon: Camera, title: 'Caméra poulailler', equipment: 'Caméra intérieure protégée poussière/humidité, vision nuit, angle large.', placement: 'Angle haut, vue mangeoires/abreuvoirs, sans gêner les animaux.', priority: 'Important', budget: '25 000 à 90 000 FCFA', alert: 'Surveillance comportement, accès, panne éclairage/eau.' },
  { key: 'water', icon: Droplets, title: 'Niveau eau', equipment: 'Capteur niveau eau, flotteur connecté ou sonde de niveau selon cuve.', placement: 'Cuve, abreuvoirs principaux, réserve eau.', priority: 'Prioritaire', budget: '10 000 à 45 000 FCFA', alert: 'Alerte manque d’eau ou niveau anormal.' },
  { key: 'network', icon: Wifi, title: 'Connexion ferme', equipment: 'Routeur 4G, répéteur Wi‑Fi, batterie/solaire si coupures fréquentes.', placement: 'Zone centrale, protégée poussière/chaleur.', priority: 'Base technique', budget: '30 000 à 150 000 FCFA', alert: 'Alerte si capteurs/caméras hors ligne.' },
];
const BUYING_GUIDE = [
  { place: 'Boutiques informatique / vidéosurveillance à Dakar', what: 'Caméras IP, routeurs 4G, switch PoE, câbles, cartes mémoire.', advice: 'Demander une facture, garantie, disponibilité pièces et installation.' },
  { place: 'Opérateurs télécoms / revendeurs agréés', what: 'Routeurs 4G, forfait data, antennes ou solutions internet ferme.', advice: 'Tester la couverture réseau sur le site avant achat.' },
  { place: 'Marketplaces locales et généralistes', what: 'Caméras Wi‑Fi, capteurs simples, accessoires, cartes SD.', advice: 'Comparer avis, garantie, alimentation électrique et compatibilité application.' },
  { place: 'Installateurs sécurité / solaire', what: 'Caméras extérieures, solaire, batteries, installation propre.', advice: 'Privilégier un installateur capable de revenir en maintenance.' },
];
const MODEL_GUIDE = [
  'Caméra IP extérieure Wi‑Fi/4G, vision nuit, détection mouvement, carte SD.',
  'Caméra intérieure angle large pour poulailler, résistante poussière/humidité.',
  'Capteur température/humidité avec application mobile et export ou API si possible.',
  'Détecteur mouvement PIR ou capteur ouverture porte pour magasin/entrée.',
  'Routeur 4G stable avec antenne externe si le réseau est faible.',
];

function Card({ item }) {
  const Icon = item.icon;
  return <article className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4 space-y-2"><div className="flex items-start gap-3"><span className="rounded-xl border border-[#eadcc2] bg-white p-2 text-[#9a6b12]"><Icon size={18} /></span><div><p className="font-black text-[#2f2415]">{item.title}</p><p className="text-xs font-black text-emerald-700">{item.priority}</p></div></div><p className="text-sm text-[#7d6a4a]"><b>Matériel :</b> {item.equipment}</p><p className="text-sm text-[#7d6a4a]"><b>Installation :</b> {item.placement}</p><p className="text-sm text-[#7d6a4a]"><b>Budget indicatif :</b> {item.budget}</p><p className="rounded-xl border border-emerald-200 bg-emerald-50 p-2 text-xs text-emerald-800"><ShieldCheck size={13} className="inline" /> {item.alert}</p></article>;
}

export default function SmartFarmEquipmentAdvisor({ sensors = [], cameras = [], onCreateSensor, onCreateCamera }) {
  const missingSensors = !sensors?.length;
  const missingCameras = !cameras?.length;
  const priority = NEEDS.filter((item) => missingSensors || missingCameras || ['temperature', 'humidity', 'presence', 'camera_entry', 'water'].includes(item.key)).slice(0, 6);
  return <section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm space-y-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs uppercase tracking-widest text-[#8a7456] font-black flex items-center gap-2"><Radio size={15} /> Assistant matériel Smart Farm</p><h3 className="text-xl font-black text-[#2f2415] mt-1">Quoi acheter et où l’installer</h3><p className="text-sm text-[#8a7456] mt-1">Priorité : température/humidité, présence, caméras entrée/poulailler, eau et connexion. Les prix sont indicatifs et doivent être confirmés par devis au Sénégal.</p></div><div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-3 text-sm text-[#7d6a4a]">{sensors?.length || 0} capteur(s) · {cameras?.length || 0} caméra(s)</div></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3">{priority.map((item) => <Card key={item.key} item={item} />)}</div><div className="grid grid-cols-1 lg:grid-cols-2 gap-3"><div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="font-black text-[#2f2415] flex items-center gap-2"><ShoppingBag size={16} /> Où chercher au Sénégal</p><div className="mt-3 space-y-2">{BUYING_GUIDE.map((row) => <div key={row.place} className="rounded-xl bg-white border border-[#eadcc2] p-3 text-sm"><b className="text-[#2f2415]"><MapPin size={13} className="inline" /> {row.place}</b><p className="text-[#7d6a4a] mt-1">{row.what}</p><p className="text-xs text-[#8a7456] mt-1">{row.advice}</p></div>)}</div></div><div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-4"><p className="font-black text-[#2f2415]">Modèles à demander</p><ul className="mt-3 space-y-2 text-sm text-[#7d6a4a]">{MODEL_GUIDE.map((item) => <li key={item} className="rounded-xl bg-white border border-[#eadcc2] p-3">{item}</li>)}</ul></div></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><b>Conseil terrain :</b> commencer simple : 1 capteur température/humidité poulailler, 1 capteur magasin stock, 1 caméra entrée, 1 caméra poulailler, puis ajouter eau et détection mouvement nuit. Demander toujours facture, garantie, alimentation électrique, compatibilité smartphone et possibilité d’export/API.</div><div className="flex flex-wrap justify-end gap-2"><button type="button" onClick={onCreateSensor} className="rounded-xl border border-[#eadcc2] bg-[#fffdf8] px-3 py-2 text-sm font-bold text-[#2f2415]"><Thermometer size={14} className="inline" /> Ajouter capteur</button><button type="button" onClick={onCreateCamera} className="rounded-xl border border-[#eadcc2] bg-[#fffdf8] px-3 py-2 text-sm font-bold text-[#2f2415]"><Camera size={14} className="inline" /> Ajouter caméra</button></div></section>;
}
