/**
 * Adaptateur historique. La source de vérité reste `src/styles/tokens.css`.
 * Les composants Hey Horizon consomment uniquement ses variables CSS.
 */
export const HORIZON_DESIGN = Object.freeze({
  pageBg: 'var(--hf-mist)',
  surface: 'var(--hf-white)',
  surfaceMuted: 'var(--hf-neutral-bg)',
  border: 'var(--hf-line)',
  borderSoft: 'var(--hf-line)',
  text: 'var(--hf-ink)',
  textMuted: 'var(--hf-slate)',
  textSoft: 'var(--hf-slate)',
  accent: 'var(--hf-earth)',
  accentDeep: 'var(--hf-leaf)',
  accentGold: 'var(--hf-horizon)',
  accentSoft: 'var(--hf-positive-bg)',
  accentGlow: 'color-mix(in srgb, var(--hf-leaf) 12%, transparent)',
  userBubble: 'var(--hf-earth)',
  userBubbleText: 'var(--hf-white)',
  assistantBubble: 'var(--hf-white)',
  assistantBubbleText: 'var(--hf-ink)',
  inputBg: 'var(--hf-white)',
  inputPlaceholder: 'var(--hf-slate)',
  shadowSoft: 'var(--hf-shadow-card)',
  shadowBubble: 'var(--hf-shadow-card)',
  radiusShell: 'var(--hf-radius-card)',
  radiusBubble: 'var(--hf-radius-card)',
  radiusInput: 'var(--hf-radius-control)',
  fontFamily: 'var(--hf-font-sans)',
});

export const HORIZON = Object.freeze({
  bg: HORIZON_DESIGN.pageBg,
  surface: HORIZON_DESIGN.surface,
  canvas: HORIZON_DESIGN.pageBg,
  primary: HORIZON_DESIGN.accent,
  primaryDark: HORIZON_DESIGN.accentDeep,
  header: HORIZON_DESIGN.accent,
  headerText: HORIZON_DESIGN.userBubbleText,
  primaryHover: HORIZON_DESIGN.accentDeep,
  secondary: HORIZON_DESIGN.textMuted,
  text: HORIZON_DESIGN.text,
  textMuted: HORIZON_DESIGN.textMuted,
  textSoft: HORIZON_DESIGN.textSoft,
  border: HORIZON_DESIGN.border,
  borderFocus: HORIZON_DESIGN.accentDeep,
  shadowSm: HORIZON_DESIGN.shadowBubble,
  shadow: HORIZON_DESIGN.shadowSoft,
  shadowLg: 'var(--hf-shadow-float)',
  shadowInput: HORIZON_DESIGN.shadowSoft,
  userBubble: HORIZON_DESIGN.userBubble,
  userBubbleText: HORIZON_DESIGN.userBubbleText,
  assistantBubble: HORIZON_DESIGN.assistantBubble,
  sendButton: HORIZON_DESIGN.accent,
  wallpaper: HORIZON_DESIGN.pageBg,
  island: HORIZON_DESIGN.text,
  chassis: HORIZON_DESIGN.text,
  radiusBubble: HORIZON_DESIGN.radiusBubble,
  radiusBubbleTail: HORIZON_DESIGN.radiusInput,
  radiusInput: HORIZON_DESIGN.radiusInput,
  maxChatWidth: '100%',
});

export default HORIZON;
