/**
 * Horizon Chat Native V7 — design tokens (premium, très clair, vert profond).
 */
export const HORIZON_DESIGN = Object.freeze({
  pageBg: '#F4F8F6',
  surface: '#FFFFFF',
  surfaceMuted: '#EEF5F1',
  border: '#D8E8DF',
  borderSoft: '#E8F0EC',
  text: '#0F2419',
  textMuted: '#4A6B5C',
  textSoft: '#6B8578',
  accent: '#0B5D3B',
  accentDeep: '#084A2F',
  accentSoft: '#E6F4EC',
  accentGlow: 'rgba(11, 93, 59, 0.12)',
  userBubble: '#0B5D3B',
  userBubbleText: '#FFFFFF',
  assistantBubble: '#FFFFFF',
  assistantBubbleText: '#0F2419',
  inputBg: '#FFFFFF',
  inputPlaceholder: '#7A9488',
  shadowSoft: '0 2px 12px rgba(11, 93, 59, 0.06)',
  shadowBubble: '0 1px 4px rgba(15, 36, 25, 0.06)',
  radiusShell: 44,
  radiusBubble: 18,
  radiusInput: 24,
  fontFamily: "'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif",
});

/** Alias rétrocompat pour composants existants (brouillons, panneaux). */
export const HORIZON = Object.freeze({
  bg: HORIZON_DESIGN.pageBg,
  surface: HORIZON_DESIGN.surface,
  canvas: HORIZON_DESIGN.pageBg,
  primary: HORIZON_DESIGN.accent,
  primaryDark: HORIZON_DESIGN.accentDeep,
  header: HORIZON_DESIGN.accent,
  headerText: '#FFFFFF',
  primaryHover: '#0E7049',
  secondary: HORIZON_DESIGN.textMuted,
  text: HORIZON_DESIGN.text,
  textMuted: HORIZON_DESIGN.textMuted,
  textSoft: HORIZON_DESIGN.textSoft,
  border: HORIZON_DESIGN.border,
  borderFocus: HORIZON_DESIGN.accent,
  shadowSm: HORIZON_DESIGN.shadowBubble,
  shadow: HORIZON_DESIGN.shadowSoft,
  shadowLg: '0 8px 24px rgba(11, 93, 59, 0.1)',
  shadowInput: HORIZON_DESIGN.shadowSoft,
  userBubble: HORIZON_DESIGN.userBubble,
  userBubbleText: HORIZON_DESIGN.userBubbleText,
  assistantBubble: HORIZON_DESIGN.assistantBubble,
  sendButton: HORIZON_DESIGN.accent,
  wallpaper: HORIZON_DESIGN.pageBg,
  island: '#0F2419',
  chassis: '#101010',
  radiusBubble: '18px',
  radiusBubbleTail: '6px',
  radiusInput: '24px',
  maxChatWidth: '100%',
});

export default HORIZON;
