const commonDisplay = ['Informations importantes en haut', 'Lecture facile', 'Actions visibles', 'Pas de doublons inutiles', 'Courbes et historiques en bas'];

export const auditManifest = [
  { module: 'Accueil', route: 'dashboard', priority: 'haute', purpose: 'Comprendre l’état de la ferme en moins d’une minute.', data: ['animaux','avicole','cultures','sales_orders','payments','finances','stock','alertes_center','taches'], display: ['KPI CA/charges/marge/alertes visibles', ...commonDisplay], checks: ['CA global cohérent', 'Marge cohérente', 'Alertes reliées aux modules', 'Actions rapides utiles'], forms: [], human: ['Ouvrir Accueil', 'Lire KPI sans scroller', 'Cliquer une alerte', 'Comparer avec Objectifs/Finances'], expected: 'Accueil doit donner une vision claire, fiable et actionnable.', lots: ['Lot 1 · Bloquants revenus','Lot 3 · Formulaires et UX'] },
  { module: 'Centre décisionnel', route: 'centre_ia', priority: 'haute', purpose: 'Prioriser les décisions sans noyer l’utilisateur.', data: ['animaux','avicole','cultures','stock','finances','sales_orders','business_events','alertes_center'], display: ['Top 3 priorités', 'Recommandations courtes', 'Détails repliables', ...commonDisplay], checks: ['Décisions basées sur données', 'Actions vers bon module', 'Pas de doublon avec Ventes/Objectifs'], forms: [], human: ['Lire priorités', 'Déplier recommandation', 'Cliquer action', 'Vérifier module cible'], expected: 'Le centre doit être un copilote décisionnel.', lots: ['Lot 4 · Automatisations terrain'] },
  { module: 'Objectifs', route: 'objectifs_croissance', priority: 'haute', purpose: 'Suivre objectifs, réalisé, marges et croissance.', data: ['sales_orders','payments','finances','animaux','avicole','cultures','business_plans'], display: ['Objectif/réalisé visible', 'Écarts expliqués', ...commonDisplay], checks: ['CA animaux si ventes animaux', 'CA avicole si ventes avicoles', 'CA cultures si ventes cultures', 'Marge avec coûts'], forms: [], human: ['Comparer Accueil/Objectifs/Ventes', 'Contrôler les zéros suspects', 'Vérifier activité par activité'], expected: 'Aucune activité vendue ne doit rester à réalisé zéro.', lots: ['Lot 1 · Bloquants revenus'] },
  { module: 'Animaux', route: 'animaux', priority: 'haute', purpose: 'Piloter bovins, ovins, caprins de l’entrée à la vente.', data: ['animaux','alimentation_logs','sante','sales_orders','payments','finances','sales_opportunities','business_events'], display: ['Liste par espèce', 'Fiche complète', 'Coûts détaillés', 'Marge visible', 'Pesées', 'Animal vendu verrouillé', ...commonDisplay], checks: ['Prix achat', 'Coût alimentation', 'Coût santé', 'Frais directs', 'Pesées 15 jours', 'Vente liée commande', 'CA objectifs alimenté'], forms: ['Ajouter animal', 'Modifier pesée', 'Clôturer vente'], human: ['Choisir espèce', 'Ouvrir fiche', 'Ajouter pesée', 'Vérifier coût/marge', 'Tester animal vendu', 'Vérifier opportunité/commande'], expected: 'Chaque animal doit expliquer son coût, sa croissance, sa marge et sa prochaine action.', lots: ['Lot 1 · Bloquants revenus','Lot 2 · Coûts et marges métier','Lot 4 · Automatisations terrain'] },
  { module: 'Avicole', route: 'avicole', priority: 'haute', purpose: 'Piloter lots chair/pondeuses, production, mortalité et ventes.', data: ['avicole','alimentation_logs','production_oeufs_logs','sante','sales_orders','payments','finances','sales_opportunities'], display: ['Lot lisible', 'Type chair/pondeuse', 'Âge/effectif/mortalité', 'Coûts', 'Production', ...commonDisplay], checks: ['Coût poussins', 'Coût aliment', 'Coût santé', 'Pertes', 'Vente partielle', 'CA réalisé'], forms: ['Ajouter lot', 'Ajouter production', 'Vendre partiellement'], human: ['Ouvrir lot chair', 'Ouvrir lot pondeuse', 'Vérifier coûts', 'Vérifier production', 'Créer vente partielle'], expected: 'Le lot doit expliquer sa performance et sa rentabilité.', lots: ['Lot 1 · Bloquants revenus','Lot 2 · Coûts et marges métier'] },
  { module: 'Cultures', route: 'cultures', priority: 'haute', purpose: 'Piloter parcelles, coûts, récoltes, pertes et ventes.', data: ['cultures','stock','sales_orders','payments','finances','sales_opportunities','business_events'], display: ['Culture/parcelle/stade', 'Coûts détaillés', 'Récolté/disponible/pertes', 'Action vente', ...commonDisplay], checks: ['Semences', 'Engrais', 'Eau', 'Main-d’œuvre', 'Traitements', 'Autres frais', 'Récolte disponible vendable', 'CA cultures'], forms: ['Ajouter culture', 'Modifier récolte', 'Créer opportunité récolte'], human: ['Ouvrir fiche culture', 'Vérifier coûts', 'Vérifier disponible', 'Créer opportunité', 'Comparer stock/ventes/objectifs'], expected: 'La culture doit devenir vendable sans double saisie dès qu’une récolte est disponible.', lots: ['Lot 1 · Bloquants revenus','Lot 2 · Coûts et marges métier'] },
  { module: 'Santé', route: 'sante', priority: 'haute', purpose: 'Gérer interventions sanitaires adaptatives et impact ferme.', data: ['sante','veterinaires','animaux','avicole','stock','finances','documents'], display: ['Type intervention', 'Urgence prédéfinie', 'Impact ferme structuré', 'Preuve upload', ...commonDisplay], checks: ['Vaccination: vaccin/dose/rappel/lot', 'Soin: symptômes/diagnostic/traitement/durée', 'Déparasitage: produit/dose/rappel', 'Visite véto: compte rendu', 'Coût vers finances'], forms: ['Vaccination', 'Soin curatif', 'Déparasitage', 'Visite vétérinaire', 'Biosécurité', 'Urgence'], human: ['Créer vaccination', 'Créer soin', 'Uploader preuve', 'Vérifier impact ferme', 'Vérifier finance/document'], expected: 'Le formulaire doit changer selon l’intervention et rester simple.', lots: ['Lot 3 · Formulaires et UX','Lot 2 · Coûts et marges métier'] },
  { module: 'Ventes', route: 'ventes', priority: 'haute', purpose: 'Gérer opportunité, commande, paiement, facture, document et stock.', data: ['sales_opportunities','sales_orders','payments','invoices','documents','finances','clients','stock'], display: ['Opportunités claires', 'Commande simple', 'Livré/récupéré', 'Paiement total/partiel', 'Facture émise/non émise', 'Reste à payer'], checks: ['Opportunité fermée après commande', 'Paiement crée finance', 'Facture crée document', 'Stock mis à jour', 'Objectifs mis à jour'], forms: ['Créer commande', 'Paiement', 'Facture'], human: ['Créer commande depuis opportunité', 'Payer partiellement', 'Émettre facture', 'Vérifier finance/document/objectifs'], expected: 'Une vente doit mettre à jour tout le workflow sans double saisie.', lots: ['Lot 1 · Bloquants revenus'] },
  { module: 'Finances', route: 'finances', priority: 'haute', purpose: 'Suivre recettes, charges, marges et trésorerie.', data: ['finances','sales_orders','payments','investissements','sante','stock','alimentation_logs'], display: ['Recettes/charges visibles', 'Marge lisible', 'Filtres utiles', 'Justificatifs'], checks: ['Paiements ventes', 'Charges santé', 'Alimentation', 'RH/investissements', 'Marge cohérente'], forms: ['Ajouter transaction'], human: ['Comparer Ventes/Finances', 'Vérifier charges métier', 'Contrôler marge'], expected: 'Les finances doivent expliquer réellement la rentabilité.', lots: ['Lot 1 · Bloquants revenus','Lot 2 · Coûts et marges métier'] },
  { module: 'Comptabilité', route: 'comptabilite', priority: 'haute', purpose: 'Lire CA, charges et résultat fiable.', data: ['finances','payments','sales_orders','sante','stock','investissements'], display: ['CA', 'Charges', 'Résultat', 'Pièces liées'], checks: ['Aucune charge métier manquante', 'Paiements/ventes alignés', 'Factures/documents liés'], forms: [], human: ['Comparer Finances', 'Vérifier charges à zéro', 'Contrôler résultat'], expected: 'La comptabilité ne doit pas masquer des coûts manquants.', lots: ['Lot 1 · Bloquants revenus','Lot 2 · Coûts et marges métier'] },
  { module: 'Investissements', route: 'investissements', priority: 'haute', purpose: 'Présenter le BP Horizon Farm et son ROI financeur.', data: ['business_plans','bp_investment_lines','bp_recurring_costs','bp_revenue_projections','bp_funding_sources','investissements'], display: ['Dépenses BP lisibles', 'Charges récurrentes', 'CA prévisionnel', 'ROI', 'Pas de lignes en tirets'], checks: ['BP complet', 'Projection CA', 'Charges liées modules', 'Simulation financeur'], forms: ['Créer/éditer BP', 'Ajouter ligne BP'], human: ['Ouvrir BP', 'Vérifier lignes', 'Comparer Objectifs/Accueil'], expected: 'Un financeur doit comprendre investissement, charges, CA prévisionnel et ROI.', lots: ['Lot 5 · Investissements et financeur'] },
  { module: 'Impact Business', route: 'impact_business', priority: 'moyenne', purpose: 'Mesurer impact ferme des événements.', data: ['business_events','sante','sales_orders','stock','finances','alertes_center'], display: ['Impact structuré', 'Niveau', 'Montant estimé', 'Module concerné', 'Action recommandée'], checks: ['Impact santé structuré', 'Impact vente/stock/production', 'Montants exploitables'], forms: ['Impact ferme'], human: ['Vérifier une intervention santé', 'Vérifier une perte/vente', 'Contrôler action'], expected: 'L’impact doit être mesurable, pas seulement un champ libre.', lots: ['Lot 3 · Formulaires et UX'] },
  { module: 'Stock', route: 'stock', priority: 'haute', purpose: 'Suivre aliments, récoltes, produits vendables, seuils et consommations.', data: ['stock','alimentation_logs','sales_orders','finances','alertes_center'], display: ['Seuils critiques', 'Quantités', 'Valeur stock', 'Entrées/sorties', 'Produits vendables'], checks: ['Consommations aliment', 'Stock issu récolte/abattage', 'Sortie vente', 'Alerte rupture'], forms: ['Entrée stock', 'Sortie stock', 'Consommation'], human: ['Vérifier seuil critique', 'Créer sortie', 'Comparer Finances/Alertes'], expected: 'Le stock doit éviter les ruptures et alimenter ventes/opportunités.', lots: ['Lot 4 · Automatisations terrain'] },
  { module: 'Clients', route: 'clients', priority: 'moyenne', purpose: 'Suivre commandes, paiements, créances et relances.', data: ['clients','sales_orders','payments','finances'], display: ['Fiche client', 'Historique commandes', 'Paiements', 'Reste à payer', 'Relance'], checks: ['Créance cohérente', 'Paiements liés', 'Commandes visibles'], forms: ['Créer client', 'Relance'], human: ['Ouvrir fiche client', 'Comparer commandes/paiements', 'Créer relance'], expected: 'La fiche client doit être exploitable commercialement.', lots: ['Lot 1 · Bloquants revenus'] },
  { module: 'Fournisseurs', route: 'fournisseurs', priority: 'moyenne', purpose: 'Suivre achats, dettes, stock et performance fournisseur.', data: ['fournisseurs','stock','finances','documents','taches'], display: ['Fiche fournisseur', 'Achats', 'Dettes', 'Documents', 'Tâches liées'], checks: ['Dettes cohérentes', 'Stock lié', 'Factures/justificatifs'], forms: ['Créer fournisseur', 'Dette', 'Tâche'], human: ['Ouvrir fiche', 'Vérifier dettes/stock', 'Créer tâche'], expected: 'Les fournisseurs doivent être liés aux coûts et stocks.', lots: ['Lot 2 · Coûts et marges métier'] },
  { module: 'Traçabilité', route: 'tracabilite', priority: 'moyenne', purpose: 'Raconter l’historique complet des actions métier.', data: ['tracabilite','business_events','sales_orders','payments','sante','animaux','avicole','cultures'], display: ['Timeline claire', 'Filtres', 'Liens module', 'Événements importants'], checks: ['Vente', 'Paiement', 'Intervention santé', 'Perte', 'Récolte', 'Alerte consignées'], forms: [], human: ['Filtrer animal/lot/culture', 'Vérifier événements'], expected: 'Aucune action importante ne doit disparaître.', lots: ['Lot 4 · Automatisations terrain'] },
  { module: 'Alertes', route: 'alertes', priority: 'moyenne', purpose: 'Prioriser risques et anomalies.', data: ['alertes_center','stock','sante','animaux','avicole','cultures','finances'], display: ['Critiques en haut', 'Action recommandée', 'Module lié', 'Tâche possible'], checks: ['Ruptures stock', 'Pesées retard', 'Vaccins retard', 'Paiements retard', 'Mortalité'], forms: ['Créer/traiter alerte'], human: ['Traiter alerte', 'Créer tâche', 'Vérifier traçabilité'], expected: 'Les alertes doivent guider sans noyer.', lots: ['Lot 4 · Automatisations terrain'] },
  { module: 'Documents', route: 'documents', priority: 'moyenne', purpose: 'Centraliser factures, preuves, ordonnances, rapports.', data: ['documents','invoices','sante','sales_orders','rapports'], display: ['Type document', 'Module lié', 'Preuve visible', 'Recherche', 'Export'], checks: ['Factures ventes', 'Ordonnances santé', 'Rapports audit', 'Justificatifs finances'], forms: ['Upload document'], human: ['Chercher facture', 'Chercher ordonnance', 'Ouvrir rapport audit'], expected: 'Chaque document important doit être retrouvable.', lots: ['Lot 1 · Bloquants revenus'] },
  { module: 'Tâches', route: 'taches', priority: 'moyenne', purpose: 'Transformer décisions en actions terrain.', data: ['taches','alertes_center','business_events'], display: ['Priorité', 'Échéance', 'Responsable', 'Module lié', 'Statut'], checks: ['Pesées', 'Vaccins', 'Récoltes', 'Relances', 'Maintenance'], forms: ['Créer tâche', 'Terminer tâche'], human: ['Créer/terminer tâche', 'Vérifier traçabilité'], expected: 'Le quotidien doit être piloté par actions simples.', lots: ['Lot 4 · Automatisations terrain'] },
  { module: 'RH', route: 'rh', priority: 'moyenne', purpose: 'Suivre équipe, rôles et charges RH.', data: ['finances','taches'], display: ['Équipe', 'Rôles', 'Charges', 'Tâches'], checks: ['Salaires/charges en finances', 'Responsabilités tâches'], forms: ['Ajouter membre'], human: ['Vérifier charges', 'Comparer finances'], expected: 'Les coûts RH doivent participer à la marge.', lots: ['Lot 2 · Coûts et marges métier'] },
  { module: 'Rapports', route: 'rapports', priority: 'moyenne', purpose: 'Produire rapports présentables financeur/exploitation.', data: ['rapports','finances','sales_orders','documents'], display: ['Rapport audit', 'Rapport financeur', 'Export', 'Résumé clair'], checks: ['CA/charges/marge', 'Anomalies', 'Avant/après correction'], forms: ['Générer rapport'], human: ['Ouvrir rapport audit', 'Exporter'], expected: 'Le rapport doit être exploitable et présentable.', lots: ['Lot 5 · Investissements et financeur'] },
  { module: 'Équipements', route: 'equipements', priority: 'basse', purpose: 'Suivre actifs, pannes, maintenance et coûts.', data: ['equipements','taches','finances'], display: ['Statut équipement', 'Maintenance', 'Coûts', 'Tâches'], checks: ['Pannes créent tâches/alertes', 'Réparation crée coût'], forms: ['Maintenance'], human: ['Créer maintenance', 'Vérifier coût'], expected: 'Les équipements critiques doivent être suivis.', lots: ['Lot 4 · Automatisations terrain'] },
  { module: 'Smart Farm', route: 'smartfarm', priority: 'basse', purpose: 'Préparer capteurs, caméras, météo et alertes.', data: ['sensor_devices','camera_devices','alertes_center'], display: ['Capteurs', 'Caméras', 'Météo', 'Alertes'], checks: ['Règles température/humidité/lumière', 'Alerte capteur'], forms: ['Capteur', 'Caméra'], human: ['Vérifier capteurs simulés', 'Créer alerte'], expected: 'La logique doit être claire même sans capteurs réels.', lots: ['Lot 4 · Automatisations terrain'] },
  { module: 'Sync', route: 'sync_activity', priority: 'basse', purpose: 'Vérifier fiabilité des données et synchronisation.', data: ['audit_logs'], display: ['Journaux', 'Erreurs', 'Actions offline', 'Synchronisation'], checks: ['Erreurs visibles', 'Reprise possible'], forms: [], human: ['Vérifier journaux', 'Relancer sync'], expected: 'L’utilisateur doit savoir si les données sont fiables.', lots: ['Lot 4 · Automatisations terrain'] },
  { module: 'Gestion système', route: 'gestion_systeme', priority: 'moyenne', purpose: 'Gérer comptes, rôles, droits et visiteurs.', data: [], display: ['Utilisateurs', 'Rôles', 'Matrice accès', 'Visiteur test'], checks: ['Droits cohérents', 'Assistant accessible au testeur'], forms: ['Créer utilisateur', 'Modifier rôle'], human: ['Vérifier testeur', 'Vérifier droits'], expected: 'Les accès doivent être compréhensibles et sûrs.', lots: ['Lot 3 · Formulaires et UX'] }
];

export const auditModuleNames = auditManifest.map((item) => item.module);
export const auditRequiredDataKeys = Array.from(new Set(auditManifest.flatMap((item) => item.data || [])));
export const findAuditModule = (moduleName) => auditManifest.find((item) => item.module === moduleName);
export const auditCorrectionLots = Array.from(new Set(auditManifest.flatMap((item) => item.lots || [])));
