/**
 * Revue d'implémentation des 26 événements métier V1.
 * Chaque ligne relie un écran actif, un workflow exécuté et une preuve de test.
 */

const entry = ({
  id,
  screen,
  screenMarker,
  workflow,
  workflowMarker,
  test,
  testMarker = workflowMarker,
  stock,
  finance,
  commercial,
  tasks,
  alerts,
  documents,
  reporting,
  review,
}) => Object.freeze({
  id,
  screen: Object.freeze({ file: screen, marker: screenMarker }),
  workflow: Object.freeze({ file: workflow, marker: workflowMarker }),
  impacts: Object.freeze({ stock, finance, commercial, tasks, alerts, documents, reporting }),
  test: Object.freeze({ file: test, marker: testMarker }),
  status: 'COMPLET',
  review,
});

export const BUSINESS_EVENT_IMPLEMENTATION_MATRIX = Object.freeze([
  entry({
    id: 'feed_reception',
    screen: 'src/modules/StockPurchaseReceptionForm.jsx', screenMarker: 'commitStockPurchaseWorkflow',
    workflow: 'src/utils/stockPurchaseWorkflow.js', workflowMarker: 'commitStockPurchaseWorkflow',
    test: 'tests/unit/achatsStockV1P0.test.js',
    stock: 'Entrée et mouvement de stock avec CMUP.', finance: 'Paiement ou dette fournisseur selon le statut.', commercial: 'N/A.', tasks: 'Réapprovisionnement dérivé si seuil atteint.', alerts: 'Seuil stock et preuve manquante.', documents: 'Facture ou reçu lié à la transaction.', reporting: 'Événement, coût unitaire et dette fournisseur.',
    review: 'Le formulaire bloque quantité, coût, fournisseur et statut de paiement invalides.',
  }),
  entry({
    id: 'feed_distribution',
    screen: 'src/modules/elevage/ElevageWorkflowPanels.jsx', screenMarker: 'commitElevageFeeding',
    workflow: 'src/utils/elevageWorkflow.js', workflowMarker: 'commitElevageFeeding',
    test: 'tests/unit/dailyQuickEntryContract.test.js',
    stock: 'Sortie aliment et mouvement idempotent.', finance: 'Coût imputé au lot ou à l’animal sans double caisse.', commercial: 'Marge future recalculable.', tasks: 'Tâche de réapprovisionnement au seuil.', alerts: 'Stock critique ou consommation anormale.', documents: 'N/A en saisie quotidienne.', reporting: 'Consommation, coût alimentaire et indice.',
    review: 'La cible, le stock et une quantité positive sont obligatoires.',
  }),
  entry({
    id: 'broiler_lot_start',
    screen: 'src/modules/AvicoleV10.jsx', screenMarker: 'buildBroilerLotStartWorkflow',
    workflow: 'src/utils/elevageWorkflow.js', workflowMarker: 'buildBroilerLotStartWorkflow',
    test: 'tests/unit/partialEventsCompletion.test.js',
    stock: 'Besoin aliment projeté.', finance: 'Coût initial du lot.', commercial: 'Date et marge de vente prévues.', tasks: 'Vaccination, pesée et suivi créés.', alerts: 'Blocage bâtiment occupé ou données manquantes.', documents: 'Traçabilité via événement du lot.', reporting: 'Effectif, coût, besoin aliment et marge prévisionnelle.',
    review: 'Le démarrage est bloqué sans effectif, bâtiment, fournisseur ou coût cohérent.',
  }),
  entry({
    id: 'mortality_record',
    screen: 'src/modules/elevage/ElevageWorkflowPanels.jsx', screenMarker: 'commitElevageMortality',
    workflow: 'src/utils/elevageWorkflow.js', workflowMarker: 'commitElevageMortality',
    test: 'tests/unit/dailyQuickEntryContract.test.js',
    stock: 'N/A.', finance: 'Perte technique et coût survivant dérivés.', commercial: 'Marge attendue révisée.', tasks: 'Contrôle sanitaire au seuil.', alerts: 'Mortalité élevée ou répétée.', documents: 'Historique événementiel.', reporting: 'Effectif restant, taux de mortalité et perte estimée.',
    review: 'La quantité ne peut pas dépasser l’effectif et la cause est conservée.',
  }),
  entry({
    id: 'health_treatment',
    screen: 'src/modules/SanteV6.jsx', screenMarker: 'runHealthStockConsumptionSideEffects',
    workflow: 'src/utils/healthSideEffects.js', workflowMarker: 'runHealthStockConsumptionSideEffects',
    test: 'tests/unit/achatsStockV3.test.js',
    stock: 'Consommation du produit vétérinaire.', finance: 'Coût sanitaire lié à la cible.', commercial: 'Délai d’attente protège la vente.', tasks: 'Rappel ou tâche sanitaire clôturée.', alerts: 'Stock insuffisant ou suivi en retard.', documents: 'Ordonnance ou preuve sanitaire liée.', reporting: 'Historique santé et coût sanitaire.',
    review: 'Cible, produit, quantité, date et responsable sont contrôlés.',
  }),
  entry({
    id: 'biosecurity_cleaning',
    screen: 'src/modules/SanteV6.jsx', screenMarker: 'commitBiosecurityWorkflow',
    workflow: 'src/utils/manureSideEffects.js', workflowMarker: 'runManureCollectionSideEffects',
    test: 'tests/unit/biosecurityManureWorkflow.test.js',
    stock: 'Création de matière organique collectée.', finance: 'Coût de biosécurité rattachable.', commercial: 'N/A.', tasks: 'Nettoyage, vide sanitaire ou compostage.', alerts: 'Destination culture bloquée si statut suspect.', documents: 'Preuve sanitaire et collecte.', reporting: 'Poids collecté et preuve de circularité.',
    review: 'Nombre de sacs, poids, statut sanitaire, destination et prochaine étape sont validés.',
  }),
  entry({
    id: 'egg_production',
    screen: 'src/modules/elevage/ElevageWorkflowPanels.jsx', screenMarker: 'commitElevageEggProduction',
    workflow: 'src/utils/elevageWorkflow.js', workflowMarker: 'commitElevageEggProduction',
    test: 'tests/unit/dailyQuickEntryContract.test.js',
    stock: 'Entrée d’œufs vendables et consommation emballage.', finance: 'Coût plateau dérivé.', commercial: 'Quantité rendue vendable.', tasks: 'Suivi si emballage ou stock manque.', alerts: 'Casse ou taux de ponte anormal.', documents: 'Historique de production.', reporting: 'Œufs, tablettes, casse et taux de ponte.',
    review: 'Lot, quantité produite et casse cohérente sont obligatoires.',
  }),
  entry({
    id: 'egg_sale',
    screen: 'src/modules/commercial/DailySaleModal.jsx', screenMarker: 'commitCommercialSale',
    workflow: 'src/utils/commercialSaleWorkflow.js', workflowMarker: 'resolveCommercialBusinessEventType',
    test: 'tests/unit/businessEventOperationalGaps.vite.js',
    stock: 'Sortie du stock œufs.', finance: 'Encaissement ou créance.', commercial: 'Commande, livraison, facture et client.', tasks: 'Relance si reste dû.', alerts: 'Créance ou stock insuffisant.', documents: 'Facture liée.', reporting: 'CA œufs, cash, créance et marge.',
    review: 'Produit, quantité, prix, client, paiement et disponibilité sont contrôlés.',
  }),
  entry({
    id: 'broiler_sale',
    screen: 'src/modules/commercial/DailySaleModal.jsx', screenMarker: 'commitCommercialSale',
    workflow: 'src/utils/commercialSaleWorkflow.js', workflowMarker: 'resolveCommercialBusinessEventType',
    test: 'tests/unit/businessEventOperationalGaps.vite.js',
    stock: 'Effectif du lot diminué.', finance: 'Encaissement ou créance.', commercial: 'Commande, livraison et facture.', tasks: 'Clôture ou suivi du lot.', alerts: 'Vente supérieure à l’effectif bloquée.', documents: 'Facture et traçabilité lot.', reporting: 'CA chair, marge et écart prévu/réel.',
    review: 'Le lot source et l’effectif disponible sont exigés.',
  }),
  entry({
    id: 'bovine_weighing',
    screen: 'src/modules/elevage/ElevageWorkflowPanels.jsx', screenMarker: 'commitElevageWeighing',
    workflow: 'src/utils/elevageWorkflow.js', workflowMarker: 'commitElevageWeighing',
    test: 'tests/unit/partialEventsCompletion.test.js',
    stock: 'N/A.', finance: 'Coût par kg gagné et marge dérivés.', commercial: 'Date de sortie estimée.', tasks: 'Nouvelle pesée ou adaptation ration.', alerts: 'GMQ faible ou pesée en retard.', documents: 'Historique de pesée.', reporting: 'Poids, GMQ, coût/kg et marge.',
    review: 'Animal, date et poids positif sont obligatoires.',
  }),
  entry({
    id: 'bovine_sale',
    screen: 'src/modules/commercial/DailySaleModal.jsx', screenMarker: 'commitCommercialSale',
    workflow: 'src/utils/commercialSaleWorkflow.js', workflowMarker: 'resolveCommercialBusinessEventType',
    test: 'tests/unit/businessEventOperationalGaps.vite.js',
    stock: 'Animal sorti de l’actif.', finance: 'Encaissement ou créance.', commercial: 'Commande et client liés.', tasks: 'Archivage et suivi de solde.', alerts: 'Animal déjà vendu ou indisponible bloqué.', documents: 'Facture et fiche animal liées.', reporting: 'CA bovin, marge par tête et rotation.',
    review: 'Un animal actif unique, un prix et un client sont requis.',
  }),
  entry({
    id: 'crop_campaign_start',
    screen: 'src/modules/CulturesRecoveredModule.jsx', screenMarker: 'buildCropCampaignStartWorkflow',
    workflow: 'src/utils/cultureWorkflows.js', workflowMarker: 'buildCropCampaignStartWorkflow',
    test: 'tests/unit/partialEventsCompletion.test.js',
    stock: 'Intrants initiaux et besoins liés.', finance: 'Budget initial de campagne.', commercial: 'Rendement vendable projeté.', tasks: 'Irrigation et suivi planifiés.', alerts: 'Parcelle occupée ou capacité manquante.', documents: 'Événement de campagne.', reporting: 'Surface, rendement, coût et marge prévus.',
    review: 'Parcelle, culture, surface, date et budget sont cohérents avant création.',
  }),
  entry({
    id: 'irrigation_event',
    screen: 'src/modules/cultures/CulturesIrrigationQuickForm.jsx', screenMarker: 'commitCultureIrrigation',
    workflow: 'src/utils/culturesWorkflow.js', workflowMarker: 'commitCultureIrrigation',
    test: 'tests/unit/dailyQuickEntryContract.test.js',
    stock: 'N/A.', finance: 'Coût technique affecté sans faux décaissement.', commercial: 'Marge parcelle recalculable.', tasks: 'Contrôle fuite ou pompe.', alerts: 'Volume anormal ou capteur muet.', documents: 'Historique d’irrigation.', reporting: 'Eau, durée, coût et rendement eau.',
    review: 'Culture active et volume positif sont obligatoires.',
  }),
  entry({
    id: 'organic_transfer',
    screen: 'src/modules/CulturesRecoveredModule.jsx', screenMarker: 'buildOrganicTransferWorkflow',
    workflow: 'src/utils/manureWorkflows.js', workflowMarker: 'buildOrganicTransferWorkflow',
    test: 'tests/unit/partialEventsCompletion.test.js',
    stock: 'Sortie du stock organique.', finance: 'Économie d’intrants estimée.', commercial: 'N/A.', tasks: 'Suivi parcelle ou contrôle sanitaire.', alerts: 'Blocage contamination et stock insuffisant.', documents: 'Preuve de transfert.', reporting: 'Kg valorisés et circularité.',
    review: 'Origine, parcelle, quantité et statut sanitaire sont contrôlés.',
  }),
  entry({
    id: 'crop_harvest',
    screen: 'src/modules/cultures/CulturesHarvestPanel.jsx', screenMarker: 'commitCultureHarvest',
    workflow: 'src/utils/culturesWorkflow.js', workflowMarker: 'commitCultureHarvest',
    test: 'tests/unit/culturesWorkflow.test.js',
    stock: 'Entrée de récolte vendable et mouvement.', finance: 'Coût/kg avec frais de récolte.', commercial: 'Stock rendu disponible.', tasks: 'Suivi pertes si écart.', alerts: 'Quantités incohérentes ou stock manquant.', documents: 'Événement de récolte.', reporting: 'Rendement, pertes, déclassement et coût/kg.',
    review: 'Culture, quantité, pertes, unité et destination sont validées.',
  }),
  entry({
    id: 'crop_sale',
    screen: 'src/modules/commercial/DailySaleModal.jsx', screenMarker: 'commitCommercialSale',
    workflow: 'src/utils/commercialSaleWorkflow.js', workflowMarker: 'resolveCommercialBusinessEventType',
    test: 'tests/unit/businessEventOperationalGaps.vite.js',
    stock: 'Sortie de récolte.', finance: 'Encaissement ou créance.', commercial: 'Commande, livraison et client.', tasks: 'Livraison ou relance.', alerts: 'Stock récolte insuffisant.', documents: 'Facture et preuve de livraison.', reporting: 'CA culture et marge parcelle.',
    review: 'Récolte source, quantité disponible, prix et client sont requis.',
  }),
  entry({
    id: 'customer_payment',
    screen: 'src/modules/SaleActionModal.jsx', screenMarker: 'recordSalePayment',
    workflow: 'src/utils/recordSalePayment.js', workflowMarker: 'recordSalePayment',
    test: 'tests/unit/demoFinanceurDryRun.test.js',
    stock: 'N/A.', finance: 'Entrée de trésorerie sans recompter le CA.', commercial: 'Solde commande et statut client.', tasks: 'Relances clôturées au solde.', alerts: 'Créance résolue au paiement complet.', documents: 'Facture déjà gérée par la vente.', reporting: 'Encaissements, créances et trésorerie.',
    review: 'Vente liée, plafond du reste dû, date et moyen sont contrôlés.',
  }),
  entry({
    id: 'supplier_payment',
    screen: 'src/modules/Fournisseurs.jsx', screenMarker: 'SupplierPaymentModal',
    workflow: 'src/utils/supplierSideEffects.js', workflowMarker: 'runSupplierPaymentSideEffects',
    test: 'tests/unit/businessEventOperationalGaps.vite.js',
    stock: 'Dette liée à l’achat ou au stock source.', finance: 'Sortie de trésorerie et solde partiel.', commercial: 'N/A.', tasks: 'Suivi dette clôturé seulement au solde.', alerts: 'Alerte conservée tant que la dette reste ouverte.', documents: 'Justificatif obligatoire.', reporting: 'Dette fournisseur, cash sortant et coût achat.',
    review: 'Dette source, montant plafonné, date, mode et preuve sont obligatoires.',
  }),
  entry({
    id: 'equipment_purchase',
    screen: 'src/modules/equipements/EquipementAcquisitionForm.jsx', screenMarker: 'funding_source_id',
    workflow: 'src/utils/equipmentWorkflows.js', workflowMarker: 'buildEquipmentPurchaseWorkflow',
    test: 'tests/unit/partialEventsCompletion.test.js',
    stock: 'N/A.', finance: 'Dépense d’investissement liée.', commercial: 'N/A.', tasks: 'Maintenance initiale planifiée.', alerts: 'Preuve manquante bloquée par le formulaire.', documents: 'Facture obligatoire.', reporting: 'Actif, amortissement et coût fixe.',
    review: 'Équipement, type, montant, fournisseur, financement, date et preuve sont obligatoires.',
  }),
  entry({
    id: 'equipment_maintenance',
    screen: 'src/modules/EquipementsQuickActionsBridge.jsx', screenMarker: 'runEquipmentMaintenanceSideEffects',
    workflow: 'src/utils/equipmentSideEffects.js', workflowMarker: 'runEquipmentMaintenanceSideEffects',
    test: 'tests/unit/businessEventOperationalGaps.vite.js',
    stock: 'N/A.', finance: 'Dépense maintenance idempotente.', commercial: 'N/A.', tasks: 'Tâche créée ou mise à jour.', alerts: 'Alerte panne conservée jusqu’à réparation.', documents: 'Preuve maintenance liée au coût.', reporting: 'Coût, disponibilité et prochaine échéance.',
    review: 'Équipement, date, type, responsable, coût non négatif et prochaine échéance sont validés.',
  }),
  entry({
    id: 'task_lifecycle',
    screen: 'src/modules/activiteSuivi/ActiviteWorkflowBridge.jsx', screenMarker: 'completeActiviteTask',
    workflow: 'src/utils/activiteSuiviWorkflow.js', workflowMarker: 'completeActiviteTask',
    test: 'tests/unit/activiteSuiviWorkflow.test.js',
    stock: 'N/A.', finance: 'N/A sauf opération source.', commercial: 'N/A sauf opération source.', tasks: 'Création, affectation, échéance et clôture.', alerts: 'Lien bidirectionnel et résolution explicite.', documents: 'Résultat traçable.', reporting: 'Retards, actions ouvertes et clôturées.',
    review: 'Une clôture conserve résultat, date, responsable et événement.',
  }),
  entry({
    id: 'support_document',
    screen: 'src/modules/documents/DocumentsWorkflowBridge.jsx', screenMarker: 'commitDocumentLink',
    workflow: 'src/utils/documentsWorkflow.js', workflowMarker: 'commitDocumentLink',
    test: 'tests/unit/documentsWorkflow.test.js',
    stock: 'Lien achat/réception possible.', finance: 'Lien transaction obligatoire selon cible.', commercial: 'Lien vente, paiement ou facture.', tasks: 'Tâche preuve clôturée.', alerts: 'Alerte preuve résolue.', documents: 'Document classé et rattaché.', reporting: 'Taux de justificatifs et niveau de preuve.',
    review: 'Type, fichier, cible et identifiant source sont contrôlés.',
  }),
  entry({
    id: 'monthly_financier_report',
    screen: 'src/modules/RapportsAutoBridge.jsx', screenMarker: 'buildMonthlyFinancierReportWorkflow',
    workflow: 'src/utils/reportWorkflows.js', workflowMarker: 'buildMonthlyFinancierReportWorkflow',
    test: 'tests/unit/partialEventsCompletion.test.js',
    stock: 'Valeur du stock consolidée.', finance: 'CA, cash, dépenses et financement.', commercial: 'Ventes, créances et livraisons.', tasks: 'Validation du brouillon.', alerts: 'Données ou preuves manquantes.', documents: 'Version de rapport et pièces.', reporting: 'Rapport mensuel versionné.',
    review: 'Période, date d’arrêté, auteur et validation sont tracés.',
  }),
  entry({
    id: 'funding_usage',
    screen: 'src/modules/InvestissementsV9.jsx', screenMarker: 'buildFundingUsageWorkflow',
    workflow: 'src/utils/bpLineConcretization.js', workflowMarker: 'buildFundingUsageWorkflow',
    test: 'tests/unit/partialEventsCompletion.test.js',
    stock: 'Actif ou intrant financé lié.', finance: 'Dépense affectée à la source.', commercial: 'N/A.', tasks: 'Justification ou correction budget.', alerts: 'Solde, dépassement ou preuve manquante.', documents: 'Justificatif de dépense.', reporting: 'Fonds utilisés, restants et écart budget.',
    review: 'Source, ligne budget, montant et preuve sont contrôlés.',
  }),
  entry({
    id: 'growth_objective',
    screen: 'src/modules/objectifs/ObjectifsDecisionModule.jsx', screenMarker: 'buildGrowthObjectiveWorkflow',
    workflow: 'src/utils/objectivesWorkflows.js', workflowMarker: 'buildGrowthObjectiveWorkflow',
    test: 'tests/unit/partialEventsCompletion.test.js',
    stock: 'Besoin aliment ou intrants simulé.', finance: 'Cash requis et capacité de remboursement.', commercial: 'Débouché et cible de vente.', tasks: 'Action de rattrapage.', alerts: 'Capacité, stock ou cash insuffisant.', documents: 'Historique de scénario.', reporting: 'Progression calculée et conditions de lancement.',
    review: 'La cible, l’unité, l’échéance, le responsable et la source de calcul restent dérivés du BP.',
  }),
  entry({
    id: 'smartfarm_signal',
    screen: 'src/modules/smartfarm/hooks/useSmartFarmTelemetry.js', screenMarker: 'syncSmartFarmCriticalSignals',
    workflow: 'src/services/smartFarmAlertSync.js', workflowMarker: 'syncSmartFarmCriticalSignals',
    test: 'tests/unit/businessEventOperationalGaps.vite.js',
    stock: 'N/A.', finance: 'N/A tant qu’aucune intervention n’est facturée.', commercial: 'N/A.', tasks: 'Tâche terrain créée une fois.', alerts: 'Alerte capteur dédupliquée.', documents: 'Preuve ajoutable lors de l’intervention.', reporting: 'Signal, zone, seuil et disponibilité.',
    review: 'V1 utilise uniquement les capteurs; aucun chemin caméra opérationnel.',
  }),
]);

export const BUSINESS_EVENT_IMPLEMENTATION_BY_ID = Object.freeze(
  Object.fromEntries(BUSINESS_EVENT_IMPLEMENTATION_MATRIX.map((row) => [row.id, row])),
);

export default BUSINESS_EVENT_IMPLEMENTATION_MATRIX;
