export const deepAuditDimensions = [
  {
    id: 'ui_navigation',
    title: 'Navigation complète interface',
    severity: 'critique',
    objective: 'Vérifier que chaque écran est parcouru comme un humain : haut, milieu, bas, onglets, boutons, cartes, tableaux, modales, graphiques.',
    checks: [
      'L’écran est parcouru de haut en bas',
      'Tous les onglets visibles sont ouverts',
      'Tous les boutons ont un effet clair',
      'Les cartes affichent des données utiles et lisibles',
      'Les tableaux ont colonnes, actions, filtres, tri et état vide compréhensibles',
      'Les liens inter-modules ouvrent le bon module',
      'Les modales se ferment et enregistrent correctement',
      'Les graphiques ont titre, période, unité, légende et données cohérentes',
    ],
    findings: ['bouton_sans_effet','spinner_infini','onglet_mauvais_contenu','graphique_incoherent','tableau_incomprehensible','etat_vide_non_explique'],
  },
  {
    id: 'field_choice_policy',
    title: 'Champ libre ou champ prédéfini',
    severity: 'critique',
    objective: 'Décider pour chaque champ s’il doit rester libre, devenir une liste prédéfinie, être calculé automatiquement, être masqué, ou être supprimé.',
    checks: [
      'Le champ sert-il à filtrer, calculer, déclencher une action, produire un document, créer une alerte ou alimenter un autre module ?',
      'Si oui, il ne doit pas être libre : il doit être liste, bouton, statut, catégorie ou calcul automatique',
      'Le champ libre est réservé aux observations, commentaires, notes terrain et détails non structurables',
      'Les statuts doivent être prédéfinis : prévu, en cours, terminé, vendu, payé, partiel, en retard, annulé',
      'Les types métier doivent être prédéfinis : vaccination, soin, déparasitage, visite vétérinaire, ordonnance, vente, perte, récolte',
      'Les niveaux doivent être prédéfinis : faible, moyen, haut, critique',
      'Les montants, dates, quantités, poids, unités et pourcentages doivent avoir un type strict',
      'Les champs qui peuvent être déduits d’un autre module doivent être calculés automatiquement',
      'Les champs redondants doivent être supprimés ou affichés en lecture seule',
      'Chaque champ doit avoir une raison métier claire',
    ],
    findings: ['champ_libre_devrait_etre_liste','champ_devrait_etre_calcule','champ_redondant','champ_sans_utilite_metier','statut_non_normalise','niveau_non_normalise','type_action_non_normalise'],
  },
  {
    id: 'form_field_audit',
    title: 'Audit champ par champ des formulaires',
    severity: 'critique',
    objective: 'Contrôler chaque champ de chaque formulaire pour vérifier utilité, clarté, type, obligation, adaptation métier, interconnexion et absence de double saisie.',
    checks: [
      'Chaque champ a un libellé compréhensible et non technique',
      'Chaque champ est utile pour une décision, un document, une trace, un coût, un stock, une vente ou une tâche',
      'Chaque champ obligatoire est réellement indispensable au contexte',
      'Chaque champ facultatif peut être ignoré sans casser le workflow',
      'Le type du champ est correct : montant, date, fichier, liste, nombre, texte court, commentaire',
      'Les listes déroulantes utilisent des valeurs métier prédéfinies quand le champ ne doit pas être libre',
      'Les champs changent selon le type d’intervention ou d’action choisi',
      'Les champs non pertinents sont masqués ou désactivés',
      'Les objets vendus, clôturés ou facturés verrouillent les champs sensibles',
      'L’enregistrement alimente automatiquement les modules liés',
      'Le formulaire évite la double saisie si la donnée existe déjà ailleurs',
      'Les erreurs de validation sont claires et actionnables',
    ],
    findings: ['champ_inutile','champ_incomprehensible','champ_obligatoire_injustifie','champ_type_incorrect','champ_libre_devrait_etre_liste','champ_non_adapte_au_type_action','champ_non_verrouille_objet_cloture','double_saisie','validation_absente','enregistrement_sans_interconnexion'],
  },
  {
    id: 'cards_audit',
    title: 'Audit des cartes et KPI',
    severity: 'haute',
    objective: 'Vérifier que chaque carte affiche une information utile, sourcée, lisible, non redondante et actionnable.',
    checks: [
      'Le titre de la carte est clair',
      'La valeur affichée est utile pour piloter la ferme',
      'La source de la donnée est identifiable ou cohérente',
      'Les unités sont visibles : FCFA, kg, jour, %, unité, tête, plateau',
      'Les zéros sont expliqués ou signalés comme suspects',
      'La carte ne répète pas inutilement une information déjà affichée',
      'La carte propose une action si un problème est détecté',
      'La carte ne montre pas de code technique ou libellé incompréhensible',
      'La carte est cohérente avec le module et l’onglet',
    ],
    findings: ['kpi_sans_source','kpi_zero_suspect','carte_redondante','carte_non_actionnable','libelle_technique_visible','unite_absente','carte_hors_contexte'],
  },
  {
    id: 'tables_audit',
    title: 'Audit des tableaux',
    severity: 'haute',
    objective: 'Contrôler chaque tableau : colonnes utiles, ordre logique, actions par ligne, filtres, tri, statuts, cohérence et absence de lignes vides.',
    checks: [
      'Les colonnes sont utiles et non excessives',
      'Les colonnes importantes sont visibles sans chercher',
      'Les colonnes sont dans un ordre métier logique',
      'Les montants, dates, poids et statuts sont formatés clairement',
      'Chaque ligne a les actions pertinentes : voir, modifier, clôturer, document, paiement, trace',
      'Les actions interdites sont masquées ou désactivées',
      'Recherche, filtre et tri sont disponibles si la liste peut grandir',
      'Les états vides expliquent quoi faire',
      'Les doublons sont détectés',
      'Les tirets et lignes inutiles sont évités',
    ],
    findings: ['colonne_inutile','colonne_importante_absente','ordre_colonnes_incoherent','action_ligne_absente','action_interdite_visible','filtre_absent','etat_vide_non_explique','doublon_tableau','ligne_tiret_inutile'],
  },
  {
    id: 'charts_audit',
    title: 'Audit des graphiques et courbes',
    severity: 'critique',
    objective: 'Vérifier que chaque graphique est au bon endroit, avec la bonne donnée, la bonne période, la bonne unité et une lecture métier correcte.',
    checks: [
      'Le graphique a un titre clair',
      'Le graphique est cohérent avec le module et l’onglet',
      'La source de données est cohérente avec les tableaux et KPI',
      'Les axes ont unités et périodes compréhensibles',
      'La légende est lisible',
      'Le graphique vide explique pourquoi il est vide',
      'Les courbes affichées correspondent au métier : pondeuses, chair, animaux, cultures, ventes, finances',
      'Les valeurs aberrantes ou ruptures sont signalées',
      'Le graphique n’est pas décoratif : il aide à décider',
    ],
    findings: ['graphique_sans_titre','graphique_hors_contexte','graphique_vide_sans_explication','axe_sans_unite','periode_absente','legende_incomprehensible','courbe_mauvais_metier','valeur_aberrante_non_signalee','graphique_decoratif'],
  },
  {
    id: 'workflow_interconnection',
    title: 'Interconnexion automatique',
    severity: 'critique',
    objective: 'Vérifier que les actions métier créent automatiquement les écritures, documents, traces, alertes et tâches utiles sans double saisie.',
    checks: [
      'Paiement vente crée une transaction Finance liée',
      'Facture crée un document Facture lié',
      'Commande créée depuis opportunité ferme l’opportunité',
      'Animal vendu est relié à commande, paiement, finance et verrouillé',
      'Récolte disponible alimente stock et opportunité vente',
      'Intervention santé crée coût santé, document/preuve et impact structuré si pertinent',
      'Alerte critique peut créer tâche ou action terrain',
      'Toute action importante crée une trace exploitable',
      'Une donnée saisie une fois est réutilisée partout où elle est utile',
      'Une action dans un module met à jour par ricochet les modules dépendants',
    ],
    findings: ['paiement_sans_finance','facture_sans_document','opportunite_non_fermee','animal_vendu_sans_commande','sante_sans_impact_structure','action_sans_trace','module_non_mis_a_jour_par_ricochet','double_saisie_inter_module'],
  },
  {
    id: 'erp_simplification',
    title: 'Simplification intelligente de l’ERP',
    severity: 'critique',
    objective: 'Simplifier au maximum l’ERP sans l’appauvrir : garder la richesse métier, supprimer la charge mentale et rendre les actions évidentes.',
    checks: [
      'Chaque écran affiche d’abord les 3 à 5 informations les plus importantes',
      'Les détails secondaires sont repliés ou placés plus bas',
      'Les actions principales sont visibles, les actions rares sont secondaires',
      'Le même concept utilise le même nom partout : vente, paiement, facture, document, tâche, alerte',
      'Les modules ne demandent pas à l’utilisateur de refaire une action déjà connue ailleurs',
      'Les données techniques sont cachées sauf besoin d’audit',
      'Les recommandations sont courtes, concrètes et reliées à une action',
      'Les formulaires longs sont divisés par étapes ou adaptés au choix métier',
      'Les informations riches restent disponibles en détail, historique ou rapport',
      'Le mode données simulées et le mode données réelles ont la même structure',
    ],
    findings: ['ecran_trop_charge','action_principale_cachee','detail_trop_visible','terme_non_homogene','module_demande_double_saisie','donnee_technique_visible','recommandation_trop_longue','formulaire_trop_long','richesse_mal_organisee'],
  },
  {
    id: 'business_rules',
    title: 'Règles métier terrain',
    severity: 'critique',
    objective: 'Contrôler les règles propres à Horizon Farm : élevage, avicole, cultures, santé, ventes, finance et exploitation terrain.',
    checks: [
      'Pesée animal tous les 15 jours avec tâche/alerte avant échéance',
      'Animal vendu non modifiable sauf consultation historique',
      'Pondeuses affichent ponte, œufs, mortalité, alimentation et marge pondeuses, pas courbes chair',
      'Poulets chair affichent poids, âge, mortalité, coût et prêt à vendre',
      'Culture récoltée affiche disponible, stock, pertes, coût et opportunité vente',
      'Charges santé, alimentation, RH et investissements sont visibles dans marge/comptabilité',
      'Objectifs réalisés ne restent pas à zéro si ventes existent',
    ],
    findings: ['pesee_retard','animal_vendu_modifiable','graphique_pondeuse_chair','recolte_non_stockee','charge_metier_absente','objectif_realise_zero_malgre_vente'],
  },
  {
    id: 'forms_and_documents',
    title: 'Formulaires, preuves et documents',
    severity: 'haute',
    objective: 'Vérifier que les formulaires sont simples, adaptés au type d’action et génèrent les documents/preuves nécessaires.',
    checks: [
      'Formulaire santé change selon vaccination, soin, déparasitage, visite vétérinaire, ordonnance',
      'Preuve ou ordonnance accepte upload fichier/photo, pas seulement URL',
      'Impact ferme est structuré par catégorie, niveau, montant, module et action',
      'Facture, ordonnance, preuve santé et rapport audit apparaissent dans Documents',
      'Les champs obligatoires sont cohérents avec le type choisi',
      'Les formulaires ne demandent pas deux fois la même information',
    ],
    findings: ['formulaire_non_adaptatif','preuve_url_uniquement','impact_champ_libre','document_manquant','champ_obligatoire_incoherent'],
  },
  {
    id: 'data_quality',
    title: 'Qualité données et cohérence',
    severity: 'haute',
    objective: 'Détecter les données absentes, doublons, montants incohérents, zéros suspects et écarts entre modules.',
    checks: [
      'Zéros suspects expliqués ou corrigés',
      'Pas de doublons paiements/factures/documents',
      'Montants vente, paiement, finance et comptabilité cohérents',
      'CA Accueil, Objectifs, Ventes, Finances alignés',
      'Coûts directs visibles dans chaque activité',
      'Données simulées et données réelles utilisent la même structure',
    ],
    findings: ['zero_suspect','doublon','montant_incoherent','ca_non_aligne','cout_direct_absent','structure_simulee_reelle_differente'],
  },
  {
    id: 'assistant_output',
    title: 'Qualité du rapport audit',
    severity: 'haute',
    objective: 'L’audit doit produire des constats exploitables, pas des messages génériques.',
    checks: [
      'Chaque anomalie indique module, zone, élément, cause probable et action recommandée',
      'Chaque anomalie distingue correction obligatoire et amélioration recommandée',
      'Chaque anomalie indique le workflow ou fichier probable concerné quand possible',
      'Chaque anomalie a un statut : détecté, à corriger, corrigé, à retester',
      'Le rapport peut être exporté et relu sans captures écran',
    ],
    findings: ['message_generique','cause_absente','action_absente','statut_absent','rapport_non_exploitable'],
  },
];

export const deepAuditModuleFocus = {
  Accueil: ['ui_navigation','cards_audit','charts_audit','data_quality','workflow_interconnection','erp_simplification'],
  'Centre décisionnel': ['ui_navigation','cards_audit','workflow_interconnection','business_rules','assistant_output','erp_simplification'],
  Objectifs: ['cards_audit','charts_audit','data_quality','business_rules','workflow_interconnection','erp_simplification'],
  Animaux: ['form_field_audit','field_choice_policy','cards_audit','tables_audit','charts_audit','business_rules','workflow_interconnection','ui_navigation','erp_simplification'],
  Avicole: ['form_field_audit','field_choice_policy','cards_audit','tables_audit','charts_audit','business_rules','ui_navigation','data_quality','erp_simplification'],
  Cultures: ['form_field_audit','field_choice_policy','cards_audit','tables_audit','charts_audit','business_rules','workflow_interconnection','data_quality','erp_simplification'],
  Santé: ['form_field_audit','field_choice_policy','forms_and_documents','tables_audit','workflow_interconnection','business_rules','erp_simplification'],
  Ventes: ['form_field_audit','field_choice_policy','tables_audit','cards_audit','workflow_interconnection','forms_and_documents','data_quality','erp_simplification'],
  Finances: ['form_field_audit','field_choice_policy','tables_audit','cards_audit','workflow_interconnection','data_quality','business_rules','erp_simplification'],
  Comptabilité: ['cards_audit','tables_audit','charts_audit','data_quality','workflow_interconnection','business_rules','erp_simplification'],
  'Impact Business': ['form_field_audit','field_choice_policy','forms_and_documents','cards_audit','business_rules','data_quality','erp_simplification'],
  Documents: ['form_field_audit','field_choice_policy','tables_audit','forms_and_documents','workflow_interconnection','ui_navigation','erp_simplification'],
  Tâches: ['form_field_audit','field_choice_policy','tables_audit','workflow_interconnection','business_rules','ui_navigation','erp_simplification'],
  Alertes: ['cards_audit','tables_audit','workflow_interconnection','business_rules','assistant_output','erp_simplification'],
};

export function getDeepAuditFocus(moduleName) {
  const ids = deepAuditModuleFocus[moduleName] || ['ui_navigation','form_field_audit','field_choice_policy','cards_audit','tables_audit','charts_audit','workflow_interconnection','erp_simplification','data_quality','assistant_output'];
  return ids.map((id) => deepAuditDimensions.find((dimension) => dimension.id === id)).filter(Boolean);
}
