export const deepAuditDimensions = [
  {
    id: 'ui_navigation',
    title: 'Navigation complète interface',
    severity: 'critique',
    objective: 'Vérifier que chaque écran est parcouru comme un humain : haut, milieu, bas, onglets, boutons, cartes, tableaux, modales, graphiques.',
    checks: [
      'L’écran est parcouru de haut en bas',
      'Tous les onglets visibles sont ouverts',
      'Tous les boutons ont un effet clair',
      'Les cartes affichent des données utiles et lisibles',
      'Les tableaux ont colonnes, actions, filtres, tri et état vide compréhensibles',
      'Les liens inter-modules ouvrent le bon module',
      'Les modales se ferment et enregistrent correctement',
      'Les graphiques ont titre, période, unité, légende et données cohérentes',
    ],
    findings: [
      'bouton_sans_effet',
      'spinner_infini',
      'onglet_mauvais_contenu',
      'graphique_incoherent',
      'tableau_incomprehensible',
      'etat_vide_non_explique',
    ],
  },
  {
    id: 'workflow_interconnection',
    title: 'Interconnexion automatique',
    severity: 'critique',
    objective: 'Vérifier que les actions métier créent automatiquement les écritures, documents, traces, alertes et tâches utiles sans double saisie.',
    checks: [
      'Paiement vente crée une transaction Finance liée',
      'Facture crée un document Facture lié',
      'Commande créée depuis opportunité ferme l’opportunité',
      'Animal vendu est relié à commande, paiement, finance et verrouillé',
      'Récolte disponible alimente stock et opportunité vente',
      'Intervention santé crée coût santé, document/preuve et impact structuré si pertinent',
      'Alerte critique peut créer tâche ou action terrain',
      'Toute action importante crée une trace exploitable',
    ],
    findings: [
      'paiement_sans_finance',
      'facture_sans_document',
      'opportunite_non_fermee',
      'animal_vendu_sans_commande',
      'sante_sans_impact_structure',
      'action_sans_trace',
    ],
  },
  {
    id: 'business_rules',
    title: 'Règles métier terrain',
    severity: 'critique',
    objective: 'Contrôler les règles propres à Horizon Farm : élevage, avicole, cultures, santé, ventes, finance et exploitation terrain.',
    checks: [
      'Pesée animal tous les 15 jours avec tâche/alerte avant échéance',
      'Animal vendu non modifiable sauf consultation historique',
      'Pondeuses affichent ponte, œufs, mortalité, alimentation et marge pondeuses, pas courbes chair',
      'Poulets chair affichent poids, âge, mortalité, coût et prêt à vendre',
      'Culture récoltée affiche disponible, stock, pertes, coût et opportunité vente',
      'Charges santé, alimentation, RH et investissements sont visibles dans marge/comptabilité',
      'Objectifs réalisés ne restent pas à zéro si ventes existent',
    ],
    findings: [
      'pesee_retard',
      'animal_vendu_modifiable',
      'graphique_pondeuse_chair',
      'recolte_non_stockee',
      'charge_metier_absente',
      'objectif_realise_zero_malgre_vente',
    ],
  },
  {
    id: 'forms_and_documents',
    title: 'Formulaires, preuves et documents',
    severity: 'haute',
    objective: 'Vérifier que les formulaires sont simples, adaptés au type d’action et génèrent les documents/preuves nécessaires.',
    checks: [
      'Formulaire santé change selon vaccination, soin, déparasitage, visite vétérinaire, ordonnance',
      'Preuve ou ordonnance accepte upload fichier/photo, pas seulement URL',
      'Impact ferme est structuré par catégorie, niveau, montant, module et action',
      'Facture, ordonnance, preuve santé et rapport audit apparaissent dans Documents',
      'Les champs obligatoires sont cohérents avec le type choisi',
      'Les formulaires ne demandent pas deux fois la même information',
    ],
    findings: [
      'formulaire_non_adaptatif',
      'preuve_url_uniquement',
      'impact_champ_libre',
      'document_manquant',
      'champ_obligatoire_incoherent',
    ],
  },
  {
    id: 'data_quality',
    title: 'Qualité données et cohérence',
    severity: 'haute',
    objective: 'Détecter les données absentes, doublons, montants incohérents, zéros suspects et écarts entre modules.',
    checks: [
      'Zéros suspects expliqués ou corrigés',
      'Pas de doublons paiements/factures/documents',
      'Montants vente, paiement, finance et comptabilité cohérents',
      'CA Accueil, Objectifs, Ventes, Finances alignés',
      'Coûts directs visibles dans chaque activité',
      'Données simulées et données réelles utilisent la même structure',
    ],
    findings: [
      'zero_suspect',
      'doublon',
      'montant_incoherent',
      'ca_non_aligne',
      'cout_direct_absent',
      'structure_simulee_reelle_differente',
    ],
  },
  {
    id: 'assistant_output',
    title: 'Qualité du rapport audit',
    severity: 'haute',
    objective: 'L’audit doit produire des constats exploitables, pas des messages génériques.',
    checks: [
      'Chaque anomalie indique module, zone, élément, cause probable et action recommandée',
      'Chaque anomalie distingue correction obligatoire et amélioration recommandée',
      'Chaque anomalie indique le workflow ou fichier probable concerné quand possible',
      'Chaque anomalie a un statut : détecté, à corriger, corrigé, à retester',
      'Le rapport peut être exporté et relu sans captures écran',
    ],
    findings: [
      'message_generique',
      'cause_absente',
      'action_absente',
      'statut_absent',
      'rapport_non_exploitable',
    ],
  },
];

export const deepAuditModuleFocus = {
  Accueil: ['ui_navigation', 'data_quality', 'workflow_interconnection'],
  'Centre décisionnel': ['workflow_interconnection', 'business_rules', 'assistant_output'],
  Objectifs: ['data_quality', 'business_rules', 'workflow_interconnection'],
  Animaux: ['business_rules', 'workflow_interconnection', 'ui_navigation'],
  Avicole: ['business_rules', 'ui_navigation', 'data_quality'],
  Cultures: ['business_rules', 'workflow_interconnection', 'data_quality'],
  Santé: ['forms_and_documents', 'workflow_interconnection', 'business_rules'],
  Ventes: ['workflow_interconnection', 'forms_and_documents', 'data_quality'],
  Finances: ['workflow_interconnection', 'data_quality', 'business_rules'],
  Comptabilité: ['data_quality', 'workflow_interconnection', 'business_rules'],
  'Impact Business': ['forms_and_documents', 'business_rules', 'data_quality'],
  Documents: ['forms_and_documents', 'workflow_interconnection', 'ui_navigation'],
  Tâches: ['workflow_interconnection', 'business_rules', 'ui_navigation'],
  Alertes: ['workflow_interconnection', 'business_rules', 'assistant_output'],
};

export function getDeepAuditFocus(moduleName) {
  const ids = deepAuditModuleFocus[moduleName] || ['ui_navigation', 'data_quality', 'assistant_output'];
  return ids.map((id) => deepAuditDimensions.find((dimension) => dimension.id === id)).filter(Boolean);
}
