export const interconnectionAuditRules = [
  {
    id: 'GLOBAL_ALL_MODULES_INTERCONNECTED',
    module: 'Global',
    severity: 'critique',
    title: 'Toutes les interconnexions ERP doivent être vérifiées',
    rule: 'Chaque module doit être contrôlé avec ses modules amont et aval. Une donnée créée dans un module doit être visible, réutilisable ou tracée dans tous les modules dépendants.',
    verify: [
      'Mode données identifié : réel ou simulé',
      'Modules sources identifiés',
      'Modules impactés identifiés',
      'Données dupliquées ou non synchronisées signalées',
      'Liens retour vers source disponibles',
      'Trace ou événement créé pour les actions importantes',
    ],
    anomalies: ['interconnexion_absente', 'donnee_non_synchronisee', 'source_introuvable', 'trace_absente', 'module_aval_non_mis_a_jour', 'doublon_inter_module'],
    improvements: ['Créer une matrice source → impact pour chaque action', 'Afficher les modules mis à jour après validation', 'Ajouter un bouton Voir impacts sur les fiches importantes'],
  },
  {
    id: 'ACCUEIL_GLOBAL_SYNC',
    module: 'Accueil',
    severity: 'critique',
    title: 'Accueil doit refléter toute l’exploitation',
    rule: 'Les KPI Accueil doivent consolider ventes, finances, stock, alertes, objectifs, animaux, avicole et cultures sans zéros suspects.',
    verify: ['CA global aligné avec Ventes/Finances', 'Charges alignées avec Finances/Comptabilité', 'Alertes reliées aux modules sources', 'Objectifs cohérents avec ventes', 'Stocks critiques visibles'],
    anomalies: ['ca_accueil_non_aligne', 'charges_accueil_absentes', 'alerte_sans_source', 'objectif_non_repercute_accueil', 'kpi_zero_suspect'],
    improvements: ['Afficher origine des KPI', 'Ajouter liens directs vers les modules sources', 'Signaler les zéros suspects en données simulées'],
  },
  {
    id: 'CENTRE_DECISIONNEL_CROSS_MODULE',
    module: 'Centre décisionnel',
    severity: 'critique',
    title: 'Les décisions doivent venir des données réelles ou simulées disponibles',
    rule: 'Une recommandation doit être liée à une donnée source et ne doit pas proposer une action déjà réalisée.',
    verify: ['Décision reliée à source', 'Action vers bon module', 'Pas de doublon', 'Statut source pris en compte', 'Impact financier ou opérationnel visible'],
    anomalies: ['decision_sans_source', 'decision_doublon', 'action_mauvais_module', 'decision_deja_realisee', 'impact_decision_absent'],
    improvements: ['Afficher source et justification de chaque recommandation', 'Ajouter bouton appliquer ou ignorer avec trace', 'Regrouper les décisions par urgence'],
  },
  {
    id: 'OBJECTIFS_SALES_FINANCE_SYNC',
    module: 'Objectifs',
    severity: 'critique',
    title: 'Objectifs doivent être alimentés par ventes et finances',
    rule: 'Le réalisé ne doit pas rester à zéro si des ventes existent. Les objectifs doivent être ventilés par animaux, avicole, cultures et autres activités.',
    verify: ['CA animaux', 'CA avicole', 'CA cultures', 'Réalisé vs objectif', 'Marge avec coûts', 'Lien BP si présent'],
    anomalies: ['objectif_realise_zero_malgre_vente', 'ca_non_ventile', 'marge_objectif_sans_couts', 'objectif_sans_bp', 'ecart_non_explique'],
    improvements: ['Afficher ventes sources derrière chaque réalisé', 'Ajouter ventilation par activité', 'Afficher marge réelle et marge estimée'],
  },
  {
    id: 'ANIMAL_COST_BREAKDOWN',
    module: 'Animaux',
    severity: 'critique',
    title: 'Chaque fiche animal doit montrer ses coûts liés',
    rule: 'Une fiche animal, vendu ou non, doit afficher prix achat, alimentation, santé, autres frais, coût total, prix de vente si vendu, marge ou marge estimée.',
    verify: ['Prix achat visible', 'Coût alimentation visible et sourcé', 'Coût santé visible et sourcé', 'Autres frais visibles si existants', 'Coût total calculé', 'Prix vente et commande liée si vendu', 'Marge réelle si vendu, marge estimée si actif', 'Historique coûts consultable', 'Pesée J+15 et rappel J-1 pour actif'],
    anomalies: ['cout_achat_absent_fiche_animal', 'cout_alimentation_absent_fiche_animal', 'cout_sante_absent_fiche_animal', 'cout_total_absent_ou_faux', 'animal_vendu_sans_prix_vente', 'animal_vendu_sans_marge_reelle', 'animal_actif_sans_marge_estimee', 'rappel_pesee_jmoins1_absent'],
    improvements: ['Ajouter bloc Coûts liés dans la fiche animal', 'Afficher détail coût achat + alimentation + santé + autres frais', 'Ajouter liens vers Finances, Santé, Stock/Alimentation et Vente', 'Afficher marge en haut de fiche avec statut estimée ou réelle'],
  },
  {
    id: 'AVICOLE_COST_PRODUCTION_SYNC',
    module: 'Avicole',
    severity: 'critique',
    title: 'Lots avicoles liés aux coûts, production, ventes et stock',
    rule: 'Chaque lot doit relier effectif, mortalité, alimentation, santé, production œufs ou chair, ventes, finance, stock et marge.',
    verify: ['Coût poussins', 'Coût aliment', 'Coût santé', 'Mortalité', 'Production œufs', 'Vente partielle', 'Effectif restant', 'Finance liée', 'Stock ou sortie liée', 'Marge lot'],
    anomalies: ['cout_lot_absent', 'production_non_liee_stock', 'vente_partielle_non_tracee', 'effectif_restant_faux', 'ca_avicole_non_reconnu', 'marge_lot_absente'],
    improvements: ['Afficher fiche lot complète', 'Séparer chair et pondeuses', 'Afficher coût par sujet, kg, œuf ou plateau', 'Tracer automatiquement ventes partielles'],
  },
  {
    id: 'CULTURES_HARVEST_STOCK_SALES_SYNC',
    module: 'Cultures',
    severity: 'critique',
    title: 'Culture récoltée doit alimenter stock, ventes, finances et marge',
    rule: 'Une récolte disponible doit créer ou mettre à jour le stock, proposer vente, calculer pertes/coûts et alimenter objectifs/finances après vente.',
    verify: ['Parcelle/surface', 'Coûts semences/engrais/eau/MO/traitements', 'Récolte disponible', 'Pertes', 'Stock alimenté', 'Opportunité vente', 'CA cultures', 'Marge culture'],
    anomalies: ['recolte_non_stockee', 'culture_sans_couts', 'pertes_non_tracees', 'recolte_sans_opportunite', 'ca_culture_non_reconnu', 'marge_culture_absente'],
    improvements: ['Afficher coût par kg', 'Créer opportunité vente si stock disponible', 'Relier récolte à stock et traçabilité'],
  },
  {
    id: 'HEALTH_TO_ANIMAL_FINANCE_DOCUMENT',
    module: 'Santé',
    severity: 'haute',
    title: 'Intervention santé liée aux sujets, finances, URL photo et traçabilité',
    rule: 'Une intervention santé avec coût doit créer ou lier une charge Finance. La preuve santé attendue est une URL photo valide. L’animal ou le lot concerné doit afficher ce coût dans sa fiche.',
    verify: ['Intervention reliée à animal, lot ou culture', 'Coût santé visible dans Finances', 'Coût santé remonté dans fiche animal/lot', 'URL photo preuve valide', 'Trace créée', 'Rappel créé si vaccination ou suivi nécessaire'],
    anomalies: ['sante_sans_cible', 'cout_sante_sans_finance', 'cout_sante_non_visible_fiche_animal', 'preuve_photo_url_absente', 'preuve_photo_url_invalide', 'sante_sans_trace'],
    improvements: ['Afficher la preuve URL photo directement dans l’intervention', 'Lier chaque coût santé à la fiche animal ou lot', 'Créer automatiquement une charge Finance typée Santé'],
  },
  {
    id: 'SALE_TO_FINANCE_DOCUMENT_TRACE',
    module: 'Ventes',
    severity: 'critique',
    title: 'Une vente doit alimenter finance, document, stock, objectif et traçabilité',
    rule: 'Une commande validée ou payée doit avoir ses ricochets : paiement finance, facture/document si facturée, sortie stock ou actif vendu, objectif réalisé, trace historique.',
    verify: ['Commande reliée au client', 'Paiement relié à la commande', 'Paiement visible dans Finances', 'Facture visible dans Documents si émise', 'Stock ou actif source mis à jour', 'Objectif réalisé mis à jour', 'Trace créée dans Traçabilité ou business_events'],
    anomalies: ['paiement_sans_finance', 'facture_sans_document', 'vente_sans_sortie_stock', 'vente_sans_objectif_realise', 'commande_sans_trace', 'opportunite_non_fermee_apres_commande'],
    improvements: ['Afficher un bloc Après validation listant les modules mis à jour', 'Ajouter un bouton Voir les impacts de cette vente', 'Empêcher le statut payé si aucune transaction finance n’existe'],
  },
  {
    id: 'FINANCES_CHARGES_NON_ZERO',
    module: 'Finances',
    severity: 'critique',
    title: 'Toutes les charges existantes doivent être visibles',
    rule: 'En données simulées, si l’exploitation contient animaux, avicole, cultures, stock, santé, RH ou investissements, les charges ne doivent pas rester à zéro. En données réelles, charges à zéro peut être normal seulement si aucune charge n’a encore été saisie.',
    verify: ['Charges alimentation visibles', 'Charges santé visibles', 'Charges stock/achats visibles', 'Charges RH visibles si équipe ou tâches terrain', 'Charges investissement visibles si BP ou équipements', 'Chaque charge a une source ou catégorie métier'],
    anomalies: ['charges_zero_malgre_donnees_simulees', 'charge_sans_source', 'charge_sante_absente_finances', 'charge_alimentation_absente_finances', 'charge_rh_absente_finances', 'charge_investissement_absente_finances'],
    improvements: ['Afficher une ventilation charges par activité : animaux, avicole, cultures, RH, stock, santé, investissements', 'Ajouter un lien depuis chaque charge vers son animal, lot, culture, fournisseur, intervention ou équipement', 'Afficher un avertissement si charges = 0 alors que des activités simulées existent'],
  },
  {
    id: 'COMPTA_FINANCE_DOCUMENT_SYNC',
    module: 'Comptabilité',
    severity: 'critique',
    title: 'Comptabilité doit rapprocher finances, ventes, charges et documents',
    rule: 'Le résultat comptable doit reprendre CA, charges, paiements, factures et justificatifs sans masquer les coûts métier.',
    verify: ['CA ventes', 'Charges exploitation', 'Résultat', 'Paiements rapprochés', 'Factures liées', 'Justificatifs visibles'],
    anomalies: ['resultat_incoherent', 'charges_compta_zero', 'ecart_finances_compta', 'facture_non_rapprochee', 'justificatif_absent'],
    improvements: ['Afficher rapprochement Finances ↔ Comptabilité', 'Lister pièces manquantes', 'Bloquer rapport fiable si charges métier absentes'],
  },
  {
    id: 'INVESTMENTS_BP_OBJECTIVES_FINANCE_SYNC',
    module: 'Investissements',
    severity: 'haute',
    title: 'Business plan lié aux objectifs, finances, rapports et activités',
    rule: 'Le BP doit relier lignes investissement, charges récurrentes, CA prévisionnel, sources financement, objectifs, rapports et ROI.',
    verify: ['Lignes BP', 'Charges récurrentes', 'CA prévisionnel', 'Sources financement', 'ROI', 'Lien Objectifs', 'Rapport financeur'],
    anomalies: ['bp_sans_lignes', 'bp_sans_charges_recurrentes', 'bp_sans_ca_previsionnel', 'bp_sans_sources_financement', 'roi_absent_ou_faux', 'objectif_non_lie_bp'],
    improvements: ['Créer vue financeur lisible', 'Relier BP aux objectifs croissance', 'Afficher simulation ROI par activité'],
  },
  {
    id: 'IMPACT_BUSINESS_EVENT_SYNC',
    module: 'Impact Business',
    severity: 'haute',
    title: 'Impact Business doit mesurer les événements des modules',
    rule: 'Chaque impact doit avoir type, niveau, montant, module source et action recommandée.',
    verify: ['Impact santé', 'Impact stock', 'Impact vente', 'Impact production', 'Montant estimé', 'Action recommandée'],
    anomalies: ['impact_champ_libre', 'impact_sans_montant', 'impact_sans_source', 'impact_sans_action'],
    improvements: ['Structurer les impacts', 'Relier impacts aux décisions', 'Afficher valeur financière estimée'],
  },
  {
    id: 'STOCK_ALL_MODULES_SYNC',
    module: 'Stock',
    severity: 'haute',
    title: 'Stock doit recevoir récoltes, achats, ventes, consommations et alertes',
    rule: 'Le stock doit être alimenté par cultures/récoltes/achats, diminué par ventes/consommations, valorisé en finances et relié aux alertes.',
    verify: ['Entrées récolte', 'Entrées achat fournisseur', 'Sorties vente', 'Consommation alimentation', 'Valeur stock', 'Seuil critique', 'Alerte rupture'],
    anomalies: ['stock_sans_source', 'vente_sans_sortie_stock', 'recolte_non_entree_stock', 'consommation_non_tracee', 'stock_critique_sans_alerte', 'valeur_stock_absente'],
    improvements: ['Afficher historique mouvements', 'Créer alerte seuil automatique', 'Relier stock à finances et fournisseurs'],
  },
  {
    id: 'CLIENTS_SALES_PAYMENTS_SYNC',
    module: 'Clients',
    severity: 'haute',
    title: 'Clients reliés aux ventes, paiements, créances et relances',
    rule: 'Une fiche client doit afficher commandes, paiements, reste à payer, documents et relances.',
    verify: ['Historique commandes', 'Paiements', 'Créances', 'Factures', 'Relances', 'Coordonnées'],
    anomalies: ['client_sans_commandes_visibles', 'creance_incoherente', 'paiement_client_non_lie', 'relance_absente', 'coordonnees_absentes'],
    improvements: ['Afficher solde client', 'Créer relance si reste à payer', 'Lien direct vers factures et paiements'],
  },
  {
    id: 'SUPPLIERS_STOCK_FINANCE_SYNC',
    module: 'Fournisseurs',
    severity: 'haute',
    title: 'Fournisseurs liés aux achats, stocks, dettes et documents',
    rule: 'Un achat fournisseur doit alimenter stock ou charge finance, et une dette doit être visible dans Finances/Comptabilité.',
    verify: ['Achats', 'Stock lié', 'Dette fournisseur', 'Facture fournisseur', 'Charge finance', 'Tâche de suivi'],
    anomalies: ['achat_sans_stock', 'dette_sans_finance', 'facture_fournisseur_absente', 'fournisseur_sans_historique', 'tache_suivi_absente'],
    improvements: ['Créer réception stock depuis achat', 'Lier dette à finance', 'Afficher performance fournisseur'],
  },
  {
    id: 'TRACEABILITY_ALL_ACTIONS_SYNC',
    module: 'Traçabilité',
    severity: 'haute',
    title: 'Toute action importante doit laisser une trace',
    rule: 'Vente, paiement, intervention santé, récolte, stock, alerte, tâche, correction agent et document doivent être traçables.',
    verify: ['Commande tracée', 'Paiement tracé', 'Santé tracée', 'Récolte tracée', 'Stock tracé', 'Correction agent tracée', 'Filtres efficaces'],
    anomalies: ['commande_sans_trace', 'paiement_sans_trace', 'sante_sans_trace', 'stock_sans_trace', 'correction_agent_sans_trace', 'filtre_trace_inutile'],
    improvements: ['Créer timeline globale', 'Ajouter filtres par animal/lot/culture/commande', 'Lien retour vers module source'],
  },
  {
    id: 'ALERTS_TO_TASKS_MODULES_SYNC',
    module: 'Alertes',
    severity: 'haute',
    title: 'Alertes reliées aux risques et aux tâches terrain',
    rule: 'Une alerte doit avoir source, criticité, action recommandée, module lié et possibilité de tâche.',
    verify: ['Source alerte', 'Criticité', 'Action recommandée', 'Module lié', 'Tâche créée', 'Trace traitement'],
    anomalies: ['alerte_sans_source', 'alerte_sans_action', 'risque_sans_alerte', 'alerte_traitee_sans_trace', 'alerte_sans_tache_possible'],
    improvements: ['Créer tâche depuis alerte', 'Afficher risques par module', 'Tracer traitement alerte'],
  },
  {
    id: 'DOCUMENTS_ALL_MODULES_SYNC',
    module: 'Documents',
    severity: 'haute',
    title: 'Documents centralise factures, preuves URL, rapports et justificatifs',
    rule: 'Chaque document doit avoir type, module lié, source et lien ouvrable. Les preuves santé sont des URL photo.',
    verify: ['Factures ventes', 'URL photo santé', 'Rapports audit', 'Justificatifs finance', 'Factures fournisseurs', 'Recherche et filtres'],
    anomalies: ['document_sans_module', 'document_sans_type', 'preuve_url_invalide', 'facture_absente_documents', 'rapport_introuvable'],
    improvements: ['Ajouter filtres type/module/source', 'Prévisualiser URL photo', 'Lier documents à traçabilité'],
  },
  {
    id: 'TASKS_FROM_ALERTS_DECISIONS_OPERATIONS_SYNC',
    module: 'Tâches',
    severity: 'haute',
    title: 'Tâches créées depuis alertes, décisions et opérations terrain',
    rule: 'Une tâche doit avoir responsable, échéance, priorité, module lié, statut et trace de clôture.',
    verify: ['Tâches alertes', 'Tâches pesées J-1', 'Tâches vaccination/rappel', 'Tâches récolte', 'Tâches relance client', 'Responsable et échéance'],
    anomalies: ['tache_sans_responsable', 'tache_sans_echeance', 'pesee_sans_tache_jmoins1', 'alerte_sans_tache', 'tache_terminee_sans_trace'],
    improvements: ['Créer tâches automatiques', 'Afficher tâches par module source', 'Tracer clôture avec résultat'],
  },
  {
    id: 'RH_COSTS_TASKS_SYNC',
    module: 'RH',
    severity: 'moyenne',
    title: 'RH lié aux charges, rôles, tâches et responsabilités',
    rule: 'Les salaires, primes et affectations doivent alimenter Finances/Comptabilité et les tâches doivent avoir un responsable clair.',
    verify: ['Rôles', 'Affectations', 'Charges RH', 'Tâches responsables', 'Salaires en finances'],
    anomalies: ['charge_rh_absente', 'role_non_clair', 'tache_sans_responsable', 'salaire_non_repercute_finances'],
    improvements: ['Afficher coût RH mensuel', 'Lier RH aux tâches', 'Ventiler charges RH par activité'],
  },
  {
    id: 'REPORTS_DOCUMENTS_AUDIT_SYNC',
    module: 'Rapports',
    severity: 'haute',
    title: 'Rapports liés aux données, documents et corrections',
    rule: 'Un rapport doit reprendre données sources, anomalies, corrections, avant/après, exports et documents liés.',
    verify: ['Rapport audit', 'Rapport financeur', 'Sources visibles', 'Avant/après correction', 'Export', 'Document associé'],
    anomalies: ['rapport_vide', 'score_sans_justification', 'rapport_sans_sources', 'avant_apres_absent', 'rapport_non_documente'],
    improvements: ['Créer rapport actionnable', 'Ajouter sources et liens modules', 'Exporter anomalies et plan de retest'],
  },
  {
    id: 'EQUIPMENT_MAINTENANCE_FINANCE_SYNC',
    module: 'Équipements',
    severity: 'moyenne',
    title: 'Équipements liés aux pannes, maintenance, tâches et coûts',
    rule: 'Une panne ou maintenance doit créer tâche, coût finance et trace/document si pertinent.',
    verify: ['Statut équipement', 'Panne', 'Maintenance', 'Tâche', 'Coût finance', 'Document preuve'],
    anomalies: ['panne_sans_tache', 'maintenance_sans_trace', 'reparation_sans_cout', 'equipement_sans_statut'],
    improvements: ['Créer tâche maintenance', 'Relier coûts à finances', 'Historique équipement'],
  },
  {
    id: 'SMARTFARM_ALERTS_TASKS_SYNC',
    module: 'Smart Farm',
    severity: 'moyenne',
    title: 'Capteurs liés aux alertes, tâches et décisions',
    rule: 'Une donnée capteur ou seuil dépassé doit générer alerte/action si nécessaire, même en simulation.',
    verify: ['Capteur actif', 'Dernière donnée datée', 'Seuil', 'Alerte si seuil dépassé', 'Tâche si action terrain'],
    anomalies: ['capteur_muet_sans_alerte', 'donnee_capteur_non_datee', 'seuil_depasse_sans_alerte', 'alerte_capteur_sans_tache'],
    improvements: ['Afficher état capteur', 'Créer alerte automatique', 'Lien vers Centre décisionnel'],
  },
  {
    id: 'SYNC_ACTIVITY_AUDIT_LOGS_SYNC',
    module: 'Sync',
    severity: 'haute',
    title: 'Synchronisation et journaux doivent expliquer les données',
    rule: 'Les erreurs de sync, actions offline et corrections agent doivent être visibles et traçables.',
    verify: ['Dernière sync', 'Erreurs', 'Actions en attente', 'Reprise', 'Logs correction agent', 'Données non synchronisées'],
    anomalies: ['erreur_sync_silencieuse', 'action_offline_perdue', 'donnee_non_synchronisee', 'correction_sans_log'],
    improvements: ['Afficher journal lisible', 'Relancer sync depuis interface', 'Tracer corrections agent'],
  },
  {
    id: 'SYSTEM_ACCESS_AUDIT_SYNC',
    module: 'Gestion système',
    severity: 'haute',
    title: 'Droits et accès liés aux actions sensibles',
    rule: 'Les utilisateurs, rôles et droits doivent protéger corrections, finances, ventes, documents et données sensibles.',
    verify: ['Compte testeur', 'Droits module', 'Assistant ERP accessible', 'Correction agent protégée', 'Actions sensibles contrôlées'],
    anomalies: ['droit_trop_large', 'testeur_sans_acces', 'correction_sans_code', 'module_sensible_non_protege'],
    improvements: ['Afficher matrice droits', 'Protéger corrections par code', 'Tracer actions sensibles'],
  },
  {
    id: 'DATA_MODE_INTERCONNECTION_CONTEXT',
    module: 'Global',
    severity: 'critique',
    title: 'Le mode données change l’interprétation des anomalies',
    rule: 'En données réelles vides, l’audit doit guider la première saisie. En données simulées, il doit exiger que les interconnexions soient démontrables.',
    verify: ['Mode données identifié', 'Données réelles vides signalées comme état initial, pas bug', 'Données simulées suffisantes pour tester ventes/finances/coûts', 'Rapport séparant bug, donnée absente et simulation insuffisante'],
    anomalies: ['mode_donnees_non_identifie', 'donnees_reelles_vides_classees_bug', 'simulation_insuffisante_non_signalee'],
    improvements: ['Ajouter badge mode données dans chaque rapport', 'Afficher checklist première saisie en mode réel vide', 'Afficher scénarios obligatoires en mode simulé'],
  },
];

export const interconnectionAuditModules = interconnectionAuditRules.map((rule) => rule.module);

export default interconnectionAuditRules;
