export const interconnectionAuditRules = [
  {
    id: 'FINANCES_CHARGES_NON_ZERO',
    module: 'Finances',
    severity: 'critique',
    title: 'Toutes les charges existantes doivent être visibles',
    rule: 'En données simulées, si l’exploitation contient animaux, avicole, cultures, stock, santé, RH ou investissements, les charges ne doivent pas rester à zéro. En données réelles, charges à zéro peut être normal seulement si aucune charge n’a encore été saisie.',
    verify: [
      'Charges alimentation visibles',
      'Charges santé visibles',
      'Charges stock/achats visibles',
      'Charges RH visibles si équipe ou tâches terrain',
      'Charges investissement visibles si BP ou équipements',
      'Chaque charge a une source ou catégorie métier',
    ],
    anomalies: [
      'charges_zero_malgre_donnees_simulees',
      'charge_sans_source',
      'charge_sante_absente_finances',
      'charge_alimentation_absente_finances',
      'charge_rh_absente_finances',
      'charge_investissement_absente_finances',
    ],
    improvements: [
      'Afficher une ventilation charges par activité : animaux, avicole, cultures, RH, stock, santé, investissements.',
      'Ajouter un lien depuis chaque charge vers son animal, lot, culture, fournisseur, intervention ou équipement.',
      'Afficher un avertissement si charges = 0 alors que des activités simulées existent.',
    ],
  },
  {
    id: 'ANIMAL_COST_BREAKDOWN',
    module: 'Animaux',
    severity: 'critique',
    title: 'Chaque fiche animal doit montrer ses coûts liés',
    rule: 'Une fiche animal, vendu ou non, doit afficher prix achat, alimentation, santé, autres frais, coût total, prix de vente si vendu, marge ou marge estimée.',
    verify: [
      'Prix achat visible',
      'Coût alimentation visible et sourcé',
      'Coût santé visible et sourcé',
      'Autres frais visibles si existants',
      'Coût total calculé',
      'Prix vente et commande liée si vendu',
      'Marge réelle si vendu, marge estimée si actif',
      'Historique coûts consultable',
    ],
    anomalies: [
      'cout_achat_absent_fiche_animal',
      'cout_alimentation_absent_fiche_animal',
      'cout_sante_absent_fiche_animal',
      'cout_total_absent_ou_faux',
      'animal_vendu_sans_prix_vente',
      'animal_vendu_sans_marge_reelle',
      'animal_actif_sans_marge_estimee',
    ],
    improvements: [
      'Ajouter bloc Coûts liés dans la fiche animal.',
      'Afficher détail coût achat + alimentation + santé + autres frais.',
      'Ajouter liens vers Finances, Santé, Stock/Alimentation et Vente.',
      'Afficher marge en haut de fiche avec statut estimée ou réelle.',
    ],
  },
  {
    id: 'SALE_TO_FINANCE_DOCUMENT_TRACE',
    module: 'Ventes',
    severity: 'critique',
    title: 'Une vente doit alimenter finance, document, stock, objectif et traçabilité',
    rule: 'Une commande validée ou payée doit avoir ses ricochets : paiement finance, facture/document si facturée, sortie stock ou actif vendu, objectif réalisé, trace historique.',
    verify: [
      'Commande reliée au client',
      'Paiement relié à la commande',
      'Paiement visible dans Finances',
      'Facture visible dans Documents si émise',
      'Stock ou actif source mis à jour',
      'Objectif réalisé mis à jour',
      'Trace créée dans Traçabilité ou business_events',
    ],
    anomalies: [
      'paiement_sans_finance',
      'facture_sans_document',
      'vente_sans_sortie_stock',
      'vente_sans_objectif_realise',
      'commande_sans_trace',
      'opportunite_non_fermee_apres_commande',
    ],
    improvements: [
      'Afficher un bloc Après validation listant les modules mis à jour.',
      'Ajouter un bouton Voir les impacts de cette vente.',
      'Empêcher le statut payé si aucune transaction finance n’existe.',
    ],
  },
  {
    id: 'HEALTH_TO_ANIMAL_FINANCE_DOCUMENT',
    module: 'Santé',
    severity: 'haute',
    title: 'Une intervention santé doit impacter animal/lot, finance, preuve URL et traçabilité',
    rule: 'Une intervention santé avec coût doit créer ou lier une charge Finance. La preuve santé attendue est une URL photo valide. L’animal ou le lot concerné doit afficher ce coût dans sa fiche.',
    verify: [
      'Intervention reliée à animal, lot ou culture',
      'Coût santé visible dans Finances',
      'Coût santé remonté dans fiche animal/lot',
      'URL photo preuve valide',
      'Trace créée',
      'Rappel créé si vaccination ou suivi nécessaire',
    ],
    anomalies: [
      'sante_sans_cible',
      'cout_sante_sans_finance',
      'cout_sante_non_visible_fiche_animal',
      'preuve_photo_url_absente',
      'preuve_photo_url_invalide',
      'sante_sans_trace',
    ],
    improvements: [
      'Afficher la preuve URL photo directement dans l’intervention.',
      'Lier chaque coût santé à la fiche animal ou lot.',
      'Créer automatiquement une charge Finance typée Santé.',
    ],
  },
  {
    id: 'DATA_MODE_INTERCONNECTION_CONTEXT',
    module: 'Global',
    severity: 'critique',
    title: 'Le mode données change l’interprétation des anomalies',
    rule: 'En données réelles vides, l’audit doit guider la première saisie. En données simulées, il doit exiger que les interconnexions soient démontrables.',
    verify: [
      'Mode données identifié',
      'Données réelles vides signalées comme état initial, pas bug',
      'Données simulées suffisantes pour tester ventes/finances/coûts',
      'Rapport séparant bug, donnée absente et simulation insuffisante',
    ],
    anomalies: [
      'mode_donnees_non_identifie',
      'donnees_reelles_vides_classees_bug',
      'simulation_insuffisante_non_signalee',
    ],
    improvements: [
      'Ajouter badge mode données dans chaque rapport.',
      'Afficher checklist première saisie en mode réel vide.',
      'Afficher scénarios obligatoires en mode simulé.',
    ],
  },
];

export default interconnectionAuditRules;
