export const moduleAuditChecklist = [
  {
    module: 'Accueil', priority: 'critique',
    open: ['Charger dashboard', 'Comparer données réelles/simulées', 'Cliquer alertes et raccourcis'],
    verify: ['CA total', 'Charges', 'Marge', 'Alertes', 'Tâches', 'Ventilation animaux/avicole/cultures', 'Zéros suspects'],
    compare: ['Ventes', 'Finances', 'Objectifs', 'Centre décisionnel'],
    anomalies: ['CA global différent des ventes', 'Marge sans charges métier', 'Alerte sans lien module', 'KPI impossible à comprendre'],
  },
  {
    module: 'Assistant ERP', priority: 'critique',
    open: ['Vérifier agent GitHub/Vercel', 'Lancer audit complet', 'Tester paquets', 'Appliquer paquet sécurisé'],
    verify: ['Statut agent', 'Code approbation', 'Rapport audit', 'Historique correction', 'Avant/après', 'Message Vercel honnête'],
    compare: ['Rapports', 'GitHub', 'Vercel', 'Tous modules audités'],
    anomalies: ['Score trop rassurant', 'Lot sans détail', 'Bouton correction sans paquet', 'Message de build non prouvé', 'Aucun rapport exploitable'],
  },
  {
    module: 'Centre décisionnel', priority: 'critique',
    open: ['Lire priorités', 'Déplier recommandations', 'Cliquer actions', 'Comparer avec modules sources'],
    verify: ['Top priorités', 'Recommandations non redondantes', 'Actions vers bon module', 'Décisions basées sur données réelles'],
    compare: ['Animaux', 'Avicole', 'Cultures', 'Stock', 'Finances', 'Objectifs', 'Alertes'],
    anomalies: ['Décision doublonnée', 'Décision sans donnée source', 'Action au mauvais endroit', 'Vente proposée déjà commandée'],
  },
  {
    module: 'Objectifs & Croissance', priority: 'critique',
    open: ['Comparer objectif/réalisé par activité', 'Vérifier croissance', 'Vérifier marges', 'Vérifier projections'],
    verify: ['CA animaux', 'CA avicole', 'CA cultures', 'Objectif', 'Réalisé', 'Écart', 'Marge', 'ROI simulé'],
    compare: ['Accueil', 'Ventes', 'Finances', 'Investissements', 'Centre décisionnel'],
    anomalies: ['Réalisé zéro malgré ventes', 'Objectif non lié au BP', 'CA activité non ventilé', 'Marge sans coût'],
  },
  {
    module: 'Animaux', priority: 'critique',
    open: ['Liste animaux', 'Fiche animal', 'Édition', 'Nouvelle pesée', 'Vente', 'Historique'],
    verify: ['Espèce', 'Date entrée', 'Ancienneté', 'Prix achat', 'Poids actuel', 'Poids cible', 'Pesée tous les 15 jours', 'Coût alimentation', 'Coût santé', 'Coût total', 'Prix vente', 'Marge', 'Statut vendu verrouillé'],
    compare: ['Santé', 'Alimentation', 'Ventes', 'Finances', 'Objectifs', 'Traçabilité', 'Documents'],
    anomalies: ['Animal vendu encore modifiable', 'Pesées espacées de plus de 15 jours', 'Coût santé absent', 'Marge incohérente', 'Vente sans commande', 'CA animaux à zéro'],
  },
  {
    module: 'Avicole', priority: 'critique',
    open: ['Liste lots', 'Fiche lot chair', 'Fiche pondeuses', 'Production', 'Vente partielle', 'Mortalité'],
    verify: ['Type lot', 'Âge', 'Effectif initial/actuel', 'Mortalité', 'Poids moyen', 'Coût poussins', 'Coût aliment', 'Coût santé', 'Production œufs', 'Prêt à vendre', 'Vente partielle', 'Marge'],
    compare: ['Stock', 'Santé', 'Ventes', 'Finances', 'Objectifs', 'Centre décisionnel'],
    anomalies: ['Poulets chair au-delà de 45 jours sans décision', 'Pondeuses sans production', 'Vente partielle non tracée', 'Coûts incomplets', 'CA avicole à zéro'],
  },
  {
    module: 'Cultures', priority: 'critique',
    open: ['Liste cultures', 'Fiche culture', 'Récolte', 'Stock issu récolte', 'Opportunité vente'],
    verify: ['Parcelle', 'Surface', 'Stade', 'Date semis', 'Coût semences', 'Engrais', 'Eau', 'Main-d’œuvre', 'Traitements', 'Récolté', 'Disponible', 'Pertes', 'Marge'],
    compare: ['Stock', 'Ventes', 'Finances', 'Objectifs', 'Traçabilité'],
    anomalies: ['Récolte disponible sans opportunité', 'Stock non alimenté', 'Culture vendue sans CA', 'Coût culture incomplet', 'Pertes non tracées'],
  },
  {
    module: 'Santé & Vaccins', priority: 'critique',
    open: ['Ajouter intervention', 'Changer type intervention', 'Uploader preuve', 'Créer coût'],
    verify: ['Formulaire adaptatif', 'Vaccination vaccin/dose/rappel/lot', 'Soin symptômes/diagnostic/traitement/durée', 'Déparasitage produit/dose/rappel', 'Visite véto compte rendu', 'Urgence prédéfinie', 'Impact ferme structuré', 'Coût vers finances', 'Preuve upload'],
    compare: ['Animaux', 'Avicole', 'Stock', 'Finances', 'Documents', 'Impact Business'],
    anomalies: ['Même formulaire pour tous types', 'Preuve en URL seulement', 'Impact libre non exploitable', 'Urgence non cadrée', 'Coût santé absent des finances'],
  },
  {
    module: 'Ventes', priority: 'critique',
    open: ['Opportunité', 'Commande', 'Paiement total/partiel', 'Facture émise/non émise', 'Livraison/récupération'],
    verify: ['Opportunité fermée après commande', 'Commande simple', 'Livré ou récupéré', 'Frais livraison si livré', 'Paiement commande', 'Reste à payer', 'Facture document automatique', 'Stock mis à jour'],
    compare: ['Clients', 'Finances', 'Documents', 'Stock', 'Objectifs', 'Traçabilité'],
    anomalies: ['Spinner sans fermeture formulaire', 'Commande créée mais opportunité ouverte', 'Paiement sans finance', 'Facture sans document', 'Trop de statuts facture'],
  },
  {
    module: 'Finances', priority: 'critique',
    open: ['Recettes', 'Charges', 'Filtres', 'Transaction issue vente/santé/stock/RH'],
    verify: ['Paiements ventes', 'Charges santé', 'Charges alimentation', 'Charges RH', 'Investissements', 'Marge par activité', 'Justificatifs'],
    compare: ['Ventes', 'Comptabilité', 'Santé', 'Stock', 'RH', 'Investissements'],
    anomalies: ['Paiement non visible', 'Charge métier absente', 'Marge trop élevée car coûts oubliés', 'Transaction sans source'],
  },
  {
    module: 'Comptabilité', priority: 'critique',
    open: ['Résultat', 'CA', 'Charges', 'Pièces liées'],
    verify: ['CA ventes', 'Charges exploitation', 'Résultat', 'Rapprochement paiements', 'Factures', 'Justificatifs'],
    compare: ['Finances', 'Ventes', 'Documents', 'Investissements'],
    anomalies: ['Résultat incohérent', 'Charges à zéro', 'Factures manquantes', 'Écart avec finances'],
  },
  {
    module: 'Investissements', priority: 'critique',
    open: ['BP Horizon Farm', 'Données simulées', 'Lignes investissement', 'Charges récurrentes', 'CA prévisionnel', 'ROI'],
    verify: ['Montants investis', 'Ancienneté par activité', 'Charges par module', 'CA prévisionnel', 'Sources financement', 'ROI', 'Simulation financeur'],
    compare: ['Objectifs', 'Accueil', 'Finances', 'Rapports', 'Animaux', 'Avicole', 'Cultures'],
    anomalies: ['BP incomplet', 'Pas de CA prévisionnel', 'Ancienneté non respectée', 'Charges santé/RH/exploitation absentes', 'ROI faux'],
  },
  {
    module: 'Impact & Valeur', priority: 'haute',
    open: ['Événements impact', 'Santé', 'Stock', 'Vente', 'Production'],
    verify: ['Type impact', 'Niveau', 'Montant estimé', 'Module source', 'Action recommandée'],
    compare: ['Santé', 'Finances', 'Centre décisionnel', 'Alertes'],
    anomalies: ['Champ libre inexploitable', 'Impact sans montant', 'Impact sans module source', 'Aucune décision associée'],
  },
  {
    module: 'Stock', priority: 'haute',
    open: ['Liste stock', 'Entrée', 'Sortie', 'Consommation', 'Seuil'],
    verify: ['Quantité', 'Unité', 'Valeur', 'Seuil critique', 'Source entrée', 'Sortie vente', 'Consommation alimentation'],
    compare: ['Avicole', 'Animaux', 'Cultures', 'Ventes', 'Finances', 'Alertes'],
    anomalies: ['Stock critique sans alerte', 'Quantité sans valeur', 'Vente sans sortie stock', 'Récolte non entrée en stock'],
  },
  {
    module: 'Clients', priority: 'haute',
    open: ['Fiche client', 'Historique commandes', 'Paiements', 'Créances'],
    verify: ['Commandes', 'Paiements', 'Reste à payer', 'Relances', 'Coordonnées'],
    compare: ['Ventes', 'Finances', 'Documents'],
    anomalies: ['Client avec commande absente', 'Créance incohérente', 'Paiement non lié', 'Relance absente'],
  },
  {
    module: 'Fournisseurs', priority: 'haute',
    open: ['Fiche fournisseur', 'Achats', 'Dettes', 'Documents', 'Tâches'],
    verify: ['Stock lié', 'Dettes', 'Factures', 'Charges finance', 'Performance fournisseur'],
    compare: ['Stock', 'Finances', 'Documents', 'Tâches'],
    anomalies: ['Dette sans finance', 'Achat sans stock', 'Facture fournisseur absente', 'Tâche non créée'],
  },
  {
    module: 'Traçabilité', priority: 'haute',
    open: ['Timeline', 'Filtres animal/lot/culture/commande', 'Détails événement'],
    verify: ['Vente', 'Paiement', 'Intervention santé', 'Récolte', 'Stock', 'Alerte', 'Correction audit'],
    compare: ['Tous modules sources'],
    anomalies: ['Commande sans trace', 'Paiement sans trace', 'Santé sans trace', 'Correction agent sans trace utile'],
  },
  {
    module: 'Alertes', priority: 'haute',
    open: ['Liste alertes', 'Traiter alerte', 'Créer tâche', 'Module source'],
    verify: ['Criticité', 'Action recommandée', 'Responsable', 'Statut', 'Lien module'],
    compare: ['Stock', 'Santé', 'Animaux', 'Avicole', 'Cultures', 'Finances', 'Tâches'],
    anomalies: ['Alerte sans action', 'Alerte sans source', 'Risque métier sans alerte', 'Alerte traitée sans trace'],
  },
  {
    module: 'Documents', priority: 'haute',
    open: ['Recherche', 'Factures', 'Ordonnances', 'Preuves santé', 'Rapports'],
    verify: ['Type document', 'Module lié', 'Fichier visible', 'Recherche', 'Export'],
    compare: ['Ventes', 'Santé', 'Finances', 'Rapports'],
    anomalies: ['Facture absente', 'Preuve introuvable', 'Document sans lien', 'Rapport non accessible'],
  },
  {
    module: 'Tâches', priority: 'haute',
    open: ['Liste tâches', 'Créer tâche', 'Terminer tâche', 'Priorité'],
    verify: ['Échéance', 'Responsable', 'Module lié', 'Statut', 'Traçabilité'],
    compare: ['Alertes', 'Centre décisionnel', 'Animaux', 'Santé', 'Stock'],
    anomalies: ['Risque sans tâche', 'Pesée retard sans tâche', 'Tâche terminée sans trace', 'Tâche sans responsable'],
  },
  {
    module: 'RH & Équipe', priority: 'moyenne',
    open: ['Équipe', 'Rôles', 'Charges', 'Affectations'],
    verify: ['Salaires', 'Charges RH', 'Rôles terrain', 'Tâches affectées'],
    compare: ['Finances', 'Tâches', 'Comptabilité'],
    anomalies: ['Charge RH absente', 'Tâche sans responsable', 'Rôle non clair'],
  },
  {
    module: 'Rapports', priority: 'haute',
    open: ['Rapport audit', 'Rapport financeur', 'Export', 'Avant/après'],
    verify: ['Résumé clair', 'Lots détectés', 'Corrections appliquées', 'KPI financeur', 'Export exploitable'],
    compare: ['Assistant ERP', 'Finances', 'Investissements', 'Documents'],
    anomalies: ['Rapport vide', 'Pas d’avant/après', 'Score sans justification', 'Rapport non présentable'],
  },
  {
    module: 'Équipements', priority: 'moyenne',
    open: ['Liste équipements', 'Maintenance', 'Panne', 'Coût'],
    verify: ['Statut', 'Maintenance', 'Tâche créée', 'Coût finance', 'Document'],
    compare: ['Tâches', 'Finances', 'Documents'],
    anomalies: ['Panne sans tâche', 'Réparation sans coût', 'Maintenance non tracée'],
  },
  {
    module: 'Smart Farm', priority: 'moyenne',
    open: ['Capteurs', 'Caméras', 'Météo', 'Alertes'],
    verify: ['Statut capteur', 'Dernière donnée', 'Règles seuils', 'Alerte automatique'],
    compare: ['Alertes', 'Tâches', 'Centre décisionnel'],
    anomalies: ['Capteur muet sans alerte', 'Seuil dépassé sans action', 'Donnée non datée'],
  },
  {
    module: 'Activité & Sync ERP', priority: 'haute',
    open: ['Journaux', 'Actions offline', 'Erreurs sync', 'Relancer sync'],
    verify: ['Erreurs', 'Actions en attente', 'Dernière sync', 'Reprise', 'Audit logs'],
    compare: ['Tous modules modifiés'],
    anomalies: ['Erreur silencieuse', 'Donnée non synchronisée', 'Action perdue', 'Aucun journal'],
  },
  {
    module: 'Gestion du système', priority: 'haute',
    open: ['Utilisateurs', 'Rôles', 'Droits', 'Compte testeur'],
    verify: ['Accès testeur', 'Droits module', 'Assistant ERP accessible', 'Actions sensibles protégées'],
    compare: ['Assistant ERP', 'Audit logs'],
    anomalies: ['Testeur sans accès', 'Droits trop larges', 'Agent sans code', 'Module sensible non protégé'],
  },
];

export const auditChecklistByModule = Object.fromEntries(moduleAuditChecklist.map((item) => [item.module, item]));
