// Horizon Farm ERP — carte officielle des événements métier et interconnexions.
// Objectif : une saisie terrain déclenche automatiquement les impacts stock, finance, production, traçabilité, tâches et reporting.

export const BUSINESS_EVENT_WORKFLOWS = Object.freeze([
  {
    id: 'feed_reception',
    label: 'Réception d’aliment',
    sourceModule: 'achats_stock',
    sourceTables: ['stock', 'fournisseurs', 'finances', 'documents'],
    impactedModules: ['achats_stock', 'finance_pilotage', 'elevage', 'documents_rapports', 'centre_ia', 'agri_feeds'],
    requiredFields: ['date', 'supplier_id', 'product_id', 'quantity', 'unit_cost', 'payment_status'],
    automaticEffects: [
      'Créer ou mettre à jour le stock aliment',
      'Créer la dépense ou la dette fournisseur',
      'Historiser le prix fournisseur',
      'Attacher facture, bon ou reçu si disponible',
      'Mettre à jour la référence coût aliment pour élevage et AGRI FEEDS',
    ],
    metricsImpacted: ['stock_aliment', 'dette_fournisseur', 'cout_aliment_reference', 'tresorerie'],
    coherenceRules: ['Achat aliment sans entrée stock', 'Dépense fournisseur sans fournisseur', 'Prix unitaire absent'],
    nextSteps: ['Planifier distribution', 'Surveiller seuil stock', 'Mettre à jour coût lot lors de la distribution'],
  },
  {
    id: 'feed_distribution',
    label: 'Distribution d’aliment',
    sourceModule: 'elevage',
    sourceTables: ['alimentation_logs', 'stock', 'avicole', 'animaux'],
    impactedModules: ['elevage', 'achats_stock', 'finance_pilotage', 'centre_ia', 'documents_rapports'],
    requiredFields: ['date', 'target_type', 'target_id', 'quantity', 'feed_stock_id'],
    automaticEffects: [
      'Diminuer le stock aliment',
      'Rattacher le coût au lot, bâtiment ou animal',
      'Recalculer coût alimentaire et coût de revient',
      'Comparer consommation réelle et courbe attendue',
    ],
    metricsImpacted: ['cout_lot', 'cout_bovin', 'cout_plateau_oeufs', 'indice_consommation', 'marge_future'],
    coherenceRules: ['Distribution sans stock suffisant', 'Distribution sans lot ou animal cible', 'Consommation anormale'],
    nextSteps: ['Créer alerte si écart consommation', 'Mettre à jour marge prévisionnelle'],
  },
  {
    id: 'broiler_lot_start',
    label: 'Mise en place d’un lot de poulets de chair',
    sourceModule: 'elevage',
    sourceTables: ['avicole', 'stock', 'finances', 'taches'],
    impactedModules: ['elevage', 'achats_stock', 'finance_pilotage', 'activite_suivi', 'commercial', 'objectifs_croissance'],
    requiredFields: ['start_date', 'initial_count', 'supplier_id', 'unit_cost', 'building_id'],
    automaticEffects: [
      'Créer la fiche lot',
      'Créer coût initial du lot',
      'Planifier vaccins, pesées et date prévisionnelle de vente',
      'Projeter besoin aliment et cash du cycle',
    ],
    metricsImpacted: ['effectif_initial', 'cout_initial_lot', 'besoin_aliment_cycle', 'date_vente_prevue', 'marge_prevue'],
    coherenceRules: ['Lot sans effectif initial', 'Lot sans bâtiment', 'Lot sans coût initial'],
    nextSteps: ['Programmer vaccination', 'Programmer pesée', 'Suivre consommation aliment'],
  },
  {
    id: 'mortality_record',
    label: 'Mortalité dans un lot',
    sourceModule: 'elevage',
    sourceTables: ['avicole', 'sante', 'business_events', 'taches'],
    impactedModules: ['elevage', 'finance_pilotage', 'activite_suivi', 'centre_ia', 'documents_rapports'],
    requiredFields: ['date', 'lot_id', 'quantity', 'cause_or_observation'],
    automaticEffects: [
      'Réduire l’effectif restant',
      'Recalculer taux de mortalité',
      'Réviser coût par sujet survivant et marge attendue',
      'Créer tâche sanitaire si seuil dépassé',
    ],
    metricsImpacted: ['effectif_restant', 'taux_mortalite', 'cout_sujet_survivant', 'perte_estimee'],
    coherenceRules: ['Mortalité supérieure à effectif', 'Mortalité sans cause', 'Seuil sanitaire dépassé sans tâche'],
    nextSteps: ['Contrôle eau/aliment', 'Observation vétérinaire si répétition', 'Documenter décision'],
  },
  {
    id: 'health_treatment',
    label: 'Vaccination ou traitement sanitaire',
    sourceModule: 'elevage',
    sourceTables: ['sante', 'stock', 'finances', 'taches', 'documents'],
    impactedModules: ['elevage', 'achats_stock', 'finance_pilotage', 'activite_suivi', 'documents_rapports'],
    requiredFields: ['date', 'target_type', 'target_id', 'product_id', 'quantity_used', 'responsible_person'],
    automaticEffects: [
      'Créer événement sanitaire',
      'Diminuer stock vétérinaire',
      'Rattacher coût sanitaire au lot ou animal',
      'Clôturer tâche prévue si applicable',
    ],
    metricsImpacted: ['cout_sanitaire', 'historique_sante', 'stock_veterinaire', 'taches_cloturees'],
    coherenceRules: ['Traitement sans stock produit', 'Vaccination prévue non clôturée', 'Coût sanitaire non rattaché'],
    nextSteps: ['Programmer rappel', 'Surveiller réaction', 'Joindre document si nécessaire'],
  },
  {
    id: 'biosecurity_cleaning',
    label: 'Nettoyage box / bâtiment et collecte biosécurité',
    sourceModule: 'elevage',
    sourceTables: ['business_events', 'stock', 'taches', 'finances', 'cultures'],
    impactedModules: ['elevage', 'achats_stock', 'cultures', 'finance_pilotage', 'activite_suivi', 'centre_ia', 'documents_rapports'],
    requiredFields: ['date', 'building_id', 'cleaning_type', 'responsible_person', 'bags_collected', 'estimated_weight_per_bag', 'organic_material_type', 'sanitary_status', 'destination', 'next_step'],
    automaticEffects: [
      'Clôturer la tâche de nettoyage',
      'Créer un stock de matière organique collectée',
      'Calculer poids total collecté',
      'Démarrer vide sanitaire ou tâche de désinfection',
      'Bloquer la valorisation agricole si statut sanitaire suspect',
      'Créer prochaine étape : compostage, stockage, parcelle ou évacuation',
    ],
    metricsImpacted: ['sacs_fientes_litiere', 'kg_matiere_organique', 'cout_biosecurite', 'stock_organique', 'preuve_circularite'],
    coherenceRules: ['Nettoyage sans nombre de sacs collectés', 'Matière organique sans destination', 'Statut suspect envoyé en culture', 'Bâtiment remis en service sans vide sanitaire'],
    nextSteps: ['Désinfection', 'Vide sanitaire', 'Compostage', 'Transfert parcelle', 'Contrôle sanitaire'],
  },
  {
    id: 'egg_production',
    label: 'Ponte du jour',
    sourceModule: 'elevage',
    sourceTables: ['production_oeufs_logs', 'stock', 'avicole'],
    impactedModules: ['elevage', 'achats_stock', 'commercial', 'dashboard', 'centre_ia', 'documents_rapports'],
    requiredFields: ['date', 'building_id', 'trays_count'],
    automaticEffects: [
      'Créer production du jour',
      'Augmenter stock œufs',
      'Recalculer taux de ponte',
      'Rendre quantité disponible pour la vente',
    ],
    metricsImpacted: ['plateaux_jour', 'stock_oeufs', 'taux_ponte', 'marge_plateau'],
    coherenceRules: ['Ponte sans stock œufs', 'Taux de ponte anormal', 'Bâtiment absent'],
    nextSteps: ['Préparer livraison', 'Surveiller baisse ponte', 'Calculer marge par plateau'],
  },
  {
    id: 'egg_sale',
    label: 'Vente d’œufs',
    sourceModule: 'commercial',
    sourceTables: ['sales_orders', 'sales_order_items', 'stock', 'payments', 'clients', 'invoices'],
    impactedModules: ['commercial', 'achats_stock', 'finance_pilotage', 'documents_rapports', 'elevage', 'centre_ia'],
    requiredFields: ['date', 'client_id', 'quantity_trays', 'unit_price', 'stock_id', 'payment_status'],
    automaticEffects: [
      'Créer vente et ligne de vente',
      'Diminuer stock œufs',
      'Créer paiement ou créance',
      'Mettre à jour historique client',
      'Préparer facture et bon de livraison',
    ],
    metricsImpacted: ['ca_oeufs', 'cash_encaisse', 'creance_client', 'stock_oeufs', 'marge_plateau'],
    coherenceRules: ['Vente œufs sans stock', 'Vente sans facture', 'Vente non livrée', 'Créance non relancée'],
    nextSteps: ['Livraison', 'Encaissement', 'Relance client', 'Rapport mensuel'],
  },
  {
    id: 'broiler_sale',
    label: 'Vente de poulets de chair',
    sourceModule: 'commercial',
    sourceTables: ['sales_orders', 'sales_order_items', 'avicole', 'payments', 'stock'],
    impactedModules: ['commercial', 'elevage', 'finance_pilotage', 'documents_rapports', 'centre_ia'],
    requiredFields: ['date', 'client_id', 'lot_id', 'quantity', 'weight_or_unit_price', 'payment_status'],
    automaticEffects: [
      'Créer vente liée au lot',
      'Mettre à jour effectif vendu ou statut lot',
      'Créer paiement ou créance',
      'Calculer marge réelle du lot',
    ],
    metricsImpacted: ['ca_chair', 'marge_lot', 'cout_aliment_reel', 'ecart_prevu_reel'],
    coherenceRules: ['Lot vendu sans lot lié', 'Lot vendu sans marge', 'Vente supérieure à effectif disponible'],
    nextSteps: ['Clôturer lot', 'Archiver bilan lot', 'Nettoyage biosécurité'],
  },
  {
    id: 'bovine_weighing',
    label: 'Pesée bovine',
    sourceModule: 'elevage',
    sourceTables: ['animaux', 'business_events', 'alimentation_logs'],
    impactedModules: ['elevage', 'finance_pilotage', 'centre_ia', 'objectifs_croissance'],
    requiredFields: ['date', 'animal_id', 'weight_kg'],
    automaticEffects: [
      'Mettre à jour poids',
      'Calculer gain moyen',
      'Calculer coût/kg gagné',
      'Réviser date de sortie estimée',
    ],
    metricsImpacted: ['poids_bovin', 'gmq', 'cout_kg_gain', 'date_sortie_prevue'],
    coherenceRules: ['Bovin sans pesée récente', 'Gain de poids négatif non expliqué', 'Poids absent'],
    nextSteps: ['Adapter ration', 'Préparer vente', 'Suivre rentabilité par tête'],
  },
  {
    id: 'bovine_sale',
    label: 'Vente bovine',
    sourceModule: 'commercial',
    sourceTables: ['sales_orders', 'sales_order_items', 'animaux', 'payments'],
    impactedModules: ['commercial', 'elevage', 'finance_pilotage', 'documents_rapports', 'centre_ia'],
    requiredFields: ['date', 'client_id', 'animal_id', 'sale_price', 'payment_status'],
    automaticEffects: [
      'Créer vente liée à l’animal',
      'Sortir animal de l’actif',
      'Créer paiement ou créance',
      'Calculer marge par tête',
    ],
    metricsImpacted: ['ca_bovin', 'marge_bovin', 'rotation_embouche', 'cash_encaisse'],
    coherenceRules: ['Animal vendu encore actif', 'Vente bovine sans animal lié', 'Marge bovine absente'],
    nextSteps: ['Archiver fiche animal', 'Rapport embouche', 'Décider réinvestissement'],
  },
  {
    id: 'crop_campaign_start',
    label: 'Semis ou lancement d’une culture',
    sourceModule: 'cultures',
    sourceTables: ['cultures', 'stock', 'finances', 'taches'],
    impactedModules: ['cultures', 'achats_stock', 'finance_pilotage', 'activite_suivi', 'objectifs_croissance'],
    requiredFields: ['date', 'parcel_id', 'crop_type', 'surface', 'planned_harvest_date'],
    automaticEffects: [
      'Créer campagne de culture',
      'Rattacher coûts intrants initiaux',
      'Planifier irrigation et suivi',
      'Préparer prévision de rendement',
    ],
    metricsImpacted: ['surface_cultivee', 'cout_parcelle', 'rendement_attendu', 'marge_prevue_culture'],
    coherenceRules: ['Culture sans parcelle', 'Culture sans date', 'Campagne sans coût initial'],
    nextSteps: ['Irrigation', 'Fertilisation', 'Suivi croissance', 'Récolte'],
  },
  {
    id: 'irrigation_event',
    label: 'Irrigation',
    sourceModule: 'cultures',
    sourceTables: ['cultures', 'business_events', 'sensor_devices'],
    impactedModules: ['cultures', 'smartfarm', 'finance_pilotage', 'centre_ia', 'equipements'],
    requiredFields: ['date', 'parcel_id', 'water_volume_or_duration'],
    automaticEffects: [
      'Enregistrer consommation eau',
      'Rattacher coût eau ou énergie à la parcelle',
      'Comparer consommation attendue et réelle',
      'Créer alerte fuite si anomalie',
    ],
    metricsImpacted: ['eau_parcelle', 'cout_eau', 'rendement_eau', 'risque_fuite'],
    coherenceRules: ['Irrigation sans culture active', 'Consommation inhabituelle', 'Capteur muet'],
    nextSteps: ['Contrôle goutte-à-goutte', 'Réglage irrigation', 'Maintenance pompe si besoin'],
  },
  {
    id: 'organic_transfer',
    label: 'Transfert fientes / fumier / compost vers parcelle',
    sourceModule: 'cultures',
    sourceTables: ['business_events', 'stock', 'cultures'],
    impactedModules: ['cultures', 'elevage', 'achats_stock', 'finance_pilotage', 'documents_rapports', 'centre_ia'],
    requiredFields: ['date', 'origin_id', 'destination_parcel_id', 'organic_material_type', 'quantity_kg', 'sanitary_status'],
    automaticEffects: [
      'Sortir stock matière organique',
      'Rattacher fertilisation à la parcelle',
      'Estimer économie d’intrants',
      'Alimenter indicateur économie circulaire',
    ],
    metricsImpacted: ['kg_matiere_valorisee', 'economie_intrants', 'cout_parcelle', 'preuve_circularite'],
    coherenceRules: ['Transfert sans origine', 'Transfert sans destination', 'Statut sanitaire suspect valorisé'],
    nextSteps: ['Suivi parcelle', 'Rapport vert', 'Contrôle sanitaire si nécessaire'],
  },
  {
    id: 'crop_harvest',
    label: 'Récolte maraîchère',
    sourceModule: 'cultures',
    sourceTables: ['cultures', 'stock', 'business_events'],
    impactedModules: ['cultures', 'achats_stock', 'commercial', 'finance_pilotage', 'documents_rapports'],
    requiredFields: ['date', 'parcel_id', 'crop_type', 'quantity_kg'],
    automaticEffects: [
      'Créer stock récolte',
      'Calculer rendement parcelle',
      'Mettre à jour coût/kg',
      'Rendre quantité disponible pour la vente',
    ],
    metricsImpacted: ['stock_recolte', 'rendement_m2', 'cout_kg_culture', 'marge_prevue_culture'],
    coherenceRules: ['Récolte sans culture active', 'Rendement incohérent', 'Récolte sans stock'],
    nextSteps: ['Vente maraîchère', 'Suivi pertes', 'Rapport rendement'],
  },
  {
    id: 'crop_sale',
    label: 'Vente maraîchère',
    sourceModule: 'commercial',
    sourceTables: ['sales_orders', 'sales_order_items', 'stock', 'payments', 'cultures'],
    impactedModules: ['commercial', 'cultures', 'achats_stock', 'finance_pilotage', 'documents_rapports', 'centre_ia'],
    requiredFields: ['date', 'client_id', 'parcel_or_stock_id', 'quantity_kg', 'unit_price', 'payment_status'],
    automaticEffects: [
      'Créer vente liée à la récolte',
      'Diminuer stock récolte',
      'Créer paiement ou créance',
      'Calculer marge parcelle',
    ],
    metricsImpacted: ['ca_culture', 'marge_parcelle', 'stock_recolte', 'creance_client'],
    coherenceRules: ['Vente culture sans stock', 'Vente culture sans parcelle', 'Marge parcelle absente'],
    nextSteps: ['Livraison', 'Encaissement', 'Prévision prochain cycle'],
  },
  {
    id: 'client_payment',
    label: 'Paiement client',
    sourceModule: 'commercial',
    sourceTables: ['payments', 'sales_orders', 'clients', 'finances'],
    impactedModules: ['commercial', 'finance_pilotage', 'documents_rapports', 'centre_ia', 'dashboard'],
    requiredFields: ['date', 'client_id', 'sales_order_id', 'amount', 'payment_method'],
    automaticEffects: [
      'Créer paiement',
      'Diminuer reste à payer',
      'Mettre à jour trésorerie',
      'Mettre à jour statut client',
    ],
    metricsImpacted: ['cash_encaisse', 'creance_client', 'tresorerie', 'retard_paiement'],
    coherenceRules: ['Paiement sans vente liée', 'Paiement supérieur au reste dû', 'Double comptage CA/cash'],
    nextSteps: ['Reçu', 'Relance si solde restant', 'Rapport encaissements'],
  },
  {
    id: 'supplier_payment',
    label: 'Dette fournisseur / paiement fournisseur',
    sourceModule: 'achats_stock',
    sourceTables: ['finances', 'fournisseurs', 'stock', 'documents'],
    impactedModules: ['achats_stock', 'finance_pilotage', 'documents_rapports', 'centre_ia'],
    requiredFields: ['date', 'supplier_id', 'amount', 'purchase_or_stock_id', 'payment_status'],
    automaticEffects: [
      'Créer dépense ou réduire dette',
      'Mettre à jour historique fournisseur',
      'Rattacher justificatif',
      'Réviser trésorerie disponible',
    ],
    metricsImpacted: ['dette_fournisseur', 'cash_sortant', 'cout_achat', 'tresorerie'],
    coherenceRules: ['Dépense sans fournisseur', 'Dette payée sans dette source', 'Dépense sans justificatif'],
    nextSteps: ['Archiver reçu', 'Comparer prix fournisseur', 'Mettre à jour échéancier'],
  },
  {
    id: 'equipment_purchase',
    label: 'Achat d’équipement',
    sourceModule: 'equipements',
    sourceTables: ['equipements', 'finances', 'investissements', 'documents'],
    impactedModules: ['equipements', 'finance_pilotage', 'documents_rapports', 'objectifs_croissance', 'smartfarm'],
    requiredFields: ['date', 'equipment_type', 'amount', 'supplier_id', 'funding_source'],
    automaticEffects: [
      'Créer fiche équipement',
      'Créer dépense investissement',
      'Rattacher financement si applicable',
      'Planifier maintenance initiale',
    ],
    metricsImpacted: ['investissements', 'actifs', 'amortissement', 'cout_fixe'],
    coherenceRules: ['Dépense équipement sans fiche équipement', 'Équipement critique sans plan maintenance'],
    nextSteps: ['Maintenance préventive', 'Suivi garantie', 'Impact sur capacité production'],
  },
  {
    id: 'equipment_maintenance',
    label: 'Maintenance équipement',
    sourceModule: 'equipements',
    sourceTables: ['equipements', 'taches', 'finances', 'business_events'],
    impactedModules: ['equipements', 'finance_pilotage', 'activite_suivi', 'smartfarm', 'centre_ia'],
    requiredFields: ['date', 'equipment_id', 'maintenance_type', 'status', 'cost'],
    automaticEffects: [
      'Mettre à jour statut équipement',
      'Créer coût maintenance',
      'Clôturer ou créer tâche',
      'Planifier prochaine maintenance',
    ],
    metricsImpacted: ['cout_maintenance', 'disponibilite_equipement', 'risque_operationnel'],
    coherenceRules: ['Équipement critique en panne sans tâche', 'Maintenance sans coût ni observation'],
    nextSteps: ['Contrôle réparation', 'Prévenir panne récurrente', 'Ajuster budget'],
  },
  {
    id: 'task_lifecycle',
    label: 'Tâche opérationnelle',
    sourceModule: 'activite_suivi',
    sourceTables: ['taches', 'alertes_center', 'business_events'],
    impactedModules: ['dashboard', 'activite_suivi', 'centre_ia', 'documents_rapports'],
    requiredFields: ['date', 'task_type', 'responsible_person', 'status', 'linked_entity'],
    automaticEffects: [
      'Afficher priorité sur tableau de bord',
      'Relier tâche à alerte ou événement',
      'Archiver résultat une fois clôturée',
    ],
    metricsImpacted: ['taches_ouvertes', 'retards', 'actions_cloturees', 'discipline_operationnelle'],
    coherenceRules: ['Alerte critique sans tâche', 'Tâche clôturée sans résultat', 'Tâche en retard non escaladée'],
    nextSteps: ['Relance responsable', 'Clôture documentée', 'Rapport actions'],
  },
  {
    id: 'support_document',
    label: 'Document justificatif',
    sourceModule: 'documents_rapports',
    sourceTables: ['documents', 'finances', 'sales_orders', 'stock', 'business_events'],
    impactedModules: ['documents_rapports', 'finance_pilotage', 'commercial', 'achats_stock', 'centre_ia', 'investisseurs_forums'],
    requiredFields: ['date', 'document_type', 'linked_entity_type', 'linked_entity_id'],
    automaticEffects: [
      'Rattacher document à opération source',
      'Augmenter niveau de preuve',
      'Alimenter rapport financeur',
    ],
    metricsImpacted: ['taux_justificatifs', 'fiabilite_rapport', 'preuves_financeur'],
    coherenceRules: ['Dépense importante sans justificatif', 'Vente facturée sans document', 'Document non rattaché'],
    nextSteps: ['Validation document', 'Archivage', 'Export rapport'],
  },
  {
    id: 'monthly_financier_report',
    label: 'Rapport financeur mensuel',
    sourceModule: 'documents_rapports',
    sourceTables: ['rapports', 'finances', 'sales_orders', 'payments', 'stock', 'avicole', 'cultures', 'documents', 'business_events'],
    impactedModules: ['documents_rapports', 'finance_pilotage', 'investisseurs_forums', 'objectifs_croissance', 'dashboard'],
    requiredFields: ['period', 'generated_by', 'data_cutoff_date'],
    automaticEffects: [
      'Assembler activité par filière',
      'Comparer réel et prévisionnel',
      'Lister écarts expliqués',
      'Lister alertes traitées et décisions',
      'Créer trace audit du rapport',
    ],
    metricsImpacted: ['ca', 'cash', 'marges', 'ecarts_budget', 'fonds_utilises', 'preuves'],
    coherenceRules: ['Rapport avec données manquantes', 'Chiffres contradictoires', 'Écart non expliqué'],
    nextSteps: ['Envoyer financeur', 'Préparer actions du mois suivant', 'Archiver version'],
  },
  {
    id: 'funding_usage',
    label: 'Suivi du financement',
    sourceModule: 'finance_pilotage',
    sourceTables: ['finances', 'investissements', 'business_plans', 'documents', 'rapports'],
    impactedModules: ['finance_pilotage', 'objectifs_croissance', 'documents_rapports', 'investisseurs_forums', 'dashboard'],
    requiredFields: ['date', 'funding_source', 'amount', 'usage_category', 'linked_document_id'],
    automaticEffects: [
      'Rattacher dépense à une ligne de financement',
      'Mettre à jour solde disponible',
      'Mettre à jour rapport financeur',
      'Vérifier justificatif',
    ],
    metricsImpacted: ['fonds_utilises', 'fonds_restants', 'tresorerie', 'ecart_budget'],
    coherenceRules: ['Dépense financement sans catégorie', 'Financement utilisé sans justificatif', 'Solde négatif'],
    nextSteps: ['Justifier dépense', 'Réviser budget', 'Préparer remboursement'],
  },
  {
    id: 'growth_objective',
    label: 'Objectif de croissance',
    sourceModule: 'objectifs_croissance',
    sourceTables: ['business_plans', 'finances', 'stock', 'avicole', 'animaux', 'cultures', 'sales_orders'],
    impactedModules: ['objectifs_croissance', 'finance_pilotage', 'elevage', 'cultures', 'commercial', 'achats_stock', 'centre_ia'],
    requiredFields: ['scenario', 'target_date', 'target_capacity', 'cash_required'],
    automaticEffects: [
      'Simuler besoin aliment, cash, espace, main-d’œuvre',
      'Comparer capacité réelle et cible',
      'Créer risques et conditions de lancement',
    ],
    metricsImpacted: ['besoin_financement', 'seuil_rentabilite', 'capacite_remboursement', 'risque_croissance'],
    coherenceRules: ['Croissance sans cash suffisant', 'Croissance sans capacité stock', 'Croissance sans débouché commercial'],
    nextSteps: ['Valider ou reporter', 'Préparer achats', 'Informer financeur'],
  },
  {
    id: 'smartfarm_signal',
    label: 'Signal Smart Farm / capteur',
    sourceModule: 'smartfarm',
    sourceTables: ['sensor_devices', 'camera_devices', 'business_events', 'alertes_center'],
    impactedModules: ['smartfarm', 'cultures', 'elevage', 'equipements', 'activite_suivi', 'centre_ia', 'documents_rapports'],
    requiredFields: ['timestamp', 'device_id', 'signal_type', 'value', 'status'],
    automaticEffects: [
      'Créer événement technique',
      'Créer alerte si valeur anormale',
      'Créer tâche maintenance si capteur muet ou équipement critique',
      'Rattacher impact à culture ou élevage si possible',
    ],
    metricsImpacted: ['eau', 'temperature', 'humidite', 'energie', 'risque_panne'],
    coherenceRules: ['Capteur muet', 'Valeur anormale sans tâche', 'Équipement critique sans suivi'],
    nextSteps: ['Contrôle terrain', 'Maintenance', 'Ajustement irrigation ou ventilation'],
  },
]);

export const BUSINESS_EVENT_IDS = BUSINESS_EVENT_WORKFLOWS.map((event) => event.id);

export const BUSINESS_EVENT_ALIASES = Object.freeze({
  supplier_debt_payment: 'supplier_payment',
  operational_task: 'task_lifecycle',
  supporting_document: 'support_document',
  monthly_funder_report: 'monthly_financier_report',
  funding_tracking: 'funding_usage',
  smart_farm_signal: 'smartfarm_signal',
});

export const BUSINESS_EVENT_INTERCONNECTIONS = Object.freeze(
  Object.fromEntries(BUSINESS_EVENT_WORKFLOWS.map((event) => [event.id, event.impactedModules])),
);

export const MODULE_INTERCONNECTIONS = Object.freeze(
  BUSINESS_EVENT_WORKFLOWS.reduce((acc, event) => {
    event.impactedModules.forEach((moduleId) => {
      if (!acc[moduleId]) acc[moduleId] = new Set();
      event.impactedModules.filter((id) => id !== moduleId).forEach((id) => acc[moduleId].add(id));
    });
    return acc;
  }, {}),
);

export const MODULE_INTERCONNECTIONS_LIST = Object.freeze(
  Object.fromEntries(Object.entries(MODULE_INTERCONNECTIONS).map(([moduleId, modules]) => [moduleId, [...modules].sort()])),
);

export const BUSINESS_EVENT_REFRESH_CLUSTERS = Object.freeze(
  Object.fromEntries(BUSINESS_EVENT_WORKFLOWS.map((event) => [
    event.id,
    [...new Set([...event.sourceTables, 'business_events', 'alertes_center', 'taches', 'audit_logs'])],
  ])),
);

export function getBusinessEventWorkflow(eventId) {
  const resolvedId = BUSINESS_EVENT_ALIASES[eventId] || eventId;
  return BUSINESS_EVENT_WORKFLOWS.find((event) => event.id === resolvedId) || null;
}

export function workflowsForModule(moduleId) {
  return BUSINESS_EVENT_WORKFLOWS.filter((event) => (
    event.sourceModule === moduleId || event.impactedModules.includes(moduleId)
  ));
}

export function requiredFieldsForEvent(eventId) {
  return getBusinessEventWorkflow(eventId)?.requiredFields || [];
}
