/**
 * Parc de capteurs SIMULÉ (Smart Farm).
 *
 * Reprend les 86 équipements « intégration directe » du catalogue Alibaba pour
 * montrer, AVANT achat, leur apport concret sur la ferme : ce qu'ils mesurent,
 * l'état simulé, et l'alerte / action qu'ils déclenchent. Au branchement réel,
 * ces valeurs simulées seront remplacées par les vrais relevés (même schéma) —
 * voir src/services/smartFarmAlertEngine.js.
 */
export const SMARTFARM_SIMULATED_FLEET = Object.freeze([
  {"id": "SIM-1-00", "name": "Collier GPS 4G anti-arrachement", "categorie": "1. Sécurité, vol et identification du bétail", "zone": "Ferme & parc", "tech": "4G", "priorite": "HAUTE", "type": "localisation", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Localise et identifie chaque animal : anti-vol, sortie de zone, traçabilité.", "action": "Vérifier la position et l’identité de l’animal", "alibaba": "4G livestock GPS tracker anti tamper geofence API"},
  {"id": "SIM-1-01", "name": "Collier GPS solaire pour bovins", "categorie": "1. Sécurité, vol et identification du bétail", "zone": "Ferme & parc", "tech": "4G", "priorite": "MOYENNE", "type": "localisation", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Localise et identifie chaque animal : anti-vol, sortie de zone, traçabilité.", "action": "Vérifier la position et l’identité de l’animal", "alibaba": "solar powered cattle GPS tracker 4G API"},
  {"id": "SIM-1-02", "name": "Caméra solaire 4G", "categorie": "1. Sécurité, vol et identification du bétail", "zone": "Ferme & parc", "tech": "4G", "priorite": "HAUTE", "type": "camera", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "alerte", "gravite": "urgence", "apport": "Surveille la ferme et détecte les intrusions, jour comme nuit.", "action": "Ouvrir le flux et vérifier la zone", "alibaba": "4G solar security camera farm ONVIF"},
  {"id": "SIM-1-03", "name": "Caméra thermique", "categorie": "1. Sécurité, vol et identification du bétail", "zone": "Ferme & parc", "tech": "CAM", "priorite": "MOYENNE", "type": "camera", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Surveille la ferme et détecte les intrusions, jour comme nuit.", "action": "Ouvrir le flux et vérifier la zone", "alibaba": "thermal imaging camera livestock ONVIF"},
  {"id": "SIM-1-04", "name": "Collier d’activité bovine", "categorie": "1. Sécurité, vol et identification du bétail", "zone": "Ferme & parc", "tech": "API", "priorite": "À ÉVALUER", "type": "localisation", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Localise et identifie chaque animal : anti-vol, sortie de zone, traçabilité.", "action": "Vérifier la position et l’identité de l’animal", "alibaba": "cow activity monitoring collar API"},
  {"id": "SIM-1-05", "name": "Collier de rumination", "categorie": "1. Sécurité, vol et identification du bétail", "zone": "Ferme & parc", "tech": "API", "priorite": "À ÉVALUER", "type": "localisation", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "hors_ligne", "gravite": null, "apport": "Localise et identifie chaque animal : anti-vol, sortie de zone, traçabilité.", "action": "Vérifier la position et l’identité de l’animal", "alibaba": "cow rumination monitoring collar API"},
  {"id": "SIM-2-06", "name": "Balance électronique pour bovins", "categorie": "2. Pesée, reproduction et santé animale", "zone": "Élevage", "tech": "MODBUS", "priorite": "HAUTE", "type": "pesee", "unite": "kg", "valeur": 0, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la croissance / la production sans manipulation.", "action": "Consulter la courbe de poids", "alibaba": "cattle weighing scale RS485 Bluetooth"},
  {"id": "SIM-2-07", "name": "Indicateur de pesée RFID", "categorie": "2. Pesée, reproduction et santé animale", "zone": "Élevage", "tech": "AUTRE", "priorite": "MOYENNE", "type": "pesee", "unite": "kg", "valeur": 0, "seuil": 0, "sens": "", "etat": "alerte", "gravite": "warning", "apport": "Suit la croissance / la production sans manipulation.", "action": "Consulter la courbe de poids", "alibaba": "livestock weighing indicator RFID RS232"},
  {"id": "SIM-2-08", "name": "Analyseur de lait portable", "categorie": "2. Pesée, reproduction et santé animale", "zone": "Élevage", "tech": "AUTRE", "priorite": "À ÉVALUER", "type": "analyse", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Contrôle la qualité du lait.", "action": "Vérifier l’échantillon", "alibaba": "portable milk analyzer ultrasonic RS232"},
  {"id": "SIM-3-09", "name": "Capteur température-humidité", "categorie": "3. Aviculture : climat et environnement", "zone": "Poulailler", "tech": "MODBUS", "priorite": "HAUTE", "type": "temperature", "unite": "°C", "valeur": 28, "seuil": 33, "sens": "high", "etat": "ras", "gravite": null, "apport": "Évite le coup de chaleur : mortalité et chute de ponte.", "action": "Ventiler, brumiser, vérifier l’eau", "alibaba": "poultry house temperature humidity sensor RS485 Modbus"},
  {"id": "SIM-3-10", "name": "Capteur température-humidité 4G", "categorie": "3. Aviculture : climat et environnement", "zone": "Poulailler", "tech": "4G", "priorite": "MOYENNE", "type": "temperature", "unite": "°C", "valeur": 28, "seuil": 33, "sens": "high", "etat": "ras", "gravite": null, "apport": "Évite le coup de chaleur : mortalité et chute de ponte.", "action": "Ventiler, brumiser, vérifier l’eau", "alibaba": "4G temperature humidity sensor poultry farm API"},
  {"id": "SIM-3-11", "name": "Capteur de CO2", "categorie": "3. Aviculture : climat et environnement", "zone": "Poulailler", "tech": "MODBUS", "priorite": "MOYENNE", "type": "gaz", "unite": "ppm", "valeur": 900, "seuil": 3000, "sens": "high", "etat": "ras", "gravite": null, "apport": "Qualité de l’air du bâtiment : confort et santé.", "action": "Aérer le bâtiment", "alibaba": "RS485 Modbus CO2 sensor poultry house"},
  {"id": "SIM-3-12", "name": "Capteur d’ammoniac NH3", "categorie": "3. Aviculture : climat et environnement", "zone": "Poulailler", "tech": "MODBUS", "priorite": "MOYENNE", "type": "gaz", "unite": "ppm", "valeur": 28.7, "seuil": 25, "sens": "high", "etat": "alerte", "gravite": "warning", "apport": "Détecte l’ammoniac : protège l’appareil respiratoire.", "action": "Nettoyer la litière et ventiler", "alibaba": "RS485 ammonia NH3 sensor poultry farm"},
  {"id": "SIM-3-13", "name": "Capteur de sulfure d’hydrogène H2S", "categorie": "3. Aviculture : climat et environnement", "zone": "Poulailler", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "gaz", "unite": "ppm", "valeur": 5, "seuil": 20, "sens": "high", "etat": "ras", "gravite": null, "apport": "Détecte un gaz nocif ou des poussières dangereuses.", "action": "Aérer et vérifier la source", "alibaba": "H2S gas sensor RS485 poultry farm"},
  {"id": "SIM-3-14", "name": "Capteur PM2.5/PM10", "categorie": "3. Aviculture : climat et environnement", "zone": "Poulailler", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "gaz", "unite": "ppm", "valeur": 5, "seuil": 20, "sens": "high", "etat": "ras", "gravite": null, "apport": "Détecte un gaz nocif ou des poussières dangereuses.", "action": "Aérer et vérifier la source", "alibaba": "RS485 particulate matter sensor poultry house"},
  {"id": "SIM-3-15", "name": "Capteur de luminosité", "categorie": "3. Aviculture : climat et environnement", "zone": "Poulailler", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "lumiere", "unite": "lux", "valeur": 0, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Optimise le programme lumineux (ponte).", "action": "Ajuster l’éclairage", "alibaba": "RS485 light intensity sensor poultry house"},
  {"id": "SIM-4-16", "name": "Compteur de débit d’eau", "categorie": "4. Aviculture : eau, aliment et production", "zone": "Poulailler", "tech": "MODBUS", "priorite": "HAUTE", "type": "debit", "unite": "m³/h", "valeur": 3.0, "seuil": 8, "sens": "high", "etat": "ras", "gravite": null, "apport": "Détecte fuite ou surconsommation d’eau.", "action": "Inspecter le réseau d’eau", "alibaba": "smart poultry water flow meter RS485"},
  {"id": "SIM-4-17", "name": "Capteur de pression d’eau", "categorie": "4. Aviculture : eau, aliment et production", "zone": "Poulailler", "tech": "MODBUS", "priorite": "MOYENNE", "type": "pression", "unite": "bar", "valeur": 0.7, "seuil": 1.0, "sens": "low", "etat": "alerte", "gravite": "warning", "apport": "Protège la pompe et le réseau d’irrigation.", "action": "Vérifier pompe et canalisations", "alibaba": "poultry drinking line pressure sensor RS485"},
  {"id": "SIM-4-18", "name": "Compteur d’eau connecté", "categorie": "4. Aviculture : eau, aliment et production", "zone": "Poulailler", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "debit", "unite": "m³/h", "valeur": 3.0, "seuil": 8, "sens": "high", "etat": "ras", "gravite": null, "apport": "Détecte fuite ou surconsommation d’eau.", "action": "Inspecter le réseau d’eau", "alibaba": "smart water meter Modbus poultry farm"},
  {"id": "SIM-4-19", "name": "Capteur de niveau de silo", "categorie": "4. Aviculture : eau, aliment et production", "zone": "Poulailler", "tech": "MODBUS", "priorite": "MOYENNE", "type": "niveau", "unite": "%", "valeur": 70, "seuil": 15, "sens": "low", "etat": "ras", "gravite": null, "apport": "Évite la rupture d’eau ou d’aliment.", "action": "Réapprovisionner", "alibaba": "feed silo level sensor radar Modbus"},
  {"id": "SIM-4-20", "name": "Capteur ultrasonique de silo", "categorie": "4. Aviculture : eau, aliment et production", "zone": "Poulailler", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "niveau", "unite": "%", "valeur": 70, "seuil": 15, "sens": "low", "etat": "ras", "gravite": null, "apport": "Évite la rupture d’eau ou d’aliment.", "action": "Réapprovisionner", "alibaba": "ultrasonic feed silo level sensor RS485"},
  {"id": "SIM-4-21", "name": "Capteur radar de silo", "categorie": "4. Aviculture : eau, aliment et production", "zone": "Poulailler", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "securite", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Détecte une intrusion ou une ouverture non autorisée.", "action": "Envoyer un agent vérifier le périmètre", "alibaba": "radar feed silo level sensor Modbus"},
  {"id": "SIM-4-22", "name": "Caméra IA pour poulailler", "categorie": "4. Aviculture : eau, aliment et production", "zone": "Poulailler", "tech": "API", "priorite": "MOYENNE", "type": "camera", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "alerte", "gravite": "urgence", "apport": "Surveille la ferme et détecte les intrusions, jour comme nuit.", "action": "Ouvrir le flux et vérifier la zone", "alibaba": "AI poultry monitoring camera API"},
  {"id": "SIM-5-23", "name": "Capteur de niveau d’eau immergé", "categorie": "5. Eau, forage et pompage", "zone": "Forage & château d’eau", "tech": "MODBUS", "priorite": "HAUTE", "type": "niveau", "unite": "%", "valeur": 70, "seuil": 15, "sens": "low", "etat": "ras", "gravite": null, "apport": "Évite la rupture d’eau ou d’aliment.", "action": "Réapprovisionner", "alibaba": "submersible water level sensor RS485 Modbus"},
  {"id": "SIM-5-24", "name": "Capteur radar de niveau", "categorie": "5. Eau, forage et pompage", "zone": "Forage & château d’eau", "tech": "MODBUS", "priorite": "MOYENNE", "type": "securite", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Détecte une intrusion ou une ouverture non autorisée.", "action": "Envoyer un agent vérifier le périmètre", "alibaba": "radar water tank level sensor Modbus"},
  {"id": "SIM-5-25", "name": "Capteur de débit d’eau", "categorie": "5. Eau, forage et pompage", "zone": "Forage & château d’eau", "tech": "MODBUS", "priorite": "MOYENNE", "type": "debit", "unite": "m³/h", "valeur": 3.0, "seuil": 8, "sens": "high", "etat": "ras", "gravite": null, "apport": "Détecte fuite ou surconsommation d’eau.", "action": "Inspecter le réseau d’eau", "alibaba": "water flow meter RS485 Modbus irrigation"},
  {"id": "SIM-5-26", "name": "Débitmètre électromagnétique", "categorie": "5. Eau, forage et pompage", "zone": "Forage & château d’eau", "tech": "MODBUS", "priorite": "MOYENNE", "type": "debit", "unite": "m³/h", "valeur": 3.0, "seuil": 8, "sens": "high", "etat": "ras", "gravite": null, "apport": "Détecte fuite ou surconsommation d’eau.", "action": "Inspecter le réseau d’eau", "alibaba": "electromagnetic water flow meter Modbus"},
  {"id": "SIM-5-27", "name": "Capteur de pression", "categorie": "5. Eau, forage et pompage", "zone": "Forage & château d’eau", "tech": "MODBUS", "priorite": "MOYENNE", "type": "pression", "unite": "bar", "valeur": 0.7, "seuil": 1.0, "sens": "low", "etat": "alerte", "gravite": "warning", "apport": "Protège la pompe et le réseau d’irrigation.", "action": "Vérifier pompe et canalisations", "alibaba": "water pressure sensor RS485 4-20mA"},
  {"id": "SIM-5-28", "name": "Compteur d’eau intelligent", "categorie": "5. Eau, forage et pompage", "zone": "Forage & château d’eau", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "debit", "unite": "m³/h", "valeur": 3.0, "seuil": 8, "sens": "high", "etat": "hors_ligne", "gravite": null, "apport": "Détecte fuite ou surconsommation d’eau.", "action": "Inspecter le réseau d’eau", "alibaba": "smart water meter RS485 Modbus"},
  {"id": "SIM-5-29", "name": "Capteur de turbidité", "categorie": "5. Eau, forage et pompage", "zone": "Forage & château d’eau", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "qualite", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la qualité de l’eau ou du sol.", "action": "Analyser et corriger", "alibaba": "water turbidity sensor RS485 Modbus"},
  {"id": "SIM-5-30", "name": "Capteur de pH de l’eau", "categorie": "5. Eau, forage et pompage", "zone": "Forage & château d’eau", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "aqua", "unite": "pH", "valeur": 7.0, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la qualité de l’eau ou du sol (pH).", "action": "Corriger le pH", "alibaba": "online water pH sensor RS485"},
  {"id": "SIM-5-31", "name": "Capteur EC/TDS", "categorie": "5. Eau, forage et pompage", "zone": "Forage & château d’eau", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "qualite", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la qualité de l’eau ou du sol.", "action": "Analyser et corriger", "alibaba": "water EC TDS sensor RS485 Modbus"},
  {"id": "SIM-5-32", "name": "Capteur de chlore résiduel", "categorie": "5. Eau, forage et pompage", "zone": "Forage & château d’eau", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "qualite", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "alerte", "gravite": "warning", "apport": "Suit la qualité de l’eau ou du sol.", "action": "Analyser et corriger", "alibaba": "online residual chlorine sensor RS485"},
  {"id": "SIM-5-33", "name": "Enregistreur de données pour forage", "categorie": "5. Eau, forage et pompage", "zone": "Forage & château d’eau", "tech": "4G", "priorite": "À ÉVALUER", "type": "actionneur", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Pilote le forage à distance : marche/arrêt, anti-marche à sec.", "action": "Commander la pompe à distance", "alibaba": "water well data logger 4G Modbus"},
  {"id": "SIM-6-34", "name": "Sonde d’humidité du sol", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "HAUTE", "type": "humidite_sol", "unite": "%", "valeur": 30, "seuil": 18, "sens": "low", "etat": "ras", "gravite": null, "apport": "Déclenche l’irrigation au bon moment : économie d’eau, meilleur rendement.", "action": "Lancer l’irrigation de la parcelle", "alibaba": "RS485 Modbus soil moisture sensor agriculture"},
  {"id": "SIM-6-35", "name": "Sonde température-humidité du sol", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "MOYENNE", "type": "temperature", "unite": "°C", "valeur": 28, "seuil": 33, "sens": "high", "etat": "ras", "gravite": null, "apport": "Évite le coup de chaleur : mortalité et chute de ponte.", "action": "Ventiler, brumiser, vérifier l’eau", "alibaba": "soil temperature moisture sensor RS485 Modbus"},
  {"id": "SIM-6-36", "name": "Sonde pH du sol", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "aqua", "unite": "pH", "valeur": 7.0, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la qualité de l’eau ou du sol (pH).", "action": "Corriger le pH", "alibaba": "industrial soil pH sensor RS485 Modbus"},
  {"id": "SIM-6-37", "name": "Sonde EC du sol", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "qualite", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "alerte", "gravite": "warning", "apport": "Suit la qualité de l’eau ou du sol.", "action": "Analyser et corriger", "alibaba": "soil EC conductivity sensor RS485"},
  {"id": "SIM-6-38", "name": "Sonde NPK", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "qualite", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la qualité de l’eau ou du sol.", "action": "Analyser et corriger", "alibaba": "soil NPK sensor RS485 Modbus agriculture"},
  {"id": "SIM-6-39", "name": "Sonde sol 4-en-1", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "aqua", "unite": "pH", "valeur": 7.0, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la qualité de l’eau ou du sol (pH).", "action": "Corriger le pH", "alibaba": "soil moisture temperature EC pH sensor RS485"},
  {"id": "SIM-6-40", "name": "Sonde sol 7-en-1", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "aqua", "unite": "pH", "valeur": 7.0, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la qualité de l’eau ou du sol (pH).", "action": "Corriger le pH", "alibaba": "soil 7 in 1 sensor NPK pH EC moisture RS485"},
  {"id": "SIM-6-41", "name": "Station météo agricole", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "4G", "priorite": "HAUTE", "type": "meteo", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Prévoit les conditions : irrigation, traitements, alerte climat.", "action": "Adapter les travaux du jour", "alibaba": "automatic weather station agriculture Modbus 4G"},
  {"id": "SIM-6-42", "name": "Pluviomètre connecté", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "meteo", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "alerte", "gravite": "warning", "apport": "Prévoit les conditions : irrigation, traitements, alerte climat.", "action": "Adapter les travaux du jour", "alibaba": "tipping bucket rain gauge RS485"},
  {"id": "SIM-6-43", "name": "Anémomètre", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "meteo", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Prévoit les conditions : irrigation, traitements, alerte climat.", "action": "Adapter les travaux du jour", "alibaba": "wind speed sensor RS485 Modbus agriculture"},
  {"id": "SIM-6-44", "name": "Girouette numérique", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "meteo", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Prévoit les conditions : irrigation, traitements, alerte climat.", "action": "Adapter les travaux du jour", "alibaba": "wind direction sensor RS485"},
  {"id": "SIM-6-45", "name": "Capteur de rayonnement solaire", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "meteo", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Prévoit les conditions : irrigation, traitements, alerte climat.", "action": "Adapter les travaux du jour", "alibaba": "solar radiation sensor pyranometer RS485"},
  {"id": "SIM-6-46", "name": "Capteur UV", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "meteo", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Prévoit les conditions : irrigation, traitements, alerte climat.", "action": "Adapter les travaux du jour", "alibaba": "UV radiation sensor RS485 agriculture"},
  {"id": "SIM-6-47", "name": "Capteur d’humectation des feuilles", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "meteo", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "alerte", "gravite": "warning", "apport": "Prévoit les conditions : irrigation, traitements, alerte climat.", "action": "Adapter les travaux du jour", "alibaba": "leaf wetness sensor RS485 agriculture"},
  {"id": "SIM-6-48", "name": "Pompe doseuse connectée", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "MOYENNE", "type": "actionneur", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Pilote le forage à distance : marche/arrêt, anti-marche à sec.", "action": "Commander la pompe à distance", "alibaba": "smart dosing pump RS485 Modbus agriculture"},
  {"id": "SIM-6-49", "name": "Capteur de pression d’irrigation", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "MOYENNE", "type": "pression", "unite": "bar", "valeur": 2.2, "seuil": 1.0, "sens": "low", "etat": "ras", "gravite": null, "apport": "Protège la pompe et le réseau d’irrigation.", "action": "Vérifier pompe et canalisations", "alibaba": "irrigation pressure sensor RS485"},
  {"id": "SIM-6-50", "name": "Débitmètre d’irrigation", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "MODBUS", "priorite": "MOYENNE", "type": "debit", "unite": "m³/h", "valeur": 3.0, "seuil": 8, "sens": "high", "etat": "ras", "gravite": null, "apport": "Détecte fuite ou surconsommation d’eau.", "action": "Inspecter le réseau d’eau", "alibaba": "irrigation water flow meter Modbus"},
  {"id": "SIM-6-51", "name": "Caméra IA de ravageurs", "categorie": "6. Irrigation et cultures", "zone": "Parcelles", "tech": "API", "priorite": "MOYENNE", "type": "camera", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "hors_ligne", "gravite": null, "apport": "Surveille la ferme et détecte les intrusions, jour comme nuit.", "action": "Ouvrir le flux et vérifier la zone", "alibaba": "AI pest monitoring camera trap API"},
  {"id": "SIM-7-52", "name": "Station de capteurs pour serre", "categorie": "7. Serres et environnement contrôlé", "zone": "Serre", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "capteur", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "alerte", "gravite": "warning", "apport": "Mesure de terrain et alerte automatique.", "action": "Vérifier sur place", "alibaba": "greenhouse environment monitoring system RS485"},
  {"id": "SIM-7-53", "name": "Capteur température-humidité", "categorie": "7. Serres et environnement contrôlé", "zone": "Serre", "tech": "MODBUS", "priorite": "HAUTE", "type": "temperature", "unite": "°C", "valeur": 28, "seuil": 33, "sens": "high", "etat": "ras", "gravite": null, "apport": "Évite le coup de chaleur : mortalité et chute de ponte.", "action": "Ventiler, brumiser, vérifier l’eau", "alibaba": "greenhouse temperature humidity sensor RS485"},
  {"id": "SIM-7-54", "name": "Capteur de lumière PAR", "categorie": "7. Serres et environnement contrôlé", "zone": "Serre", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "meteo", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Prévoit les conditions : irrigation, traitements, alerte climat.", "action": "Adapter les travaux du jour", "alibaba": "PAR light sensor greenhouse RS485"},
  {"id": "SIM-7-55", "name": "Capteur d’oxygène dissous", "categorie": "7. Serres et environnement contrôlé", "zone": "Serre", "tech": "MODBUS", "priorite": "HAUTE", "type": "aqua", "unite": "mg/L", "valeur": 6.5, "seuil": 4, "sens": "low", "etat": "ras", "gravite": null, "apport": "Évite l’asphyxie des poissons : sauve un bassin entier.", "action": "Activer l’aération du bassin", "alibaba": "dissolved oxygen sensor hydroponics RS485"},
  {"id": "SIM-8-56", "name": "Enregistreur température-humidité 4G", "categorie": "8. Stockage, conservation et chambre froide", "zone": "Magasin & chambre froide", "tech": "4G", "priorite": "MOYENNE", "type": "temperature", "unite": "°C", "valeur": 28, "seuil": 33, "sens": "high", "etat": "ras", "gravite": null, "apport": "Évite le coup de chaleur : mortalité et chute de ponte.", "action": "Ventiler, brumiser, vérifier l’eau", "alibaba": "4G temperature humidity data logger warehouse API"},
  {"id": "SIM-8-57", "name": "Alarme de chambre froide", "categorie": "8. Stockage, conservation et chambre froide", "zone": "Magasin & chambre froide", "tech": "4G", "priorite": "HAUTE", "type": "froid", "unite": "°C", "valeur": 9.2, "seuil": 8, "sens": "high", "etat": "alerte", "gravite": "critique", "apport": "Protège la chaîne du froid : évite les pertes.", "action": "Vérifier le groupe froid", "alibaba": "cold room temperature alarm 4G Modbus"},
  {"id": "SIM-8-58", "name": "Capteur d’humidité de stockage", "categorie": "8. Stockage, conservation et chambre froide", "zone": "Magasin & chambre froide", "tech": "MODBUS", "priorite": "MOYENNE", "type": "humidite", "unite": "%", "valeur": 60, "seuil": 85, "sens": "high", "etat": "ras", "gravite": null, "apport": "Prévient condensation et maladies respiratoires.", "action": "Améliorer la ventilation", "alibaba": "warehouse humidity sensor RS485"},
  {"id": "SIM-8-59", "name": "Capteur CO2 pour stockage", "categorie": "8. Stockage, conservation et chambre froide", "zone": "Magasin & chambre froide", "tech": "MODBUS", "priorite": "MOYENNE", "type": "gaz", "unite": "ppm", "valeur": 900, "seuil": 3000, "sens": "high", "etat": "ras", "gravite": null, "apport": "Qualité de l’air du bâtiment : confort et santé.", "action": "Aérer le bâtiment", "alibaba": "CO2 sensor cold storage RS485"},
  {"id": "SIM-8-60", "name": "Capteur d’éthylène", "categorie": "8. Stockage, conservation et chambre froide", "zone": "Magasin & chambre froide", "tech": "MODBUS", "priorite": "PLUS TARD", "type": "froid", "unite": "°C", "valeur": 4, "seuil": 8, "sens": "high", "etat": "ras", "gravite": null, "apport": "Protège la chaîne du froid : évite les pertes.", "action": "Vérifier le groupe froid", "alibaba": "ethylene gas sensor fruit storage RS485"},
  {"id": "SIM-8-61", "name": "Balance plateforme RS232", "categorie": "8. Stockage, conservation et chambre froide", "zone": "Magasin & chambre froide", "tech": "AUTRE", "priorite": "MOYENNE", "type": "pesee", "unite": "kg", "valeur": 0, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la croissance / la production sans manipulation.", "action": "Consulter la courbe de poids", "alibaba": "digital platform scale RS232 Bluetooth"},
  {"id": "SIM-8-62", "name": "Balance palette", "categorie": "8. Stockage, conservation et chambre froide", "zone": "Magasin & chambre froide", "tech": "AUTRE", "priorite": "MOYENNE", "type": "pesee", "unite": "kg", "valeur": 0, "seuil": 0, "sens": "", "etat": "alerte", "gravite": "warning", "apport": "Suit la croissance / la production sans manipulation.", "action": "Consulter la courbe de poids", "alibaba": "digital pallet scale RS232"},
  {"id": "SIM-8-63", "name": "Scanner code-barres", "categorie": "8. Stockage, conservation et chambre froide", "zone": "Magasin & chambre froide", "tech": "API", "priorite": "À ÉVALUER", "type": "logistique", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Inventaire rapide et fiable du stock.", "action": "Scanner les articles", "alibaba": "wireless barcode scanner SDK inventory"},
  {"id": "SIM-8-64", "name": "Imprimante code-barres", "categorie": "8. Stockage, conservation et chambre froide", "zone": "Magasin & chambre froide", "tech": "API", "priorite": "À ÉVALUER", "type": "logistique", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Inventaire rapide et fiable du stock.", "action": "Scanner les articles", "alibaba": "thermal barcode label printer SDK"},
  {"id": "SIM-8-65", "name": "Lecteur UHF RFID", "categorie": "8. Stockage, conservation et chambre froide", "zone": "Magasin & chambre froide", "tech": "API", "priorite": "MOYENNE", "type": "localisation", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Localise et identifie chaque animal : anti-vol, sortie de zone, traçabilité.", "action": "Vérifier la position et l’identité de l’animal", "alibaba": "UHF RFID inventory reader SDK"},
  {"id": "SIM-8-66", "name": "Capteur de niveau de silo", "categorie": "8. Stockage, conservation et chambre froide", "zone": "Magasin & chambre froide", "tech": "MODBUS", "priorite": "MOYENNE", "type": "niveau", "unite": "%", "valeur": 70, "seuil": 15, "sens": "low", "etat": "ras", "gravite": null, "apport": "Évite la rupture d’eau ou d’aliment.", "action": "Réapprovisionner", "alibaba": "grain silo level sensor radar Modbus"},
  {"id": "SIM-9-67", "name": "Compteur électrique intelligent monophasé", "categorie": "9. Énergie et maintenance des équipements", "zone": "Local technique", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "energie", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "alerte", "gravite": "warning", "apport": "Suit la consommation et anticipe les pannes.", "action": "Vérifier l’installation", "alibaba": "single phase smart energy meter RS485 Modbus"},
  {"id": "SIM-9-68", "name": "Compteur électrique intelligent triphasé", "categorie": "9. Énergie et maintenance des équipements", "zone": "Local technique", "tech": "MODBUS", "priorite": "HAUTE", "type": "energie", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la consommation et anticipe les pannes.", "action": "Vérifier l’installation", "alibaba": "three phase smart energy meter RS485 Modbus"},
  {"id": "SIM-9-69", "name": "Capteur de vibration moteur", "categorie": "9. Énergie et maintenance des équipements", "zone": "Local technique", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "energie", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la consommation et anticipe les pannes.", "action": "Vérifier l’installation", "alibaba": "industrial vibration sensor RS485 Modbus"},
  {"id": "SIM-9-70", "name": "Analyseur de réseau électrique", "categorie": "9. Énergie et maintenance des équipements", "zone": "Local technique", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "energie", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la consommation et anticipe les pannes.", "action": "Vérifier l’installation", "alibaba": "power quality analyzer Modbus RS485"},
  {"id": "SIM-9-71", "name": "Capteur de niveau de carburant", "categorie": "9. Énergie et maintenance des équipements", "zone": "Local technique", "tech": "4G", "priorite": "MOYENNE", "type": "niveau", "unite": "%", "valeur": 80, "seuil": 15, "sens": "low", "etat": "ras", "gravite": null, "apport": "Anti-vol carburant et fin de réservoir anticipée.", "action": "Vérifier le niveau et sécuriser la cuve", "alibaba": "fuel tank level sensor 4G Modbus"},
  {"id": "SIM-9-72", "name": "Onduleur solaire Modbus", "categorie": "9. Énergie et maintenance des équipements", "zone": "Local technique", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "energie", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "alerte", "gravite": "warning", "apport": "Suit la consommation et anticipe les pannes.", "action": "Vérifier l’installation", "alibaba": "solar inverter Modbus RS485 API"},
  {"id": "SIM-9-73", "name": "Contrôleur de batterie solaire", "categorie": "9. Énergie et maintenance des équipements", "zone": "Local technique", "tech": "MODBUS", "priorite": "MOYENNE", "type": "energie", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la consommation et anticipe les pannes.", "action": "Vérifier l’installation", "alibaba": "solar battery monitor Bluetooth Modbus"},
  {"id": "SIM-9-74", "name": "Compteur d’énergie solaire", "categorie": "9. Énergie et maintenance des équipements", "zone": "Local technique", "tech": "MODBUS", "priorite": "MOYENNE", "type": "energie", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "hors_ligne", "gravite": null, "apport": "Suit la consommation et anticipe les pannes.", "action": "Vérifier l’installation", "alibaba": "solar power meter RS485 Modbus"},
  {"id": "SIM-9-75", "name": "Prise connectée industrielle", "categorie": "9. Énergie et maintenance des équipements", "zone": "Local technique", "tech": "4G", "priorite": "À ÉVALUER", "type": "energie", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la consommation et anticipe les pannes.", "action": "Vérifier l’installation", "alibaba": "industrial smart socket 4G Modbus"},
  {"id": "SIM-10-76", "name": "Balance connectée pour ruche", "categorie": "10. Apiculture", "zone": "Rucher", "tech": "4G", "priorite": "MOYENNE", "type": "pesee", "unite": "kg", "valeur": 0, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la croissance / la production sans manipulation.", "action": "Consulter la courbe de poids", "alibaba": "smart beehive scale 4G API"},
  {"id": "SIM-10-77", "name": "Caméra solaire pour rucher", "categorie": "10. Apiculture", "zone": "Rucher", "tech": "4G", "priorite": "MOYENNE", "type": "pesee", "unite": "kg", "valeur": 0, "seuil": 0, "sens": "", "etat": "alerte", "gravite": "warning", "apport": "Suit la croissance / la production sans manipulation.", "action": "Consulter la courbe de poids", "alibaba": "solar 4G apiary security camera"},
  {"id": "SIM-11-78", "name": "Capteur d’oxygène dissous", "categorie": "11. Pisciculture et aquaculture", "zone": "Bassins", "tech": "MODBUS", "priorite": "HAUTE", "type": "aqua", "unite": "mg/L", "valeur": 6.5, "seuil": 4, "sens": "low", "etat": "ras", "gravite": null, "apport": "Évite l’asphyxie des poissons : sauve un bassin entier.", "action": "Activer l’aération du bassin", "alibaba": "dissolved oxygen sensor RS485 aquaculture"},
  {"id": "SIM-11-79", "name": "Sonde pH", "categorie": "11. Pisciculture et aquaculture", "zone": "Bassins", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "aqua", "unite": "pH", "valeur": 7.0, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la qualité de l’eau ou du sol (pH).", "action": "Corriger le pH", "alibaba": "aquaculture pH sensor RS485 Modbus"},
  {"id": "SIM-11-80", "name": "Capteur température d’eau", "categorie": "11. Pisciculture et aquaculture", "zone": "Bassins", "tech": "MODBUS", "priorite": "MOYENNE", "type": "capteur", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Mesure de terrain et alerte automatique.", "action": "Vérifier sur place", "alibaba": "water temperature sensor aquaculture RS485"},
  {"id": "SIM-11-81", "name": "Capteur ORP", "categorie": "11. Pisciculture et aquaculture", "zone": "Bassins", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "qualite", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la qualité de l’eau ou du sol.", "action": "Analyser et corriger", "alibaba": "ORP sensor RS485 aquaculture"},
  {"id": "SIM-11-82", "name": "Capteur d’ammoniaque", "categorie": "11. Pisciculture et aquaculture", "zone": "Bassins", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "gaz", "unite": "ppm", "valeur": 28.7, "seuil": 25, "sens": "high", "etat": "alerte", "gravite": "warning", "apport": "Détecte l’ammoniac : protège l’appareil respiratoire.", "action": "Nettoyer la litière et ventiler", "alibaba": "ammonia sensor aquaculture RS485"},
  {"id": "SIM-11-83", "name": "Capteur de turbidité", "categorie": "11. Pisciculture et aquaculture", "zone": "Bassins", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "qualite", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la qualité de l’eau ou du sol.", "action": "Analyser et corriger", "alibaba": "turbidity sensor RS485 aquaculture"},
  {"id": "SIM-11-84", "name": "Capteur de salinité", "categorie": "11. Pisciculture et aquaculture", "zone": "Bassins", "tech": "MODBUS", "priorite": "À ÉVALUER", "type": "qualite", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Suit la qualité de l’eau ou du sol.", "action": "Analyser et corriger", "alibaba": "salinity sensor aquaculture RS485"},
  {"id": "SIM-11-85", "name": "Caméra sous-marine IP", "categorie": "11. Pisciculture et aquaculture", "zone": "Bassins", "tech": "CAM", "priorite": "MOYENNE", "type": "camera", "unite": "", "valeur": null, "seuil": 0, "sens": "", "etat": "ras", "gravite": null, "apport": "Surveille la ferme et détecte les intrusions, jour comme nuit.", "action": "Ouvrir le flux et vérifier la zone", "alibaba": "underwater aquaculture camera RTSP"},
]);

const arr = (v) => (Array.isArray(v) ? v : []);

/** Synthese du parc simule : l'apport en un coup d'oeil. */
export function buildSimulatedFleetSummary(fleet = SMARTFARM_SIMULATED_FLEET) {
  const rows = arr(fleet);
  const alertes = rows.filter((d) => d.etat === 'alerte');
  const horsLigne = rows.filter((d) => d.etat === 'hors_ligne');
  const zones = Array.from(new Set(rows.map((d) => d.zone)));
  const parCategorie = {};
  rows.forEach((d) => {
    (parCategorie[d.categorie] = parCategorie[d.categorie] || []).push(d);
  });
  return {
    total: rows.length,
    actifs: rows.length - horsLigne.length,
    alertes: alertes.length,
    horsLigne: horsLigne.length,
    urgences: alertes.filter((d) => d.gravite === 'urgence').length,
    zones,
    zonesCount: zones.length,
    actions: alertes.length,
    parCategorie,
  };
}
