import { AlertTriangle, Bell, ClipboardList, CreditCard, FileText, GitBranch, PackageCheck, ShoppingCart } from 'lucide-react';
import { fmtCurrency, fmtNumber } from '../utils/format';
import { buildEntityLinks, buildModuleConnections, humanLinkRow, MODULE_ROUTES, summarizeEntityLinks } from '../utils/moduleInterconnections';

const arr = (value) => Array.isArray(value) ? value : [];
const iconMap = { salesOrders: ShoppingCart, payments: CreditCard, transactions: CreditCard, documents: FileText, tasks: ClipboardList, alertes: Bell, stocks: PackageCheck, businessEvents: GitBranch };
const labelMap = { salesOrders: 'Ventes liées', payments: 'Paiements', transactions: 'Finance', documents: 'Documents / preuves', tasks: 'Tâches', alertes: 'Alertes', stocks: 'Stock', businessEvents: 'Historique métier', health: 'Santé', feedLogs: 'Alimentation', productionLogs: 'Production' };

function Pill({ children }) { return <span className="rounded-full border border-[#eadcc2] bg-[#fffdf8] px-3 py-1 text-xs font-black text-[#8a7456]">{children}</span>; }
function MiniStat({ label, value }) { return <div className="rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-3"><p className="text-xs text-[#8a7456]">{label}</p><p className="mt-1 font-black text-[#2f2415]">{value}</p></div>; }
function Row({ title, detail, value }) { return <div className="grid grid-cols-1 gap-2 border-b border-[#eadcc2]/70 py-3 last:border-b-0 md:grid-cols-[220px_1fr_auto] md:items-center"><b className="text-sm text-[#2f2415]">{title}</b><span className="text-xs text-[#8a7456]">{detail}</span><Pill>{typeof value === 'number' ? fmtCurrency(value) : value}</Pill></div>; }
function Bucket({ name, rows }) { const Icon = iconMap[name] || GitBranch; if (!arr(rows).length) return null; return <section className="rounded-2xl border border-[#eadcc2] bg-white p-4"><h4 className="mb-2 flex items-center gap-2 font-black text-[#2f2415]"><Icon size={16} /> {labelMap[name] || name}</h4>{arr(rows).slice(0, 5).map((row, index) => <Row key={`${name}-${row.id || index}`} {...humanLinkRow(row)} />)}</section>; }

export function EntityConnectionsPanel({ entity, context = {}, compact = false }) {
  if (!entity) return null;
  const links = buildEntityLinks(entity, context);
  const summary = summarizeEntityLinks(links);
  const hasLinks = Object.values(links).some((rows) => arr(rows).length);
  return <section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><div className="mb-4 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs uppercase tracking-[0.2em] text-[#9a6b12] font-black">Connexions métier</p><h3 className="text-lg font-black text-[#2f2415]">Données liées à cette fiche</h3></div>{hasLinks ? <Pill>{summary.eventsCount + summary.documentsCount + summary.tasksCount + summary.alertsCount} lien(s)</Pill> : <Pill>Aucun lien</Pill>}</div><div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><MiniStat label="Ventes" value={fmtCurrency(summary.totalSales)} /><MiniStat label="Payé" value={fmtCurrency(summary.paid)} /><MiniStat label="Reste" value={fmtCurrency(summary.remaining)} /><MiniStat label="Charges" value={fmtCurrency(summary.charges)} /><MiniStat label="Preuves" value={fmtNumber(summary.documentsCount)} /></div>{compact ? null : <div className="mt-4 grid grid-cols-1 gap-3 xl:grid-cols-2">{Object.entries(links).map(([name, rows]) => <Bucket key={name} name={name} rows={rows} />)}{!hasLinks ? <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><AlertTriangle size={15} className="inline" /> Aucune donnée liée trouvée. Vérifier les identifiants, lots, animaux, ventes, finances ou documents.</div> : null}</div>}</section>;
}

export function ModuleConnectionsPanel({ moduleKey, context = {}, onNavigate }) {
  const model = buildModuleConnections(moduleKey, context);
  return <section className="rounded-3xl border border-[#d6c3a0] bg-white p-5 shadow-sm"><div className="mb-4 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs uppercase tracking-[0.2em] text-[#9a6b12] font-black">Interconnexions</p><h3 className="text-lg font-black text-[#2f2415]">Ce module impacte les autres espaces</h3></div><Pill>{MODULE_ROUTES[moduleKey] || moduleKey}</Pill></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-6"><MiniStat label="Ventes" value={fmtNumber(model.counts.salesOrders)} /><MiniStat label="Finance" value={fmtNumber(model.counts.transactions)} /><MiniStat label="Documents" value={fmtNumber(model.counts.documents)} /><MiniStat label="Tâches" value={fmtNumber(model.counts.tasks)} /><MiniStat label="Alertes" value={fmtNumber(model.counts.alertes)} /><MiniStat label="Stock" value={fmtNumber(model.counts.stocks)} /></div><div className="mt-4 space-y-2">{model.suggestions.length ? model.suggestions.map((item) => <button key={item.id} type="button" onClick={() => onNavigate?.(item.moduleKey)} className="grid w-full grid-cols-1 gap-2 rounded-2xl border border-[#eadcc2] bg-[#fffdf8] p-3 text-left hover:bg-[#dcfce7] md:grid-cols-[240px_1fr_auto] md:items-center"><b className="text-[#2f2415]">{item.title}</b><span className="text-sm text-[#8a7456]">{item.detail}</span><Pill>{item.value}</Pill></button>) : <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">Aucune interconnexion urgente détectée.</div>}</div></section>;
}
