export const MODULE_CONFIG = {
  dashboard: { label: 'Dashboard', table: null, idField: 'id' },
  animaux: { label: 'Animaux', table: 'animals', idField: 'id', idPrefix: 'BOV' },
  avicole: { label: 'Avicole', table: 'lots', idField: 'id', idPrefix: 'LOTPO' },
  sante: { label: 'Sante', table: 'vaccins', idField: 'id', idPrefix: 'VAC' },
  veterinaires: { label: 'Veterinaires', table: 'veterinaires', idField: 'id', idPrefix: 'VET' },
  finances: { label: 'Finances', table: 'transactions', idField: 'id', idPrefix: 'TRX' },
  comptabilite: { label: 'Comptabilite', table: null, idField: 'id', idPrefix: 'ACC' },
  investissements: { label: 'Investissements', table: 'investissements', idField: 'id', idPrefix: 'INV' },
  business_plans: { label: 'Business Plans', table: 'business_plans', idField: 'id', idPrefix: 'BP' },
  bp_investment_lines: { label: 'Lignes investissement BP', table: 'bp_investment_lines', idField: 'id', idPrefix: 'BPLI' },
  bp_recurring_costs: { label: 'Charges recurrentes BP', table: 'bp_recurring_costs', idField: 'id', idPrefix: 'BPCOST' },
  bp_revenue_projections: { label: 'Projections BP', table: 'bp_revenue_projections', idField: 'id', idPrefix: 'BPREV' },
  bp_funding_sources: { label: 'Financements BP', table: 'bp_funding_sources', idField: 'id', idPrefix: 'BPFUND' },
  bp_links: { label: 'Liens BP', table: 'bp_links', idField: 'id', idPrefix: 'BPLINK' },
  bp_risks: { label: 'Risques BP', table: 'bp_risks', idField: 'id', idPrefix: 'BPRISK' },
  price_catalog: { label: 'Catalogue prix', table: 'price_catalog', idField: 'id', idPrefix: 'PRICE' },
  bp_versions: { label: 'Versions BP', table: 'bp_versions', idField: 'id', idPrefix: 'BPVER' },
  bp_lines_history: { label: 'Historique lignes BP', table: 'bp_lines_history', idField: 'id', idPrefix: 'BPHIST' },
  stock: { label: 'Stock', table: 'stocks', idField: 'id', idPrefix: 'STK' },
  clients: { label: 'Clients', table: 'clients', idField: 'id', idPrefix: 'CLI' },
  fournisseurs: { label: 'Fournisseurs', table: 'fournisseurs', idField: 'id', idPrefix: 'FOU' },
  tracabilite: { label: 'Tracabilite', table: 'tracabilite', idField: 'id', idPrefix: 'TRA' },
  business_events: { label: 'Evenements', table: 'business_events', idField: 'id', idPrefix: 'EVT' },
  alertes_center: { label: 'Alertes', table: 'alertes_center', idField: 'id', idPrefix: 'ALE' },
  whatsapp_templates: { label: 'Templates WhatsApp', table: 'whatsapp_templates', idField: 'id', idPrefix: 'WTP' },
  whatsapp_logs: { label: 'Logs WhatsApp', table: 'whatsapp_logs', idField: 'id', idPrefix: 'WTL' },
  cultures: { label: 'Cultures', table: 'cultures', idField: 'id', idPrefix: 'CULT' },
  ventes: { label: 'Ventes', table: 'sales_orders', idField: 'id', idPrefix: 'CMD' },
  sales_orders: { label: 'Commandes', table: 'sales_orders', idField: 'id', idPrefix: 'CMD' },
  sales_order_items: { label: 'Lignes commande', table: 'sales_order_items', idField: 'id', idPrefix: 'CMDI' },
  deliveries: { label: 'Livraisons', table: 'deliveries', idField: 'id', idPrefix: 'LIV' },
  invoices: { label: 'Factures', table: 'invoices', idField: 'id', idPrefix: 'FAC' },
  payments: { label: 'Paiements', table: 'payments', idField: 'id', idPrefix: 'PAI' },
  sales_opportunities: { label: 'Opportunites vente', table: 'sales_opportunities', idField: 'id', idPrefix: 'OPP' },
  documents: { label: 'Documents', table: 'documents', idField: 'id', idPrefix: 'DOC' },
  taches: { label: 'Taches', table: 'tasks', idField: 'id', idPrefix: 'TSK' },
  rapports: { label: 'Rapports', table: 'reports', idField: 'id', idPrefix: 'RPT' },
  equipements: { label: 'Equipements', table: 'equipment', idField: 'id', idPrefix: 'EQP' },
  audit_logs: { label: 'Audit logs', table: 'audit_logs', idField: 'id', idPrefix: 'LOG' },
  alimentation_logs: { label: 'Alimentation', table: 'alimentation_logs', idField: 'id', idPrefix: 'ALIM' },
  production_oeufs_logs: { label: 'Production oeufs', table: 'production_oeufs_logs', idField: 'id', idPrefix: 'PROD' },
  sensor_devices: { label: 'Capteurs', table: 'sensor_devices', idField: 'id', idPrefix: 'SENS' },
  sensor_readings: { label: 'Mesures capteurs', table: 'sensor_readings', idField: 'id', idPrefix: 'READ' },
  camera_devices: { label: 'Cameras', table: 'camera_devices', idField: 'id', idPrefix: 'CAM' },
};

export const MODULE_FORM_FIELDS = {
  animaux: [
    { key: 'section_identification', label: 'Identification', type: 'section' },
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'tag', label: 'Tag', type: 'text' },
    { key: 'photo_url', label: 'Photo animal', type: 'image' },
    { key: 'name', label: 'Nom', type: 'text', required: true },
    { key: 'type', label: 'Type', type: 'select', options: ['Bovin', 'Ovin', 'Caprin'] },
    { key: 'race', label: 'Race', type: 'text' },
    { key: 'sexe', label: 'Sexe', type: 'select', options: ['M', 'F'] },
    { key: 'poids', label: 'Poids (kg)', type: 'number' },
    { key: 'section_origine', label: 'Origine & dates', type: 'section', description: 'Permet de distinguer achat, naissance sur la ferme et reproduction interne.' },
    { key: 'mode_acquisition', label: 'Mode acquisition', type: 'select', options: [
      { value: 'achat', label: 'Achat' },
      { value: 'naissance_ferme', label: 'Naissance sur la ferme' },
      { value: 'reproduction_interne', label: 'Reproduction interne' },
      { value: 'don', label: 'Don' },
      { value: 'autre', label: 'Autre' },
    ] },
    { key: 'date_achat', label: 'Date achat', type: 'date', required: true, showWhen: (form) => (form.mode_acquisition || 'achat') === 'achat' },
    { key: 'date_naissance', label: 'Date naissance', type: 'date', required: true, showWhen: (form) => ['naissance_ferme', 'reproduction_interne'].includes(form.mode_acquisition) },
    { key: 'date_entree_ferme', label: 'Date entree ferme', type: 'date', showWhen: (form) => !['naissance_ferme', 'reproduction_interne'].includes(form.mode_acquisition) },
    { key: 'provenance', label: 'Origine / provenance', type: 'text', showWhen: (form) => ['don', 'autre'].includes(form.mode_acquisition) },
    { key: 'fournisseur_id', label: 'ID fournisseur', type: 'text', showWhen: (form) => (form.mode_acquisition || 'achat') === 'achat' },
    { key: 'fournisseur_vendeur', label: 'Fournisseur / vendeur', type: 'text', showWhen: (form) => (form.mode_acquisition || 'achat') === 'achat' },
    { key: 'mere_id', label: 'Mere', type: 'select', options: [], showWhen: (form) => ['naissance_ferme', 'reproduction_interne'].includes(form.mode_acquisition) },
    { key: 'pere_id', label: 'Pere', type: 'select', options: [], showWhen: (form) => ['naissance_ferme', 'reproduction_interne'].includes(form.mode_acquisition) },
    { key: 'portee_id', label: 'ID portee', type: 'text', showWhen: (form) => ['naissance_ferme', 'reproduction_interne'].includes(form.mode_acquisition) },
    { key: 'notes_reproduction', label: 'Notes origine / reproduction', type: 'text', fullWidth: true },
    { key: 'section_sante', label: 'Sante', type: 'section' },
    { key: 'health_status', label: 'Etat de sante', type: 'select', options: [
      { value: 'sain', label: 'Sain' },
      { value: 'malade', label: 'Malade' },
      { value: 'blesse', label: 'Blesse' },
      { value: 'sous_traitement', label: 'Sous traitement' },
      { value: 'a_surveiller', label: 'A surveiller' },
    ] },
    { key: 'frais_sante', label: 'Frais sante / soins', type: 'number' },
    { key: 'ras_veterinaire', label: 'RAS veterinaire', type: 'text', fullWidth: true },
    { key: 'date_detection_maladie', label: 'Date detection maladie', type: 'date', showWhen: (form) => form.health_status === 'malade' },
    { key: 'symptomes', label: 'Symptomes', type: 'text', fullWidth: true, showWhen: (form) => form.health_status === 'malade' },
    { key: 'traitement_prevu', label: 'Traitement prevu', type: 'text', fullWidth: true, showWhen: (form) => form.health_status === 'malade' },
    { key: 'veterinaire_id', label: 'Veterinaire', type: 'text', showWhen: (form) => ['malade', 'sous_traitement'].includes(form.health_status) },
    { key: 'cout_traitement_estime', label: 'Cout traitement estime', type: 'number', showWhen: (form) => form.health_status === 'malade' },
    { key: 'traitement_en_cours', label: 'Traitement en cours', type: 'text', fullWidth: true, showWhen: (form) => form.health_status === 'sous_traitement' },
    { key: 'date_debut_traitement', label: 'Date debut traitement', type: 'date', showWhen: (form) => form.health_status === 'sous_traitement' },
    { key: 'date_fin_traitement_prevue', label: 'Date fin traitement prevue', type: 'date', showWhen: (form) => form.health_status === 'sous_traitement' },
    { key: 'cout_traitement', label: 'Cout traitement', type: 'number', showWhen: (form) => form.health_status === 'sous_traitement' },
    { key: 'raison_surveillance', label: 'Raison surveillance', type: 'text', fullWidth: true, showWhen: (form) => form.health_status === 'a_surveiller' },
    { key: 'date_prochaine_verification', label: 'Date prochaine verification', type: 'date', showWhen: (form) => form.health_status === 'a_surveiller' },
    { key: 'traitements_notes', label: 'Traitements / soins', type: 'text', fullWidth: true },
    { key: 'section_reproduction', label: 'Reproduction', type: 'section', description: 'A renseigner principalement pour les femelles reproductrices.' },
    { key: 'en_gestation', label: 'En gestation', type: 'checkbox', showWhen: (form) => form.sexe === 'F' },
    { key: 'date_debut_gestation', label: 'Date debut gestation', type: 'date', showWhen: (form) => form.sexe === 'F' && Boolean(form.en_gestation) },
    { key: 'date_prevue_mise_bas', label: 'Date prevue mise bas', type: 'date', showWhen: (form) => form.sexe === 'F' && Boolean(form.en_gestation) },
    { key: 'male_reproducteur_id', label: 'Male reproducteur', type: 'select', options: [], showWhen: (form) => form.sexe === 'F' },
    { key: 'statut_reproduction', label: 'Statut reproduction', type: 'select', options: [
      { value: 'non_reproductrice', label: 'Non reproductrice' },
      { value: 'disponible', label: 'Disponible' },
      { value: 'en_gestation', label: 'En gestation' },
      { value: 'mise_bas_proche', label: 'Mise bas proche' },
      { value: 'a_reposer', label: 'A reposer' },
      { value: 'infertile', label: 'Infertile' },
      { value: 'inconnu', label: 'Inconnu' },
    ], showWhen: (form) => form.sexe === 'F' },
    { key: 'section_finances', label: 'Finances internes', type: 'section' },
    { key: 'purchase_cost', label: 'Prix achat', type: 'number', showWhen: (form) => (form.mode_acquisition || 'achat') === 'achat' },
    { key: 'alimentation_calculee_view', label: 'Alimentation calculee', type: 'readonly' },
    { key: 'frais_sante_view', label: 'Frais sante / soins calcules', type: 'readonly' },
    { key: 'autres_frais', label: 'Autres frais', type: 'number' },
    { key: 'cout_total_calcule_view', label: 'Cout total calcule', type: 'readonly' },
    { key: 'prix_vente_reel', label: 'Prix vente reel', type: 'number', showWhen: (form) => form.status === 'vendu' },
    { key: 'marge_calculee_view', label: 'Marge / perte calculee', type: 'readonly' },
    { key: 'status', label: 'Statut administratif', type: 'select', options: [
      { value: 'actif', label: 'Actif' },
      { value: 'pret_a_la_vente', label: 'Pret a la vente' },
      { value: 'reserve', label: 'Reserve' },
      { value: 'vendu', label: 'Vendu' },
      { value: 'mort', label: 'Mort' },
      { value: 'vole', label: 'Vole' },
      { value: 'reforme', label: 'Reforme' },
    ] },
    { key: 'section_vente', label: 'Maturite commerciale', type: 'section', description: 'Le systeme peut recommander, mais la confirmation reste manuelle.' },
    { key: 'poids_objectif', label: 'Poids objectif vente', type: 'number' },
    { key: 'date_objectif_vente', label: 'Date objectif vente', type: 'date' },
    { key: 'sale_readiness_score', label: 'Score pret vente', type: 'readonly' },
    { key: 'sale_readiness_status', label: 'Maturite vente', type: 'select', options: [
      { value: 'non_pret', label: 'Non pret' },
      { value: 'presque_pret', label: 'Presque pret' },
      { value: 'recommande_pret', label: 'Recommande pret a vendre' },
      { value: 'pret_confirme', label: 'Pret confirme' },
    ] },
    { key: 'pret_vente_recommande', label: 'Recommande pret vente', type: 'checkbox' },
    { key: 'pret_vente_confirme', label: 'Pret vente confirme', type: 'checkbox' },
    { key: 'raison_pret_vente', label: 'Raison recommandation vente', type: 'text', fullWidth: true },
    { key: 'section_situation', label: 'Situation administrative', type: 'section' },
    { key: 'date_vente', label: 'Date vente', type: 'date', showWhen: (form) => form.status === 'vendu' },
    { key: 'client_id', label: 'Client', type: 'text', showWhen: (form) => form.status === 'vendu' },
    { key: 'moyen_paiement', label: 'Moyen paiement', type: 'select', options: ['Cash', 'Banque', 'Wave', 'Orange Money', 'Free Money', 'Carte bancaire'], showWhen: (form) => form.status === 'vendu' },
    { key: 'commentaire_vente', label: 'Commentaire vente', type: 'text', fullWidth: true, showWhen: (form) => form.status === 'vendu' },
    { key: 'date_deces', label: 'Date deces', type: 'date', showWhen: (form) => form.status === 'mort' },
    { key: 'cause_deces', label: 'Cause deces', type: 'text', fullWidth: true, showWhen: (form) => form.status === 'mort' },
    { key: 'valeur_perte_estimee', label: 'Valeur perte estimee', type: 'number', showWhen: (form) => ['mort', 'vole'].includes(form.status) },
    { key: 'commentaire_deces', label: 'Commentaire deces', type: 'text', fullWidth: true, showWhen: (form) => form.status === 'mort' },
    { key: 'date_vol_detecte', label: 'Date vol detecte', type: 'date', showWhen: (form) => form.status === 'vole' },
    { key: 'lieu_vol', label: 'Lieu vol', type: 'text', showWhen: (form) => form.status === 'vole' },
    { key: 'commentaire_vol', label: 'Commentaire vol', type: 'text', fullWidth: true, showWhen: (form) => form.status === 'vole' },
    { key: 'date_reforme', label: 'Date reforme', type: 'date', showWhen: (form) => form.status === 'reforme' },
    { key: 'motif_reforme', label: 'Motif reforme', type: 'text', showWhen: (form) => form.status === 'reforme' },
    { key: 'valeur_residuelle', label: 'Valeur residuelle', type: 'number', showWhen: (form) => form.status === 'reforme' },
    { key: 'commentaire_reforme', label: 'Commentaire reforme', type: 'text', fullWidth: true, showWhen: (form) => form.status === 'reforme' },
    { key: 'business_plan_id', label: 'Business Plan lie', type: 'text' },
  ],
  avicole: [
    { key: 'section_identification', label: 'Identification du lot', type: 'section' },
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'name', label: 'Nom lot', type: 'text', required: true },
    { key: 'type', label: 'Type lot', type: 'select', options: [
      { value: 'Pondeuse', label: 'Pondeuses' },
      { value: 'Chair', label: 'Poulets de chair' },
    ] },
    { key: 'phase', label: 'Phase actuelle', type: 'text' },
    { key: 'phase_suggeree_view', label: 'Phase suggeree', type: 'readonly' },
    { key: 'date_debut', label: 'Date debut du lot', type: 'date', required: true },
    { key: 'duree_cycle_valeur', label: 'Duree cycle', type: 'number' },
    { key: 'duree_cycle_unite', label: 'Unite duree', type: 'select', options: ['jours', 'mois'] },
    { key: 'age_lot_view', label: 'Age du lot', type: 'readonly' },
    { key: 'date_fin_prevue_calculee_view', label: 'Date fin prevue calculee', type: 'readonly' },
    { key: 'date_fin_prevue', label: 'Date fin / vente prevue ajustable', type: 'date' },
    { key: 'date_fin_reelle', label: 'Date fin reelle', type: 'date', showWhen: (form) => ['vendu', 'vendu_partiellement', 'termine', 'perdu', 'reforme', 'pret_a_vendre_reforme'].includes(form.status) },
    { key: 'section_effectifs', label: 'Effectifs & pertes', type: 'section', description: 'Effectif actuel calcule automatiquement. Les malades restent presents dans le lot.' },
    { key: 'initial_count', label: 'Effectif initial', type: 'number' },
    { key: 'mortality', label: 'Morts', type: 'number' },
    { key: 'vols', label: 'Voles', type: 'number' },
    { key: 'vendus', label: 'Vendus', type: 'number' },
    { key: 'reformes', label: 'Reformes', type: 'number' },
    { key: 'sorties', label: 'Autres sorties', type: 'number' },
    { key: 'malades', label: 'Malades / sujets a surveiller', type: 'number' },
    { key: 'current_count', label: 'Effectif actuel calcule', type: 'readonly' },
    { key: 'section_sante', label: 'Sante & statut', type: 'section' },
    { key: 'frais_sante', label: 'Frais sante / soins', type: 'number' },
    { key: 'health_status', label: 'Etat sante lot', type: 'select', options: [
      { value: 'sain', label: 'Sain' },
      { value: 'a_surveiller', label: 'A surveiller' },
      { value: 'malade', label: 'Malade' },
      { value: 'sous_traitement', label: 'Sous traitement' },
      { value: 'critique', label: 'Critique' },
    ] },
    { key: 'status', label: 'Statut operationnel', type: 'select', options: [
      { value: 'actif', label: 'Actif' },
      { value: 'en_croissance', label: 'En croissance' },
      { value: 'en_ponte', label: 'En ponte' },
      { value: 'baisse_ponte', label: 'Baisse ponte' },
      { value: 'a_reformer', label: 'A reformer' },
      { value: 'pret_a_vendre_reforme', label: 'Pret a vendre comme reformees' },
      { value: 'finition', label: 'Finition' },
      { value: 'pret_a_la_vente', label: 'Pret a la vente' },
      { value: 'vendu_partiellement', label: 'Vendu partiellement' },
      { value: 'vendu', label: 'Vendu' },
      { value: 'termine', label: 'Termine' },
      { value: 'perdu', label: 'Perdu' },
    ] },
    { key: 'section_technique', label: 'Indicateurs techniques', type: 'section', description: 'Les indicateurs quotidiens se saisissent dans le journal dedie, pas dans la fiche lot.' },
    { key: 'weight_avg', label: 'Poids moyen (kg)', type: 'number' },
    { key: 'poids_objectif', label: 'Poids objectif vente (kg)', type: 'number', showWhen: (form) => form.type === 'Chair' },
    { key: 'ic', label: 'Indice de consommation (IC)', type: 'number', showWhen: (form) => form.type === 'Chair' },
    { key: 'cout_poussins', label: 'Cout poussins', type: 'number', showWhen: (form) => form.type === 'Chair' },
    { key: 'prix_vente_prevu', label: 'Prix vente prevu', type: 'number', showWhen: (form) => form.type === 'Chair' },
    { key: 'prix_vente_reel', label: 'Prix vente reel', type: 'number', showWhen: (form) => form.type === 'Chair' },
    { key: 'autres_frais', label: 'Autres frais', type: 'number' },
    { key: 'section_calculs', label: 'Calculs automatiques', type: 'section' },
    { key: 'alimentation_calculee_view', label: 'Alimentation calculee totale', type: 'readonly' },
    { key: 'alimentation_tete_view', label: 'Alimentation moyenne / tete', type: 'readonly' },
    { key: 'alimentation_tete_jour_view', label: 'Alimentation moyenne / tete / jour', type: 'readonly' },
    { key: 'marge_calculee_view', label: 'Marge calculee', type: 'readonly' },
    { key: 'section_opportunite', label: 'Opportunite commerciale', type: 'section', description: 'Le systeme recommande, mais la confirmation reste manuelle.' },
    { key: 'sale_readiness_score', label: 'Score pret vente', type: 'readonly' },
    { key: 'sale_readiness_status', label: 'Maturite vente', type: 'select', options: [
      { value: 'non_pret', label: 'Non pret' },
      { value: 'presque_pret', label: 'Presque pret' },
      { value: 'recommande_pret', label: 'Recommande pret' },
      { value: 'pret_confirme', label: 'Pret confirme' },
    ] },
    { key: 'pret_vente_recommande', label: 'Recommande pret vente', type: 'checkbox' },
    { key: 'pret_vente_confirme', label: 'Pret vente confirme', type: 'checkbox' },
    { key: 'raison_pret_vente', label: 'Raisons / criteres manquants', type: 'text', fullWidth: true },
    { key: 'business_plan_id', label: 'Business Plan lie', type: 'text' },
  ],
  sante: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'nom', label: 'Vaccin', type: 'text', required: true },
    { key: 'animal', label: 'Animal', type: 'text' },
    { key: 'prevue', label: 'Date prevue', type: 'date' },
    { key: 'effectuee', label: 'Date effectuee', type: 'date' },
    { key: 'vet', label: 'Veterinaire', type: 'text' },
    { key: 'cout', label: 'Cout intervention (FCFA)', type: 'number' },
    { key: 'statut', label: 'Statut', type: 'select', options: ['fait', 'a_faire', 'retard', 'annule'] },
  ],
  veterinaires: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'nom', label: 'Nom', type: 'text', required: true },
    { key: 'specialite', label: 'Specialite', type: 'text' },
    { key: 'tel', label: 'Telephone', type: 'text' },
    { key: 'whatsapp', label: 'WhatsApp', type: 'text' },
    { key: 'email', label: 'Email', type: 'email' },
    { key: 'gps', label: 'GPS', type: 'text' },
    { key: 'adresse', label: 'Adresse', type: 'text' },
    { key: 'latitude', label: 'Latitude', type: 'number' },
    { key: 'longitude', label: 'Longitude', type: 'number' },
    { key: 'distance_km', label: 'Distance (km)', type: 'number' },
    { key: 'note', label: 'Note', type: 'number' },
    { key: 'source', label: 'Source', type: 'select', options: ['manuel', 'google_places', 'openstreetmap', 'import', 'demo'] },
    { key: 'external_id', label: 'ID source externe', type: 'text' },
    { key: 'verified', label: 'Verifie', type: 'checkbox' },
    { key: 'favorite', label: 'Favori', type: 'checkbox' },
    { key: 'notes', label: 'Notes', type: 'text', fullWidth: true },
  ],
  finances: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'type', label: 'Type', type: 'select', options: [{ value: 'entree', label: 'Argent reçu' }, { value: 'sortie', label: 'Argent dépensé' }] },
    { key: 'libelle', label: 'Libellé simple', type: 'text', required: true },
    { key: 'montant', label: 'Montant', type: 'number', required: true },
    { key: 'date', label: 'Date', type: 'date' },
    { key: 'categorie', label: 'Categorie', type: 'select', options: ['Vente animaux', 'Vente oeufs', 'Vente cultures', 'Alimentation', 'Sante', 'Salaires', 'Transport', 'Energie', 'Investissements', 'Stocks', 'Autre'] },
    { key: 'module_lie', label: 'Module lie', type: 'select', options: ['animaux', 'avicole', 'cultures', 'stock', 'clients', 'fournisseurs', 'investissements', 'autre'] },
    { key: 'related_id', label: 'Fiche liée', type: 'text' },
    { key: 'client_id', label: 'Client lié', type: 'text' },
    { key: 'fournisseur_id', label: 'Fournisseur lié', type: 'text' },
    { key: 'paiement', label: 'Moyen paiement', type: 'select', options: ['Cash', 'Banque', 'Wave', 'Orange Money', 'Free Money', 'Carte bancaire'] },
    { key: 'statut', label: 'Statut paiement', type: 'select', options: ['paye', 'partiel', 'impaye', 'annule'] },
    { key: 'justificatif_url', label: 'Preuve / facture', type: 'image' },
    { key: 'treasury_account_id', label: 'Caisse / banque', type: 'text' },
    { key: 'business_plan_id', label: 'Business Plan lié', type: 'text' },
  ],
  investissements: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'type', label: 'Type', type: 'text' },
    { key: 'libelle', label: 'Libelle', type: 'text', required: true },
    { key: 'montant', label: 'Montant', type: 'number' },
    { key: 'roi', label: 'ROI', type: 'number' },
    { key: 'objectif', label: 'Objectif', type: 'text' },
    { key: 'statut', label: 'Statut', type: 'select', options: ['actif', 'pause', 'termine'] },
    { key: 'gain', label: 'Gain', type: 'number' },
    { key: 'business_plan_id', label: 'Business Plan lie', type: 'text' },
  ],
  business_plans: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'nom', label: 'Nom du business plan', type: 'text', required: true },
    { key: 'activity_type', label: 'Activite', type: 'select', options: [
      { value: 'avicole_pondeuse', label: 'Pondeuses' },
      { value: 'avicole_chair', label: 'Poulets de chair' },
      { value: 'bovin_lait', label: 'Bovins laitiers' },
      { value: 'bovin_embouche', label: 'Bovins embouche' },
      { value: 'ovin_embouche', label: 'Ovins Tabaski / embouche' },
      { value: 'ovin_lait', label: 'Ovins laitiers' },
      { value: 'caprin_embouche', label: 'Caprins viande' },
      { value: 'caprin_lait', label: 'Caprins lait' },
      { value: 'culture_maraichere', label: 'Cultures maraicheres' },
      { value: 'culture_cereale', label: 'Cultures cerealieres' },
      { value: 'culture_arboricole', label: 'Arboriculture' },
      { value: 'infrastructure', label: 'Infrastructure' },
      { value: 'equipement', label: 'Equipement' },
      { value: 'autre', label: 'Autre' },
    ] },
    { key: 'description', label: 'Description', type: 'text', fullWidth: true },
    { key: 'localisation', label: 'Localisation', type: 'text' },
    { key: 'date_debut', label: 'Date debut', type: 'date' },
    { key: 'date_fin_prevue', label: 'Date fin prevue', type: 'date' },
    { key: 'duree_cycle_mois', label: 'Duree cycle (mois)', type: 'number' },
    { key: 'mode_projection', label: 'Mode projection', type: 'select', options: [
      { value: 'vente_fin_cycle', label: 'Vente en fin de cycle' },
      { value: 'vente_progressive', label: 'Vente progressive' },
      { value: 'manuel', label: 'Manuel' },
      { value: 'production_mensuelle', label: 'Production mensuelle' },
      { value: 'recolte_progressive', label: 'Recolte progressive' },
      { value: 'economie_mensuelle', label: 'Economie mensuelle' },
    ] },
    { key: 'capacite_initiale', label: 'Capacite initiale', type: 'number' },
    { key: 'unite_capacite', label: 'Unite capacite', type: 'text' },
    { key: 'objectif_production', label: 'Objectif production', type: 'text' },
    { key: 'statut', label: 'Statut', type: 'select', options: ['planifie', 'en_cours', 'en_production', 'termine', 'abandonne'] },
    { key: 'apport_personnel', label: 'Apport personnel', type: 'number' },
    { key: 'financement_recherche', label: 'Financement recherche', type: 'number' },
    { key: 'taux_remboursement_pct', label: 'Taux remboursement CA (%)', type: 'number' },
    { key: 'unite_calcul_cout', label: 'Unite calcul cout', type: 'select', options: ['tete', 'poulet', 'pondeuse', 'oeuf', 'plateau', 'kg', 'botte', 'caisse', 'm2', 'hectare', 'unite'] },
    { key: 'nombre_tetes_prevu', label: 'Nombre tetes prevu', type: 'number' },
    { key: 'nombre_tetes_reel', label: 'Nombre tetes reel', type: 'number' },
    { key: 'quantite_production_prevue', label: 'Production prevue', type: 'number' },
    { key: 'quantite_production_reelle', label: 'Production reelle', type: 'number' },
    { key: 'prix_vente_prevu_unitaire', label: 'Prix vente prevu unitaire', type: 'number' },
    { key: 'prix_vente_reel_unitaire', label: 'Prix vente reel unitaire', type: 'number' },
    { key: 'notes', label: 'Notes', type: 'text', fullWidth: true },
  ],
  bp_investment_lines: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'business_plan_id', label: 'Business Plan', type: 'text', required: true },
    { key: 'designation', label: 'Designation', type: 'text', required: true },
    { key: 'categorie', label: 'Categorie', type: 'select', options: ['cheptel', 'infrastructure', 'alimentation', 'equipement', 'vaccins', 'main_oeuvre', 'autre'] },
    { key: 'quantite', label: 'Quantite', type: 'number' },
    { key: 'unite', label: 'Unite', type: 'text' },
    { key: 'prix_unitaire', label: 'Prix unitaire', type: 'number' },
    { key: 'ordre', label: 'Ordre', type: 'number' },
    { key: 'notes', label: 'Notes', type: 'text' },
  ],
  bp_recurring_costs: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'business_plan_id', label: 'Business Plan', type: 'text', required: true },
    { key: 'designation', label: 'Designation', type: 'text', required: true },
    { key: 'categorie', label: 'Categorie', type: 'select', options: ['alimentation', 'salaires', 'energie', 'sante_veto', 'logistique', 'imprevus', 'autre'] },
    { key: 'montant_mensuel', label: 'Montant mensuel', type: 'number' },
    { key: 'frequence', label: 'Frequence', type: 'select', options: ['mensuelle', 'trimestrielle', 'annuelle', 'ponctuelle'] },
    { key: 'date_debut', label: 'Date debut', type: 'date' },
    { key: 'date_fin', label: 'Date fin', type: 'date' },
    { key: 'notes', label: 'Notes', type: 'text' },
  ],
  bp_revenue_projections: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'business_plan_id', label: 'Business Plan', type: 'text', required: true },
    { key: 'mois_index', label: 'Mois index', type: 'number', required: true },
    { key: 'date_mois', label: 'Mois', type: 'date' },
    { key: 'capacite_active', label: 'Capacite active', type: 'number' },
    { key: 'production_estimee', label: 'Production estimee', type: 'number' },
    { key: 'unite_production', label: 'Unite production', type: 'text' },
    { key: 'prix_unitaire_estime', label: 'Prix unitaire estime', type: 'number' },
    { key: 'ca_estime', label: 'CA estime calcule', type: 'readonly' },
    { key: 'charges_estimees', label: 'Charges estimees', type: 'number' },
    { key: 'marge_estimee', label: 'Marge estimee calculee', type: 'readonly' },
    { key: 'remboursement_prevu', label: 'Remboursement prevu', type: 'number' },
    { key: 'notes', label: 'Notes', type: 'text' },
  ],
  bp_funding_sources: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'business_plan_id', label: 'Business Plan', type: 'text', required: true },
    { key: 'source_type', label: 'Type financement', type: 'select', options: ['apport_personnel', 'pret_bancaire', 'investisseur_prive', 'subvention', 'partenaire_commercial'] },
    { key: 'nom_source', label: 'Nom source', type: 'text' },
    { key: 'montant', label: 'Montant', type: 'number' },
    { key: 'taux_interet_pct', label: 'Taux interet (%)', type: 'number' },
    { key: 'duree_remboursement_mois', label: 'Duree remboursement (mois)', type: 'number' },
    { key: 'date_obtention', label: 'Date obtention', type: 'date' },
    { key: 'conditions', label: 'Conditions', type: 'text' },
    { key: 'statut', label: 'Statut', type: 'select', options: ['demande', 'accorde', 'refuse', 'rembourse_total', 'rembourse_partiel'] },
    { key: 'notes', label: 'Notes', type: 'text' },
  ],
  bp_risks: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'business_plan_id', label: 'Business Plan', type: 'text', required: true },
    { key: 'categorie', label: 'Categorie', type: 'select', options: ['sanitaire', 'marche', 'concurrence', 'logistique', 'climatique', 'financier'] },
    { key: 'titre', label: 'Titre', type: 'text', required: true },
    { key: 'description', label: 'Description', type: 'text' },
    { key: 'probabilite', label: 'Probabilite', type: 'select', options: ['faible', 'moyenne', 'elevee'] },
    { key: 'impact', label: 'Impact', type: 'select', options: ['faible', 'moyen', 'eleve', 'critique'] },
    { key: 'mesure_attenuation', label: 'Mesure attenuation', type: 'text' },
    { key: 'cout_attenuation', label: 'Cout attenuation', type: 'number' },
    { key: 'statut', label: 'Statut', type: 'select', options: ['identifie', 'traite', 'surveille', 'materialise'] },
  ],
  stock: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'produit', label: 'Produit', type: 'text', required: true },
    { key: 'categorie', label: 'Categorie', type: 'text' },
    { key: 'quantite', label: 'Quantite', type: 'number' },
    { key: 'unite', label: 'Unite', type: 'text' },
    { key: 'seuil', label: 'Seuil', type: 'number' },
    { key: 'prixUnit', label: 'Prix unitaire', type: 'number' },
  ],
  clients: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'photo_url', label: 'Photo / logo', type: 'image' },
    { key: 'nom', label: 'Nom', type: 'text', required: true },
    { key: 'tel', label: 'Telephone', type: 'text' },
    { key: 'whatsapp', label: 'WhatsApp', type: 'text' },
    { key: 'email', label: 'Email', type: 'email' },
    { key: 'adresse', label: 'Adresse', type: 'text' },
    { key: 'gps', label: 'Geolocalisation', type: 'text' },
    { key: 'type', label: 'Type', type: 'text' },
    { key: 'statut', label: 'Statut', type: 'select', options: ['actif', 'inactif', 'VIP', 'a_relancer'] },
    { key: 'score', label: 'Score', type: 'number' },
    { key: 'totalAchats', label: 'Total achats', type: 'number' },
    { key: 'derniereCommande', label: 'Derniere commande', type: 'date' },
    { key: 'prefs', label: 'Preferences', type: 'text' },
    { key: 'historique_achats', label: 'Historique achats', type: 'text' },
    { key: 'historique_communications', label: 'Historique communications', type: 'text' },
    { key: 'notes_internes', label: 'Notes internes', type: 'text' },
  ],
  fournisseurs: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'nom', label: 'Nom', type: 'text', required: true },
    { key: 'tel', label: 'Telephone', type: 'text' },
    { key: 'whatsapp', label: 'WhatsApp', type: 'text' },
    { key: 'email', label: 'Email', type: 'email' },
    { key: 'categorie', label: 'Categorie', type: 'text' },
    { key: 'statut', label: 'Statut', type: 'select', options: ['actif', 'fiable', 'a_risque', 'suspendu'] },
    { key: 'contact', label: 'Contact', type: 'text' },
    { key: 'note', label: 'Note', type: 'number' },
    { key: 'dettes', label: 'Dettes', type: 'number' },
    { key: 'livraisons', label: 'Livraisons', type: 'number' },
    { key: 'source', label: 'Source', type: 'select', options: ['manuel', 'google_places', 'openstreetmap', 'import', 'demo'] },
    { key: 'latitude', label: 'Latitude', type: 'number' },
    { key: 'longitude', label: 'Longitude', type: 'number' },
    { key: 'distance_km', label: 'Distance (km)', type: 'number' },
    { key: 'external_id', label: 'ID source externe', type: 'text' },
    { key: 'verified', label: 'Verifie', type: 'checkbox' },
    { key: 'favorite', label: 'Favori', type: 'checkbox' },
    { key: 'notes', label: 'Notes', type: 'text', fullWidth: true },
  ],
  tracabilite: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'animal', label: 'Animal', type: 'text' },
    { key: 'type', label: 'Type', type: 'text' },
    { key: 'margeFinale', label: 'Marge finale', type: 'number' },
    { key: 'roi', label: 'ROI', type: 'number' },
  ],
  cultures: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'nom', label: 'Culture', type: 'text', required: true },
    { key: 'type', label: 'Type', type: 'select', options: ['Laitue', 'Tomate', 'Poivron', 'Piment', 'Oignon', 'Concombre', 'Herbes aromatiques', 'Autre'] },
    { key: 'variete', label: 'Variete', type: 'text' },
    { key: 'parcelle', label: 'Parcelle', type: 'text' },
    { key: 'surface', label: 'Surface cultivee', type: 'number' },
    { key: 'date_semis', label: 'Date semis', type: 'date' },
    { key: 'date_repiquage', label: 'Date repiquage', type: 'date' },
    { key: 'date_recolte_prevue', label: 'Recolte prevue', type: 'date' },
    { key: 'date_recolte_reelle', label: 'Recolte reelle', type: 'date' },
    { key: 'quantite_prevue', label: 'Quantite prevue', type: 'number' },
    { key: 'quantite_recoltee', label: 'Quantite recoltee', type: 'number' },
    { key: 'pertes', label: 'Pertes', type: 'number' },
    { key: 'cout_semences', label: 'Cout semences', type: 'number' },
    { key: 'cout_engrais', label: 'Cout engrais', type: 'number' },
    { key: 'cout_eau', label: 'Cout eau', type: 'number' },
    { key: 'cout_main_oeuvre', label: 'Cout main oeuvre', type: 'number' },
    { key: 'cout_traitement', label: 'Cout traitement', type: 'number' },
    { key: 'revenu_estime', label: 'Revenu estime', type: 'number' },
    { key: 'revenu_reel', label: 'Revenu reel', type: 'number' },
    { key: 'statut', label: 'Statut', type: 'select', options: ['semis', 'croissance', 'floraison', 'recolte', 'termine', 'perdu'] },
    { key: 'score_sante', label: 'Score sante', type: 'number' },
    { key: 'business_plan_id', label: 'Business Plan lie', type: 'text' },
  ],
  ventes: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'date', label: 'Date', type: 'date' },
    { key: 'client_id', label: 'Client', type: 'text' },
    { key: 'type', label: 'Type', type: 'select', options: ['commande', 'devis', 'facture', 'livraison'] },
    { key: 'produit', label: 'Produit / service', type: 'text', required: true },
    { key: 'quantite', label: 'Quantite', type: 'number' },
    { key: 'montant', label: 'Montant', type: 'number' },
    { key: 'statut', label: 'Statut', type: 'select', options: ['brouillon', 'confirme', 'livre', 'paye', 'annule'] },
    { key: 'paiement', label: 'Paiement', type: 'select', options: ['Cash', 'Banque', 'Wave', 'Orange Money', 'Free Money', 'Carte bancaire'] },
    { key: 'livraison_date', label: 'Date livraison', type: 'date' },
    { key: 'notes', label: 'Notes', type: 'text' },
  ],
  erp_documents: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'title', label: 'Titre', type: 'text', required: true },
    { key: 'document_type', label: 'Type', type: 'select', options: ['contrat', 'ordonnance', 'facture', 'bon_livraison', 'certificat', 'administratif', 'autre'] },
    { key: 'module_lie', label: 'Module lie', type: 'text' },
    { key: 'related_id', label: 'Element lie', type: 'text' },
    { key: 'file_url', label: 'Fichier', type: 'image' },
    { key: 'status', label: 'Statut', type: 'select', options: ['actif', 'archive', 'expire'] },
    { key: 'tags', label: 'Tags', type: 'text' },
  ],
  taches: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'title', label: 'Tache', type: 'text', required: true },
    { key: 'module_lie', label: 'Module lie', type: 'text' },
    { key: 'assigned_to', label: 'Responsable', type: 'text' },
    { key: 'due_date', label: 'Echeance', type: 'date' },
    { key: 'priority', label: 'Priorite', type: 'select', options: ['basse', 'normale', 'haute', 'critique'] },
    { key: 'status', label: 'Statut', type: 'select', options: ['a_faire', 'en_cours', 'termine', 'retard'] },
    { key: 'checklist', label: 'Checklist', type: 'text' },
  ],
  rapports: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'title', label: 'Rapport', type: 'text', required: true },
    { key: 'report_type', label: 'Type', type: 'select', options: ['hebdo_whatsapp', 'mensuel_pdf', 'rentabilite', 'production', 'comptable'] },
    { key: 'period', label: 'Periode', type: 'text' },
    { key: 'status', label: 'Statut', type: 'select', options: ['programme', 'genere', 'envoye', 'archive'] },
    { key: 'channel', label: 'Canal', type: 'select', options: ['ERP', 'WhatsApp', 'PDF', 'Email'] },
    { key: 'file_url', label: 'Fichier', type: 'image' },
    { key: 'summary', label: 'Resume', type: 'text' },
  ],
  equipements: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'name', label: 'Equipement', type: 'text', required: true },
    { key: 'type', label: 'Type', type: 'select', options: ['machine', 'incubateur', 'pompe', 'groupe_electrogene', 'vehicule', 'outil', 'autre'] },
    { key: 'status', label: 'Statut', type: 'select', options: ['operationnel', 'maintenance', 'panne', 'hors_service'] },
    { key: 'purchase_date', label: 'Date achat', type: 'date' },
    { key: 'purchase_cost', label: 'Cout achat', type: 'number' },
    { key: 'maintenance_due', label: 'Prochaine maintenance', type: 'date' },
    { key: 'fuel_cost', label: 'Carburant', type: 'number' },
    { key: 'notes', label: 'Notes', type: 'text' },
  ],
  audit_logs: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'actor', label: 'Utilisateur', type: 'text' },
    { key: 'action', label: 'Action', type: 'text' },
    { key: 'module', label: 'Module', type: 'text' },
    { key: 'record_id', label: 'Element', type: 'text' },
    { key: 'device', label: 'Appareil', type: 'text' },
    { key: 'created_at', label: 'Date', type: 'text' },
  ],
  alimentation_logs: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'date', label: 'Date', type: 'date', required: true },
    { key: 'categorie', label: 'Categorie', type: 'select', options: ['bovin', 'ovin', 'caprin', 'pondeuse', 'poulet_chair'] },
    { key: 'type_cible', label: 'Type cible', type: 'select', options: ['categorie_animale', 'lot_avicole'] },
    { key: 'cible_id', label: 'ID cible / lot', type: 'text' },
    { key: 'quantite', label: 'Quantite', type: 'number' },
    { key: 'unite', label: 'Unite', type: 'text' },
    { key: 'montant_total', label: 'Montant total', type: 'number' },
    { key: 'duree_jours', label: 'Duree couverte (jours)', type: 'number' },
    { key: 'fournisseur_id', label: 'Fournisseur', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'text' },
  ],
  production_oeufs_logs: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'lot_id', label: 'Lot pondeuse', type: 'text', required: true },
    { key: 'date', label: 'Date', type: 'date', required: true },
    { key: 'oeufs_produits', label: 'Oeufs produits', type: 'number' },
    { key: 'oeufs_casses', label: 'Oeufs casses', type: 'number' },
    { key: 'oeufs_vendables_view', label: 'Oeufs vendables calcules', type: 'readonly' },
    { key: 'plateaux_view', label: 'Plateaux calcules', type: 'readonly' },
    { key: 'taux_ponte_view', label: 'Taux ponte calcule', type: 'readonly' },
    { key: 'notes', label: 'Notes', type: 'text', fullWidth: true },
  ],
  sensor_devices: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'name', label: 'Nom capteur', type: 'text', required: true },
    { key: 'type', label: 'Type', type: 'select', options: ['temperature', 'humidite', 'eau', 'energie', 'porte', 'mouvement', 'air', 'autre'] },
    { key: 'zone', label: 'Zone', type: 'text' },
    { key: 'location', label: 'Localisation', type: 'text' },
    { key: 'status', label: 'Statut', type: 'select', options: ['online', 'offline', 'simulation', 'maintenance'] },
    { key: 'source_type', label: 'Source', type: 'select', options: ['simulation', 'reel'] },
    { key: 'module_lie', label: 'Module lié', type: 'select', options: ['smartfarm', 'cultures', 'avicole', 'stock', 'equipements'] },
    { key: 'value', label: 'Dernière mesure', type: 'number' },
    { key: 'seuil_min', label: 'Seuil minimum', type: 'number' },
    { key: 'seuil_max', label: 'Seuil maximum', type: 'number' },
    { key: 'battery_level', label: 'Batterie (%)', type: 'number' },
    { key: 'notes', label: 'Notes terrain', type: 'text', fullWidth: true },
  ],
  camera_devices: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'name', label: 'Nom camera', type: 'text', required: true },
    { key: 'zone', label: 'Zone', type: 'text' },
    { key: 'type', label: 'Type', type: 'select', options: ['RTSP', 'ONVIF', 'IP', 'simulation'] },
    { key: 'source_type', label: 'Source', type: 'select', options: ['simulation', 'reel'] },
    { key: 'module_lie', label: 'Module lié', type: 'select', options: ['smartfarm', 'cultures', 'avicole', 'stock', 'equipements'] },
    { key: 'stream_url', label: 'URL flux', type: 'text' },
    { key: 'snapshot_url', label: 'URL snapshot', type: 'text' },
    { key: 'status', label: 'Statut', type: 'select', options: ['online', 'offline', 'simulation', 'maintenance'] },
    { key: 'notes', label: 'Notes terrain', type: 'text', fullWidth: true },
  ],
  business_events: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'event_type', label: 'Type evenement', type: 'text', required: true },
    { key: 'module_source', label: 'Module source', type: 'select', options: ['animaux', 'avicole', 'cultures', 'stocks', 'finances', 'ventes', 'sante', 'tracabilite', 'documents', 'autre'] },
    { key: 'entity_type', label: 'Type entite', type: 'select', options: ['animal', 'lot_avicole', 'culture', 'stock', 'transaction', 'vente', 'document', 'autre'] },
    { key: 'entity_id', label: 'ID entite liee', type: 'text' },
    { key: 'title', label: 'Titre', type: 'text', required: true },
    { key: 'description', label: 'Description', type: 'text', fullWidth: true },
    { key: 'amount', label: 'Montant', type: 'number' },
    { key: 'event_date', label: 'Date evenement', type: 'date' },
    { key: 'severity', label: 'Gravite', type: 'select', options: ['info', 'warning', 'critique', 'urgence'] },
  ],
  alertes_center: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'title', label: 'Titre', type: 'text', required: true },
    { key: 'message', label: 'Message', type: 'text', fullWidth: true },
    { key: 'module_source', label: 'Module', type: 'select', options: ['animaux', 'avicole', 'cultures', 'stock', 'finances', 'ventes', 'clients', 'fournisseurs', 'sante', 'documents', 'taches', 'equipements', 'smartfarm', 'meteo', 'autre'] },
    { key: 'entity_type', label: 'Type entite', type: 'text' },
    { key: 'entity_id', label: 'ID entite', type: 'text' },
    { key: 'severity', label: 'Gravite', type: 'select', options: ['info', 'warning', 'critique', 'urgence'] },
    { key: 'status', label: 'Statut', type: 'select', options: ['nouvelle', 'lue', 'traitee', 'ignoree'] },
    { key: 'action_recommandee', label: 'Action recommandee', type: 'text', fullWidth: true },
    { key: 'send_whatsapp', label: 'Envoyer WhatsApp', type: 'checkbox' },
  ],
  documents: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'title', label: 'Titre', type: 'text', required: true },
    { key: 'document_category', label: 'Categorie', type: 'select', options: ['facture', 'recu', 'ordonnance', 'certificat', 'contrat', 'bon_livraison', 'photo', 'rapport', 'autre'] },
    { key: 'file_url', label: 'Fichier', type: 'image' },
    { key: 'file_type', label: 'Type fichier', type: 'select', options: ['pdf', 'image', 'word', 'excel', 'autre'] },
    { key: 'module_source', label: 'Module', type: 'select', options: ['animaux', 'avicole', 'cultures', 'stock', 'finances', 'ventes', 'sante', 'fournisseurs', 'clients', 'autre'] },
    { key: 'entity_type', label: 'Type entite', type: 'text' },
    { key: 'entity_id', label: 'ID entite liee', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'text', fullWidth: true },
  ],
  sales_orders: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'date', label: 'Date', type: 'date', required: true },
    { key: 'client_id', label: 'Client', type: 'text' },
    { key: 'type_document', label: 'Type document', type: 'select', options: ['devis', 'commande', 'facture', 'vente_directe'] },
    { key: 'montant_total', label: 'Montant total', type: 'number' },
    { key: 'remise', label: 'Remise', type: 'number' },
    { key: 'moyen_paiement', label: 'Moyen paiement', type: 'select', options: ['Cash', 'Banque', 'Wave', 'Orange Money', 'Free Money', 'Carte bancaire'] },
    { key: 'statut_commande', label: 'Statut commande', type: 'select', options: ['brouillon', 'confirme', 'prepare', 'livre', 'annule'] },
    { key: 'statut_paiement', label: 'Statut paiement', type: 'select', options: ['non_paye', 'partiel', 'paye', 'rembourse'] },
    { key: 'statut_livraison', label: 'Statut livraison', type: 'select', options: ['a_livrer', 'en_livraison', 'livre', 'retire_sur_place', 'annule'] },
    { key: 'notes', label: 'Notes', type: 'text', fullWidth: true },
  ],
  sales_order_items: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'order_id', label: 'Commande', type: 'text', required: true },
    { key: 'source_type', label: 'Source', type: 'select', options: ['stock', 'lot_avicole', 'animal', 'culture', 'autre'] },
    { key: 'source_id', label: 'ID source', type: 'text' },
    { key: 'product_name', label: 'Produit', type: 'text', required: true },
    { key: 'quantity', label: 'Quantite', type: 'number', required: true },
    { key: 'unit', label: 'Unite', type: 'select', options: ['kg', 'plateau', 'tete', 'caisse', 'botte', 'sac', 'litre', 'unite'] },
    { key: 'unit_price', label: 'Prix unitaire', type: 'number' },
    { key: 'discount', label: 'Remise', type: 'number' },
    { key: 'total', label: 'Total', type: 'number' },
    { key: 'cost_estimated', label: 'Cout estime', type: 'number' },
    { key: 'margin_estimated', label: 'Marge estimee', type: 'number' },
  ],
  deliveries: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'order_id', label: 'Commande', type: 'text', required: true },
    { key: 'date_livraison', label: 'Date livraison', type: 'date' },
    { key: 'statut', label: 'Statut', type: 'select', options: ['prevue', 'en_cours', 'livree', 'annulee'] },
    { key: 'destinataire', label: 'Destinataire', type: 'text' },
    { key: 'adresse', label: 'Adresse', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'text', fullWidth: true },
  ],
  invoices: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'order_id', label: 'Commande', type: 'text', required: true },
    { key: 'numero_facture', label: 'Numero facture', type: 'text' },
    { key: 'date_facture', label: 'Date facture', type: 'date' },
    { key: 'montant_total', label: 'Montant total', type: 'number' },
    { key: 'statut', label: 'Statut', type: 'select', options: ['emise', 'payee', 'annulee', 'remboursee'] },
  ],
  payments: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'order_id', label: 'Commande', type: 'text' },
    { key: 'invoice_id', label: 'Facture', type: 'text' },
    { key: 'date_paiement', label: 'Date paiement', type: 'date', required: true },
    { key: 'montant', label: 'Montant', type: 'number', required: true },
    { key: 'moyen_paiement', label: 'Moyen paiement', type: 'select', options: ['Cash', 'Banque', 'Wave', 'Orange Money', 'Free Money', 'Carte bancaire'] },
    { key: 'reference', label: 'Reference', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'text' },
  ],
  sales_opportunities: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'opportunity_type', label: 'Type', type: 'select', options: ['animal', 'lot_avicole', 'culture', 'stock', 'client'] },
    { key: 'source_type', label: 'Source', type: 'select', options: ['animal', 'lot', 'culture', 'stock', 'libre'] },
    { key: 'source_id', label: 'ID source', type: 'text' },
    { key: 'title', label: 'Titre', type: 'text', required: true },
    { key: 'description', label: 'Description', type: 'text' },
    { key: 'quantity', label: 'Quantite', type: 'number' },
    { key: 'unit', label: 'Unite', type: 'text' },
    { key: 'estimated_value', label: 'Valeur estimee', type: 'number' },
    { key: 'estimated_margin', label: 'Marge estimee', type: 'number' },
    { key: 'score', label: 'Score (0-100)', type: 'number' },
    { key: 'reason', label: 'Raison', type: 'text', fullWidth: true },
    { key: 'status', label: 'Statut', type: 'select', options: ['a_traiter', 'en_discussion', 'reserve', 'converti', 'ignore'] },
  ],
};
