export const MODULE_CONFIG = {
  dashboard: { label: 'Dashboard', table: null, idField: 'id' },
  animaux: { label: 'Animaux', table: 'animals', idField: 'id', idPrefix: 'BOV' },
  avicole: { label: 'Avicole', table: 'lots', idField: 'id', idPrefix: 'LOTPO' },
  sante: { label: 'Sante', table: 'vaccins', idField: 'id', idPrefix: 'VAC' },
  veterinaires: { label: 'Veterinaires', table: 'veterinaires', idField: 'id', idPrefix: 'VET' },
  finances: { label: 'Finances', table: 'transactions', idField: 'id', idPrefix: 'TRX' },
  comptabilite: { label: 'Comptabilite', table: null, idField: 'id', idPrefix: 'ACC' },
  investissements: { label: 'Investissements', table: 'investissements', idField: 'id', idPrefix: 'INV' },
  business_plans: { label: 'Business Plans', table: 'business_plans', idField: 'id', idPrefix: 'BP' },
  bp_investment_lines: { label: 'Lignes investissement BP', table: 'bp_investment_lines', idField: 'id', idPrefix: 'BPLI' },
  bp_recurring_costs: { label: 'Charges recurrentes BP', table: 'bp_recurring_costs', idField: 'id', idPrefix: 'BPCOST' },
  bp_revenue_projections: { label: 'Projections BP', table: 'bp_revenue_projections', idField: 'id', idPrefix: 'BPREV' },
  bp_funding_sources: { label: 'Financements BP', table: 'bp_funding_sources', idField: 'id', idPrefix: 'BPFUND' },
  bp_links: { label: 'Liens BP', table: 'bp_links', idField: 'id', idPrefix: 'BPLINK' },
  bp_risks: { label: 'Risques BP', table: 'bp_risks', idField: 'id', idPrefix: 'BPRISK' },
  price_catalog: { label: 'Catalogue prix', table: 'price_catalog', idField: 'id', idPrefix: 'PRICE' },
  bp_versions: { label: 'Versions BP', table: 'bp_versions', idField: 'id', idPrefix: 'BPVER' },
  bp_lines_history: { label: 'Historique lignes BP', table: 'bp_lines_history', idField: 'id', idPrefix: 'BPHIST' },
  stock: { label: 'Stock', table: 'stocks', idField: 'id', idPrefix: 'STK' },
  clients: { label: 'Clients', table: 'clients', idField: 'id', idPrefix: 'CLI' },
  fournisseurs: { label: 'Fournisseurs', table: 'fournisseurs', idField: 'id', idPrefix: 'FOU' },
  tracabilite: { label: 'Tracabilite', table: 'tracabilite', idField: 'id', idPrefix: 'TRA' },
  business_events: { label: 'Evenements', table: 'business_events', idField: 'id', idPrefix: 'EVT' },
  alertes_center: { label: 'Alertes', table: 'alertes_center', idField: 'id', idPrefix: 'ALE' },
  whatsapp_templates: { label: 'Templates WhatsApp', table: 'whatsapp_templates', idField: 'id', idPrefix: 'WTP' },
  whatsapp_logs: { label: 'Logs WhatsApp', table: 'whatsapp_logs', idField: 'id', idPrefix: 'WTL' },
  cultures: { label: 'Cultures', table: 'cultures', idField: 'id', idPrefix: 'CULT' },
  ventes: { label: 'Ventes', table: 'sales_orders', idField: 'id', idPrefix: 'CMD' },
  sales_orders: { label: 'Commandes', table: 'sales_orders', idField: 'id', idPrefix: 'CMD' },
  sales_order_items: { label: 'Lignes commande', table: 'sales_order_items', idField: 'id', idPrefix: 'CMDI' },
  deliveries: { label: 'Livraisons', table: 'deliveries', idField: 'id', idPrefix: 'LIV' },
  invoices: { label: 'Factures', table: 'invoices', idField: 'id', idPrefix: 'FAC' },
  payments: { label: 'Paiements', table: 'payments', idField: 'id', idPrefix: 'PAI' },
  sales_opportunities: { label: 'Opportunites vente', table: 'sales_opportunities', idField: 'id', idPrefix: 'OPP' },
  documents: { label: 'Documents', table: 'documents', idField: 'id', idPrefix: 'DOC' },
  taches: { label: 'Taches', table: 'tasks', idField: 'id', idPrefix: 'TSK' },
  rapports: { label: 'Rapports', table: 'reports', idField: 'id', idPrefix: 'RPT' },
  equipements: { label: 'Equipements', table: 'equipment', idField: 'id', idPrefix: 'EQP' },
  audit_logs: { label: 'Audit logs', table: 'audit_logs', idField: 'id', idPrefix: 'LOG' },
  alimentation_logs: { label: 'Alimentation', table: 'alimentation_logs', idField: 'id', idPrefix: 'ALIM' },
  production_oeufs_logs: { label: 'Production oeufs', table: 'production_oeufs_logs', idField: 'id', idPrefix: 'PROD' },
  sensor_devices: { label: 'Capteurs', table: 'sensor_devices', idField: 'id', idPrefix: 'SENS' },
  sensor_readings: { label: 'Mesures capteurs', table: 'sensor_readings', idField: 'id', idPrefix: 'READ' },
  camera_devices: { label: 'Cameras', table: 'camera_devices', idField: 'id', idPrefix: 'CAM' },
};

export const MODULE_FORM_FIELDS = {
  taches: [
    { key: 'id', label: 'ID', type: 'text', required: true },
    { key: 'title', label: 'Action à faire', type: 'text', required: true },
    { key: 'module_lie', label: 'Module concerné', type: 'text' },
    { key: 'assigned_to', label: 'Responsable', type: 'text' },
    { key: 'due_date', label: 'Échéance', type: 'date' },
    { key: 'priority', label: 'Priorité', type: 'select', options: ['basse', 'normale', 'haute', 'critique'] },
    { key: 'status', label: 'Statut', type: 'select', options: ['a_faire', 'en_cours', 'termine', 'retard'] },
    { key: 'checklist', label: 'Étapes optionnelles', type: 'text', fullWidth: true },
  ],
};
