import { toNumber } from './format';

const arr = (value) => Array.isArray(value) ? value : [];
const clean = (value) => String(value || '').trim().toLowerCase();
const amountOf = (row = {}) => toNumber(row.montant ?? row.amount ?? row.total ?? row.montant_total ?? row.total_amount ?? row.cout ?? row.coût ?? row.cost ?? 0);
const orderAmount = (order = {}) => toNumber(order.montant_total ?? order.total ?? order.amount ?? order.total_amount ?? 0);
const orderPaidField = (order = {}) => toNumber(order.montant_paye ?? order.paid_amount ?? order.amount_paid ?? 0);
const paymentAmount = (payment = {}) => toNumber(payment.montant_paye ?? payment.montant ?? payment.amount ?? payment.paid_amount ?? 0);
const paymentOrderId = (payment = {}) => payment.order_id || payment.sale_id || payment.source_record_id || payment.related_id;
const isCancelled = (row = {}) => ['annule', 'annulee', 'cancelled', 'rejete'].includes(clean(row.statut || row.status || row.statut_commande));
const isIn = (row = {}) => ['entree', 'entrée', 'income', 'in'].includes(clean(row.type));
const isOut = (row = {}) => ['sortie', 'expense', 'out', 'charge', 'depense', 'dépense'].includes(clean(row.type));
const isPaid = (row = {}) => !['impaye', 'partiel', 'en_retard', 'annule', 'annulee'].includes(clean(row.statut || row.status || 'paye'));
const isReceivableTx = (row = {}) => isIn(row) && ['impaye', 'partiel', 'en_retard'].includes(clean(row.statut || row.status));
const isSalesLikeTx = (tx = {}) => ['vente', 'ventes', 'client', 'clients'].some((key) => clean(`${tx.categorie || ''} ${tx.module_lie || ''} ${tx.source_module || ''} ${tx.libelle || ''}`).includes(key));
const isLossEvent = (event = {}) => ['perte_animal', 'perte_avicole', 'perte_culturale'].includes(clean(event.type_evenement || event.event_type)) || clean(`${event.title || ''} ${event.description || ''}`).includes('perte');
const eventAmount = (event = {}) => toNumber(event.montant ?? event.amount ?? event.valeur_perte_estimee ?? event.total ?? 0);
const firstPositive = (...values) => values.map((value) => toNumber(value)).find((value) => value > 0) || 0;

function keyForTransaction(tx = {}) { return [tx.source_module || tx.module_lie || 'finance', tx.source_record_id || tx.related_id || tx.order_id || tx.sale_id || tx.payment_id || tx.invoice_id || tx.id].map((v) => String(v || '').trim()).join(':'); }
function keyForLossEvent(event = {}) { return [event.module || event.source_type || 'perte', event.source_id || event.source_record_id || event.related_id || event.id].map((v) => String(v || '').trim()).join(':'); }
function animalCosts(animal = {}) { const achat = firstPositive(animal.purchase_cost, animal.prix_achat, animal.cout_achat, animal.cost_purchase); const alimentation = firstPositive(animal.alimentation, animal.cout_alimentation, animal.feed_cost, animal.cout_nourriture); const sante = firstPositive(animal.sante, animal.cout_sante, animal.health_cost, animal.vet_cost); const autres = firstPositive(animal.autres_frais, animal.frais_directs, animal.other_costs, animal.direct_costs); const totalDirect = firstPositive(animal.cout_total, animal.total_cost, animal.cost_total); const componentTotal = achat + alimentation + sante + autres; const total = totalDirect > 0 ? totalDirect : componentTotal; return { achat, alimentation, sante, autres, total }; }
function lotCosts(lot = {}) { const poussins = firstPositive(lot.cout_poussins, lot.purchase_cost, lot.cout_achat, lot.cost_purchase); const aliment = firstPositive(lot.cout_aliment, lot.alimentation, lot.cout_alimentation, lot.feed_cost); const sante = firstPositive(lot.frais_sante, lot.cout_sante, lot.sante, lot.health_cost); const pertes = firstPositive(lot.cout_pertes, lot.pertes_valeur, lot.loss_cost); const autres = firstPositive(lot.autres_frais, lot.frais_directs, lot.other_costs); const totalDirect = firstPositive(lot.cout_total, lot.total_cost, lot.cost_total); const componentTotal = poussins + aliment + sante + pertes + autres; const total = totalDirect > 0 ? totalDirect : componentTotal; return { poussins, aliment, sante, pertes, autres, total }; }
function cultureCosts(culture = {}) { const semences = firstPositive(culture.cout_semences, culture.semences_cost, culture.seed_cost); const engrais = firstPositive(culture.cout_engrais, culture.engrais_cost, culture.fertilizer_cost); const eau = firstPositive(culture.cout_eau, culture.cout_irrigation, culture.water_cost, culture.irrigation_cost); const mainOeuvre = firstPositive(culture.cout_main_oeuvre, culture.cout_mo, culture.labor_cost); const traitements = firstPositive(culture.cout_traitement, culture.cout_traitements, culture.treatment_cost); const pertes = firstPositive(culture.cout_pertes, culture.pertes_valeur, culture.loss_cost); const autres = firstPositive(culture.autres_frais, culture.frais_directs, culture.other_costs); const totalDirect = firstPositive(culture.cout_total, culture.total_cost, culture.cost_total); const componentTotal = semences + engrais + eau + mainOeuvre + traitements + pertes + autres; const total = totalDirect > 0 ? totalDirect : componentTotal; return { semences, engrais, eau, mainOeuvre, traitements, pertes, autres, total }; }
function healthCost(row = {}) { return firstPositive(row.cout, row.coût, row.montant, row.amount, row.cout_sante, row.health_cost, row.vet_cost, row.prix, row.price); }
function investmentCost(row = {}) { return firstPositive(row.montant, row.amount, row.total, row.cout, row.coût, row.budget, row.cost, row.prix, row.price); }
function stockValueOf(item = {}) { return firstPositive(item.valeur, item.valeur_stock, item.value, item.total, toNumber(item.quantite ?? item.quantity) * toNumber(item.prix_unitaire ?? item.prixUnit ?? item.prixunit ?? item.unit_price)); }
function stockPurchaseCost(item = {}) {
  const explicitCost = firstPositive(item.purchase_cost, item.cout_achat, item.cout_total_achat, item.montant_achat, item.montant_total_achat, item.last_purchase_amount, item.last_entry_amount, item.total_achat);
  if (explicitCost > 0) return explicitCost;
  const movement = clean(`${item.last_movement_type || ''} ${item.mouvement || ''} ${item.source_module || ''} ${item.notes || ''}`);
  const isRealEntry = ['achat', 'entree_stock', 'entrée_stock', 'approvisionnement', 'reception', 'réception'].some((word) => movement.includes(word));
  return isRealEntry ? stockValueOf(item) : 0;
}
function deriveBusinessCharges({ animaux = [], lots = [], cultures = [], stocks = [], fournisseurs = [], sante = [], alimentationLogs = [], productionLogs = [], investissements = [], businessEvents = [] } = {}) {
  const animalBreakdown = arr(animaux).map(animalCosts); const lotBreakdown = arr(lots).map(lotCosts); const cultureBreakdown = arr(cultures).map(cultureCosts);
  const animalFieldTotal = animalBreakdown.reduce((sum, item) => sum + item.total, 0); const lotFieldTotal = lotBreakdown.reduce((sum, item) => sum + item.total, 0); const cultureTotal = cultureBreakdown.reduce((sum, item) => sum + item.total, 0);
  const unified = summarizeUnifiedFarmCosts({ animaux, lots, alimentationLogs, productionLogs, vaccins: sante, healthEvents: businessEvents, directCharges: businessEvents });
  const animalTotal = mergeFieldAndUnifiedTotals(animalFieldTotal, unified.animaux.totalCost);
  const lotTotal = mergeFieldAndUnifiedTotals(lotFieldTotal, unified.avicole.totalCost);
  const stockPurchases = arr(stocks).reduce((sum, item) => sum + stockPurchaseCost(item), 0);
  const healthTotal = arr(sante).reduce((sum, row) => sum + healthCost(row), 0); const alimentationTotal = arr(alimentationLogs).reduce((sum, row) => sum + firstPositive(row.cout, row.coût, row.montant, row.amount, row.total, row.cout_total), 0); const investmentTotal = arr(investissements).reduce((sum, row) => sum + investmentCost(row), 0); const supplierDebt = arr(fournisseurs).reduce((sum, supplier) => sum + firstPositive(supplier.dettes, supplier.dette, supplier.solde_du, supplier.montant_du), 0);
  const eventCharges = arr(businessEvents).reduce((sum, event) => { if (isLossEvent(event)) return sum; const kind = clean(`${event.type_evenement || ''} ${event.event_type || ''} ${event.title || ''} ${event.description || ''}`); const looksLikeCost = ['charge', 'cout', 'coût', 'depense', 'dépense', 'maintenance', 'sante', 'santé', 'aliment', 'investissement'].some((word) => kind.includes(word)); return sum + (looksLikeCost ? eventAmount(event) : 0); }, 0);
  const total = animalTotal + lotTotal + cultureTotal + stockPurchases + healthTotal + alimentationTotal + investmentTotal + supplierDebt + eventCharges;
  return { animaux: animalTotal, avicole: lotTotal, cultures: cultureTotal, stockAchats: stockPurchases, sante: healthTotal, alimentation: alimentationTotal, investissements: investmentTotal, dettesFournisseurs: supplierDebt, evenements: eventCharges, total, details: { animaux: animalBreakdown, avicole: lotBreakdown, cultures: cultureBreakdown } };
}
function expenseCoverageRatio(txExpenses = 0, derivedTotal = 0) { if (derivedTotal <= 0) return txExpenses > 0 ? 1 : 0; return Math.min(1, txExpenses / derivedTotal); }
function reconcileCharges({ txExpenses = 0, derivedCharges = {} }) { const derivedTotal = toNumber(derivedCharges.total); if (txExpenses <= 0) return { chargesMetier: derivedTotal, chargesComptabilisees: 0, chargesDeriveesNonComptabilisees: derivedTotal, coverageRatio: 0, mode: 'derived_only' }; if (derivedTotal <= 0) return { chargesMetier: txExpenses, chargesComptabilisees: txExpenses, chargesDeriveesNonComptabilisees: 0, coverageRatio: 1, mode: 'finance_only' }; const coverageRatio = expenseCoverageRatio(txExpenses, derivedTotal); const nonAccounted = Math.max(0, derivedTotal - txExpenses); return { chargesMetier: txExpenses + nonAccounted, chargesComptabilisees: txExpenses, chargesDeriveesNonComptabilisees: nonAccounted, coverageRatio, mode: nonAccounted > 0 ? 'finance_plus_unposted_derived' : 'finance_covers_derived' }; }
export function paymentsForOrder(order = {}, payments = []) { const orderId = String(order.id || ''); return arr(payments).filter((payment) => !isCancelled(payment) && String(paymentOrderId(payment) || '') === orderId); }
export function calculateOrderSettlement(order = {}, payments = []) { const total = orderAmount(order); const linkedPayments = paymentsForOrder(order, payments); const paidFromPayments = linkedPayments.reduce((sum, payment) => sum + paymentAmount(payment), 0); const paidRaw = Math.max(orderPaidField(order), paidFromPayments); const paid = total > 0 ? Math.min(total, paidRaw) : paidRaw; const overpaid = total > 0 ? Math.max(0, paidRaw - total) : 0; const remaining = Math.max(0, total - paid); const paymentStatus = total <= 0 ? 'non_paye' : remaining <= 0 ? 'paye' : paid > 0 ? 'partiel' : 'non_paye'; const orderStatus = isCancelled(order) ? 'annule' : paymentStatus !== 'non_paye' ? 'confirme' : total > 0 ? 'enregistree' : 'brouillon'; return { total, paid, paidRaw, overpaid, remaining, paymentStatus, orderStatus, linkedPayments }; }
export function calculateClientSettlement(client = {}, orders = [], payments = []) { const clientOrders = arr(orders).filter((order) => String(order.client_id || '') === String(client.id || '') && !isCancelled(order)); const details = clientOrders.map((order) => ({ order, ...calculateOrderSettlement(order, payments) })); const total = details.reduce((sum, item) => sum + item.total, 0); const paid = details.reduce((sum, item) => sum + item.paid, 0); const remaining = details.reduce((sum, item) => sum + item.remaining, 0); return { clientId: client.id, orders: details, total, paid, remaining, openOrders: details.filter((item) => item.remaining > 0), status: remaining > 0 ? 'a_relancer' : total > 0 ? 'actif' : (client.statut || 'prospect') }; }
export function consolidateFinance({ transactions = [], salesOrders = [], payments = [], fournisseurs = [], stocks = [], animaux = [], lots = [], cultures = [], sante = [], alimentationLogs = [], investissements = [], businessEvents = [] } = {}) {
  const orders = arr(salesOrders).filter((order) => !isCancelled(order)); const txRows = arr(transactions).filter((tx) => Math.abs(amountOf(tx)) > 0 && !isCancelled(tx)); const paymentRows = arr(payments).filter((payment) => paymentAmount(payment) > 0 && !isCancelled(payment)); const lossEvents = arr(businessEvents).filter((event) => isLossEvent(event) && eventAmount(event) > 0 && !isCancelled(event)); const derivedCharges = deriveBusinessCharges({ animaux, lots, cultures, stocks, fournisseurs, sante, alimentationLogs, investissements, businessEvents });
  const lossEventMap = new Map(); lossEvents.forEach((event) => { const key = keyForLossEvent(event); const existing = lossEventMap.get(key); if (!existing || eventAmount(event) >= eventAmount(existing)) lossEventMap.set(key, event); }); const uniqueLossEvents = Array.from(lossEventMap.values()); const lossCharges = uniqueLossEvents.reduce((sum, event) => sum + eventAmount(event), 0);
  const orderSettlements = orders.map((order) => ({ order, ...calculateOrderSettlement(order, paymentRows) })); const caFacture = orderSettlements.reduce((sum, item) => sum + item.total, 0); const cashOrders = orderSettlements.reduce((sum, item) => sum + item.paid, 0); const creancesCommandes = orderSettlements.reduce((sum, item) => sum + item.remaining, 0); const overpaidOrders = orderSettlements.reduce((sum, item) => sum + item.overpaid, 0);
  const transactionMap = new Map(); txRows.forEach((tx) => { const key = keyForTransaction(tx); const existing = transactionMap.get(key); if (!existing || Math.abs(amountOf(tx)) >= Math.abs(amountOf(existing))) transactionMap.set(key, tx); }); const uniqueTransactions = Array.from(transactionMap.values());
  const txCashIn = uniqueTransactions.filter((tx) => isIn(tx) && isPaid(tx) && isSalesLikeTx(tx)).reduce((sum, tx) => sum + amountOf(tx), 0); const otherCashIn = uniqueTransactions.filter((tx) => isIn(tx) && isPaid(tx) && !isSalesLikeTx(tx)).reduce((sum, tx) => sum + amountOf(tx), 0); const txReceivables = uniqueTransactions.filter(isReceivableTx).reduce((sum, tx) => sum + amountOf(tx), 0); const txExpenses = uniqueTransactions.filter(isOut).reduce((sum, tx) => sum + amountOf(tx), 0); const paidExpenses = uniqueTransactions.filter((tx) => isOut(tx) && isPaid(tx)).reduce((sum, tx) => sum + amountOf(tx), 0); const supplierDebt = arr(fournisseurs).reduce((sum, supplier) => sum + toNumber(supplier.dettes ?? supplier.dette ?? supplier.solde_du ?? supplier.montant_du), 0); const stockValue = arr(stocks).reduce((sum, item) => sum + toNumber(item.quantite ?? item.quantity) * toNumber(item.prix_unitaire ?? item.prixUnit ?? item.prixunit ?? item.unit_price), 0); const orphanPayments = paymentRows.filter((payment) => !paymentOrderId(payment)); const orphanPaymentsTotal = orphanPayments.reduce((sum, payment) => sum + paymentAmount(payment), 0);
  const salesCashRaw = Math.max(cashOrders, txCashIn); const cashEncaisse = caFacture > 0 ? Math.min(caFacture, salesCashRaw) : salesCashRaw; const creancesReelles = Math.max(0, caFacture - cashEncaisse, creancesCommandes); const caConsolide = caFacture;
  const chargeRecon = reconcileCharges({ txExpenses, derivedCharges }); const chargesMetier = chargeRecon.chargesMetier; const chargesEngagees = chargesMetier + lossCharges; const chargesPayees = paidExpenses > 0 ? paidExpenses : Math.min(chargesMetier, chargeRecon.chargesComptabilisees || chargesMetier); const cashNet = cashEncaisse + otherCashIn + orphanPaymentsTotal - chargesPayees; const margeReelle = caConsolide - chargesEngagees;
  const warnings = [];
  if (orphanPayments.length) warnings.push(`${orphanPayments.length} paiement(s) sans vente liée`); if (overpaidOrders > 0) warnings.push(`${overpaidOrders} FCFA reçus en trop par rapport aux ventes liées`); if (txReceivables > 0 && creancesCommandes > 0) warnings.push('Reste à encaisser présent à deux endroits : anti-doublon appliqué'); if (lossCharges > 0) warnings.push(`${lossCharges} FCFA de pertes intégrées aux coûts sans sortie de caisse`); if (txExpenses <= 0 && derivedCharges.total > 0) warnings.push('Dépenses Finance absentes : coûts estimés depuis les modules métier'); if (txExpenses > 0 && chargeRecon.chargesDeriveesNonComptabilisees > 0) warnings.push(`${chargeRecon.chargesDeriveesNonComptabilisees} FCFA de coûts métier non retrouvés dans les lignes finance`); if (derivedCharges.total <= 0 && (arr(animaux).length || arr(lots).length || arr(cultures).length || arr(sante).length || arr(alimentationLogs).length || arr(investissements).length)) warnings.push('Coûts métier à zéro malgré activités présentes : vérifier achats, alimentation, santé, cultures, investissements et mouvements stock réels');
  return { caFacture, caConsolide, cashEncaisse, otherCashIn, orphanPaymentsTotal, creancesReelles, chargesEngagees, chargesPayees, chargesMetier, chargesComptabilisees: chargeRecon.chargesComptabilisees, chargesDeriveesNonComptabilisees: chargeRecon.chargesDeriveesNonComptabilisees, chargesReconciliationMode: chargeRecon.mode, chargesCoverageRatio: chargeRecon.coverageRatio, chargesDerivees: derivedCharges.total, chargesDeriveesDetail: derivedCharges, lossCharges, dettesFournisseurs: supplierDebt, stockValue, cashNet, margeReelle, marginRate: caConsolide > 0 ? Number(((margeReelle / caConsolide) * 100).toFixed(1)) : 0, orderSettlements, uniqueTransactions, uniqueLossEvents, orphanPayments, warnings };
}
