export const FORM_SCHEMA_REGISTRY = {
  ventes: { label: 'Ventes', intents: ['créer vente', 'enregistrer paiement', 'vendre animal', 'vendre poulets', 'vendre récolte'], required: ['client_id', 'source_module', 'source_id', 'quantity', 'prix_unitaire'], recommended: ['moyen_paiement', 'date', 'statut_paiement'], auto: ['montant_total', 'reste_a_payer', 'statut_commande', 'statut_facture', 'transaction_finance', 'document', 'business_event'], effects: ['clients', 'payments', 'finances', 'documents', 'business_events', 'alertes_center', 'stock/animaux/avicole/cultures'] },
  paiements: { label: 'Paiements', intents: ['encaisser', 'ajouter paiement', 'solder commande'], required: ['order_id', 'client_id', 'montant', 'moyen_paiement'], recommended: ['date_paiement', 'invoice_id'], auto: ['reste_a_payer', 'statut_paiement', 'statut_client', 'transaction_finance'], effects: ['sales_orders', 'clients', 'finances', 'alertes_center'] },
  clients: { label: 'Clients & WhatsApp', intents: ['ajouter client', 'modifier client', 'relancer client', 'ouvrir whatsapp client'], required: ['nom'], recommended: ['tel', 'whatsapp', 'type', 'prefs'], auto: ['statut_client', 'reste_a_payer', 'score_fidelite', 'relance_si_creance'], effects: ['ventes', 'paiements', 'taches', 'alertes_center', 'whatsapp_logs'] },
  stock: { label: 'Stock', intents: ['ajouter stock', 'sortir stock', 'déclarer perte', 'réceptionner stock'], required: ['produit', 'categorie', 'quantite', 'unite'], recommended: ['prixUnit', 'fournisseur_id', 'seuil', 'activite_liee'], auto: ['valeur_stock', 'statut', 'alerte_stock', 'finance_si_achat_ou_perte'], effects: ['finances', 'fournisseurs', 'documents', 'business_events', 'alertes_center', 'taches'] },
  animaux: { label: 'Animaux', intents: ['ajouter animal', 'modifier animal', 'vendre animal', 'signaler santé animal', 'enregistrer abattage'], required: ['tag', 'type', 'sexe'], recommended: ['poids', 'purchase_cost', 'date_achat', 'health_status'], auto: ['cout_total', 'marge', 'prix_recommande', 'stock_viande_si_abattage', 'traçabilité'], effects: ['sante', 'ventes', 'stock', 'finances', 'business_events'] },
  avicole: { label: 'Avicole', intents: ['créer lot', 'sortie lot', 'vente poulets', 'mortalité lot', 'production oeufs'], required: ['name', 'type', 'initial_count', 'date_debut'], recommended: ['prix_vente_prevu', 'cout_poussins', 'phase'], auto: ['current_count', 'cout_par_tete', 'marge_lot', 'readiness_vente'], effects: ['ventes', 'stock', 'sante', 'finances', 'business_events'] },
  cultures: { label: 'Cultures', intents: ['créer culture', 'récolter', 'vendre récolte', 'traitement culture'], required: ['nom', 'type', 'parcelle', 'surface'], recommended: ['quantite_prevue', 'cout_semences', 'cout_engrais', 'statut'], auto: ['cout_total', 'cout_unitaire', 'stock_recolte', 'marge_culture'], effects: ['stock', 'ventes', 'finances', 'business_events'] },
  sante: { label: 'Santé & Biosécurité', intents: ['ajouter soin', 'vacciner', 'traiter maladie', 'désinfecter', 'urgence sanitaire'], required: ['nom', 'type_intervention', 'target_mode', 'date'], recommended: ['cout', 'vet', 'product_source', 'prochaine_action'], auto: ['sortie_stock_sante', 'finance', 'tache_suivi', 'alerte_si_urgence', 'document_preuve'], effects: ['stock', 'finances', 'taches', 'alertes_center', 'documents', 'business_events'] },
  fournisseurs: { label: 'Fournisseurs', intents: ['ajouter fournisseur', 'payer fournisseur', 'commander fournisseur'], required: ['nom', 'categorie'], recommended: ['tel', 'whatsapp', 'contact', 'note'], auto: ['dette_reelle', 'tache_paiement', 'document', 'transaction_finance'], effects: ['stock', 'finances', 'documents', 'taches', 'alertes_center'] },
  rh: { label: 'RH & Équipe', intents: ['ajouter employé', 'payer salaire', 'noter avance', 'affecter équipe'], required: ['nom', 'role', 'fonction'], recommended: ['salaire_mensuel', 'prime_mensuelle', 'avance_mois', 'modules'], auto: ['net_a_payer', 'masse_salariale', 'charge_finance_si_payé'], effects: ['finances', 'comptabilite', 'taches', 'impact_business'] },
  documents: { label: 'Documents', intents: ['ajouter document', 'joindre facture', 'créer reçu', 'lier document'], required: ['title', 'document_category'], recommended: ['module_source', 'entity_id', 'related_id', 'file_url'], auto: ['preuve_liee', 'timeline_document', 'statut_document'], effects: ['ventes', 'paiements', 'fournisseurs', 'finances', 'business_events'] },
  taches: { label: 'Tâches', intents: ['créer tâche', 'terminer tâche', 'assigner tâche', 'planifier suivi'], required: ['title', 'due_date'], recommended: ['module_lie', 'related_id', 'priority', 'assigned_to'], auto: ['alerte_liee', 'business_event', 'dedupe_key'], effects: ['alertes_center', 'business_events', 'rh'] },
  alertes_center: { label: 'Alertes', intents: ['créer alerte', 'traiter alerte', 'transformer alerte en tâche'], required: ['title', 'severity'], recommended: ['module_source', 'entity_id', 'message', 'action_recommandee'], auto: ['task_dedupe_key', 'linked_task_id', 'status'], effects: ['taches', 'business_events'] },
  equipements: { label: 'Équipements', intents: ['ajouter équipement', 'déclarer panne', 'programmer maintenance', 'saisir carburant'], required: ['name', 'type'], recommended: ['status', 'purchase_cost', 'maintenance_due', 'fuel_cost'], auto: ['tache_panne', 'alerte_panne', 'finance_carburant_maintenance', 'business_event'], effects: ['finances', 'taches', 'alertes_center', 'documents', 'business_events'] },
  smartfarm: { label: 'Smart Farm', intents: ['ajouter capteur', 'ajouter caméra', 'créer action météo', 'synchroniser capteurs'], required: ['name', 'type', 'zone'], recommended: ['status', 'battery_level', 'stream_url', 'location'], auto: ['alerte_si_risque', 'tache_terrain', 'business_event'], effects: ['taches', 'alertes_center', 'business_events', 'sync'] },
  rapports: { label: 'Rapports', intents: ['créer rapport', 'programmer rapport', 'exporter module', 'préparer présentation'], required: ['title', 'report_type', 'period'], recommended: ['channel', 'status', 'module_source'], auto: ['document_export', 'business_event', 'statut_generation'], effects: ['documents', 'business_events'] },
  sync: { label: 'Sync Offline', intents: ['synchroniser', 'faire backup', 'voir actions en attente'], required: [], recommended: ['module', 'action', 'status'], auto: ['risque_conflit', 'backup_json', 'timeline_sync'], effects: ['audit_logs', 'business_events'] },
};

export function getFormSchema(moduleKey) { return FORM_SCHEMA_REGISTRY[moduleKey] || null; }
export function listAssistantModules() { return Object.entries(FORM_SCHEMA_REGISTRY).map(([key, schema]) => ({ key, label: schema.label, intents: schema.intents, required: schema.required })); }
export function missingRequiredFields(moduleKey, payload = {}) { const schema = getFormSchema(moduleKey); if (!schema) return []; return schema.required.filter((key) => payload[key] === undefined || payload[key] === null || payload[key] === ''); }
export function buildAssistantDraft(moduleKey, payload = {}) { const schema = getFormSchema(moduleKey); if (!schema) return { ok: false, error: 'Module inconnu', moduleKey, payload }; const missing = missingRequiredFields(moduleKey, payload); return { ok: missing.length === 0, moduleKey, label: schema.label, payload, missing, required: schema.required, recommended: schema.recommended, auto: schema.auto, effects: schema.effects }; }
