import { mergeSimulationScenarios } from './horizonFarmSimulationScenarios.js';

const DAY = 86400000;
const dateDaysAgo = (days) => new Date(Date.now() - days * DAY).toISOString().slice(0, 10);
const dateDaysFromNow = (days) => new Date(Date.now() + days * DAY).toISOString().slice(0, 10);
const isoNow = () => new Date().toISOString();
const id = (prefix, n) => `${prefix}-${String(n).padStart(3, '0')}`;
const money = (value) => Math.round(Number(value || 0));

const SOURCE = 'simulation_bp_horizon_farm';
const EGGS_PER_TABLET = 30;

const client = (n, nom, type, prefs) => ({ id: id('HF-CLI', n), nom, name: nom, type, prefs, statut: n <= 3 ? 'VIP / Gros acheteur' : 'actif', score: 4 + (n % 5) / 10, tel: `+221 77 10${n} 20${n}`, whatsapp: `+221 77 10${n} 20${n}`, email: `client${n}@horizonfarm.demo`, adresse: 'Dakar / Thiès / Mbour', source: SOURCE });
const fournisseur = (n, nom, categorie) => ({ id: id('HF-FOU', n), nom, name: nom, categorie, statut: 'fiable', contact: 'Responsable commercial', note: 4.4, tel: `+221 76 30${n} 40${n}`, whatsapp: `+221 76 30${n} 40${n}`, email: `fournisseur${n}@horizonfarm.demo`, dettes: n === 2 ? 185000 : 0, livraisons: 8 + n, source: SOURCE });
const stock = (n, produit, quantite, unite, seuil, prixUnit, categorie, extra = {}) => ({ id: id('HF-STK', n), produit, nom: produit, quantite, unite, seuil, prixUnit, prixunit: prixUnit, prix_unitaire: prixUnit, categorie, category: categorie, is_sellable: Boolean(extra.is_sellable), source: SOURCE, ...extra });
const finance = (n, type, libelle, montant, date, categorie, module_lie, related_id, extra = {}) => ({ id: id('HF-TRX', n), type, libelle, description: libelle, montant: money(montant), date, categorie, module_lie, related_id, statut: extra.statut || 'paye', paiement: extra.paiement || 'Wave', moyen_paiement: extra.paiement || 'Wave', client_id: extra.client_id || '', fournisseur_id: extra.fournisseur_id || '', source_module: module_lie, source_record_id: related_id, activite: extra.activite || module_lie, source: SOURCE, ...extra });
const event = (n, event_type, module_source, entity_type, entity_id, title, description, severity = 'info', extra = {}) => ({ id: id('HF-EVT', n), event_type, module_source, entity_type, entity_id, title, description, severity, status: extra.status || 'nouveau', event_date: extra.event_date || dateDaysAgo(1), date: extra.event_date || dateDaysAgo(1), amount: extra.amount || null, montant: extra.amount || null, decision_key: extra.decision_key || '', source: SOURCE, ...extra });
const task = (n, title, module_lie, related_id, due_date, priority, checklist, extra = {}) => ({ id: id('HF-TSK', n), title, module_lie, related_id, due_date, priority, status: extra.status || 'a_faire', checklist, source_module: module_lie, decision_key: extra.decision_key || '', source: SOURCE, ...extra });
const alert = (n, title, message, module_source, entity_id, severity, action, extra = {}) => ({ id: id('HF-ALT', n), title, message, module_source, entity_type: extra.entity_type || module_source, entity_id, severity, status: 'nouvelle', action_recommandee: action, decision_key: extra.decision_key || '', source: SOURCE, ...extra });
const document = (n, title, category, module_source, entity_type, entity_id, extra = {}) => ({ id: id('HF-DOC', n), title, document_type: category, document_category: category, module_lie: module_source, module_source, entity_type, entity_id, related_id: entity_id, status: 'actif', file_url: extra.file_url || 'simulation://photo-preuve-horizon-farm.jpg', tags: `simulation,bp,horizon,${category}`, source: SOURCE, ...extra });

function buildLots() {
  return [
    { id: 'HF-PO-001', name: 'BP Pondeuses 4000 - ponte active', nom: 'BP Pondeuses 4000 - ponte active', type: 'Pondeuse', type_lot: 'Pondeuse', phase: 'Production', initial_count: 4000, effectif_initial: 4000, current_count: 3928, effectif_actuel: 3928, mortality: 72, morts: 72, malades: 18, vendus: 0, reformes: 0, purchase_cost: 3600000, cout_achat: 3600000, cout_alimentation: 554400, real_feed_cost: 554400, cout_sante: 120000, health_cost: 120000, autres_charges: 42500, cout_emballage: 30600, cout_transport: 11900, prix_tablette: 2800, prix_plateau: 2800, prix_vente_tablette: 2800, health_status: 'sain', status: 'en_ponte', date_debut: dateDaysAgo(210), age_days: 210, debut_ponte: dateDaysAgo(60), taux_ponte: 95.4, productionJour: 2995, weight_avg: 1.82, ic: 2.2, scoresSante: 88, source: SOURCE },
    { id: 'HF-CH-001', name: 'Chair cycle 1 - vendu 42 jours', nom: 'Chair cycle 1 - vendu 42 jours', type: 'Chair', type_lot: 'Chair', phase: 'Terminé', initial_count: 200, effectif_initial: 200, current_count: 0, effectif_actuel: 0, mortality: 6, morts: 6, vendus: 194, frais_sante: 22000, health_status: 'sain', status: 'vendu', date_debut: dateDaysAgo(135), date_fin_reelle: dateDaysAgo(93), age_days: 42, weight_avg: 1.72, poids_cible: 1.5, ic: 1.88, purchase_cost: 130000, cout_poussins: 130000, cout_alimentation: 178000, cout_sante: 22000, autres_charges: 18000, prix_vente_reel: 3800, source: SOURCE },
    { id: 'HF-CH-002', name: 'Chair cycle 2 - vendu partiel 38 jours', nom: 'Chair cycle 2 - vendu partiel 38 jours', type: 'Chair', type_lot: 'Chair', phase: 'Terminé', initial_count: 200, effectif_initial: 200, current_count: 0, effectif_actuel: 0, mortality: 5, morts: 5, vendus: 195, health_status: 'sain', status: 'vendu', date_debut: dateDaysAgo(88), date_fin_reelle: dateDaysAgo(50), age_days: 38, weight_avg: 1.58, poids_cible: 1.5, ic: 1.82, purchase_cost: 130000, cout_poussins: 130000, cout_alimentation: 166000, cout_sante: 18000, autres_charges: 11000, prix_vente_reel: 3650, source: SOURCE },
    { id: 'HF-CH-003', name: 'Chair prêt à vendre - 35 jours 1,52 kg', nom: 'Chair prêt à vendre - 35 jours 1,52 kg', type: 'Chair', type_lot: 'Chair', phase: 'Finition', initial_count: 200, effectif_initial: 200, current_count: 192, effectif_actuel: 192, mortality: 5, morts: 5, malades: 3, vendus: 0, health_status: 'sain', status: 'pret_vente', date_debut: dateDaysAgo(35), age_days: 35, weight_avg: 1.52, poids_cible: 1.5, ic: 1.79, purchase_cost: 130000, cout_poussins: 130000, cout_alimentation: 154000, cout_sante: 26000, autres_charges: 15000, prix_vente_prevu: 3700, ready_to_sell: true, partial_sale_recommended: true, recommended_sale_qty: 115, decision_key: 'avicole:HF-CH-003:vente_partielle', source: SOURCE },
    { id: 'HF-CH-004', name: 'Chair croissance normale - 28 jours', type: 'Chair', type_lot: 'Chair', phase: 'Croissance', initial_count: 200, effectif_initial: 200, current_count: 196, effectif_actuel: 196, mortality: 2, morts: 2, malades: 1, status: 'en_croissance', date_debut: dateDaysAgo(28), age_days: 28, weight_avg: 1.18, poids_cible: 1.5, purchase_cost: 130000, cout_alimentation: 116000, cout_sante: 12000, autres_charges: 9000, prix_vente_prevu: 3700, source: SOURCE },
    { id: 'HF-CH-005', name: 'Chair retard de poids - 40 jours', type: 'Chair', type_lot: 'Chair', phase: 'A corriger', initial_count: 200, effectif_initial: 200, current_count: 188, effectif_actuel: 188, mortality: 8, morts: 8, malades: 7, health_status: 'a_surveiller', status: 'retard_poids', date_debut: dateDaysAgo(40), age_days: 40, weight_avg: 1.31, poids_cible: 1.5, purchase_cost: 130000, cout_alimentation: 196000, cout_sante: 42000, autres_charges: 17500, prix_vente_prevu: 3500, decision_key: 'avicole:HF-CH-005:retard_poids', source: SOURCE },
  ];
}

function buildAnimals() {
  const rows = [];
  [
    ['BOV', 'Bovin', 10, 100, 250000, 365000, 2, 285, 330, 72000, 6500, 0],
    ['OV', 'Ovin', 5, 96, 60000, 95000, 2, 42, 55, 18000, 4500, 2000],
    ['CAP', 'Caprin', 5, 96, 45000, 75000, 1, 31, 42, 15000, 3500, 1500],
  ].forEach(([prefix, type, count, cycleDays, cost, sale, sold, poidsBase, poidsCible, feed, health, other]) => {
    for (let i = 1; i <= count; i += 1) {
      const late = i === count;
      const ready = i <= sold || i === sold + 1;
      const soldStatus = i <= sold;
      const code = `HF-${prefix}-${String(i).padStart(3, '0')}`;
      const poids = poidsBase + (ready ? 22 : late ? -3 : 10) + i;
      rows.push({ id: code, tag: code, boucle_numero: code, name: `${type} embouche ${i}`, nom: `${type} embouche ${i}`, type, espece: type, sexe: i % 2 ? 'M' : 'F', poids, poids_initial: poidsBase, poids_entree: poidsBase, poids_cible: poidsCible, duree_embouche_jours: 90, purchase_cost: cost, prix_achat: cost, alimentation: feed, cout_alimentation: feed, sante: late ? health + 7500 : health, cout_sante: late ? health + 7500 : health, autres_frais: other, cout_eau: type === 'Bovin' ? 5500 : 900, cout_transport: soldStatus ? (type === 'Bovin' ? 40000 : 0) : 0, health_status: late ? 'a_surveiller' : 'sain', status: soldStatus ? 'vendu' : 'actif', date_achat: dateDaysAgo(cycleDays + (soldStatus ? 8 : 0)), date_entree_ferme: dateDaysAgo(cycleDays + (soldStatus ? 8 : 0)), mode_acquisition: 'achat', date_vente: soldStatus ? dateDaysAgo(12 - i) : '', sale_price: soldStatus ? sale + (type === 'Bovin' ? 40000 : 0) : 0, prix_vente_reel: soldStatus ? sale + (type === 'Bovin' ? 40000 : 0) : 0, prix_vente_estime: sale, ready_to_sell: ready && !soldStatus, growth_status: late ? 'retard_poids' : ready ? 'pret_vente' : 'normal', decision_key: ready && !soldStatus ? `animaux:${code}:vendre` : late ? `animaux:${code}:retard_poids` : '', source: SOURCE });
    }
  });
  return rows;
}

function buildCultures() {
  return [
    { id: 'HF-CULT-001', nom: 'Laitue Batavia BP', type: 'Laitue', parcelle: 'Zone maraîchère A', surface: 350, date_semis: dateDaysAgo(72), date_recolte_prevue: dateDaysFromNow(3), quantite_prevue: 1200, quantite_recoltee: 0, quantite_disponible: 0, pertes: 45, cout_semences: 45000, cout_engrais: 65000, cout_eau: 36000, cout_main_oeuvre: 98000, cout_traitement: 28000, revenu_estime: 780000, statut: 'pret_recolte', score_sante: 86, ready_to_harvest: true, decision_key: 'cultures:HF-CULT-001:recolter_vendre', source: SOURCE },
    { id: 'HF-CULT-002', nom: 'Tomates Roma BP', type: 'Tomate', parcelle: 'Zone maraîchère B', surface: 520, date_semis: dateDaysAgo(95), date_recolte_prevue: dateDaysAgo(5), date_recolte_reelle: dateDaysAgo(5), quantite_prevue: 2100, quantite_recoltee: 1680, quantite_disponible: 720, pertes: 180, cout_semences: 70000, cout_engrais: 125000, cout_eau: 62000, cout_main_oeuvre: 165000, cout_traitement: 53000, revenu_estime: 1680000, revenu_reel: 864000, statut: 'recolte_partielle', score_sante: 78, ready_to_sell: true, decision_key: 'cultures:HF-CULT-002:vendre_stock_recolte', source: SOURCE },
    { id: 'HF-CULT-003', nom: 'Piment Safi BP', type: 'Piment', parcelle: 'Zone maraîchère C', surface: 260, date_semis: dateDaysAgo(125), date_recolte_reelle: dateDaysAgo(28), quantite_prevue: 650, quantite_recoltee: 610, quantite_disponible: 0, pertes: 40, cout_semences: 38000, cout_engrais: 58000, cout_eau: 26000, cout_main_oeuvre: 72000, cout_traitement: 18000, revenu_estime: 715000, revenu_reel: 671000, statut: 'termine', score_sante: 92, source: SOURCE },
  ];
}

function buildLogs() {
  const alimentation_logs = [
    { id: 'HF-ALOG-001', lot_id: 'HF-PO-001', date: dateDaysAgo(7), produit: 'Aliment pondeuses', quantite: 6300, unite: 'kg', prix_unitaire: 88, cout_total: 554400, source_module: 'avicole', source_record_id: 'HF-PO-001', source: SOURCE },
    { id: 'HF-ALOG-002', lot_id: 'HF-CH-001', date: dateDaysAgo(110), produit: 'Aliment chair cycle 1', quantite: 1700, unite: 'kg', prix_unitaire: 105, cout_total: 178000, source_module: 'avicole', source_record_id: 'HF-CH-001', source: SOURCE },
    { id: 'HF-ALOG-003', lot_id: 'HF-CH-002', date: dateDaysAgo(63), produit: 'Aliment chair cycle 2', quantite: 1580, unite: 'kg', prix_unitaire: 105, cout_total: 166000, source_module: 'avicole', source_record_id: 'HF-CH-002', source: SOURCE },
    { id: 'HF-ALOG-004', lot_id: 'HF-CH-003', date: dateDaysAgo(14), produit: 'Aliment chair finition', quantite: 1465, unite: 'kg', prix_unitaire: 105, cout_total: 154000, source_module: 'avicole', source_record_id: 'HF-CH-003', source: SOURCE },
    { id: 'HF-ALOG-005', lot_id: 'HF-CH-005', date: dateDaysAgo(10), produit: 'Aliment chair retard poids', quantite: 1867, unite: 'kg', prix_unitaire: 105, cout_total: 196000, source_module: 'avicole', source_record_id: 'HF-CH-005', source: SOURCE },
    { id: 'HF-ALOG-006', animal_id: 'HF-BOV-001', date: dateDaysAgo(20), produit: 'Fourrage + concentré bovin', quantite: 720, unite: 'kg', prix_unitaire: 100, cout_total: 72000, source_module: 'animaux', source_record_id: 'HF-BOV-001', source: SOURCE },
    { id: 'HF-ALOG-007', animal_id: 'HF-OV-001', date: dateDaysAgo(18), produit: 'Ration ovin', quantite: 180, unite: 'kg', prix_unitaire: 100, cout_total: 18000, source_module: 'animaux', source_record_id: 'HF-OV-001', source: SOURCE },
  ];
  const production_oeufs_logs = Array.from({ length: 14 }, (_, idx) => ({ id: `HF-EGG-${String(idx + 1).padStart(3, '0')}`, lot_id: 'HF-PO-001', date: dateDaysAgo(13 - idx), oeufs_produits: idx % 2 ? 2990 : 3025, oeufs_casses: idx % 3 === 0 ? 42 : 38, vendables: (idx % 2 ? 2990 : 3025) - (idx % 3 === 0 ? 42 : 38), responsable: 'Equipe ponte', source: SOURCE }));
  return { alimentation_logs, production_oeufs_logs };
}

function buildHealth() {
  return [
    { id: 'HF-SAN-001', nom: 'Programme Newcastle pondeuses', type_intervention: 'vaccination', module_lie: 'avicole', animal: 'HF-PO-001', related_id: 'HF-PO-001', lot_id: 'HF-PO-001', target_type: 'avicole', target_id: 'HF-PO-001', target_summary: '3928 pondeuses', prevue: dateDaysAgo(185), effectuee: dateDaysAgo(185), date: dateDaysAgo(185), vet: 'Dr. Kone', cout: 120000, montant: 120000, statut: 'fait', risk_level: 'faible', impact_business_category: 'sante_production', proof_photo_url: 'simulation://ordonnance-newcastle.jpg', source: SOURCE },
    { id: 'HF-SAN-002', nom: 'Déparasitage bovins', type_intervention: 'deparasitage', module_lie: 'animaux', animal: 'HF-BOV-001', related_id: 'HF-BOV-001', animal_id: 'HF-BOV-001', target_type: 'animaux', target_id: 'HF-BOV-001', target_summary: 'Bovin embouche 1', prevue: dateDaysAgo(70), effectuee: dateDaysAgo(70), date: dateDaysAgo(70), vet: 'Dr. Diallo', cout: 6500, montant: 6500, statut: 'fait', risk_level: 'moyen', proof_photo_url: 'simulation://ordonnance-deparasitage-bovin.jpg', source: SOURCE },
    { id: 'HF-SAN-003', nom: 'Vitamines chair finition', type_intervention: 'preventif', module_lie: 'avicole', related_id: 'HF-CH-003', lot_id: 'HF-CH-003', target_type: 'avicole', target_id: 'HF-CH-003', target_summary: '192 poulets', prevue: dateDaysAgo(8), effectuee: dateDaysAgo(8), date: dateDaysAgo(8), cout: 26000, montant: 26000, statut: 'fait', risk_level: 'faible', proof_photo_url: 'simulation://vitamines-chair.jpg', source: SOURCE },
    { id: 'HF-SAN-004', nom: 'Traitement retard poids chair', type_intervention: 'curatif', module_lie: 'avicole', related_id: 'HF-CH-005', lot_id: 'HF-CH-005', target_type: 'avicole', target_id: 'HF-CH-005', target_summary: '188 poulets', prevue: dateDaysAgo(5), effectuee: dateDaysAgo(5), date: dateDaysAgo(5), cout: 42000, montant: 42000, statut: 'fait', risk_level: 'eleve', proof_photo_url: 'simulation://traitement-retard-poids.jpg', source: SOURCE },
    { id: 'HF-SAN-005', nom: 'Vitamines croissance caprin faible', type_intervention: 'preventif', module_lie: 'animaux', animal: 'HF-CAP-005', related_id: 'HF-CAP-005', animal_id: 'HF-CAP-005', target_type: 'animaux', target_id: 'HF-CAP-005', target_summary: 'Caprin embouche 5', prevue: dateDaysAgo(4), effectuee: '', date: dateDaysAgo(4), cout: 11000, montant: 11000, statut: 'a_faire', risk_level: 'moyen', source: SOURCE },
  ];
}

function buildSalesAndFinance() {
  const orders = [
    ['HF-CMD-001', dateDaysAgo(92), 'HF-CLI-001', 'HF-CH-001', 'lot_avicole', 'avicole', 'Poulets chair cycle 1', 194, 'tête', 3800, 'recupere', 0, true, 'paye', 737200, 737200, 'chair'],
    ['HF-CMD-002', dateDaysAgo(50), 'HF-CLI-001', 'HF-CH-002', 'lot_avicole', 'avicole', 'Poulets chair cycle 2', 195, 'tête', 3650, 'livraison', 25000, true, 'partiel', 736750, 500000, 'chair'],
    ['HF-CMD-003', dateDaysAgo(7), 'HF-CLI-002', 'HF-PO-001', 'lot_avicole', 'avicole', 'Œufs plateaux semaine 1', 680, 'tablette', 2800, 'livraison', 15000, true, 'paye', 1919000, 1919000, 'oeufs_tablettes'],
    ['HF-CMD-004', dateDaysAgo(2), 'HF-CLI-003', 'HF-CULT-002', 'culture', 'culture', 'Tomates Roma récolte partielle', 720, 'kg', 1200, 'recupere', 0, true, 'non_paye', 864000, 0, 'culture'],
    ['HF-CMD-005', dateDaysAgo(10), 'HF-CLI-004', 'HF-BOV-001', 'animal', 'animal', 'Bovin embouche 1', 1, 'tête', 405000, 'livraison', 0, true, 'paye', 405000, 405000, 'animal'],
    ['HF-CMD-006', dateDaysAgo(8), 'HF-CLI-004', 'HF-OV-001', 'animal', 'animal', 'Ovin embouche 1', 1, 'tête', 95000, 'recupere', 0, false, 'paye', 95000, 95000, 'animal'],
  ];
  const sales_orders = orders.map(([orderId, date, client_id, source_id, source_type, source_module, product_name, quantity, unit, unit_price, mode, fee, invoice, payStatus, total, paid, sale_kind]) => ({ id: orderId, date, date_commande: date, client_id, source_id, source_type, source_module, source_label: product_name, product_name, produit: product_name, quantity, quantite: quantity, unit, unite: unit, unit_price, prix_unitaire: unit_price, eggs_per_unit: sale_kind === 'oeufs_tablettes' ? EGGS_PER_TABLET : undefined, eggs_quantity: sale_kind === 'oeufs_tablettes' ? quantity * EGGS_PER_TABLET : undefined, sale_kind, montant_ht: total - fee, total: total, total_amount: total, montant_total: total, chiffre_affaires: total, montant_paye: paid, paid_amount: paid, reste_a_payer: Math.max(0, total - paid), statut_commande: 'livre', statut_livraison: mode === 'livraison' ? 'livre' : 'recupere', fulfillment_mode: mode, frais_livraison: fee, facture_emise: invoice, invoice_status: invoice ? 'emise' : 'non_emise', invoice_id: invoice ? orderId.replace('CMD', 'FAC') : '', statut_paiement: payStatus, payment_status: payStatus, source: SOURCE }));
  const sales_order_items = sales_orders.map((o, idx) => ({ id: id('HF-CMDI', idx + 1), order_id: o.id, source_type: o.source_type, source_module: o.source_module, source_id: o.source_id, product_name: o.product_name, label: o.product_name, quantity: o.quantity, unit: o.unit, unite: o.unit, eggs_per_unit: o.eggs_per_unit, eggs_quantity: o.eggs_quantity, sale_kind: o.sale_kind, unit_price: o.unit_price, total: o.montant_ht, line_total: o.montant_ht, source: SOURCE }));
  const invoices = sales_orders.filter((o) => o.facture_emise).map((o) => ({ id: o.invoice_id, order_id: o.id, sale_id: o.id, numero_facture: `FAC-${o.id.slice(-3)}`, date_facture: o.date, montant_total: o.montant_total, statut: 'emise', invoice_status: 'emise', source: SOURCE }));
  const payments = sales_orders.filter((o) => Number(o.montant_paye) > 0).map((o, idx) => ({ id: id('HF-PAY', idx + 1), order_id: o.id, sale_id: o.id, source_record_id: o.id, client_id: o.client_id, invoice_id: o.invoice_id || '', date_paiement: o.date, date: o.date, montant: o.montant_paye, montant_paye: o.montant_paye, amount: o.montant_paye, moyen_paiement: idx % 2 ? 'Wave' : 'Orange Money', statut: 'paye', source: SOURCE }));
  const deliveries = sales_orders.map((o, idx) => ({ id: id('HF-LIV', idx + 1), order_id: o.id, sale_id: o.id, date_livraison: o.date, statut: 'livre', fulfillment_mode: o.fulfillment_mode, mode_livraison: o.fulfillment_mode, frais_livraison: o.frais_livraison, destinataire: o.client_id, source: SOURCE }));
  const documents = invoices.map((inv, idx) => document(idx + 1, `Facture ${inv.numero_facture}`, 'facture', 'ventes', 'commande', inv.order_id, { invoice_id: inv.id, amount: inv.montant_total }));
  const finances = [
    finance(1, 'entree', 'Financement bancaire Horizon Farm BP', 12000000, dateDaysAgo(210), 'Financement', 'investissements', 'HF-BP-001', { activite: 'global' }),
    finance(2, 'entree', 'Apport promoteur Horizon Farm', 6905000, dateDaysAgo(210), 'Apport', 'investissements', 'HF-BP-001', { activite: 'global' }),
    finance(3, 'sortie', 'Achat 4000 pondeuses', 3600000, dateDaysAgo(210), 'Investissement cheptel', 'avicole', 'HF-PO-001', { activite: 'avicole_pondeuses' }),
    finance(4, 'sortie', 'Aliment pondeuses cycle courant', 554400, dateDaysAgo(7), 'Alimentation', 'avicole', 'HF-PO-001', { activite: 'avicole_pondeuses' }),
    finance(5, 'sortie', 'Alvéoles et transport œufs', 42500, dateDaysAgo(16), 'Emballages', 'avicole', 'HF-PO-001', { activite: 'avicole_pondeuses' }),
    finance(6, 'sortie', 'Achat poussins chair cycles initiaux', 390000, dateDaysAgo(135), 'Investissement cheptel', 'avicole', 'HF-CH-001', { activite: 'avicole_chair' }),
    finance(7, 'sortie', 'Achat bovins embouche BP', 2500000, dateDaysAgo(100), 'Investissement cheptel', 'animaux', 'bovins', { activite: 'bovins' }),
    finance(8, 'sortie', 'Achat ovins embouche BP', 300000, dateDaysAgo(98), 'Investissement cheptel', 'animaux', 'ovins', { activite: 'ovins' }),
    finance(9, 'sortie', 'Achat caprins embouche BP', 225000, dateDaysAgo(98), 'Investissement cheptel', 'animaux', 'caprins', { activite: 'caprins' }),
    finance(10, 'sortie', 'Salaires équipe ferme mois courant', 420000, dateDaysAgo(28), 'Salaires', 'rh', 'HF-RH-001', { activite: 'global' }),
    ...payments.map((p, idx) => finance(30 + idx, 'entree', `Encaissement ${p.order_id}`, p.montant_paye, p.date, 'Vente', 'ventes', p.order_id, { client_id: p.client_id, related_id: p.order_id, activite: 'ventes', payment_id: p.id })),
    finance(50, 'entree', 'Créance client tomates Roma', 864000, dateDaysAgo(2), 'Creance client', 'ventes', 'HF-CMD-004', { statut: 'impaye', client_id: 'HF-CLI-003', activite: 'cultures' }),
  ];
  return { sales_orders, sales_order_items, invoices, payments, deliveries, documents, finances };
}

function buildSimulation() {
  const avicole = buildLots();
  const animaux = buildAnimals();
  const cultures = buildCultures();
  const logs = buildLogs();
  const sante = buildHealth();
  const sales = buildSalesAndFinance();
  const clients = [client(1, 'Grossiste Dakar Œufs', 'grossiste', 'tablettes œufs'), client(2, 'Restaurant Teranga', 'restaurant', 'poulets chair'), client(3, 'Boutique Mbour Frais', 'détaillant', 'légumes'), client(4, 'Marché Rufisque Viande', 'grossiste', 'animaux embouche')];
  const fournisseurs = [fournisseur(1, 'Provenderie Touba Aliment', 'aliments'), fournisseur(2, 'Veto Sénégal Santé', 'santé animale'), fournisseur(3, 'Emballages Plateau Thiès', 'emballages')];
  const stockRows = [stock(1, 'Aliment pondeuses', 4280, 'kg', 800, 88, 'aliment'), stock(2, 'Aliment chair finition', 1850, 'kg', 500, 105, 'aliment'), stock(3, 'Fourrage bovin', 3200, 'kg', 600, 100, 'aliment'), stock(4, 'Alvéoles / tablettes 30 œufs', 1680, 'unité', 300, 45, 'emballage'), stock(5, 'Vaccin Newcastle', 6, 'flacon', 2, 18000, 'sante'), stock(6, 'Tomates Roma récoltées', 720, 'kg', 100, 1200, 'produit_fini', { is_sellable: true })];
  const investments = [{ id: 'HF-INV-001', designation: 'Poulailler pondeuses', categorie: 'Infrastructure', montant: 3500000, total: 3500000, statut: 'réalisé', source: SOURCE }, { id: 'HF-INV-002', designation: 'Enclos embouche', categorie: 'Infrastructure', montant: 1800000, total: 1800000, statut: 'réalisé', source: SOURCE }, { id: 'HF-INV-003', designation: 'Stock initial aliments et santé', categorie: 'Stock initial', montant: 2450000, total: 2450000, statut: 'réalisé', source: SOURCE }];
  const opportunities = [{ id: 'HF-OPP-001', title: 'Vendre partiellement lot chair HF-CH-003', source_type: 'lot_avicole', source_id: 'HF-CH-003', quantity: 115, unit: 'tête', estimated_value: 425500, status: 'nouveau', priority: 'haute', reason: '35 jours, poids moyen 1,52 kg, marge positive.', decision_key: 'avicole:HF-CH-003:vente_partielle', detected_at: dateDaysAgo(1), source: SOURCE }, { id: 'HF-OPP-002', title: 'Vendre bovin HF-BOV-003 prêt', source_type: 'animal', source_id: 'HF-BOV-003', quantity: 1, unit: 'tête', estimated_value: 365000, status: 'nouveau', priority: 'haute', reason: 'Poids cible atteint, coût journalier à limiter.', decision_key: 'animaux:HF-BOV-003:vendre', detected_at: dateDaysAgo(1), source: SOURCE }];
  const business_events = [event(1, 'decision_vente_partielle', 'centre_decisionnel', 'lot_avicole', 'HF-CH-003', 'Vendre 115 poulets HF-CH-003', 'Le lot a atteint 1,52 kg à 35 jours.', 'warning', { decision_key: 'avicole:HF-CH-003:vente_partielle', amount: 425500, linked_opportunity_id: 'HF-OPP-001' }), event(2, 'decision_vendre', 'centre_decisionnel', 'animal', 'HF-BOV-003', 'Bovin prêt à vendre', 'Poids cible atteint.', 'warning', { decision_key: 'animaux:HF-BOV-003:vendre', amount: 365000, linked_opportunity_id: 'HF-OPP-002' }), event(3, 'charge_directe', 'avicole', 'lot_avicole', 'HF-PO-001', 'Emballages et transport œufs', 'Alvéoles, transport et pertes de casse.', 'info', { amount: 42500, montant: 42500, target_type: 'avicole', target_id: 'HF-PO-001' }), ...sante.map((row, idx) => event(10 + idx, 'intervention_sante', 'sante', row.module_lie === 'animaux' ? 'animal' : 'lot_avicole', row.related_id, row.nom, 'Intervention santé simulée reliée à la cible.', row.risk_level === 'eleve' ? 'warning' : 'info', { amount: row.cout, montant: row.cout, target_type: row.target_type, target_id: row.target_id, event_date: row.date }))];
  const taches = [task(1, 'Vendre 115 poulets HF-CH-003', 'ventes', 'HF-OPP-001', dateDaysFromNow(1), 'haute', 'Confirmer client; saisir vente; facture; livraison'), task(2, 'Peser bovin HF-BOV-003 avant vente', 'animaux', 'HF-BOV-003', dateDaysFromNow(1), 'haute', 'Confirmer poids; vérifier coût; vendre si marge OK'), task(3, 'Relancer créance tomates Roma', 'ventes', 'HF-CMD-004', dateDaysFromNow(1), 'moyenne', 'Appeler client; enregistrer paiement')];
  const alertes_center = [alert(1, 'Lot chair prêt à vendre', 'HF-CH-003 peut être vendu partiellement maintenant.', 'avicole', 'HF-CH-003', 'warning', 'Transformer l’opportunité en vente.', { entity_type: 'lot_avicole' }), alert(2, 'Créance client à suivre', 'Tomates Roma vendues non encaissées.', 'ventes', 'HF-CMD-004', 'warning', 'Relancer le client.')];
  const documents = [...sales.documents, document(20, 'Ordonnance Newcastle pondeuses', 'ordonnance', 'sante', 'intervention', 'HF-SAN-001', { file_url: 'simulation://photo-ordonnance-newcastle.jpg' }), document(21, 'Preuve traitement chair retard poids', 'preuve_photo', 'sante', 'intervention', 'HF-SAN-004', { file_url: 'simulation://photo-traitement-chair.jpg' })];
  const core = { dashboard: [], clients, fournisseurs, stock: stockRows, stocks: stockRows, avicole, lots: avicole, animaux, cultures, sante, veterinaires: [{ id: 'HF-VET-001', nom: 'Dr. Kone', tel: '+221 77 900 0001', source: SOURCE }], finances: sales.finances, investissements: investments, tracabilite: [], ventes: sales.sales_orders, sales_orders: sales.sales_orders, sales_order_items: sales.sales_order_items, invoices: sales.invoices, payments: sales.payments, deliveries: sales.deliveries, documents, taches, rapports: [], equipements: [], audit_logs: [{ id: 'HF-AUD-001', action: 'simulation_seed_loaded', module: 'simulation', created_at: isoNow(), source: SOURCE }], alimentation_logs: logs.alimentation_logs, production_oeufs_logs: logs.production_oeufs_logs, business_events, sales_opportunities: opportunities, alertes_center, sensor_devices: [], camera_devices: [], whatsapp_templates: [], whatsapp_logs: [{ id: 'HF-WA-001', status: 'simule', provider: 'simulation', sent_at: isoNow(), message: 'Relance créance HF-CMD-004 simulée', source: SOURCE }], price_catalog: [{ id: 'HF-PRICE-001', produit: 'Tablette 30 œufs', prix_vente: 2800, prix_revient_source: 'simulation_pondeuses', source: SOURCE }], business_plans: [{ id: 'HF-BP-001', title: 'Business Plan Horizon Farm Simulation fiable', statut: 'actif', source: SOURCE }], bp_investment_lines: investments, bp_recurring_costs: [{ id: 'HF-BPR-001', designation: 'Salaires équipe ferme', categorie: 'RH', montant_mensuel: 420000, source: SOURCE }], bp_revenue_projections: [], bp_funding_sources: [], bp_links: [], bp_risks: [], bp_versions: [], bp_lines_history: [] };
  return mergeSimulationScenarios(core);
}

export const horizonFarmSimulationSeed = buildSimulation();
export default horizonFarmSimulationSeed;
