import { lazy, Suspense, useMemo, useState } from 'react';
import { BarChart3, Beef, Bell, Bird, Bot, BrainCircuit, Calculator, ClipboardList, DollarSign, FolderOpen, GitBranch, Goal, Handshake, HeartPulse, LayoutDashboard, PiggyBank, Scale, Settings, ShoppingCart, Sprout, Tractor, UserCog, UserRound, Warehouse, Wifi, Wrench } from 'lucide-react';
import AppNotificationManager from './components/AppNotificationManager';
import AssistantPanel from './components/AssistantPanel';
import ErrorBoundary from './components/ErrorBoundary';
import { useAuth } from './context/AuthContext';
import { useAppData } from './context/AppContext';
import useCrudModule from './hooks/useCrudModule';
import useLiveWeather from './hooks/useLiveWeather';
import useOnlineStatus from './hooks/useOnlineStatus';
import AppLayout from './layouts/AppLayout';
import HomePage from './pages/HomePage';
import LoginPage from './pages/LoginPage';

const MODULES = {
  dashboard: lazy(() => import('./modules/DashboardV2')), assistant_erp: lazy(() => import('./modules/AssistantERPV2')), centre_ia: lazy(() => import('./modules/CentreIA')), objectifs_croissance: lazy(() => import('./modules/ObjectifsCroissance')),
  animaux: lazy(() => import('./modules/AnimauxV2')), avicole: lazy(() => import('./modules/AvicoleV10')), sante: lazy(() => import('./modules/SanteV7')), finances: lazy(() => import('./modules/FinancesV12')), comptabilite: lazy(() => import('./modules/ComptabiliteV7')), investissements: lazy(() => import('./modules/InvestissementsV8')), impact_business: lazy(() => import('./modules/ImpactBusiness')), stock: lazy(() => import('./modules/StocksV4')),
  clients: lazy(() => import('./modules/ClientsReadable')), fournisseurs: lazy(() => import('./modules/FournisseursReadable')), tracabilite: lazy(() => import('./modules/TracabiliteV2')), alertes: lazy(() => import('./modules/AlertesCenterV2')), cultures: lazy(() => import('./modules/CulturesV4')), smartfarm: lazy(() => import('./modules/SmartFarm')), ventes: lazy(() => import('./modules/VentesV3')), documents: lazy(() => import('./modules/DocumentsV2')), taches: lazy(() => import('./modules/TachesV3')),
  rh: lazy(() => import('./modules/RHV2')), rapports: lazy(() => import('./modules/RapportsV2')), equipements: lazy(() => import('./modules/EquipementsV2')), sync: lazy(() => import('./modules/SyncActivityCenterV2')), sync_activity: lazy(() => import('./modules/SyncActivityCenterV2')), audit_logs: lazy(() => import('./modules/SyncActivityCenterV2')), gestion_systeme: lazy(() => import('./modules/GestionSystemeV2')),
};
const CRUD_KEYS = ['animaux','avicole','sante','veterinaires','finances','investissements','business_plans','bp_investment_lines','bp_recurring_costs','bp_revenue_projections','bp_funding_sources','bp_links','bp_risks','stock','clients','fournisseurs','tracabilite','cultures','documents','taches','rapports','equipements','audit_logs','alimentation_logs','production_oeufs_logs','sensor_devices','camera_devices','business_events','alertes_center','whatsapp_templates','whatsapp_logs','sales_orders','sales_order_items','deliveries','invoices','payments','sales_opportunities'];
const rows = (crud) => crud?.rows || [];

export default function App() {
  const [active, setActive] = useState('dashboard');
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [assistantOpen, setAssistantOpen] = useState(false);
  const { user, loading: authLoading, signOut } = useAuth();
  const { dataMap, refreshModule, flushOfflineQueue } = useAppData();
  const { online, lastOnlineAt } = useOnlineStatus();
  const { weather: liveMeteo, loading: weatherLoading, source: weatherSource } = useLiveWeather();
  const c = Object.fromEntries(CRUD_KEYS.map((key) => [key, useCrudModule(key)]));
  const base = (key) => ({ rows: rows(c[key]), loading: c[key]?.loading, onCreate: c[key]?.create, onUpdate: c[key]?.update, onDelete: c[key]?.remove, onRefresh: c[key]?.refresh });

  const vaccinsRetard = rows(c.sante).filter((v) => v.statut === 'retard').length;
  const stocksCritiques = rows(c.stock).filter((s) => Number(s.quantite || 0) <= Number(s.seuil || 0)).length;
  const animauxMalades = rows(c.animaux).filter((a) => a.health_status === 'malade').length;
  const culturesRisque = rows(c.cultures).filter((x) => Number(x.score_sante || 0) < 80 || x.statut === 'perdu').length;
  const lotsAlerte = rows(c.avicole).filter((lot) => Number(lot.mortality || 0) > Number(lot.initial_count || 0) * 0.04 || Number(lot.scoresSante || 100) < 88).length;
  const financesAlerte = rows(c.finances).filter((trx) => ['impaye', 'partiel'].includes(trx.statut)).length;
  const fournisseursAlerte = rows(c.fournisseurs).filter((f) => Number(f.dettes || 0) > 0 || f.statut === 'a_risque').length;
  const equipementsAlerte = rows(c.equipements).filter((e) => ['panne', 'maintenance', 'hors_service'].includes(e.status)).length;
  const tachesAlerte = rows(c.taches).filter((t) => t.priority === 'critique' || t.status === 'retard').length;
  const notifs = vaccinsRetard + stocksCritiques + animauxMalades + culturesRisque + lotsAlerte + financesAlerte + fournisseursAlerte + equipementsAlerte + tachesAlerte + (online ? 0 : 1);
  const refreshAll = async () => Promise.allSettled(CRUD_KEYS.map((m) => refreshModule(m)));
  const refreshSalesWorkflow = async () => Promise.allSettled(['sales_orders','invoices','payments','finances','clients','stock','animaux','avicole','cultures','documents','business_events','alertes_center'].map((k) => c[k]?.refresh?.()));

  const actionTraceShared = { tasks: rows(c.taches), alertes: rows(c.alertes_center), businessEvents: rows(c.business_events), events: rows(c.business_events), auditLogs: rows(c.audit_logs), online };
  const internalResourcesShared = { equipements: rows(c.equipements), transactions: rows(c.finances), documents: rows(c.documents), tasks: rows(c.taches) };
  const decisionDataMap = useMemo(() => ({ animaux: rows(c.animaux), avicole: rows(c.avicole), lots: rows(c.avicole), cultures: rows(c.cultures), stock: rows(c.stock), stocks: rows(c.stock), clients: rows(c.clients), fournisseurs: rows(c.fournisseurs), investissements: rows(c.investissements), business_plans: rows(c.business_plans), sales_orders: rows(c.sales_orders), salesOrders: rows(c.sales_orders), payments: rows(c.payments), finances: rows(c.finances), transactions: rows(c.finances), production_oeufs_logs: rows(c.production_oeufs_logs), productionLogs: rows(c.production_oeufs_logs), alimentation_logs: rows(c.alimentation_logs), alimentationLogs: rows(c.alimentation_logs), market_prices: dataMap.market_prices || [], market_calendar_events: dataMap.market_calendar_events || [], smartfarm_events: dataMap.smartfarm_events || [], meteo: liveMeteo }), [c, dataMap, liveMeteo]);
  const navItems = useMemo(() => [
    ['dashboard','Accueil',LayoutDashboard], ['assistant_erp','Assistant ERP',Bot], ['centre_ia','Centre décisionnel',BrainCircuit, stocksCritiques > 0 || lotsAlerte > 0 || financesAlerte > 0 || culturesRisque > 0], ['objectifs_croissance','Objectifs & Croissance',Goal, financesAlerte > 0 || lotsAlerte > 0 || culturesRisque > 0], ['animaux','Animaux',Beef], ['avicole','Avicole',Bird], ['sante','Santé & Vaccins',HeartPulse, vaccinsRetard > 0], ['finances','Finances',DollarSign], ['comptabilite','Comptabilité',Calculator], ['investissements','Investissements',PiggyBank], ['impact_business','Impact & Valeur',Scale, vaccinsRetard > 0 || stocksCritiques > 0 || animauxMalades > 0 || lotsAlerte > 0], ['stock','Stock',Warehouse, stocksCritiques > 0], ['clients','Clients',UserRound], ['ventes','Ventes',ShoppingCart], ['fournisseurs','Fournisseurs',Handshake], ['tracabilite','Traçabilité',GitBranch], ['alertes','Alertes',Bell, rows(c.alertes_center).some((a) => a.status === 'nouvelle')], ['cultures','Cultures',Sprout, culturesRisque > 0], ['documents','Documents',FolderOpen], ['taches','Tâches',ClipboardList], ['rh','RH & Équipe',UserCog], ['rapports','Rapports',BarChart3], ['equipements','Équipements',Wrench], ['smartfarm','Smart Farm',Tractor], ['sync_activity','Activité & Sync ERP',Wifi, !online], ['gestion_systeme','Gestion du système',Settings]
  ].map(([id, label, icon, hasAlert]) => ({ id, label, icon, hasAlert })), [vaccinsRetard, stocksCritiques, culturesRisque, online, animauxMalades, lotsAlerte, financesAlerte, c.alertes_center]);

  const syncActivityProps = { onRefreshAll: refreshAll, onFlushOffline: flushOfflineQueue, online, lastOnlineAt, dataMap, tasks: rows(c.taches), alertes: rows(c.alertes_center), businessEvents: rows(c.business_events), auditLogs: rows(c.audit_logs), auditLoading: c.audit_logs.loading, onRefreshAuditLogs: c.audit_logs.refresh, onNavigate: setActive, onCreateTask: c.taches.create, onRefreshTasks: c.taches.refresh, onCreateAlert: c.alertes_center.create, onRefreshAlertes: c.alertes_center.refresh, onUpdateSalesOrder: c.sales_orders.update, onRefreshSalesOrders: c.sales_orders.refresh, onUpdateOpportunity: c.sales_opportunities.update, onRefreshOpportunities: c.sales_opportunities.refresh, onCreateDocument: c.documents.create, onRefreshDocuments: c.documents.refresh, onCreateBusinessEvent: c.business_events.create, onRefreshBusinessEvents: c.business_events.refresh };
  const reportData = { animaux: rows(c.animaux), lots: rows(c.avicole), sante: rows(c.sante), stocks: rows(c.stock), cultures: rows(c.cultures), salesOrders: rows(c.sales_orders), payments: rows(c.payments), transactions: rows(c.finances), finances: rows(c.finances), documents: rows(c.documents), clients: rows(c.clients), fournisseurs: rows(c.fournisseurs), taches: rows(c.taches), alertes: rows(c.alertes_center), equipements: rows(c.equipements) };
  const shared = { onNavigate: setActive, onCreateBusinessEvent: c.business_events.create, onRefreshBusinessEvents: c.business_events.refresh };
  const bpCallbacks = {
    onCreateBpInvestmentLine: c.bp_investment_lines.create, onUpdateBpInvestmentLine: c.bp_investment_lines.update, onDeleteBpInvestmentLine: c.bp_investment_lines.remove, onRefreshBpInvestmentLines: c.bp_investment_lines.refresh,
    onCreateBpRecurringCost: c.bp_recurring_costs.create, onUpdateBpRecurringCost: c.bp_recurring_costs.update, onDeleteBpRecurringCost: c.bp_recurring_costs.remove, onRefreshBpRecurringCosts: c.bp_recurring_costs.refresh,
    onCreateBpRevenueProjection: c.bp_revenue_projections.create, onUpdateBpRevenueProjection: c.bp_revenue_projections.update, onDeleteBpRevenueProjection: c.bp_revenue_projections.remove, onRefreshBpRevenueProjections: c.bp_revenue_projections.refresh,
    onCreateBpFundingSource: c.bp_funding_sources.create, onUpdateBpFundingSource: c.bp_funding_sources.update, onDeleteBpFundingSource: c.bp_funding_sources.remove, onRefreshBpFundingSources: c.bp_funding_sources.refresh,
    onCreateBpLink: c.bp_links.create, onUpdateBpLink: c.bp_links.update, onDeleteBpLink: c.bp_links.remove, onRefreshBpLinks: c.bp_links.refresh,
    onCreateBpRisk: c.bp_risks.create, onUpdateBpRisk: c.bp_risks.update, onDeleteBpRisk: c.bp_risks.remove, onRefreshBpRisks: c.bp_risks.refresh,
  };
  const moduleProps = {
    dashboard: { lotsData: rows(c.avicole), animaux: rows(c.animaux), vaccins: rows(c.sante), stocks: rows(c.stock), clients: rows(c.clients), cultures: rows(c.cultures), salesOrders: rows(c.sales_orders), payments: rows(c.payments), transactions: rows(c.finances), alimentationLogs: rows(c.alimentation_logs), productionLogs: rows(c.production_oeufs_logs), opportunities: rows(c.sales_opportunities), taches: rows(c.taches), alertes: rows(c.alertes_center), equipements: rows(c.equipements), businessEvents: rows(c.business_events), meteo: liveMeteo, onNavigate: setActive, onRefresh: refreshAll },
    assistant_erp: { dataMap, onNavigate: setActive }, centre_ia: { lots: rows(c.avicole), productionLogs: rows(c.production_oeufs_logs), alimentationLogs: rows(c.alimentation_logs), stocks: rows(c.stock), marketPrices: dataMap.market_prices || [], marketCalendarEvents: dataMap.market_calendar_events || [], salesOrders: rows(c.sales_orders), payments: rows(c.payments), transactions: rows(c.finances), smartfarmEvents: dataMap.smartfarm_events || [], sensors: rows(c.sensor_devices), cameras: rows(c.camera_devices), meteo: liveMeteo, dataMap: decisionDataMap, onNavigate: setActive }, objectifs_croissance: { dataMap: decisionDataMap, onNavigate: setActive, onCreateBusinessPlan: c.business_plans.create, onRefreshBusinessPlans: c.business_plans.refresh },
    animaux: { ...base('animaux'), alimentationLogs: rows(c.alimentation_logs), vaccins: rows(c.sante), businessEvents: rows(c.business_events), salesOrders: rows(c.sales_orders), payments: rows(c.payments), opportunities: rows(c.sales_opportunities), onCreateOpportunity: c.sales_opportunities.create, onUpdateOpportunity: c.sales_opportunities.update, onRefreshOpportunities: c.sales_opportunities.refresh, ...shared },
    avicole: { ...base('avicole'), transactions: rows(c.finances), alimentationLogs: rows(c.alimentation_logs), productionLogs: rows(c.production_oeufs_logs), onCreateProduction: c.production_oeufs_logs.create, onUpdateProduction: c.production_oeufs_logs.update, onDeleteProduction: c.production_oeufs_logs.remove, onRefreshProduction: c.production_oeufs_logs.refresh, opportunities: rows(c.sales_opportunities), onCreateOpportunity: c.sales_opportunities.create, onUpdateOpportunity: c.sales_opportunities.update, onRefreshOpportunities: c.sales_opportunities.refresh, ...shared },
    sante: { ...base('sante'), vets: rows(c.veterinaires), onCreateVet: c.veterinaires.create, onUpdateVet: c.veterinaires.update, onDeleteVet: c.veterinaires.remove, onRefreshVets: c.veterinaires.refresh, animaux: rows(c.animaux), lots: rows(c.avicole), stocks: rows(c.stock), transactions: rows(c.finances), onCreateFinanceTransaction: c.finances.create, onRefreshFinances: c.finances.refresh, onNavigate: setActive },
    finances: { ...base('finances'), animaux: rows(c.animaux), lots: rows(c.avicole), cultures: rows(c.cultures), stocks: rows(c.stock), investissements: rows(c.investissements), clients: rows(c.clients), fournisseurs: rows(c.fournisseurs), documents: rows(c.documents), alimentationLogs: rows(c.alimentation_logs), businessPlans: rows(c.business_plans), salesOrders: rows(c.sales_orders), payments: rows(c.payments), ...shared },
    comptabilite: { transactions: rows(c.finances), finances: rows(c.finances), salesOrders: rows(c.sales_orders), payments: rows(c.payments), clients: rows(c.clients), fournisseurs: rows(c.fournisseurs), stocks: rows(c.stock), animaux: rows(c.animaux), lots: rows(c.avicole), cultures: rows(c.cultures), sante: rows(c.sante), investissements: rows(c.investissements), equipements: rows(c.equipements), documents: rows(c.documents), onRefreshFinances: c.finances.refresh, onNavigate: setActive },
    investissements: { ...base('investissements'), businessPlans: rows(c.business_plans), bpInvestmentLines: rows(c.bp_investment_lines), bpRecurringCosts: rows(c.bp_recurring_costs), bpRevenueProjections: rows(c.bp_revenue_projections), bpFundingSources: rows(c.bp_funding_sources), bpLinks: rows(c.bp_links), bpRisks: rows(c.bp_risks), transactions: rows(c.finances), lots: rows(c.avicole), animaux: rows(c.animaux), cultures: rows(c.cultures), onCreateBusinessPlan: c.business_plans.create, onUpdateBusinessPlan: c.business_plans.update, onDeleteBusinessPlan: c.business_plans.remove, onRefreshBusinessPlans: c.business_plans.refresh, ...bpCallbacks, onCreateFinanceTransaction: c.finances.create, onRefreshFinances: c.finances.refresh, onCreateLot: c.avicole.create, onRefreshLots: c.avicole.refresh, onCreateAnimal: c.animaux.create, onRefreshAnimals: c.animaux.refresh, onCreateCulture: c.cultures.create, onRefreshCultures: c.cultures.refresh },
    impact_business: { animaux: rows(c.animaux), lots: rows(c.avicole), productionLogs: rows(c.production_oeufs_logs), sante: rows(c.sante), stocks: rows(c.stock), transactions: rows(c.finances), salesOrders: rows(c.sales_orders), payments: rows(c.payments), alertes: rows(c.alertes_center), taches: rows(c.taches), documents: rows(c.documents), whatsappLogs: rows(c.whatsapp_logs), businessEvents: rows(c.business_events), cultures: rows(c.cultures), clients: rows(c.clients), fournisseurs: rows(c.fournisseurs), investissements: rows(c.investissements), businessPlans: rows(c.business_plans), alimentationLogs: rows(c.alimentation_logs), onNavigate: setActive },
    stock: { ...base('stock'), alimentationLogs: rows(c.alimentation_logs), animaux: rows(c.animaux), lots: rows(c.avicole), fournisseurs: rows(c.fournisseurs), opportunities: rows(c.sales_opportunities), taches: rows(c.taches), onCreateAlimentation: c.alimentation_logs.create, onUpdateAlimentation: c.alimentation_logs.update, onDeleteAlimentation: c.alimentation_logs.remove, onRefreshAlimentation: c.alimentation_logs.refresh, onCreateFinanceTransaction: c.finances.create, onRefreshFinances: c.finances.refresh, onCreateOpportunity: c.sales_opportunities.create, onUpdateOpportunity: c.sales_opportunities.update, onRefreshOpportunities: c.sales_opportunities.refresh, onCreateTask: c.taches.create, onUpdateTask: c.taches.update, onRefreshTasks: c.taches.refresh, onCreateAlert: c.alertes_center.create, onRefreshAlertes: c.alertes_center.refresh, ...shared },
    clients: { ...base('clients'), salesOrders: rows(c.sales_orders), payments: rows(c.payments), transactions: rows(c.finances), onNavigate: setActive },
    fournisseurs: { ...base('fournisseurs'), stocks: rows(c.stock), tasks: rows(c.taches), transactions: rows(c.finances), finances: rows(c.finances), documents: rows(c.documents), onUpdateStock: c.stock.update, onRefreshStock: c.stock.refresh, onCreateTask: c.taches.create, onRefreshTasks: c.taches.refresh, onCreateAlert: c.alertes_center.create, onRefreshAlertes: c.alertes_center.refresh, ...shared },
    tracabilite: { ...base('tracabilite'), ...actionTraceShared, events: rows(c.business_events), animaux: rows(c.animaux), lots: rows(c.avicole), cultures: rows(c.cultures), onCreate: c.business_events.create, onUpdate: c.business_events.update, onDelete: c.business_events.remove, onNavigate: setActive, onRefresh: async () => { await c.tracabilite.refresh(); await c.business_events.refresh(); } },
    alertes: { ...actionTraceShared, alertes: rows(c.alertes_center), transactions: rows(c.finances), animaux: rows(c.animaux), lots: rows(c.avicole), stocks: rows(c.stock), cultures: rows(c.cultures), sensorDevices: rows(c.sensor_devices), loading: c.alertes_center.loading, onCreate: c.alertes_center.create, onUpdate: c.alertes_center.update, onDelete: c.alertes_center.remove, onRefresh: c.alertes_center.refresh, onNavigate: setActive, whatsappTemplates: rows(c.whatsapp_templates), whatsappLogs: rows(c.whatsapp_logs), onSendWhatsApp: async (alerte, recipient = 'responsable') => { await c.whatsapp_logs.create({ alert_id: alerte.id, recipient, message: `${alerte.title || 'Alerte Horizon Farm'}\n${alerte.message || ''}\nAction recommandee: ${alerte.action_recommandee || 'Verifier dans Horizon Farm.'}`, status: 'simule', provider: 'simulation', sent_at: new Date().toISOString() }); await c.whatsapp_logs.refresh(); } },
    cultures: { ...base('cultures'), transactions: rows(c.finances), salesOrders: rows(c.sales_orders), payments: rows(c.payments), deliveriesList: rows(c.deliveries), businessEvents: rows(c.business_events), opportunities: rows(c.sales_opportunities), onCreateOpportunity: c.sales_opportunities.create, onUpdateOpportunity: c.sales_opportunities.update, onRefreshOpportunities: c.sales_opportunities.refresh, ...shared },
    ventes: { ...base('sales_orders'), orderItems: rows(c.sales_order_items), deliveriesList: rows(c.deliveries), invoicesList: rows(c.invoices), paymentsList: rows(c.payments), opportunities: rows(c.sales_opportunities), animaux: rows(c.animaux), lots: rows(c.avicole), cultures: rows(c.cultures), stocks: rows(c.stock), clients: rows(c.clients), transactions: rows(c.finances), businessEvents: rows(c.business_events), documents: rows(c.documents), alertes: rows(c.alertes_center), onRefreshWorkflow: refreshSalesWorkflow, onRefreshOpportunities: c.sales_opportunities.refresh, onCreateItem: c.sales_order_items.create, onUpdateItem: c.sales_order_items.update, onDeleteItem: c.sales_order_items.remove, onCreateDelivery: c.deliveries.create, onUpdateDelivery: c.deliveries.update, onDeleteDelivery: c.deliveries.remove, onRefreshDeliveries: c.deliveries.refresh, onCreateInvoice: c.invoices.create, onUpdateInvoice: c.invoices.update, onDeleteInvoice: c.invoices.remove, onRefreshInvoices: c.invoices.refresh, onCreatePayment: c.payments.create, onUpdatePayment: c.payments.update, onDeletePayment: c.payments.remove, onRefreshPayments: c.payments.refresh, onCreateOpportunity: c.sales_opportunities.create, onUpdateOpportunity: c.sales_opportunities.update, onDeleteOpportunity: c.sales_opportunities.remove, onUpdateAnimal: c.animaux.update, onRefreshAnimals: c.animaux.refresh, onUpdateLot: c.avicole.update, onRefreshLots: c.avicole.refresh, onUpdateCulture: c.cultures.update, onRefreshCultures: c.cultures.refresh, onUpdateStock: c.stock.update, onRefreshStocks: c.stock.refresh, onCreateFinanceTransaction: c.finances.create, onRefreshFinances: c.finances.refresh, onCreateTrace: c.tracabilite.create, onCreateBusinessEvent: c.business_events.create, onRefreshBusinessEvents: c.business_events.refresh, onCreateDocument: c.documents.create, onRefreshDocuments: c.documents.refresh, onCreateAlert: c.alertes_center.create, onRefreshAlertes: c.alertes_center.refresh, onUpdateClient: c.clients.update, onNavigate: setActive },
    documents: { ...base('documents'), animaux: rows(c.animaux), lots: rows(c.avicole), cultures: rows(c.cultures), clients: rows(c.clients), fournisseurs: rows(c.fournisseurs), transactions: rows(c.finances), finances: rows(c.finances) },
    taches: { ...base('taches'), ...actionTraceShared, alertes: rows(c.alertes_center), animaux: rows(c.animaux), lots: rows(c.avicole), stocks: rows(c.stock), sensorDevices: rows(c.sensor_devices), onUpdateAlert: c.alertes_center.update, onRefreshAlertes: c.alertes_center.refresh, ...shared },
    rh: { ...internalResourcesShared, onRefresh: refreshAll, onCreateFinanceTransaction: c.finances.create, onRefreshFinances: c.finances.refresh, ...shared },
    rapports: { ...base('rapports'), data: reportData, onCreateDocument: c.documents.create, onRefreshDocuments: c.documents.refresh, ...shared },
    equipements: { ...base('equipements'), ...internalResourcesShared, tasks: rows(c.taches), onCreateTask: c.taches.create, onUpdateTask: c.taches.update, onRefreshTasks: c.taches.refresh, onCreateAlert: c.alertes_center.create, onRefreshAlertes: c.alertes_center.refresh, onCreateFinanceTransaction: c.finances.create, onRefreshFinances: c.finances.refresh, onCreateDocument: c.documents.create, onRefreshDocuments: c.documents.refresh, ...shared },
    audit_logs: syncActivityProps, smartfarm: { meteo: liveMeteo, online, sensors: rows(c.sensor_devices), cameras: rows(c.camera_devices), tasks: rows(c.taches), sensorLoading: c.sensor_devices.loading, cameraLoading: c.camera_devices.loading, onCreateSensor: c.sensor_devices.create, onUpdateSensor: c.sensor_devices.update, onDeleteSensor: c.sensor_devices.remove, onRefreshSensors: c.sensor_devices.refresh, onCreateCamera: c.camera_devices.create, onUpdateCamera: c.camera_devices.update, onDeleteCamera: c.camera_devices.remove, onRefreshCameras: c.camera_devices.refresh, onCreateTask: c.taches.create, onRefreshTasks: c.taches.refresh, onCreateAlert: c.alertes_center.create, onRefreshAlertes: c.alertes_center.refresh, ...shared }, gestion_systeme: { ...internalResourcesShared, onNavigate: setActive }, sync: syncActivityProps, sync_activity: syncActivityProps,
  };

  const Module = MODULES[active] || MODULES.dashboard;
  if (authLoading) return <div className="min-h-screen bg-[#f8f5ef] text-[#2f2415] flex items-center justify-center"><div className="text-center"><div className="mx-auto mb-4 w-12 h-12 rounded-xl bg-[#c9a96a] animate-pulse" /><p className="text-sm font-semibold text-[#8a7456]">Chargement Horizon Farm...</p></div></div>;
  if (!user) return <LoginPage />;
  return <AppLayout navItems={navItems} active={active} setActive={setActive} sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} online={online} meteo={liveMeteo} weatherLoading={weatherLoading} weatherSource={weatherSource} notifs={notifs} user={user} onSignOut={signOut} dataMap={dataMap} onOpenAssistant={() => setAssistantOpen(true)}><AppNotificationManager dataMap={dataMap} onNavigate={setActive} /><ErrorBoundary resetKey={active} moduleName={navItems.find((item) => item.id === active)?.label || active} onBackToDashboard={() => setActive('dashboard')}><Suspense fallback={<div className="text-sm text-[#8a7456]">Chargement du module...</div>}><HomePage Module={Module} moduleProps={moduleProps[active] || {}} /></Suspense></ErrorBoundary><AssistantPanel open={assistantOpen} onClose={() => setAssistantOpen(false)} dataMap={dataMap} onNavigate={setActive} /></AppLayout>;
}
